### PR TITLE
Anexia endpoint to get vlan list

### LINKED ISSUE #6890: Add endpoint to get Anexia Vlans
**User Story**
Add endpoint to get Anexia Vlans

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: Anexia endpoint to get VLAN list

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6890

```release-note
NONE
```

### CODE REVIEW

**Comment by kgroschoff** [comment]
Looks good, but since it is on machine deployment level don't we need a second endpoint to list them after cluster creation (in add/edit md dialog)?

**Comment by zreigz** [comment]
@kgroschoff you are right, I will add second endpoint, thanks

**Comment by zreigz** [comment]
@kgroschoff PTAL

**Review by kgroschoff — COMMENTED** [review]
/lgtm

Will create issue for ui and probably work on it on monday.

**Comment by zreigz** [comment]
/cherry-pick/release/v2.17

**Pull request merged**
