### PR TITLE
remove Kubernetes versions released with broken Anago

### PR DESCRIPTION
**Pull request by kdomanski**
```release-note
NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
This is not part of this PR, but this seems wrong to me: https://github.com/kubermatic/kubermatic/blob/95332480af14b48eb8e6ba59358aaa0af3f6e124/api/pkg/controller/operator/common/defaults.go#L531-L534

Shouldn't this be `1.17.*` to `1.18.*` instead?

**Comment by kdomanski** [comment]
Yeah, sure, I'll make a separate PR.

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
