### PR TITLE
add endpoint to get security groups from openstack

### LINKED ISSUE #1448: Offer endpoint for getting Security Group from Openstack
### Current state
`Security Group` is an optional field in the UI, but the user has to add it manually.

### Desired state
As the kubermatic api is already able to get all Security Groups, there should be an endpoint for it, so that a user could select it from a dropdown in the UI.
https://github.com/kubermatic/kubermatic/blob/master/api/pkg/provider/cloud/openstack/helper.go

### PR DESCRIPTION
**Pull request by kgroschoff**
**What this PR does / why we need it**:
add endpoint to get security groups from openstack

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1448 

**Special notes for your reviewer**:
/

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
nice pull, what do you think about adding a unit test for this and the previous endpoint ?

**Comment by kgroschoff** [comment]
That's not a real question, isn't it?! :stuck_out_tongue_winking_eye:
But yes, I think that is a pretty good idea

**Comment by glower** [comment]
You can have a look into https://github.com/kubermatic/kubermatic/pull/1516
I have started to some testing for our openstack stuff, maybe you can reuse it

**Review by p0lyn0mial — APPROVED** [review]

**Comment by mrIncompetent** [comment]
Do we require tests for this endpoint or not?

**Comment by mrIncompetent** [comment]
As discussed, the testing code is not ready yet to implement.

**Review by mrIncompetent — APPROVED** [review]

**Pull request merged**
