### PR TITLE
Add MLA controller scaffolding

### LINKED ISSUE #6497: Create MLA controller in KKP - Automate Grafana configuration
A controller needs to be created in KKP in order to automate Grafana configuration for KKP users

### PR DESCRIPTION
**Pull request by aborilov**
**What this PR does / why we need it**:
This PR is only adding MLA controller scaffolding and feature gate for it. Cluster, Project, and UserProjectBinding controllers will be added in the future PRs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6497 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zreigz** [comment]
I prefer PR with whole functionality
Let's wait for the controller body.

**Comment by aborilov** [comment]
> I prefer PR with whole functionality
> Let's wait for the controller body.

will be at least 3 controllers, reviewing all of the all together will be painful, I can add the first one here if you think is better

**Pull request merged**
