### PR TITLE
bump machine-controller to v.1.20.0

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: bump machine-controller to v.1.20.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

```release-note
bump machine-controller to v.1.20.0
```

### CODE REVIEW

**Review by floreks — APPROVED** [review]

**Review by xrstf — APPROVED** [review]
Neat!

/approve

**Pull request merged**
