### PR TITLE
extend vSphere provider for default tag category

### LINKED ISSUE #9331: Create default category for the vSphere cluster
The user should be able to create tags for the vSphere cluster in the KKP. All tags must be assigned to the category. The KKP will create a default category for the new created tags

### PR DESCRIPTION
**Pull request by zreigz**
**What does this PR do / Why do we need it**: extend vSphere provider for default tag category

**Does this PR close any issues?**:
Fixes #9331

```release-note
Extend vSphere provider for default tag category
```

### CODE REVIEW

**Comment by zreigz** [comment]
@moadqassem PTAL

**Review by moadqassem — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
