### PR TITLE
Conformance tester: Do not delete kubernetes-dashboard NS

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Prevents the NS cleanup that is run before each ginkgo run to delete the kubernetes-dashboard NS, to not cause errors in the userclustercontroller manager, which will try to create content in it.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

/assign @xrstf

### CODE REVIEW

**Comment by xrstf** [comment]
Proposal: Can we make the `namespace` const in `pkg/resources/kubernetes-dashboard/deployment.go` public and use that instead of the string literal? I don't have strong opinions here.

**Comment by alvaroaleman** [comment]
> Proposal: Can we make the namespace const in pkg/resources/kubernetes-dashboard/deployment.go public and use that instead of the string literal? I don't have strong opinions here.

Done

**Comment by xrstf** [comment]
Prow does not understand Fakadian (Fake Canadian). :-(

/lgtm

**Pull request merged**
