### PR TITLE
Move api/ to root directory

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
As proposed in https://github.com/kubermatic/kubermatic/pull/5439, we want to remove the `api/` directory. This PR accomplishes that. I recommend reviewing commit-by-commit.

Anticipating frequent rebasing and pain with rebasing file-renames, I have a script that created this PR:

```bash
#!/usr/bin/env bash

set -euo pipefail

cd $(dirname $0)
KUBERMATIC=$(realpath kubermatic)

cd $KUBERMATIC
git co -B move-api-to-root-directory

# reset
git reset --hard upstream/master
rm -f docs/zz_generated.addondata.go.txt

#################################################
# step 1: mv api/* .

cat api/.gitignore >> .gitignore
rm api/.gitignore

cat api/README.md >> README.md
rm api/README.md

cd api
mv * ..
cd ..
rm -rf api

git add .
git commit -m "cd api; mv * .."

#################################################
# step 2: mv config charts

rm -rf charts
mv config charts
git add -f config charts

git commit -m "mv config/ charts/"

#################################################
# step 3: update repository URL

grep -rl 'kubermatic/kubermatic/api' . | xargs sed -i 's#github.com/kubermatic/kubermatic/api#github.com/kubermatic/kubermatic#g'
grep -rl 'github.com/kubermatic/kubermatic/blob/master/api' . | xargs sed -i 's#github.com/kubermatic/kubermatic/blob/master/api#github.com/kubermatic/kubermatic/blob/master#g'
git commit -am "sed 'github.com/kubermatic/kubermatic/api' => 'github.com/kubermatic/kubermatic'"

#################################################
# step 4: dos2unix

# This is the perfect time to fix some odd CRLF files and to
# trim whitespace. We moved all files anyway.
# Pay close attention to not ruin the LICENSE formatting.

txtidy '*.sh' '*.txt' '*.yml' '*.yaml' '*.go' '*.prow.yaml' '*.md' '*.svg' '*.css' 'LICENSE'
echo -e "   $(cat LICENSE)" > LICENSE
echo -e "                  $(cat pkg/ee/LICENSE)" > pkg/ee/LICENSE

git co -- vendor/
git co -- charts/backup/
git co -- pkg/userdata/openshift/testdata/
git co -- pkg/controller/seed-controller-manager/openshift/resources/testdata/
git commit -am "dos2unix, trim trailing spaces"

#################################################
# step 5: update stuff

git apply ../cleanup.diff --reject

# prevent problems with go-based scanners (e.g. running `go test -v ./...` in the root directory)
# mis-interpreting the docs directory as a valid package, which is it not. scripts are already
# adjusted in cleanup.diff.
git add docs

# keep this the last commit to make amending easier
git commit -am "adjust hack/, README, .gitignore, .prow.yaml"
```

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

Wait until everybody had time to notice.

**Review by thetechnick — APPROVED** [review]
This is a good PR, the best PR.
Many have PRs, but his is with no doubt the best of them.
12/10 would review again ;D

**Pull request merged**
