### PR TITLE
Update OSM to latest commit

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Update CRDs and image tag for OSM to consume latest changes from https://github.com/kubermatic/operating-system-manager/commit/ea5b2581b8c2dc9db6e54cd60de5893ab602870e

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
cc @kubermatic/sig-release-managers

**Comment by ahmedwaleedmalik** [comment]
@xrstf will need another LGTM :D Updated the `CustomOperatingSystemProfile` CRD as well.

**Pull request merged**
