### PR TITLE
[release/v2.19] Bump machine controller 1.42.5

### PR DESCRIPTION
**Pull request by moadqassem**
**What does this PR do / Why do we need it**:
Upgrading machine controller to v1.42.5 in KKP.

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
upgrade machine controller to v1.42.5
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
/hold

looks like this is missing a `go mod tidy`

**Comment by moadqassem** [comment]
> /hold
> 
> looks like this is missing a `go mod tidy`

@xrstf Fixed

**Pull request merged**
