### PR TITLE
[release/v2.19] Refactor vSphere ingegration tests

### PR DESCRIPTION
**Pull request by hdurand0710**
Signed-off-by: Helene Durand <helene@kubermatic.com>

**What this PR does / why we need it**:
Manual backport of https://github.com/kubermatic/kubermatic/pull/11681

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind failing-test

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/override pre-kubermatic-e2e-vsphere-ubuntu-1.21 
/override pre-kubermatic-e2e-vsphere-ubuntu-1.21-customfolder
/override pre-kubermatic-e2e-vsphere-ubuntu-1.21-datastore-cluster

**Review by embik — APPROVED** [review]

**Pull request merged**
