### PR TITLE
upgrade to urfave/cli v2 for the installer

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
cli/v1 is pretty ancient. v2 brings a few improvements, none really important for us. This is mostly just housekeeping.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by embik — APPROVED** [review]
/approve
/lgtm

**Comment by embik** [comment]
/lgtm cancel

@xrstf Looks like a problem with the config flag?

```
time="11:05:27" level=info msg="🚀 Initializing installer…" edition="Enterprise Edition" version=95d7ccca2e4e8235a22a7b598405aab6bc84380c
time="11:05:27" level=error msg="❌ Operation failed: failed to load KubermaticConfiguration: no file specified via --config flag."
```

**Comment by xrstf** [comment]
Works:

```
_build/kubermatic-installer deploy \
  --helm-values=test-helm-values.yaml \
  --config test-kubermatic-config.yaml \
  --storageclass copy-default
```

Does not work:

```
_build/kubermatic-installer deploy kubermatic-master \
  --helm-values=test-helm-values.yaml \
  --config test-kubermatic-config.yaml \
  --storageclass copy-default
```

So adding additional arguments break the flag parsing. WTF.

**Comment by embik** [comment]
that's kinda stupid.

**Pull request closed without merging**
