### PR TITLE
add a method to validate spec changes by cloud providers

### PR DESCRIPTION
**Pull request by kdomanski**
**What this PR does / why we need it**:
It allows a cloud provider to ensure that no breaking changes to the spec are applied by the API consumers, e.g. you can still update credentials but you cannot mess with network configuration of an existing cluster.
I need it to forbid changing of the CIDR mentioned in https://github.com/kubermatic/kubermatic/issues/3024 but I'm opening as a separate PR for clarity.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/assign @mrIncompetent

### CODE REVIEW

**Comment by alvaroaleman** [comment]
An alternative approach to this would be to wait for https://github.com/kubermatic/kubermatic/issues/2336 which @nikhita  is currently working on.

That way we would just update the referenced secret and can continue to view the cluster spec as immutable

**Comment by kdomanski** [comment]
The point is not being able to update it. Besides, the example I have (CIDR) is not really a secret.

**Comment by alvaroaleman** [comment]
> The point is not being able to update it. Besides, the example I have (CIDR) is not really a secret.

The point is being able to update credentials but not being able to update anything else or did I understand that wrong?

**Comment by kdomanski** [comment]
The point is being able to update some fields, but not others.

**Comment by mrIncompetent** [comment]
I see the need for such an validation and i'm fine with merging it.

But: We should think of moving such validation into a webhook.
Despite its deployment complexity, it gives us a better separation of concerns (The CRD basically belongs to the cluster-lifecycle team) and does not leak possibilities to circumvent the validation (Like performing a `kubectl edit cluster xxxxxx` like now).

/lgtm
/approve no-issue

**Pull request merged**
