### PR TITLE
Quote certain helm values

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
For those could be yaml-blocks, without quotes they don't render

```release-note
Quote potential yaml block values in helm template
```

### CODE REVIEW

**Comment by kron4eg** [comment]
With this change now it's possible to specify yaml blocks instead of those huge oneliners like base64 datacenters.yaml. 

To obtain such "wrapped" base64 output:

```bash
base64 -b 70 < datacenters.yaml
```

**Comment by kron4eg** [comment]
PTAL @alvaroaleman @kdomanski @mrIncompetent @xrstf

**Comment by kdomanski** [comment]
OMG <3

/approve
/lgtm

**Pull request merged**
