### PR TITLE
replace __KUBERMATIC__TAG__ when deploying via Prow

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This makes it so that when Prow deployed Kubermatic, we can see the exact version via `helm ls`. The chart-sync script already takes care of that for publicly relased versions, but it's nice to have this for our dev versions as well.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
@alvaroaleman Does it make more sense to put this into the `hack/deploy.sh` script, so it applies to all clusters? The `GIT_HEAD_HASH` variable is exported, so it should be available in the `deploy.sh`.

**Comment by alvaroaleman** [comment]
Yes, good idea

**Pull request merged**
