### PR TITLE
[release/v2.13] fix editing cluster credential secret

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: fixes update cluster. Allows to change cluster credential secret

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

```release-note
NONE
```

### CODE REVIEW

**Comment by zreigz** [comment]
@p0lyn0mial good to see you :)

**Comment by kdomanski** [comment]
I created #5595 to address the failing providers.

**Pull request merged**
