### PR TITLE
addons/csi: add nodeplugin for flatcar linux

### PR DESCRIPTION
**Pull request by kdomanski**
**What this PR does / why we need it**:
It appears that we forgot to add the CSI DaemonSet with the appropriate label selector when we added Flatcar.

```release-note
Added missing CSI DaemonSet on Flatcar
```

### CODE REVIEW

**Comment by kron4eg** [comment]
FYI @kdomanski it appears that we miss it also for `sles` and `rhel`.

**Comment by kdomanski** [comment]
@kron4eg Thanks for letting me know!
https://github.com/kubermatic/kubermatic/issues/5699
https://github.com/kubermatic/kubermatic/issues/5700

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
