### PR TITLE
Use secrets for credentials for Digitalocean

### PR DESCRIPTION
**Pull request by nikhita**
Follow up of https://github.com/kubermatic/kubermatic/pull/3836
/hold

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
This is a ready for a review.

**Comment by alvaroaleman** [comment]
/lgtm
/approve
/test pull-kubermatic-e2e-do-centos-1.15
/hold

To wait for the DO e2e test to succeed, feel free to remove the hold afterwards

**Comment by nikhita** [comment]
/assign @zreigz 
for approval

**Comment by nikhita** [comment]
DO test is green

/hold cancel

**Pull request merged**
