### PR TITLE
fix deafult tags

### LINKED ISSUE #3963: Fix tags format
**User Story**
Default tags `system/project` and `system/cluster` don't fulfill the format standard.
Change them to `system-project` and `system-cluster` for DO, OpenStack and GCP providers

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: fix tags format

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3963

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/hold

also needs to be changed for azure: https://prow.loodse.com/view/gcs/prow-data/pr-logs/pull/kubermatic_kubermatic/3945/pull-kubermatic-e2e-azure-coreos-1.15/1158682813696839680

**Comment by zreigz** [comment]
PTAL

**Review by nikhita — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
