### PR TITLE
add changelog for 2.18.1

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
What it says on the tin.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by mlavacca — COMMENTED** [review]
Shouldn't there also be this bugfix to mention? https://github.com/kubermatic/kubermatic/pull/7854

**Comment by xrstf** [comment]
Yes, but that PR has no release note, so it won't appear in the changelog.

**Comment by xrstf** [comment]
Thanks @mlavacca  :)

**Pull request merged**
