### PR TITLE
Bump Kubernetes patch versions for 1.21.12, 1.22.9 and 1.23.6

### PR DESCRIPTION
**Pull request by embik**
**What does this PR do / Why do we need it**:
Kubernetes 1.23.6 came out a while ago and included being built with a Go version that included CVE fixes. This PR bumps the version we support up to 1.23.6.

Since we did not have a KKP release that included 1.23 support yet, this replaces 1.23.5 support, as we don't really have a use-case for support multiple 1.23 versions.

Also bumps Kubernetes patch versions for 1.21 and 1.22.

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Add support for Kubernetes 1.21.12 and 1.22.9
```

(the 1.23 change does not need a release note since the 1.23 PR did not specify the patch version it is going to add in KKP 2.21)

### CODE REVIEW

**Review by xmudrii — COMMENTED** [review]
I think we should also update other minor releases (i.e. 1.22 and 1.21).

**Review by xrstf — APPROVED** [review]
/retest
/approve

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
