### PR TITLE
Avoid checking the selector fields when its nil

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
The kubermatic api will panic because of the selector being nil at the initialization of the providers.
 
```
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@moadqassem Do you have a stacktrace? How did we get into the situation of the cloudprovider being initialized in the first place?

**Comment by alvaroaleman** [comment]
*being initialized with a nil secretKeySelector

**Comment by moadqassem** [comment]
@alvaroaleman 
```
goroutine 398 [running]:
net/http.(*conn).serve.func1(0xc003c1d540)
	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1769 +0x139
panic(0x30f9320, 0x5bc5d70)
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:522 +0x1b5
github.com/kubermatic/kubermatic/api/pkg/kubernetes.ValidateSecretKeySelector(0x0, 0x3633c08, 0xa, 0xc000c14000, 0xc000603ba0)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/pkg/kubernetes/helper.go:57 +0x26
github.com/kubermatic/kubermatic/api/pkg/validation.validateKubevirtCloudSpec(...)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/pkg/validation/cluster.go:374
github.com/kubermatic/kubermatic/api/pkg/validation.ValidateCloudSpec(0xc006104b40, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/pkg/validation/cluster.go:256 +0x103a
github.com/kubermatic/kubermatic/api/pkg/validation.ValidateCreateClusterSpec(0xc0009e8400, 0xc0006489c0, 0x3b6b960, 0x5c025e0, 0x0, 0x0)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/pkg/validation/cluster.go:30 +0x11a
github.com/kubermatic/kubermatic/api/pkg/resources/cluster.Spec(0x0, 0x0, 0xc006104b00, 0x11, 0x0, 0x0, 0x0, 0x0, 0xc00611c710, 0xa, ...)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/pkg/resources/cluster/cluster.go:44 +0x41c
github.com/kubermatic/kubermatic/api/pkg/handler/v1/cluster.CreateEndpoint.func1(0x3b64e20, 0xc006161e30, 0x33c4300, 0xc0061121c0, 0x2e38d80, 0xc00618f400, 0x3b64e20, 0xc006161e30)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/pkg/handler/v1/cluster/cluster.go:99 +0x93e
github.com/kubermatic/kubermatic/api/pkg/handler/middleware.UserInfoExtractor.func1.1(0x3b64e20, 0xc006161e00, 0x33c4300, 0xc0061121c0, 0x34d9120, 0xc006165e00, 0x3b64e20, 0xc006161e00)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/pkg/handler/middleware/middleware.go:143 +0x30c
github.com/kubermatic/kubermatic/api/pkg/handler/middleware.SetPrivilegedClusterProvider.func1.1(0x3b64e20, 0xc00613bda0, 0x33c4300, 0xc0061121c0, 0x34d9120, 0xc006147440, 0x3b64e20, 0xc00613bc20)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/pkg/handler/middleware/middleware.go:85 +0x146
github.com/kubermatic/kubermatic/api/pkg/handler/middleware.SetClusterProvider.func1.1(0x3b64e20, 0xc006107a40, 0x33c4300, 0xc0061121c0, 0x35de600, 0xc006128580, 0x3b64e20, 0xc006107a40)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/pkg/handler/middleware/middleware.go:69 +0x108
github.com/kubermatic/kubermatic/api/pkg/handler/middleware.UserSaver.func1.1(0x3b64e20, 0xc006107a10, 0x33c4300, 0xc0061121c0, 0x33225a0, 0xc003c0dce0, 0x3b64e20, 0xc006107a10)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/pkg/handler/middleware/middleware.go:117 +0x430
github.com/kubermatic/kubermatic/api/pkg/handler/middleware.TokenVerifier.func1.1(0x3b64e20, 0xc006106d50, 0x33c4300, 0xc0061121c0, 0x0, 0x0, 0x0, 0x0)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/pkg/handler/middleware/middleware.go:223 +0x861
github.com/kubermatic/kubermatic/api/vendor/github.com/go-kit/kit/transport/http.Server.ServeHTTP(0xc003cc61c0, 0x371c6f0, 0xc003cba460, 0xc0000bff80, 0x1, 0x1, 0x0, 0x0, 0x0, 0x371c690, ...)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/vendor/github.com/go-kit/kit/transport/http/server.go:110 +0x311
main.setSecureHeaders.func1(0x6e47e20, 0xc003e9d270, 0xc003ee7b00)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/cmd/kubermatic-api/main.go:383 +0x3fa
net/http.HandlerFunc.ServeHTTP(0xc00610c660, 0x6e47e20, 0xc003e9d270, 0xc003ee7b00)
	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1995 +0x44
github.com/kubermatic/kubermatic/api/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc003c48230, 0x6e47e20, 0xc003e9d270, 0xc003ee7b00)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/vendor/github.com/gorilla/mux/mux.go:162 +0x105
github.com/kubermatic/kubermatic/api/vendor/github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x6e47d10, 0xc006106b10, 0xc003ee7900)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:100 +0xda
net/http.HandlerFunc.ServeHTTP(...)
	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1995
main.instrumentHandler.func1(0x6e47d10, 0xc006106b10, 0xc003ee7900)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/cmd/kubermatic-api/metrics.go:49 +0xb6
net/http.HandlerFunc.ServeHTTP(0xc003e35b20, 0x6e47d10, 0xc006106b10, 0xc003ee7900)
	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1995 +0x44
github.com/kubermatic/kubermatic/api/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x3b0c780, 0xc0000be000, 0x3b0e8e0, 0xc003e35b20, 0x371e3c0, 0x3b4e8a0, 0xc003aaf500, 0xc003ee7900)
	/Users/moathqasim/dev/goprojects/src/github.com/kubermatic/kubermatic/api/vendor/github.com/gorilla/handlers/logging.go:45 +0x242
net/http.serverHandler.ServeHTTP(0xc0031552b0, 0x3b4e8a0, 0xc003aaf500, 0xc003ee7900)
	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc003c1d540, 0x3b64d60, 0xc003f3e280)
	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:2884 +0x2f4
```

**Comment by alvaroaleman** [comment]
So make sure there is a secretKeySelector available? This change will just make the kubevirt validation _always_ fail

**Comment by alvaroaleman** [comment]
Okay and why do we get to the point where `validateKubevirtCloudSpec` is called with a cluster that has both a spec.Kubevirt that is an empty string and an empty secretKeySelector? And why it that legitimate?

**Pull request closed without merging**
