### PR TITLE
Add spell checker job to CI/CD

### PR DESCRIPTION
**Pull request by irozzo-1A**
**What this PR does / why we need it**:
This PR adds spell checking in the CI/CD and fixes currently misspelled words.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
/override pre-kubermatic-e2e-aws-openshift-4.1

This test is "not meant to pass" and mostly kept for historical reasons. In any way, fixing the OpenShift tests would not be part of this PR.

**Comment by irozzo-1A** [comment]
@zreigz PTAL I need approval from your side as well ;-)

**Comment by zreigz** [comment]
let's wait for the tests
/lgtm

**Pull request merged**
