### PR TITLE
Add CSIDriver data migration to the kubermatic-installer

### LINKED ISSUE #6976: CSI driver update fails with "field is immutable"
**User Story**

Hi,

After we upgraded to Kubermatic 2.16.8, I see an endless stream of errors in the seed-controller-manager for user clusters, for example:

```
kubermatic-seed-controller-manager-5bbf9cd5b4-nlsn8 controller-manager {"level":"error","time":"2021-05-02T19:34:52.569Z","logger":"kubermatic_addon_controller",
"caller":"addon/addon_controller.go:221","msg":"Reconciling failed","worker-name":"",
"cluster":"6trt68z9s4","addon":"csi","error":"failed to deploy the addon manifests into the cluster: failed to execute 'kubectl --kubeconfig /tmp/cluster-6trt68z9s4-addon-csi-kubeconfig apply --prune -f /tmp/cluster-6trt68z9s4-csi.yaml -l kubermatic-addon=csi' for addon csi of cluster 6trt68z9s4: exit status 1\n
serviceaccount/csi-cinder-controller-sa unchanged\nclusterrole.rbac.authorization.k8s.io/csi-attacher-role unchanged\n
clusterrolebinding.rbac.authorization.k8s.io/csi-attacher-binding unchanged\n
clusterrole.rbac.authorization.k8s.io/csi-provisioner-role unchanged\n
clusterrolebinding.rbac.authorization.k8s.io/csi-provisioner-binding unchanged\n
clusterrole.rbac.authorization.k8s.io/csi-snapshotter-role unchanged\n
clusterrolebinding.rbac.authorization.k8s.io/csi-snapshotter-binding unchanged\n
clusterrole.rbac.authorization.k8s.io/csi-resizer-role unchanged\n
clusterrolebinding.rbac.authorization.k8s.io/csi-resizer-binding unchanged\n
role.rbac.authorization.k8s.io/external-resizer-cfg unchanged\n
rolebinding.rbac.authorization.k8s.io/csi-resizer-role-cfg unchanged\n
service/csi-cinder-controller-service unchanged\n
statefulset.apps/csi-cinder-controllerplugin configured\n
Warning: storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver\n
serviceaccount/csi-cinder-node-sa unchanged\n
clusterrole.rbac.authorization.k8s.io/csi-nodeplugin-role unchanged\nclusterrolebinding.rbac.authorization.k8s.io/csi-nodeplugin-binding unchanged\n
daemonset.apps/csi-cinder-nodeplugin unchanged\n
The CSIDriver \"cinder.csi.openstack.org\" is invalid: spec: Invalid value: storage.CSIDriverSpec{AttachRequired:(*bool)(0xc0154ac978), FSGroupPolicy:(*storage.FSGroupPolicy)(nil), PodInfoOnMount:(*bool)(0xc0154ac979), VolumeLifecycleModes:[]storage.VolumeLifecycleMode{\"Persistent\", \"Ephemeral\"}, StorageCapacity:(*bool)(nil)}: field is immutable\n
","errorCauses":[{"error":"failed to deploy the addon manifests into the cluster: failed to execute 'kubectl --kubeconfig /tmp/cluster-6trt68z9s4-addon-csi-kubeconfig apply --prune -f /tmp/cluster-6trt68z9s4-csi.yaml -l kubermatic-addon=csi' for addon csi of cluster 6trt68z9s4: exit status 1\n
serviceaccount/csi-cinder-controller-sa unchanged\n
clusterrole.rbac.authorization.k8s.io/csi-attacher-role unchanged\n
clusterrolebinding.rbac.authorization.k8s.io/csi-attacher-binding unchanged\n
clusterrole.rbac.authorization.k8s.io/csi-provisioner-role unchanged\n
clusterrolebinding.rbac.authorization.k8s.io/csi-provisioner-binding unchanged\n
clusterrole.rbac.authorization.k8s.io/csi-snapshotter-role unchanged\n
clusterrolebinding.rbac.authorization.k8s.io/csi-snapshotter-binding unchanged\n
clusterrole.rbac.authorization.k8s.io/csi-resizer-role unchanged\n
clusterrolebinding.rbac.authorization.k8s.io/csi-resizer-binding unchanged\n
role.rbac.authorization.k8s.io/external-resizer-cfg unchanged\n
rolebinding.rbac.authorization.k8s.io/csi-resizer-role-cfg unchanged\n
service/csi-cinder-controller-service unchanged\n
statefulset.apps/csi-cinder-controllerplugin configured\n
Warning: storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver\n
serviceaccount/csi-cinder-node-sa unchanged\nclusterrole.rbac.authorization.k8s.io/csi-nodeplugin-role unchanged\nclusterrolebinding.rbac.authorization.k8s.io/csi-nodeplugin-binding unchanged\ndaemonset.apps/csi-cinder-nodeplugin unchanged\n
The CSIDriver \"cinder.csi.openstack.org\" is invalid: spec: Invalid value: storage.CSIDriverSpec{AttachRequired:(*bool)(0xc0154ac978), FSGroupPolicy:(*storage.FSGroupPolicy)(nil), PodInfoOnMount:(*bool)(0xc0154ac979), VolumeLifecycleModes:[]storage.VolumeLifecycleMode{\"Persistent\", \"Ephemeral\"}, StorageCapacity:(*bool)(nil)}: field is immutable\n"}]}
```

This seems to be the case for user clusters created with v1.18. The csidriver is the following:

```
kubectl get csidrivers -o yaml cinder.csi.openstack.org
[...]
spec:
  attachRequired: true
  podInfoOnMount: false
  volumeLifecycleModes:
  - Persistent
```

If I grab the csi driver yaml from the [2.16 branch](https://github.com/kubermatic/kubermatic/blob/release/v2.16/addons/csi/driver.yaml), add the label to it and try to apply it manually, it fails (logically):

```
kubectl apply --prune -f temp/driver.yaml -l kubermatic-addon=csi
Warning: storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
The CSIDriver "cinder.csi.openstack.org" is invalid: spec: Invalid value: storage.CSIDriverSpec{AttachRequired:(*bool)(0xc01016cf88), FSGroupPolicy:(*storage.FSGroupPolicy)(nil), PodInfoOnMount:(*bool)(0xc01016cf89), VolumeLifecycleModes:[]storage.VolumeLifecycleMode{"Persistent", "Ephemeral"}, StorageCapacity:(*bool)(nil)}: field is immutable
```

Should this work? Or am I doing something wrong?

**Acceptance criteria**

* Upgrade to 1.19 works

### PR DESCRIPTION
**Pull request by kron4eg**
Fixes #6976 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Add CSIDriver data migration to the kubermatic-installer
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]

**Comment by kron4eg** [comment]
@mlavacca FYI: I had to revert your two commits about multiarch docker builds of user-ssh-agent since it was giving me fails like this in CI:

```
make[1]: Entering directory '/home/prow/go/src/github.com/kubermatic/kubermatic/cmd/user-ssh-keys-agent'
GOOS=linux CGO_ENABLED=0 go build -o ./_build/user-ssh-keys-agent
docker buildx build --platform linux/arm64,linux/amd64 --push -t quay.io/kubermatic/user-ssh-keys-agent:f13054ad73e06cbfffd79bcc6a715a058fcecb2b .
error: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
make[1]: *** [Makefile:24: docker] Error 1
make[1]: Leaving directory '/home/prow/go/src/github.com/kubermatic/kubermatic/cmd/user-ssh-keys-agent'
```

**Review by xmudrii — APPROVED** [review]

**Pull request merged**
