### PR TITLE
[release/v2.20] Anexia: allow extended disk configuration in AnexiaNodeSpec

### PR DESCRIPTION
**Pull request by LittleFox94**
**What this PR does / why we need it**:

This extends apiv1.AnexiaNodeSpec to allow extended disk configuration introduced in machine-controller with pull request [1402](https://github.com/kubermatic/machine-controller/pull/1402).

Without this, Kubermatic API returns a 500 when trying to do any MachineDeployment operation on a cluster which has a MachineDeployment with the new disks attribute (and thus without the old diskSize attribute).

Backport of #10816 

**What type of PR is this?**
/kind bug
/kind feature
/kind api-change

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
* Extend disk configuration for provider Anexia
* Update machine-controller to v1.45.4
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by LittleFox94** [comment]
E2E tests for Anexia are not yet on this branch. I backported them as well, but didn't include them here, yet, as I'm not sure if this is wanted.

**Comment by ahmedwaleedmalik** [comment]
Please update the tag here to `v1.45.4` https://github.com/kubermatic/kubermatic/blob/release/v2.20/pkg/resources/machinecontroller/deployment.go#L55

**Comment by LittleFox94** [comment]
> Please update the tag here to `v1.45.4` https://github.com/kubermatic/kubermatic/blob/release/v2.20/pkg/resources/machinecontroller/deployment.go#L55

right, sorry for missing that - had everything prepared yesterday and today just changed to a proper release in go.mod ^^'

**Comment by LittleFox94** [comment]
Urghs - an API change in go-anxcloud from before I worked here I missed to adapt .. working on it

**Comment by LittleFox94** [comment]
/retry

everything looks like timeouts and other flakiness

**Comment by LittleFox94** [comment]
/retest

.. oops, wrong command ^^'

**Comment by LittleFox94** [comment]
`pre-kubermatic-test-integration` cannot reach a vCenter (45.66.89.2):
https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_kubermatic/10915/pre-kubermatic-test-integration/1565657584575188992

**Comment by LittleFox94** [comment]
Did something change on your test infrastructure? This failure looks extremely unrelated, but comes up again and again, while also not looking like a fluke:

https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_kubermatic/10915/pre-kubermatic-test-integration/1567055530474606592#1:build-log.txt%3A158
```
go: downloading github.com/vmware/govmomi v0.23.1
E0906 07:53:55.979461   18220 network.go:60] failed to get network backing info for "VmwareDistributedVirtualSwitch:dvs-2001": type VmwareDistributedVirtualSwitch (/Hamburg/network/DSwitchAlpha) cannot be used for EthernetCardBackingInfo
E0906 07:54:09.848842   18220 network.go:60] failed to get network backing info for "VmwareDistributedVirtualSwitch:dvs-2001": type VmwareDistributedVirtualSwitch (/Hamburg/network/DSwitchAlpha) cannot be used for EthernetCardBackingInfo
--- FAIL: TestGetPossibleVMNetworks (1.93s)
    --- FAIL: TestGetPossibleVMNetworks/get_all_networks (1.93s)
        network_test.go:72: Got network infos differ from expected ones. Diff: [slice[2].Name: Default Network != DSwitchAlpha-DVUplinks-2001 slice[2].RelativePath: Default Network != DSwitchAlpha-DVUplinks-2001 slice[2].AbsolutePath: /Hamburg/network/Default Network != /Hamburg/network/DSwitchAlpha-DVUplinks-2001 slice[3].Name: DSwitchAlpha-DVUplinks-2001 != Default Network slice[3].RelativePath: DSwitchAlpha-DVUplinks-2001 != Default Network slice[3].AbsolutePath: /Hamburg/network/DSwitchAlpha-DVUplinks-2001 != /Hamburg/network/Default Network]
FAIL
FAIL	k8c.io/kubermatic/v2/pkg/provider/cloud/vsphere	22.052s
FAIL
```

can I have an override for this one, @xrstf ?

After looking at the problem in the [v2.21 PR](10916), this could be the same problem that was fixed with #10918, in which case a backport of that to v2.20 would be better than an override.

**Comment by LittleFox94** [comment]
@ahmedwaleedmalik this one has probably the same problem as #10916 - what do we want to do here to fix that?

**Comment by ahmedwaleedmalik** [comment]
Yes, it's waiting for https://github.com/kubermatic/kubermatic/pull/10927

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
