### PR TITLE
Add support for Kubernetes 1.26

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This adds basic support for Kubernetes 1.26 to KKP. To bump the kubectl binary in our `kubermatic/util` Docker image, a new v2.3.0 had to be created as well.

**Which issue(s) this PR fixes**:
Part of #11614

**What type of PR is this?**
/kind feature

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Add support for Kubernetes 1.26
```

**Documentation**:
```documentation
TBD
```

### CODE REVIEW

**Comment by xrstf** [comment]
For future reference, https://github.com/kubernetes/kubernetes/pull/113054 removed the `replicaset_controller_rate_limiter_use` metric, but left no release note for the changelog.

**Comment by xrstf** [comment]
/test pre-kubermatic-e2e-openstack-ubuntu-1.26

prow, pls? hello?

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve 🏎️

**Pull request merged**
