### PR TITLE
Updated the velero node-agent configuration

### PR DESCRIPTION
**Pull request by archups**
**What this PR does / why we need it**:
Velero upgrade changes - replaced restic with node-agent

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
**ACTION REQUIRED**: For velero helm chart upgrade. If running node-agent daemonset along with velero, then following replacement should be made in the velero's values.yaml before proceeding with upgrade 
`velero.restic.deploy` with `velero.deployNodeAgent`
`velero.restic.resources` with `velero.nodeAgent.resources`
`velero.restic.nodeSelector` with `velero.nodeAgent.nodeSelector`
`velero.restic.affinity` with `velero.restic.affinity`
`velero.restic.tolerations` with `velero.nodeAgent.tolerations`
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by embik — COMMENTED** [review]
I don't get this change. Why are we changing the values for enabling this, it seems prone to breaking existing configurations for very little gain. Is this to adjust to some upstream configuration? I also don't see the new resource block being used anywhere.

**Comment by archups** [comment]
> I don't get this change. Why are we changing the values for enabling this, it seems prone to breaking existing configurations for very little gain. Is this to adjust to some upstream configuration? I also don't see the new resource block being used anywhere.

My bad. few changes didn't reflect to the PR. I have pushed those now. 

Yes, adjustment is to upstream configuration and to keep the values.yaml clean and remove confusion. 

For customers those are using our velero (with restic earlier/node-agent now)  can be bit confusing since with movement to 1.10.x version, node-agent has been introduced replacing restic.

**Comment by archups** [comment]
@embik FYI, release notes are updated. Thanks!

**Comment by xrstf** [comment]
> Velero upgrade changes - replaced restic with node-agent

Can you please explain why we're making this change? What are the reasons? Is one better than the other? Is one deprecated?

**Comment by xrstf** [comment]
> If running node-agent daemonset along with velero

Wait, so this is not replacing one with another? But the values.yaml now doesn't have restic anymore, so how can I run both agent and restic in parallel? Do I even want that?

**Comment by archups** [comment]
> > If running node-agent daemonset along with velero
> 
> Wait, so this is not replacing one with another? But the values.yaml now doesn't have restic anymore, so how can I run both agent and restic in parallel? Do I even want that?

Hi @xrstf Restic has been removed, and it is named  node-agent as part of velero 1.10.0 version. Details are also available as part of the template [Notes](https://github.com/vmware-tanzu/helm-charts/blob/velero-3.0.0/charts/velero/templates/NOTES.txt)

**Review by embik — APPROVED** [review]
lgtm, but will need sig-app-management approval as well.

**Pull request merged**
