### PR TITLE
Remove option to disable OSM

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
The user-data plugins from the machine-controller [have been removed](https://github.com/kubermatic/machine-controller/pull/1789). OSM is mandatory now to create a functional cluster since we can't fall back on user data generated by the machine-controller anymore.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind cleanup

**Special notes for your reviewer**:
A follow-up PR for this will add guardrails in the installer to prevent upgrades if OSM has been explicitly disabled for a cluster. Users will have to update their clusters before the KKP upgrade. We can maybe add a flag to automate this as well but it's TBD.

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Operating System Manager is now mandatory to create a functional cluster since machine-controller user-data plugins have been removed(https://github.com/kubermatic/machine-controller/pull/1789). Thus, the Operating System Manager is now always enabled for the user clusters.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by embik — COMMENTED** [review]
I had a similar deprecation/removal in #13316, so here's a question I had to ask myself: Is KKP going to be capable of differentiating between "this `*bool` field is unset because the cluster is old and still using MC user-data" and "this `*bool` is unset because the cluster is new and uses OSM by default"? Is there any migration code required that KKP will fail to run when it's confused about which type of cluster it is processing?

Maybe it makes sense to talk about this in SIG Cluster Management so we have a consistent way forward to deprecating fields in this release. As it stands, my PR will default the deprecated field to true, while this PR will go the opposite direction, and I think it would be nice if we adjusted behaviour.

**Comment by ahmedwaleedmalik** [comment]
> Is KKP going to be capable of differentiating between "this *bool field is unset because the cluster is old and still using MC user-data" and "this *bool is unset because the cluster is new and uses OSM by default"? Is there any migration code required that KKP will fail to run when it's confused about which type of cluster it is processing?

Yeah, it should. As explained in the "reviewer notes," we'll have pre-flight checks in the installer to block users who have not enabled OSM. Migration, not sure, if we'll build it in the installer or just leave it up to the user.

**Comment by embik** [comment]
Gotcha, I misunderstood the reviewer notes for some reason saying we will only reject if the field is set to `false` explicitly. Makes sense though. For Konnectivity, I've opted for just rejecting upgrades when a cluster hasn't been migrated yet, so that operators can run upgrades in their own time (and not experience a force-upgrade/migration when installing the latest KKP).

**Review by embik — APPROVED** [review]
/approve

**Pull request merged**
