### PR TITLE
move openstack tests to handler_test package

### PR DESCRIPTION
**Pull request by zreigz**
What this PR does / why we need it: this is the second step to moving unit tests from handler package to handler_test package

Special notes for your reviewer:
The issue for this task: #2359

```release-note
NONE
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold

can we please hold it for now ? I'm about to issue a big PR that moves `dc` to its own pkg.

**Comment by zreigz** [comment]
@p0lyn0mial  yes, no problem

**Comment by p0lyn0mial** [comment]
@zreigz would be nice if we could first merge https://github.com/kubermatic/kubermatic/pull/2552, WDYT ?

**Comment by zreigz** [comment]
@p0lyn0mial definitely. I will make my changes after yours

**Comment by p0lyn0mial** [comment]
> @p0lyn0mial definitely. I will make my changes after yours

bless you :)

**Review by maciaszczykm — APPROVED** [review]
+1

**Pull request merged**
