### PR TITLE
update used loglevels to adhere the logging guidelines

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Update used loglevels to adhere the logging guidelines.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
We might want to consider using `-v=2` in our `hack/run-*` scripts

**Review by alvaroaleman — COMMENTED** [review]
I really start liking the idea of having a logger that has just two levels: debug and normal

/lgtm
/approve

**Comment by mrIncompetent** [comment]
@alvaroaleman PTAL - i had to rebase due to conflicts

**Pull request merged**
