### PR TITLE
fix AllowedRegistry ConstraintTemplate OpenAPI schema

### PR DESCRIPTION
**Pull request by lsviben**
**What this PR does / why we need it**:
fixes the allowedReigstry ConstraintTemplate OpenApiSchema.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fixed the issue where AllowedRegistry ConstraintTemplate was not being reconiciled by Gatekeeper because it's `spec.crd` OpenAPI spec was missing a type.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/retest

**Comment by embik** [comment]
@lsviben does this need to be backported to releases?

**Comment by lsviben** [comment]
> @lsviben does this need to be backported to releases?

yeah, just to 2.21 though.

/cherrypick release/v2.21

**Comment by embik** [comment]
Thanks!

**Comment by embik** [comment]
Maybe we can also update the release note to include information that we will include in release notes (for 2.22 and 2.21.x)?

**Comment by lsviben** [comment]
> Maybe we can also update the release note to include information that we will include in release notes (for 2.22 and 2.21.x)?

good point, i missed the release note. Thanks!

**Pull request merged**
