### PR TITLE
Add parent cluster readable name to default worker names

### LINKED ISSUE #1838: Make node names contain human-readable cluster name
### Todo
Change node names to contain the human-readable cluster name by default e. g. cluster-name-xxx-xxx  

Was generally thumbs upped when proposed in slack, comes from here  kubermatic/customer-projects#33

### Question
Does this adjust when you rename the cluster? Or do we carry around names from the whole lifecycle of the cluster on old nodes?

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/dashboard-v2/issues/1838

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Added parent cluster readable name to default worker names.
```

### CODE REVIEW

**Comment by kdomanski** [comment]
Uhm, it looks like this function along with its unit test and perhaps some of the fixtures have been dead code ever since we switched e2e tests to MachineDeployments in 54ffc5df26dfee946534314ff0dc78fb2a9b048a

I imagine the change belongs to `func Deployment` instead. And we could get rid of the dead code while we're at it.

**Comment by maciaszczykm** [comment]
@kdomanski True, my mistake. Tried to do it too quickly. However, the code is used in the tests. I will change the correct method.

**Comment by maciaszczykm** [comment]
@kdomanski PTAL

**Pull request merged**
