### PR TITLE
fix leader election for user cluster controller manager

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**:this PR fixes usercluster-controller deployment. Currently, it can't start:
```
I0225 16:15:43.467762       1 main.go:48] registering components
I0225 16:15:43.469178       1 main.go:57] registering controllers
I0225 16:15:43.469800       1 controllers.go:45] new controller user-cluster-controller added
I0225 16:15:43.470096       1 controllers.go:45] new controller rbac-user-cluster-controller added
I0225 16:15:43.470250       1 leaderelection.go:185] attempting to acquire leader lease  cluster-6jtdrzvnx5/controller-leader-election-helper...
I0225 16:15:43.470302       1 main.go:89] starting the internal HTTP metrics server: 0.0.0.0:8085
E0225 16:15:43.529617       1 leaderelection.go:238] error initially creating leader election record: namespaces "cluster-6jtdrzvnx5" not found
I0225 16:15:43.529666       1 leaderelection.go:190] failed to acquire lease cluster-6jtdrzvnx5/controller-leader-election-helper
E0225 16:15:47.187137       1 leaderelection.go:238] error initially creating leader election record: namespaces "cluster-6jtdrzvnx5" not found

```

```release-note
NONE
```

### CODE REVIEW

**Review by alvaroaleman — COMMENTED** [review]
Oups. Should've testes this :grimace: Can we change the namespace to Kube-System?

**Comment by zreigz** [comment]
let me check this

**Comment by zreigz** [comment]
I was wondering why my e2e test are failing :)
Definitely, we need e2e for user cluster controller. Tomorrow I will add some for RBAC controller

**Comment by zreigz** [comment]
@alvaroaleman PTAL

**Pull request merged**
