### PR TITLE
Bump OSM and MC version

### PR DESCRIPTION
**Pull request by pkprzekwas**
**What this PR does / why we need it**:
Updates machine-controller to v1.57.3 and OSM to v1.3.2.

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update machine-controller to v1.57.3 and OSM to v1.3.2.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xrstf — CHANGES_REQUESTED** [review]
Please also update the tags in `pkg/resources/`

**Comment by embik** [comment]
/hold

I don't think this should be merged. @ahmedwaleedmalik just bumped the versions in #12571, the commits in questions both come from MC's and OSM's `main` branch and are therefore more recent than the patch releases. It's likely just go's confusing way of referencing non-tagged revisions.

At best, we can bump OSM to the same commit as the image in question for consistency.

**Comment by embik** [comment]
For the v2.23 component updates, please open a PR directly against `release/v2.23`.

**Comment by pkprzekwas** [comment]
> For the v2.23 component updates, please open a PR directly against `release/v2.23`.

Created direct PR https://github.com/kubermatic/kubermatic/pull/12577

**Comment by xrstf** [comment]
@pkprzekwas please do a 

```
cd pkg/resources/test
go test -update
git add .
git commit -am "codegen"
git push
```

(there is also a Makefile target for this, but it never quite worked for me, somehow  :-D )

**Comment by embik** [comment]
I believe this PR should just be closed tbh.

**Pull request closed without merging**
