### PR TITLE
Automatically add team/* labels as per OWNERS files

### PR DESCRIPTION
**Pull request by nikhita**
This will automatically add the `team/lifecycle` label to PRs modifying files which have `team-lifecycle` as reviewers/approvers.

This will help PRs to get automatically added to the "Review/QA" column in ZenHub. We can then filter using `team/*` labels and check which PRs are under review.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/lgtm
/approve

This is awesome :) 

/meow

**Comment by p0lyn0mial** [comment]
nice!

/lgtm
/approve

**Pull request merged**
