### PR TITLE
Update Dashboard dependencies to use dashboard-ee by default

### PR DESCRIPTION
**Pull request by floreks**
**What this PR does / why we need it**:
As `dashboard` image is no longer considered EE, I have updated the code to use `dashboard-ee` instead.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
I've adopted your fix to the `values.yaml` (dashboard => dashboard-ee) into my PR #5470, so I guess this one can be closed?

**Comment by floreks** [comment]
Yep

**Pull request closed without merging**
