### PR TITLE
Bump Helm dependency to 3.14.3

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:

Helm had some CVEs, so this bumps the dependency in our code to 3.14.3.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update Helm version used by KKP to 3.14.3
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
After the one or two fuckups from Helm, I got scared to bump it. That's why we have this ancient version in our Dockerfile.

And now I feel uncomfortable bumping the Go dependency, but not the helm binary in our Dockerfile. WDYT?

**Comment by embik** [comment]
> After the one or two fuckups from Helm, I got scared to bump it. That's why we have this ancient version in our Dockerfile.
> 
> And now I feel uncomfortable bumping the Go dependency, but not the helm binary in our Dockerfile. WDYT?

I would like to YOLO it, we can always revert it if we discover problems on dev. But not upgrading Helm is not a solution in my mind, as users will have more recent Helm versions installed too. Where is the Dockerfile to bump the Helm binary?

**Comment by xrstf** [comment]
https://github.com/kubermatic/kubermatic/blob/main/Dockerfile#L28

**Pull request merged**
