### PR TITLE
Migrate from Godeps to glide & upgrade k8s to 1.3.5

### PR DESCRIPTION
**Pull request by scheeles**

### CODE REVIEW

**Comment by scheeles** [comment]
@sttts can you review especially the commits 46f22ec  853e625  a5887cd

Can we merge?

**Comment by s-urbaniak** [comment]
You are not checking in the vendored source. Your mileage may vary but if an external repo disappears, you are left with local copies only. We decided to check in vendored sources in rkt not to risk source availability.

**Comment by s-urbaniak** [comment]
Gah, you _are_ checking in the sources in another commit, sorry, I overlooked that ;-) Nevertheless consider stripping as described in https://github.com/kubermatic/api/issues/66#issuecomment-241188309.

**Comment by scheeles** [comment]
Thanks for the hint with glide-vc. I wasn't aware of it. I will add it and cleanup the vendor package.

**Pull request merged**
