### PR TITLE
Added optional thanos sidecar in Prometheus to ease integration of external Thanos in the stack

### PR DESCRIPTION
**Pull request by dharapvj**
**What this PR does / why we need it**:
With #11424, we removed Thanos support from our Seed monitoring. Some of the arguments for removal are important and valid. But currently, the Cortex based monitoring stack is not available for seed. So, as of now, anyone who has KKP 2.22+ installation does not have seed level metrics beyond 5 days. This makes support really difficult.

We tried to add back the Thanos helm chart by ourselves but it still needs Prometheus sidecar to push metrics to Thanos. Alternative way of using Thanos receiver is overly complicated and resource hungry.

In this PR - we propose to bring back ONLY the Thanos sidecar in prometheus and corresponding alerts so that external Thanos helm chart can get the data fed in. By default the sidecar will be kept disabled.

**Which issue(s) this PR fixes**:

None

**What type of PR is this?**

/kind feature
/kind regression

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Made Prometheus helm chart extensible so that external metric storage solutions like Thanos can be easily integrated for seed long-term monitoring.
```

**Documentation**:

```documentation
https://github.com/kubermatic/docs/pull/1496
```

### CODE REVIEW

**Comment by dharapvj** [comment]
> wouldn't it be better to provide documentation to enable Thanos integration using the mechanisms already in the chart? e.g. show how to add correct labels, use correct config instead of the if in Prometheus container and eventually allowing arbitrary sidecar in Prometheus?

May be I could not see it how. The issue that I see is.. we need to start prometheus differently passing additional parameters etc when we start with Thanos sidecar. Can we discuss and then do the PR correctly?

**Comment by dharapvj** [comment]
This PR is now ready for re-review.

Have added `sidecarContainers`, `podLabels`, minor fix for `extraArgs` param, unconditional enabling of `web-admin-api` (which remains accessible only within the cluster) to allow me plug-in thanos.

And removed thanos scraping and alert rules. Which I add myself in my own installation via `values.yaml` customization

**Comment by wurbanski** [comment]
This looks much cleaner to me, thank you! 

/lgtm

**Comment by dharapvj** [comment]
@wurbanski - somehow LGTM did not work.. you will need to re-approve it.

**Comment by xmudrii** [comment]
@dharapvj Can you please update the release note to match the latest changes made to the PR? Please do the same for cherry-pick PRs.

**Comment by dharapvj** [comment]
@xmudrii - so do I edit the release note directly? or in the description of this issue? Since I have not done direct editing of release-notes before.. I thought I would check with you.

**Comment by dharapvj** [comment]
I do not have access on cherry picked PRs to edit description :(

**Comment by xmudrii** [comment]
> so do I edit the release note directly? or in the description of this issue?

You did it correctly -- the release note is in the PR description in a code block marked with `release-note`. To change the release note, it's sufficient just to change that block in the PR description.

> I do not have access on cherry picked PRs to edit description :(

I went ahead and copied the release note from this PR. For the future reference, you can easily change release notes using the `release-note-edit` command: https://github.com/kubermatic/kubermatic/pull/12468#issuecomment-1641863315

For example:

`````
/release-note-edit
```release-note
New release note
```
`````

**Comment by ahmedwaleedmalik** [comment]
What's up with the release note on this PR?

```
New release note
```

**Comment by ahmedwaleedmalik** [comment]
The docs comment is wrong as well. It should have just been `NONE` instead of 

```
- NONE (no documentation needed for this PR)
```

**Comment by dharapvj** [comment]
> What's up with the release note on this PR?
Ha ha... marco was [showing me how to edit release notes](https://github.com/kubermatic/kubermatic/pull/12425#issuecomment-1641866305).. in the process here edited existing releases with sample values 🤣 

I have re-fixed the notes now.

**Pull request merged**
