### PR TITLE
Update conformance test versions & Extend CI e2e coverage

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
- Update versions to test in the conformance test tool
- Remove the version limitation from the CI conformance test script

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@mrIncompetent This will quadruple the run time. We should instead make the version configurable via an env var and add three new presubmits, one per version

**Comment by mrIncompetent** [comment]
@alvaroaleman Why will this quadruple the run time?
All clusters are being created in parallel & so are the ginkgo tests

**Pull request merged**
