### PR TITLE
Refactor dualstack tests to use KubeAPI

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This is the last remaining test suite that depends on the KKP API and so getting rid of this dependency is the last step before we can remove the KKP API alltogether from this repo.

This PR also includes the WIP code for alibaba.

/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by rastislavs** [comment]
@xrstf FYI, due to the recent switch to external CCM for AWS, the `pre-kubermatic-dualstack-e2e-aws` my fail just because of that. This will be resolved as part of https://github.com/kubermatic/kubermatic/issues/11171.

In the meantime, you can use for example `pre-kubermatic-dualstack-e2e-gcp` to test this and feel free to override the AWS one if GCP passes.

**Review by embik — APPROVED** [review]

**Pull request merged**
