### PR TITLE
Update cloud provider SDKs

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This bumps all cloud provider SDKs to their latest versions.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
🤞 
/approve

**Comment by xrstf** [comment]
@ahmedwaleedmalik Should be good to go now, PTALA :)

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
/unhold

(never buying a Cherry keyboard ever again in my life...)

**Pull request merged**
