### PR TITLE
Another round of CRD sync

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
In order to keep new OpenAPI v3 CRDs in sync with our old schemaless-CRD types.

PRs to sync:
* #8352

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
@xrstf PR rebased, PTAL again.

**Review by xrstf — APPROVED** [review]
/approve

You might need to bump again if the OSM CRD PR is merged before yours.

**Comment by xrstf** [comment]
@kron4eg please bump version again 😁

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
