### PR TITLE
Fix openshift

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

/assign @mrIncompetent

### CODE REVIEW

**Comment by alvaroaleman** [comment]
CC @zreigz I _think_ this should fix the node creation

**Comment by zreigz** [comment]
@alvaroaleman thanks for this. I will test when it's merged. Unfortunately, I can't test it locally because controller-manager doesn't work locally for me.

**Pull request merged**
