### PR TITLE
Improve validation for certificate issuer in KubermaticConfiguration

### LINKED ISSUE #12674: KKP custom certificates: invalid spec
### What happened?

According to the docs at https://docs.kubermatic.com/kubermatic/v2.23/tutorials-howtos/kkp-configuration/custom-certificates/#kkp I have to simply set `spec.ingress.certificateIssuer.name` to an empty string in `KubermaticConfiguration` in order to use my own custom certificates, and not use an issuer from cer-manager.
However, when configuring the KubermaticConfiguration exactly as shown in the example in the docs, this will not work and fail with an error message:
```
INFO[0066]    📝 Applying Kubermatic Configuration…
INFO[0067]    ✅ Success.
ERRO[0067] ❌ Operation failed: failed to apply Kubermatic Configuration: KubermaticConfiguration.kubermatic.k8c.io "kubermatic" is invalid: spec.ingress.certificateIssuer.kind: Required value.
```

### Expected behavior

I expected this configuration to work:
```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    certificateIssuer:
      name: ""
    className: nginx
    domain: my-wonderful-domain.com
```

Ideally that configuration should not result in an invalid spec for `KubermaticConfiguration.kubermatic.k8c.io`.

Either `spec.ingress.certificateIssuer.kind` should need to be made optional, or the example provided by the docs at https://docs.kubermatic.com/kubermatic/v2.23/tutorials-howtos/kkp-configuration/custom-certificates/#kkp should be updated to include the required value:
```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    certificateIssuer:
      name: "" # empty string disables the cert-manager integration
      kind: ClusterIssuer # serves no purpose
    className: nginx
    domain: my-wonderful-domain.com
```

### How to reproduce the issue?

Apply the following KubermaticConfiguration to a new/fresh KKP installation:
```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    certificateIssuer:
      name: ""
    className: nginx
    domain: my-wonderful-domain.com
```

### How is your environment configured?

- KKP version: `v2.23.4`
- Shared or separate master/seed clusters?: `shared` (irrelevant for this bug report)

### Provide your KKP manifest here (if applicable)

<details>

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    certificateIssuer:
      name: ""
    className: nginx
    domain: my-wonderful-domain.com
```

</details>

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
`CertificateIssuer` in KubermaticConfiguration shouldn't be considered a "required" field since it's not required when using custom certificates; cert-manager integration is not required.

Currently, users have to configure KubermaticConfiguration like this when using custom certificates which is not ideal:

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    certificateIssuer:
      name: "" # empty string disables the cert-manager integration
      kind: ClusterIssuer # serves no purpose
    className: nginx
    domain: my-wonderful-domain.com
```

**Which issue(s) this PR fixes**:

Fixes #12674

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
`CertificateIssuer` in KubermaticConfiguration is marked as an optional field; users can omit this field to use custom certificates
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
cc @kubermatic/sig-release-managers

**Comment by embik** [comment]
I'm not sure I get the original bug. The defaulting code (that is even modified in this PR) should already set the `kind` field if it's not set yet. This is the code snippet before this PR adds a nil pointer check:

```go
if configCopy.Spec.Ingress.CertificateIssuer.Kind == "" {
    configCopy.Spec.Ingress.CertificateIssuer.Kind = certmanagerv1.ClusterIssuerKind
    logger.Debugw("Defaulting field", "field", "ingress.certificateIssuer.kind", "value", configCopy.Spec.Ingress.CertificateIssuer.Kind)
}
```

if this logic wasn't working in the first place, are we sure these changes are fixing usage of this snippet (omitting the `kind` field)? Has this been validated?

```
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    certificateIssuer:
      name: "" # empty string disables the cert-manager integration
```

Don't get me wrong, making `spec.ingress.certificateIssuer` optional is sensible in general. It's a weird API. But I'm uneasy merging an change in API behaviour when we are in code freeze plus backporting it to release branches.

**Comment by ahmedwaleedmalik** [comment]
NP I can close the PR if you are uneasy with the changes and then someone else can take a look ;) In general, the reviewer had no issues with the changes but yeah your point might be valid as well.

**Pull request closed without merging**
