### PR TITLE
uses UpdateCloudSpec funtion when updating a cluster

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: The UpdateCloudSpec is a helper for updating the cloud spec, it rewrites cloud specific credentials if were not updated. Note that cloud credentials are removed from responses and they are empty on requests, for example when a client wants to upgrade a cluster it sends the full cluster spec without the credentials.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mrIncompetent — APPROVED** [review]

**Comment by p0lyn0mial** [comment]
@mrIncompetent isn't `release/v2.7` branch pre user management ? If yes, then we should only cherry-pick to `release/v2.8`

**Comment by mrIncompetent** [comment]
Should be only cherry-picked into v2.8

**Pull request merged**
