### PR TITLE
[release/v2.20] Addition of missing images to image-loader (#9518)

### PR DESCRIPTION
**Pull request by mlavacca**
**What does this PR do / Why do we need it**:
This is a manual cherry-pick of #9518 

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
The Image-loader utility now includes all the images used by KKP, considering also the provider-specific ones (e.g., CCM, CSI).
```

### CODE REVIEW

**Review by embik — APPROVED** [review]

**Comment by mlavacca** [comment]
I changed a small part related to the crdMigration, which made all the tests fail. @embik PTAL

**Review by embik — APPROVED** [review]

**Comment by mlavacca** [comment]
@maciaszczykm PTAL

**Pull request merged**
