### PR TITLE
containers/util: Add iproute2, iptables, socat.

### PR DESCRIPTION
**Pull request by thz**
Version bump to: kubermatic/util-1.1.0

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
What do we need these tools for?

**Comment by thz** [comment]
> What do we need these tools for?

Deducing routes, setting iptables rules (NAT).

**Comment by xrstf** [comment]
> Deducing routes, setting iptables rules (NAT).

And we need this for Kubermatic because .... ? ;-) That iptables is used for managing iptables is something the man page could have told me :-p I don't want to annoy just, but instead make sure that in half a year we still know where we needed iptables.

**Comment by thz** [comment]
We need this for offline scenarios where the outbound connection attempts from Pods on workers to the ClusterIp of the Kubernetes Service (10.10.10.1) need to be translated (DNAT) towards an AWS VPC Endpoint to bridge the gap between workers in one VPC and the control-plane in another VPC. This is going to happen in a small controller running as a DaemonSet. 
We could alternatively create a dedicated util-net image, but we should try to keep maintenance needs low. The added tools are neither complex not huge, and pretty standard.

**Pull request merged**
