### PR TITLE
Match public IP address SKU to load balancer SKU for Azure

### LINKED ISSUE #10673: Public IP SKU does not match Load Balancer SKU when using `standard` LBs in Azure
### What happened?

I created an Azure cluster with `spec.cloud.azure.loadBalancerSKU` set to `standard`, a setting we support since a while. I also created a MachineDeployment within that cluster with public IP addresses enabled.

When trying to create a `Service` of type LoadBalancer, reconciling the Service fails with this error:

```
"error": {
    "code": "DifferentSkuLoadBalancersAndPublicIPAddressNotAllowed",
    "message": "Different basic sku and standard sku load balancer or public Ip resources in availability set is not allowed /subscriptions/<SUBSCRIPTION ID>/resourceGroups/kubernetes-twczbmcm4r/providers/Microsoft.Network/loadBalancers/twczbmcm4r and /subscriptions/<SUBSCRIPTION ID>/resourceGroups/kubernetes-twczbmcm4r/providers/Microsoft.Network/publicIPAddresses/twczbmcm4r-worker-vplvvd-7576494d7c-km472-netiface-pubip.",
    "details": []
  }
```

The problem is that when using the Standard SKU for load balancers, any public IP associated with a backend node must be of the same SKU type (see [Azure docs for reference](https://docs.microsoft.com/en-us/azure/virtual-network/ip-services/public-ip-addresses#sku)). KKP does not seem to do that correctly, creating public IPs with the Basic SKU.

### Expected behavior

The service gets reconciled and makes my service available via an Azure LB. For that to work, MachineDeployments need to use the `standard` SKU for public IP addresses. This might rely on a potentially missing feature in MC as well (opened https://github.com/kubermatic/machine-controller/issues/1395 for that).

### How to reproduce the issue?

1. Create Azure cluster with `standard` Load Balancer SKU
2. Create MachineDeployment with public IPs enabled
3. Try to create a LoadBalancer service, sample manifest below:

<details>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: gcr.io/google-containers/echoserver:1.8
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver
```
</details>
4. Inspect the `echoserver` Service via `kubectl describe`

### How is your environment configured?

- KKP version: `master` 
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

Azure

### What operating system are you running in your user cluster?

Ubuntu 20.04

### PR DESCRIPTION
**Pull request by embik**
**What does this PR do / Why do we need it**:

This PR fixes an issue with the `standard` load balancer SKU that apparently went unnoticed since #7208: When running with that LB SKU and using public IPs on your nodes, the public IP address SKU not matching the LB SKU will fail load balancer reconciliation. 

Through a new field in Azure's cloud spec in MC, the IP address SKU can now be set (previously, it was defaulted to basic unless dualstack was used). This PR defaults the IP address SKU on any MachineDeployment to `standard` to match the LB.

This needs a new MC release, so the PR is a draft and there's an override for a fresh MC commit.

I also took the liberty to upgrade our conformance test scenarios to the `standard` LB. It's the SKU recommended by Azure anyway.

**Does this PR close any issues?**:
Fixes #10673

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
When using the "standard" load balancer SKU for Azure clusters, MachineDeployments use the same SKU for public IP addresses
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
@embik can we move forward with this one? :D

**Comment by embik** [comment]
> @embik can we move forward with this one? :D

There's still no MC release that includes the necessary fields ...

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
