### PR TITLE
[release/v2.20] Update OSM and Machine Controller

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What does this PR do / Why do we need it**:

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
* Update OSM to v0.4.5
* Update machine-controller to v1.45.1
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
Almost all the tests would fail, that's expected. 

https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif

**Comment by moadqassem** [comment]
/approve
/lgtm 

cc @mfranczy & @xrstf

**Review by moadqassem — APPROVED** [review]
/approve
/lgtm

cc @mfranczy & @xrstf

**Pull request merged**
