### PR TITLE
mla: remove docker-related selector in some charts in kubernetes overview

### LINKED ISSUE #12500: MLA: Kubernetes Overview Dashboard pods cpu/memory usage empty
### What happened?
Panels for pods' CPU and memory usage are empty in Kubernetes Overview Dashboard.

### Expected behavior
Panels should show the data.

### How to reproduce the issue?
Install Usercluster MLA for a cluster, open dashboard.

### How is your environment configured?

- KKP version: tested on 2.22, possibly older as well
- Shared or separate master/seed clusters?: not important

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?
not relevant

### What operating system are you running in your user cluster?
not relevant

### PR DESCRIPTION
**Pull request by wurbanski**
**What this PR does / why we need it**:
This makes charts in kubernetes-overview dashboard work better

**Which issue(s) this PR fixes**:

fixes #12500

**What type of PR is this?**

**Special notes for your reviewer**:
the k8s_* prefix was left in some of the queries explicitly related to docker

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
mla: fixes for the kubernetes overview dashboard in grafana
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by wurbanski** [comment]
/assign @xrstf 

I'm still not sure about the queries for docker, do you have an idea how we can make sure that those actually show docker and not all containers in general?

**Comment by xrstf** [comment]
I don't know, but for now I would just like to see data at all. Then we can still filter down, I guess?

**Pull request merged**
