### PR TITLE
Update MC to latest image

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Update MC to latest image https://github.com/kubermatic/machine-controller/commit/24477483799684149f0b2633a967f0ef85278a6a

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

/assign @mohamed-rafraf

### CODE REVIEW

**Review by mohamed-rafraf — APPROVED** [review]

**Comment by ahmedwaleedmalik** [comment]
Seems like the issue is not fixed 

> {"level":"error","time":"2024-06-03T08:38:31.417Z","logger":"machine-controller","caller":"machine/controller.go:391","msg":"Reconciling failed","machine":"kube-system/md-rockylinux-7599f695dc-6xr75","error":"An error of type = InvalidConfiguration, with message = Failed to get AMI-ID for operating system rockylinux in region eu-west-1: could not find Image for 'rockylinux' with arch 'x86_64' occurred"}

/hold

**Comment by ahmedwaleedmalik** [comment]
@xrstf `pre-kubermatic-test-integration` needs override, seems like something is wrong with vSphere.

**Review by mohamed-rafraf — APPROVED** [review]

**Pull request merged**
