### PR TITLE
add startup container

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Add startup container. 
This is necessary as upstream never build a new container with the latest [script](https://github.com/kubernetes/contrib/blob/master/startup-script/manage-startup-script.sh).

The latest version creates checkpoints for each passed `STARTUP_SCRIPT` by hashing its content.
This ensures that changing `STARTUP_SCRIPT` will trigger a new run.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
When approved, i'll change the tag in the release script

**Comment by alvaroaleman** [comment]
/lgtm

Maybe also add an addon for this? It wont do anything unless activated but my assumption is that we will need this more often :)

**Comment by mrIncompetent** [comment]
> Maybe also add an addon for this? It wont do anything unless activated but my assumption is that we will need this more often :)

Only as a follow up and if we know exactly what we want to do with it.
Right now it only helps debugging

**Review by alvaroaleman — APPROVED** [review]

**Comment by alvaroaleman** [comment]
Testing the cherrypick bots permissions...


/cherrypick release/v2.8

**Pull request merged**
