### PR TITLE
Update LICENSE correct company

### PR DESCRIPTION
**Pull request by xmulligan**
**What this PR does / why we need it**:
The license is under the wrong company. Loodse GmbH doesn't exist anymore.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:
NONE
```release-note
NONE
```

### CODE REVIEW

**Review by xrstf — CHANGES_REQUESTED** [review]
You forgot the LICENSE in the root directory. ;-)

**Comment by xmulligan** [comment]
added :D

**Comment by xmulligan** [comment]
@scheeles ?

**Comment by xmulligan** [comment]
@scheeles will this get merged before I leave?

**Comment by xrstf** [comment]
🎉

**Comment by xmulligan** [comment]
🎊 finally got my last PR from Loodsie times merged

**Pull request merged**
