### PR TITLE
Add canal 3.25 support

### PR DESCRIPTION
**Pull request by mate4st**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add support for canal 3.25
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Comment by xrstf** [comment]
Next time please add some details to your PR. Empty PRs are of the devil.

**Comment by xrstf** [comment]
/approve cancel

This doesn't look like it's actually working.

**Comment by xrstf** [comment]
Not sure if this is flaking or not. But suddenly some nodes don't come up, with no errors or failures being logged by anyone. Only the MC is incapable of approving some CSRs, other than that, everything looks fine... except that is doesn't work :D

**Pull request merged**
