### PR TITLE
rename nodePortPoxy to nodePortProxy

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This is another attempt at fixing ye ol' `nodePortPoxy` typo. Previous PRs simply renamed the root key, but because this could bring customers into trouble when updating, the PR had been rejected.

This PR however goes the extra mile and uses a `poxy.value | default proxy.value` stanza everywhere. By defining a stub for the old `nodePortPoxy` root key, this is not entire madness, just ... slight madness. It would look okay if we didn't define an affinity for envoy itself, but because we do and want to properly handle all cases where customers might have defined some other affinity options, it got a bit out of hand.

**Does this PR introduce a user-facing change?**:
```release-note
nodePortPoxy Helm values has been renamed to nodePortProxy, old root key is now deprecated; please update your Helm values
```

### CODE REVIEW

**Comment by xrstf** [comment]
cc @mrIncompetent

**Review by kron4eg — APPROVED** [review]
/lgtm 
/approve

**Comment by mrIncompetent** [comment]
Docs must be updated: https://github.com/kubermatic/docs/blob/master/content/upgrading/2.10_to_2.11/_index.en.md

**Comment by xrstf** [comment]
Docs branch was already being prepared: https://github.com/kubermatic/docs/pull/127

**Comment by xrstf** [comment]
/hold cancel

Seems like there are finally no objections to this bold step forward :-)

**Comment by mrIncompetent** [comment]
/lgtm
/approve no-issue

Honest apologies for the bad communication last time!

**Pull request merged**
