### PR TITLE
Remove AWS AvailabilityZone endpoint

### PR DESCRIPTION
**Pull request by alvaroaleman**
We care about the subnets only and the subnets contain the AZ they
belong to, so there is no reason to have a dedicated AZ endpoint.

/assign @kgroschoff 

Please verify the UI doesn't use this :)

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
CC @kdomanski

**Comment by kgroschoff** [comment]
Thanks a lot for taking care! 👍 

As you're already on it, could you please delete `AWSZone ` & `AWSZoneList` in here: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/api/v1/types.go#L149
And `AWSZoneReq` in here: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/v1/provider/aws.go#L45

Apart from that looks good so far.

Opened up a Frontend PR to also remove the endpoint. Wasn't used anymore.

**Comment by alvaroaleman** [comment]
@kgroschoff I have removed it as well, I think there are no remainders of the AWS zone endpoint now. The apiclient generation fails thought :( I have to sit with @zreigz and figure out why

**Comment by kgroschoff** [comment]
Thanks! Will wait with lgtm then, as it will be removed again 😅 
/approve

**Pull request merged**
