### PR TITLE
bump AWS CCM

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
It's time we finally use a 1.30 CCM for 1.30 clusters.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update AWS CCM to v1.27.9, v1.28.9, v1.29.6, v1.30.3.
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

@xrstf can we please improve the release note and add a bit more details? Adding the versions that we now support would make it more coherent.

**Comment by xrstf** [comment]
> @xrstf can we please improve the release note and add a bit more details? Adding the versions that we now support would make it more coherent.

But I'm sooooo laaazy... :grin: 

Images have not been created yet, so I guess we just wait.

/hold

**Comment by xrstf** [comment]
I gave up on waiting for the AWS CCM maintainers to _eventually_ promote their images and have instead reverted down to the latest available images as per https://explore.ggcr.dev/?repo=registry.k8s.io%2Fprovider-aws%2Fcloud-controller-manager

**Comment by xrstf** [comment]
@ahmedwaleedmalik PTALA

/unhold

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
