### PR TITLE
Update MC and OSM to latest images

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Update the images for MC and OSM to https://github.com/kubermatic/machine-controller/commit/eaccda7855b6cd493f082243e0a57027158d7bd0 and https://github.com/kubermatic/operating-system-manager/commit/ba7524a3021e6e6af1c28688b6f95f7bf79eaff3, respectively.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

/assign @xrstf

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
/lgtm cancel

Doesn't work atm :D

**Pull request merged**
