### PR TITLE
Add missing CRDs for OSM

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What does this PR do / Why do we need it**:

These CRDs got mistakenly removed with https://github.com/kubermatic/kubermatic/pull/9530

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
Well this throws a giant wrench into the "pkg/validation/ is the canonical source for k8c.io CRDs", if we put files there that are _not_ generated. Hmmm.... I think I would feel better if those OSM CRD's are only in charts/kubermatic-operator/, just like the VPA CRDs already are.

**Comment by ahmedwaleedmalik** [comment]
> I think I would feel better if those OSM CRD's are only in charts/kubermatic-operator/, just like the VPA CRDs already are.

Was hesitant while doing this but then having CRDs for `k8c.io` at two distinct places seemed kinda off. But I think it's fine if we keep external CRDs separate.

**Comment by ahmedwaleedmalik** [comment]
I think it makes sense to name the directory `operatingsystemmanager.k8c.io`, instead of just osm or operatingsystemmanager. @xrstf WDYT?

**Comment by xrstf** [comment]
The installer will not find the CRDs in this directory, the installer only applies what is in k8c.io/ and k8s.io/ -- you would have to adjust the installer.

**Comment by ahmedwaleedmalik** [comment]
> The installer will not find the CRDs in this directory,

Umm, I thought we were relying on Helm for the installation and it's the default `crd` directory for Helm. I should have tested this locally. Let me check on this again.

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
