### PR TITLE
enable nosprintfhostport linter

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
This one might be overkill.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
Is this really worth it? Don't want to sound too pessimistic though 😛

**Comment by kron4eg** [comment]
>  level=error msg="Running error: unknown linters: 'nosprintfhostport', run 'golangci-lint help linters' to see the list of supported linters" 

too fresh linter :)

**Comment by ahmedwaleedmalik** [comment]
> > level=error msg="Running error: unknown linters: 'nosprintfhostport', run 'golangci-lint help linters' to see the list of supported linters"
> 
> too fresh linter :)

golangci-lint v1.46.0 has added support for this. We should upgrade to that version anyways since it re-enabled a few linters that were disabled to support generics.

**Comment by xrstf** [comment]
Yeah, I saw. I thought that we were using the build image to lint, which already includes v1.46.0, but instead the prowjob uses the upstream image and I forgot to bump it.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve ⚡

**Pull request merged**
