### PR TITLE
Implement the RuleGroup CRUD endpoints

### LINKED ISSUE #7088: Cortex Ruler API
Add API endpoints for managing cortex alertmanager rules and API will convert a group of rules from user to the `AlertmanagerRule` CR in the user-cluster namespace.

### PR DESCRIPTION
**Pull request by jiachengxu**
**What this PR does / why we need it**:
This PR adds get, list, create, update, and delete v2 endpoints for managing RuleGroup. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7088 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Add v2 endpoints for KKP users and admins to manage rule groups:
GET /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups
GET /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups/{rulegroup_id}
POST /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups
PUT  /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups/{rulegroup_id}
DELETE /api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups/{rulegroup_id}
```

### CODE REVIEW

**Comment by zreigz** [comment]
Please follow the common path pattern. Please change: `/api/v2/projects/{project_id}/clusters/{cluster_id}/rule_groups/{rule_group_name}` to `/api/v2/projects/{project_id}/clusters/{cluster_id}/rulegroups/{rulegroup_id}`

**Comment by jiachengxu** [comment]
Thanks @zreigz, the URL pattern is updated, PTAL

**Comment by zreigz** [comment]
from API perspective:
/lgtm

**Comment by jiachengxu** [comment]
Hey @zreigz, it seems that we don't have permission to approve this PR, can you please approve it? It also looks good from app-management perspective.

**Pull request merged**
