### PR TITLE
set resource requests & limits for all addon containers

### LINKED ISSUE #3267: Specify resource requests & limits for all addons
**Acceptance criteria**
- [ ] Specify resource requests & limits for all addons

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Set resource requests & limits for all Addon containers

Fixes #3267

**Does this PR introduce a user-facing change?**:
```release-note
Set resource requests & limits for all addons
```

### CODE REVIEW

**Review by alvaroaleman — COMMENTED** [review]
/lgtm
/approve
/hold

to bump the image tag

**Comment by mrIncompetent** [comment]
@alvaroaleman Tags updated, PTAL

**Review by alvaroaleman — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
