### PR TITLE
Bump OSM to 192412d78cbfb9d826fbc7cf7e077cfe7629d6ba

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
What it says on the title.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
@embik You need to update fixture data as well ;)

**Comment by embik** [comment]
> @embik You need to update fixture data as well ;)

True true. I did this before my first coffee, my mistake.

**Review by xrstf — APPROVED** [review]
/approve
/retest

**Comment by embik** [comment]
> /retest Seems like the dual-stack tests are failing after we bump OSM?! Since they seem to be 🟢 on other PRs.

It has also been failing for other PRs today (https://public-prow.loodse.com/job-history/gs/prow-dev-public-data/pr-logs/directory/pre-kubermatic-dualstack-e2e-aws), for example #11360.

**Comment by ahmedwaleedmalik** [comment]
Then at least it's not OSM 🕺

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
