### PR TITLE
Move usercluster controllers into pkg/controller/user-cluster-controller-manager/

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Moves all the controllers that run within the user-cluster-controller-manager binary from pkg/controllers into pkg/controller/user-cluster-controller-manager

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
