### PR TITLE
Opa config endpoints

### LINKED ISSUE #5895: OPA config - get and list endpoints
**User Story**
Create opa config get and list endpoint

### LINKED ISSUE #5896: OPA config - create endpoint
**User Story**
Implement OPA config create endpoint

### LINKED ISSUE #5898: OPA config - delete endpoint
**User Story**
Implement OPA config - delete endpoint

### PR DESCRIPTION
**Pull request by lsviben**
**What this PR does / why we need it**:
Adds get, create and delete endpoint for opa config.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5895, fixes #5896, fixes #5898 

**Does this PR introduce a user-facing change?**:

```release-note
v2 endpoints to manage opa config:
GET /api/v2/projects/{project_id}/clusters/{cluster_id}/gatekeeper/config
POST /api/v2/projects/{project_id}/clusters/{cluster_id}/gatekeeper/config
DELETE /api/v2/projects/{project_id}/clusters/{cluster_id}/gatekeeper/config
```

### CODE REVIEW

**Comment by zreigz** [comment]
Can you check what will happen when the user with viewer rights try to call those endpoints?

**Comment by lsviben** [comment]
> Can you check what will happen when the user with viewer rights try to call those endpoints?

good point, let me try

**Comment by lsviben** [comment]
> > Can you check what will happen when the user with viewer rights try to call those endpoints?
> 
> good point, let me try

Agreed to do it later on, added ticket for that - https://github.com/kubermatic/kubermatic/issues/6291

**Pull request merged**
