### PR TITLE
adds TokenVerifier and TokenExtractor plugins

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: this pull introduces plugins for token extraction and verification as it is needed for service accounts. The plugins are used by middlewares
in order to get and verify tokens from request in a generic way.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
See #3033 

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
the plugins are not used at the moment, I'll wire them in the next pull.

**Review by zreigz — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
