### PR TITLE
Improve rbac log messages in master-ctrl-mgr

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
This fixes ugly errors like

> failed to sync RBAC RoleBinding for &{kubermatic.k8c.io/v1, Resource=clusters kubermatic.k8c.io/v1, Kind=Cluster %!s(*meta.restScope=&{root})} resource for kubermatic cluster provider: rolebindings.rbac.authorization.k8s.io "kubermatic:etcdrestore:viewers" already exists

Now it will read:
> failed to sync RBAC RoleBinding for Cluster resource for kubermatic cluster provider: rolebindings.rbac.authorization.k8s.io "kubermatic:etcdrestore:viewers" already exists

To actually get rid of this error alltogether, we would need to finally refactor the RBAC controller to use our reconciling framework.

PS: Fun fact, "kubermatic cluster provider" means "the 'kubermatic' Seed cluster".

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/lgtm
/approve

**Comment by ahmedwaleedmalik** [comment]
/hold
In case if it's not ready to be merged.

**Comment by xrstf** [comment]
@floreks PTAL

**Review by floreks — APPROVED** [review]
/approve

**Pull request merged**
