### PR TITLE
pass through ami from datacenters.yaml

### LINKED ISSUE #3168: Make default AMIs configurable on AWS
**User Story**
Similar to #1297 and #1397, we'd like to be able to configure default AMI ID for each distribution in the datacenter config.

**Acceptance criteria**
- [ ] `AWSSpec` contains a field of the type `ImageList` that gets deserialized from the datacenters config YAML
- [ ] that field is validated in `validateDatacenters` as it already happens for VSphere and OpenStack

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:

Fixes #3168

**Release note**:
```release-note
Make the default AMI's for AWS instances configurable via the datacenters.yaml
```

### CODE REVIEW

**Comment by kdomanski** [comment]
@mrIncompetent test failed because `api/pkg/resources/test/load_files_test.go` still attempts to fill the old field.

**Comment by alvaroaleman** [comment]
Docs PR?

**Comment by mrIncompetent** [comment]
Docs PR: https://github.com/kubermatic/docs/pull/114

**Comment by mrIncompetent** [comment]
Tests are fixed

**Pull request merged**
