### PR TITLE
update minio to RELEASE.2019-06-11T00-44-33Z

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
What the title says. This includes two Major Feature Releases with these major changes:

* Self-healing feature has been implemented. See (minio/minio#7604) for more details.
* Add admin API to send trace notifications to registered listeners. Support for MINIO_HTTP_TRACE environment variable has been removed. See (minio/minio#7128) for more details.
* MinIO server runs in high performance mode by turning off content-md5 sum calculation by default. See minio/minio#7609 for more details. To run MinIO server in strict S3 compatibility mode, please start server with --compat flag.
* Major performance improvements in listing. See (minio/minio#7611) for more details.
* Major performance improvements in bulk object deletes. See (minio/minio#7607 and minio/minio#7644) for more details.

I don't think anyone needs strict S3 compat, which is why I kept the "high performance mode" the default but added a flag to the values.yaml to re-enable strict compat when needed.

**Does this PR introduce a user-facing change?**:
```release-note
updated Minio to RELEASE.2019-06-11T00-44-33Z
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

Testing on dev whether the new release works.

**Comment by xrstf** [comment]
/hold cancel

Up/downloading files via AWS CLI still works as expected, even in high performance mode. The store-uploader is still uploading backup files as well.

**Review by kron4eg — APPROVED** [review]
/approve

**Pull request merged**
