### PR TITLE
update Metering request

### PR DESCRIPTION
**Pull request by mate4st**
**What this PR does / why we need it**:
Moves requests to ee package and clarify that requests are only available in ee version in swagger.

**Special notes for your reviewer**:
I set tags for swagger generation to ee so it includes the metering requests

```release-note
NONE
```

### CODE REVIEW

**Comment by floreks** [comment]
/approve

Leaving LGTM to @moadqassem

**Review by moadqassem — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
