### PR TITLE
[release/v2.20] Fix GCE tests (#10764)

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This is a manual backport of #10764.

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mfranczy** [comment]
for KubeVirt tests pass we will have to backport https://github.com/kubermatic/kubermatic/pull/10783 to 2.20

**Comment by mfranczy** [comment]
Related for KubeVirt CI tests https://github.com/kubermatic/kubermatic/pull/10790

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
