### PR TITLE
enable deadcode, bodyclose and gocritic linters

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This enables more linters and fixes all issues reported by them (running with the v1.17.1 locally, need to update the presubmit job as well).

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

Need to at least announce the new rules in our Slack before this can get forced upon everyone.

**Comment by alvaroaleman** [comment]
/assign zreigz
The lint presubmit is failing because the underlying golang-ci lint needs a bump

**Comment by zreigz** [comment]
Really good to see this :+1: 
/approve

**Pull request merged**
