### PR TITLE
support resource pool for vSphere

### LINKED ISSUE #7282: Add vSphere resource pool field in api and machine deployment
**User Story**
As a user I would like to attach a resource pool for vSphere my cluster.

**Acceptance Criteria**
- resourcePool filed exists in the user cluster api object
- pass a resourcePool path to the machine deployment object

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
Support resource pool for vSphere workloads.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7282

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
vSphere resource pool support in KKP  
```

### CODE REVIEW

**Comment by lsviben** [comment]
Do you want the ResourcePool to also be a part of the vSphere Presets? If yes, you should also add it here: https://github.com/kubermatic/kubermatic/blob/master/pkg/crd/kubermatic/v1/preset.go#L269

**Comment by moadqassem** [comment]
> Do you want the ResourcePool to also be a part of the vSphere Presets? If yes, you should also add it here: https://github.com/kubermatic/kubermatic/blob/master/pkg/crd/kubermatic/v1/preset.go#L269

Thanks for the hint @lsviben I would leave it as it is, as there is a big issue will be opened soon for including all fields for different cloud providers where they could fit in the presets :)

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
