### PR TITLE
Update tests to kind 0.16

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Time to update our kind version and test KKP on Kubernetes 1.25. Amazingly, nothing special has to be done on our side to upgrade :-)

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by embik — APPROVED** [review]

**Comment by xrstf** [comment]
#11008 should update MLA Grafana and thereby make this PR work. Until then we have to wait.

**Comment by xrstf** [comment]
/hold

> time="2022-10-10T21:04:50Z" level=error msg="❌ Operation failed: failed to deploy Cortex: failed to deploy Helm release: failed to install: Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: \"cortex-nginx\" namespace: \"mla\" from \"\": no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\"\nensure CRDs are installed first."
[2022-10-10T21:04:50+00:00] Cleaning up clusters...

cc @wurbanski  ^^

**Comment by xrstf** [comment]
And once Cortex is fixed, we end up in 

> time="2022-10-11T11:59:06Z" level=error msg="❌ Operation failed: failed to deploy Minio Bucket Lifecycle Manager: failed to deploy Helm release: failed to install: Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: \"minio-lifecycle-mgr\" namespace: \"\" from \"\": no matches for kind \"CronJob\" in version \"batch/v1beta1\"\nensure CRDs are installed first."time="2022-10-11T11:59:06Z" level=error msg="❌ Operation failed: failed to deploy Minio Bucket Lifecycle Manager: failed to deploy Helm release: failed to install: Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: \"minio-lifecycle-mgr\" namespace: \"\" from \"\": no matches for kind \"CronJob\" in version \"batch/v1beta1\"\nensure CRDs are installed first."

I already begin to love these massive dependencies we created for MLA... This is gonna continue to be fun in the future.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
