### PR TITLE
Bump operating-system-manager to v0.3.2

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Bump operating-system-manager to v0.3.2

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Bump operating-system-manager to v0.3.2
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve
/hold
until #8535 is not merged

**Comment by ahmedwaleedmalik** [comment]
Closing this PR in favor of #8570

**Pull request closed without merging**
