### PR TITLE
remove validation for externalcluster providername

### PR DESCRIPTION
**Pull request by imharshita**
Signed-off-by: Harshita sharma <harshita.sharma6174@gmail.com>

**What does this PR do / Why do we need it**:
remove validation for externalclsuter providername.
Since ExternalCluster ProviderName possible values are not determined.
Temporarily removing the validation to avoid issues specificaly for clsuters where providerName cannot be determined as we only have access of cluster kubeconfig

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Review by moadqassem — APPROVED** [review]
/approve 
/lgtm

**Comment by ahmedwaleedmalik** [comment]
> Since ExternalCluster ProviderName possible values are not determined.

What does that even mean? 

/hold

**Comment by ahmedwaleedmalik** [comment]
/unhold

Okay

**Pull request merged**
