### PR TITLE
[EE] Use kubermatic/api-ce repository for Community Edition

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
When building a CE version of Kubermatic, the Docker images will be put into a different Docker repository. This will aid in permission management (compared to using "EE tags" only, in the same repository). To make migration for existing users easier, the existing repo is now declared to be the EE repo, and `api-ce` / `dashboard-ce` will be for the Community Edition.

This PR extends the Kubermatic Operator so it is built for either the CE or the EE variant.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by kdomanski** [comment]
I think this alone will break a couple of things. Most notably the image in the charts is not updated.

**Comment by xrstf** [comment]
> I think this alone will break a couple of things. Most notably the image in the charts is not updated.

Care to explain? The Kubermatic Helm chart is deprecated, so only existing EE customers should ever need it. New customers should use the operator, which can handle CE and EE just fine.

**Comment by kdomanski** [comment]
The official documentation still refers to installation by wizard and/or charts and not the operator.
Our own automated deployments use the charts as well.

**Comment by xrstf** [comment]
> The official documentation still refers to installation by wizard and/or charts and not the operator.

Wrong: https://docs.kubermatic.com/kubermatic/master/installation/install_kubermatic/

> Our own automated deployments use the charts as well.

So? So they will continue to use quay.io/kubermatic/api as if nothing changed. Just like our existing customers.

**Comment by kdomanski** [comment]
Ah sorry, somehow I got redirected to v2.13 documentation and never noticed.

**Comment by xrstf** [comment]
> Our own automated deployments use the charts as well.

Also, yes, this is really a TODO we should get to soon.

**Pull request merged**
