### PR TITLE
add header to express that the example values is generated by a script

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
add header to express that the example values is generated by a script

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]

**Review by xrstf — APPROVED** [review]
If I could I would approve this twice.

**Comment by mrIncompetent** [comment]
@xrstf actually you can approve multiple times :grimacing:

**Review by xrstf — APPROVED** [review]
Awww yeah.

**Pull request merged**
