### PR TITLE
Perform vault login during offline deployment

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Perform vault login during offline deployment in CI script.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
/test pull-kubermatic-e2e-gcp-offline

Lets see if its still working

**Comment by alvaroaleman** [comment]
> Lets see if its still working

Lol.

/lgtm
/approve
/hold

So you can see its state

**Pull request merged**
