### PR TITLE
allow to re-enable the Grafana login form

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
In some situations we do not have Keycloak in front of cluster services and would still like to allow customers to login manually, i.e. when port-forwarding to Grafana for debugging cluster issues. This change makes it possible to have a plain ol' login form.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
>This change makes it possible to have a plain ol' login form.

In that case we should allow passing custom [auth config](http://docs.grafana.org/auth/overview/) down to grafana.

**Comment by xrstf** [comment]
We have the admin user already, which is useless right now. Without this PR, we cannot even use the Grafana on ci (yes, we now have Grafana on that cluster ;-)).

**Review by kron4eg — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
