### PR TITLE
Upgrade Canal to 3.27

### LINKED ISSUE #13237: Add Canal CNI version 3.27.3 & deprecate Canal < 3.24
### Description of the feature you would like to add / User story
Canal CNI version 3.27.3 (https://raw.githubusercontent.com/projectcalico/calico/v3.27.3/manifests/canal.yaml) and deprecate the versions below 3.24

It also brings a fix to IP set kernel incompatibility: https://github.com/kubermatic/kubermatic/issues/13236

### PR DESCRIPTION
**Pull request by cnvergence**
**What this PR does / why we need it**:
Upgrade Canal to 3.27.3 and deprecate 3.24.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/13237
Release notes: https://docs.tigera.io/calico/latest/release-notes/

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add Canal CNI version v3.27.3
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Review by cnvergence — COMMENTED** [review]
/approve

**Pull request merged**
