### PR TITLE
Switch vcenter datastore used for CI

### PR DESCRIPTION
**Pull request by mate4st**
**What this PR does / why we need it**:

Switch vcenter datastore used by our CI.

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by WeirdMachine** [comment]
/unhold

manual tests looking good

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
