### PR TITLE
Remove optional=true setting from prow jobs

### PR DESCRIPTION
**Pull request by embik**
**What does this PR do / Why do we need it**:

This is a PR to start a discussion, not necessarily to be merged as a whole.

IMO, no prow jobs should be configured with `optional: true`. The reason for that is that it skips [checks for auto merging](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#requiring-jobs-for-auto-merge-through-tide). Usually, all of our jobs should succeed. In particular, cloud provider jobs are configured with this, but they only trigger when provider-specific code is changed - If the provider implementation is changed, our e2e tests should be a prerequisite for merging it! If they fail, our e2e setup might not be working, but then we cannot trust the PR anyway. Otherwise we might break a provider and don't realise we did.

There's just very few exceptions where these jobs can be disregarded, in particular if a provider is known to be flaky due to provider-side issues or long-term infra issues. I'm not aware we have that at the moment, but we can introduce it for jobs later on.

WDYT @xmudrii @xrstf @moadqassem?

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

Signed-off-by: Marvin Beckers <marvin@kubermatic.com>

### CODE REVIEW

**Comment by embik** [comment]
/hold

For discussing this PR.

**Comment by WeirdMachine** [comment]
/lgtm 

:100:

**Pull request merged**
