### PR TITLE
Update load test to cover external cloud provider

### PR DESCRIPTION
**Pull request by irozzo-1A**
**What this PR does / why we need it**:
ref: #6750 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
@irozzo-1A Is this a manual reverse backport?

**Comment by irozzo-1A** [comment]
> @irozzo-1A Is this a manual reverse backport?

Sorry for the delay @xrstf, the fix I added in #6750 was not needed in master branch, I just ported the tests.

**Pull request merged**
