### PR TITLE
Update machine-controller module to k8c.io/machine-controller

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Machine-controller module has been moved to `k8c.io/machine-controller`. This PR also updates MC image to the latest commit https://github.com/kubermatic/machine-controller/commit/7f090ad5fc651ffb44d8f716735f32b692973506.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/approve
For `sig-api` approval

**Comment by xrstf** [comment]
I think retesting will not help:

```
INFO[9:13AM]: go.keploy.io/server@v0.8.6: verifying module: checksum mismatch
        downloaded: h1:4u2GnKgMdI2FKiwSl8SLLNSoslUfvvnWk1efIbDdWG0=
        sum.golang.org: h1:czE9jaliyAkMMJcYnMPNuu6tun7UgwFbokxEG95vLN4=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
        http-method=GET http-path=/go.keploy.io/server/@v/v0.8.6.zip kind=Not Found module= operation=download.ZipHandler ops=[download.ZipHandler pool.Zip protocol.Zip protocol.processDownload stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule] request-id=e306390c-43cf-415f-b6c7-49e94633e0bd version=
```

keploy must have moved the 0.8.6 tag, creating a permanent unfixable drift. The only way I know of how to fix this is to bump our dependency to a functioning tag.

**Comment by ahmedwaleedmalik** [comment]
> keploy must have moved the 0.8.6 tag, creating a permanent unfixable drift. The only way I know of how to fix this is to bump our dependency to a functioning tag.

Yeah, I figured that out. Instead of pinning keploy, i'll rather pin `github.com/nutanix-cloud-native/prism-go-client` because there is no way we can test if the module upgrade for prism-go-client works or not, or if it breaks something for us.

**Comment by xrstf** [comment]
/override pre-kubermatic-e2e-vsphere-ubuntu-1.31
/override pre-kubermatic-e2e-vsphere-ubuntu-1.31-customfolder

/approve
/lgtm

**Review by cnvergence — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
/override pre-kubermatic-e2e-openstack-ubuntu-1.31

This is the ever-flaky LoadBalancer in our OpenStack environment. In an effort to be green, let's skip the CI retests.

**Pull request merged**
