### PR TITLE
Disable insecure versions v1.13.6 & v1.14.2

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Both versions are insecure: https://github.com/kubernetes/kubernetes/issues/78308

Keeping both versions commented out will avoid that users manually add those versions.

**Does this PR introduce a user-facing change?**:
```release-note
Insecure Kubernetes versions v1.13.6 and v1.14.2 have been disabled.
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@mrIncompetent Both of them are not in release/v2.10 so that cherrypick is not needed

/lgtm
/approve

**Comment by mrIncompetent** [comment]
@alvaroaleman 
> Keeping both versions commented out will avoid that users manually add those versions.

**Pull request merged**
