### PR TITLE
Fix spelling across code base, ignore third-party CRDs

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
Spellcheck suddenly started to care about typos in the `verify` Prow job. This fixes all spelling mistakes it could find from my local spellcheck installation, but it looks like it matches the Prow job failures.

I'm also excluding CRDs from third-party components that we shouldn't touch.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind cleanup

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by embik** [comment]
/cherry-pick release/v2.23

🤞🏻

**Review by wozniakjan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
