### PR TITLE
Update CSI driver

### LINKED ISSUE #6591: Update CSI addon
Current CSI addon (namely provisioner, but probably other too) contains old images that result to errors like this:

```
I0218 21:45:39.572684       1 controller.go:1196] provision "web/www-web-0" class "cinder-csi": started
E0218 21:45:39.602302       1 controller.go:1213] provision "web/www-web-0" class "cinder-csi": unexpected error getting claim reference: selfLink was empty, can't make reference
```

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
To fix the bug with old CSI components

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6591 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Update CSI drivers
```

### CODE REVIEW

**Comment by xrstf** [comment]
@kron4eg Shouldn't the openstack tests still pass?

**Comment by kron4eg** [comment]
@xrstf yeah, some RBAC permissions were missing

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
