### PR TITLE
Leaderelection: Always exit on lost leader lease

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

* Makes sure that we exit on lost leader lease rather than getting stuck in a defunct state as observed in some e2e tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by bashofmann** [comment]
Could this be cherry-picked into 2.12? We also have seen this occasionally.

**Comment by alvaroaleman** [comment]
> Could this be cherry-picked into 2.12? We also have seen this occasionally.

Yeah, definitely.

/cherrypick release/v2.12

**Pull request merged**
