### PR TITLE
Add isDefault flag to ruleGroup

### PR DESCRIPTION
**Pull request by rastislavs**
**What does this PR do / Why do we need it**:
Rebase of original PR https://github.com/kubermatic/kubermatic/pull/8459

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rastislavs** [comment]
@aborilov any chance you could sign-off your old commits?

**Comment by aborilov** [comment]
> @aborilov any chance you could sign-off your old commits?

do you mean some thing like `git rebase --signoff origin/master`?

**Comment by rastislavs** [comment]
> > @aborilov any chance you could sign-off your old commits?
> 
> do you mean something like `git rebase --signoff origin/master`?

@aborilov yeah, exactly.

**Comment by aborilov** [comment]
> > > @aborilov any chance you could sign-off your old commits?
> > 
> > 
> > do you mean something like `git rebase --signoff origin/master`?
> 
> @aborilov yeah, exactly.

but it's your repo, not sure I can do that

**Pull request closed without merging**
