### PR TITLE
Reduce ucc log level

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
This sets the log level of the UCC to 2 when being deployed by Kubermatic.
The default run script keeps using 4.

This just follows our logging guidelines: https://github.com/kubermatic/kubermatic/blob/master/docs/logging.md

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
Should these be changed as well?

https://github.com/kubermatic/kubermatic/blob/86ea417287f76db7b259809ec235ef6a29cb837c/api/pkg/controller/usercluster/reconciler.go#L20

https://github.com/kubermatic/kubermatic/blob/86ea417287f76db7b259809ec235ef6a29cb837c/api/pkg/controller/rbac-user-cluster/reconciler.go#L17

**Comment by mrIncompetent** [comment]
> Should these be changed as well?

Yes, i'll issue a follow up PR to remove that or was there any specific reason why we use a const as log level?

**Comment by mrIncompetent** [comment]
I unified the logging with https://github.com/kubermatic/kubermatic/pull/2946/commits/a5a40900cb34216a8a29632f7b029366b618401d

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

/assign @zreigz 
for rbac-user-cluster controller changes

**Comment by mrIncompetent** [comment]
/hold

I'm going to make the fixtures a bit more pretty

**Comment by mrIncompetent** [comment]
/hold cancel

@nikhita @zreigz  PTAL

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Review by zreigz — APPROVED** [review]
/approve

**Pull request merged**
