### PR TITLE
[release/v2.25] upgrade Canal to 3.27.3 (#13239)

### PR DESCRIPTION
**Pull request by cnvergence**
**What this PR does / why we need it**:
Add Canal with an updated version, containing an important fix to ipset kernel module incompatibility.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/13236

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add Canal CNI version v3.27.3, having a fix to the ipset incompatibility bug.
```

**Documentation**:

```documentation
TBD
```

### CODE REVIEW

**Review by embik — APPROVED** [review]
/approve

**Review by cnvergence — COMMENTED** [review]
/approve

**Comment by cnvergence** [comment]
/assign ahmedwaleedmalik
PTAL

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
