### PR TITLE
Add Script to verify that Chart Versions

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This adds a new script that is called as a presubmit to validate that our Charts are properly versioned.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@xrstf can we have an optional presubmit and test here that it works properly?

**Comment by xrstf** [comment]
Thought the same after creating this PR. Will send the optional presubmit PR now.

**Comment by xrstf** [comment]
Job succeeded. Will now add a dummy change to a chart to trigger the verification.

**Pull request merged**
