### PR TITLE
Bump Go dependencies

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This bumps all but the Kubernetes dependencies. The k8s dependencies should stay in-sync with controller-runtime and a dedicated PR to bup it will be opened soon (right now it's blocked because of https://github.com/open-policy-agent/gatekeeper/pull/2853).

Likewise, etcd dependencies have not been touched to keep them in-sync with the versions we deploy.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by embik — APPROVED** [review]
/approve

**Review by wozniakjan — APPROVED** [review]
/lgtm
/approve

**Comment by embik** [comment]
/retest

flake, happens sometimes.

**Pull request merged**
