### PR TITLE
[release/v2.21] Upgrade Anexia CCM to v1.5.0

### PR DESCRIPTION
**Pull request by LittleFox94**
**What this PR does / why we need it**:

Title says it all, upgrade Anexia CCM to v1.5.0.

Manual backport of #11501 

**What type of PR is this?**
/kind feature
/kind chore

**Documentation**:
```documentation
NONE
```

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update Anexia CCM (cloud-controller-manager) to version 1.5.0
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by LittleFox94** [comment]
tests done, now only needs the `do-not-merge/cherry-pick-not-approved` label removed ^^

**Pull request merged**
