### PR TITLE
Fix unauthorized eks kubeconfig

### PR DESCRIPTION
**Pull request by imharshita**
Signed-off-by: Harshita sharma <harshita.sharma6174@gmail.com>

**What this PR does / why we need it**:
Fix unauthorized eks kubeconfig by reverting `migration of aws-sdk-v2`
*This is a temporary change the issue is found with aws-sdk-v2

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
/hold

We shouldn't merge this, please take a look at #11045 instead.

**Comment by imharshita** [comment]
> /hold
> 
> We shouldn't merge this, please take a look at #11045 instead.

**Pull request closed without merging**
