### PR TITLE
Ci conformance testing

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes
**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
Why not follow the issue and:
> It deploys the kubermatic version of that PR into a dedicated namespace

?
That way, we would also test if the kubermatic chart works with its default values.

**Comment by alvaroaleman** [comment]
@mrIncompetent I'm fine with changing it like that but maybe in a follow-up?

**Comment by alvaroaleman** [comment]
And also, maybe doing both? That way we know if only the chart is broken or more

**Comment by mrIncompetent** [comment]
> @mrIncompetent I'm fine with changing it like that but maybe in a follow-up?

sgtm

> And also, maybe doing both? That way we know if only the chart is broken or more

The chart should be our main focus as that is what customers use - not the dev/hack scripts.
Whats the benefit in maintaining both? We test the hack script?

**Comment by alvaroaleman** [comment]
> The chart should be our main focus as that is what customers use - not the dev/hack scripts.
Whats the benefit in maintaining both? We test the hack script?

If we do not run everything as a presubmit we know on the next day that only the chart is broken, not the actual code

**Pull request merged**
