### PR TITLE
Refactor etcd scale up/down

### LINKED ISSUE #6711: Improve stability for scale up/down operations

### LINKED ISSUE #7505: etcd-launcher crashes during restore operation due to missing permissions
We're running KKP 2.17.2 and we've enabled both the experimental etcd-launched and the experimental new backup/restore controllers. Everything seems to work fine until we create an `EtcdRestore` resource.

This causes the etcd-launcher to crash with the following log entries:
```
$ k -n cluster-2wsfk6pbjv logs etcd-0 
{"level":"info","time":"2021-08-16T21:17:28.713Z","caller":"etcd-launcher/main.go:559","msg":"restoring datadir from backup","backup-name":"default-backups-2021-08-16t15-34-41"}
{"level":"fatal","time":"2021-08-16T21:17:28.728Z","caller":"etcd-launcher/main.go:98","msg":"failed to restore datadir from backup","error":"failed to get s3 client: failed to get CA bundle ConfigMap: configmaps \"cluster-2wsfk6pbjv-ca-bundle\" is forbidden: User \"system:serviceaccount:cluster-2wsfk6pbjv:etcd-launcher\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""}
```

I've tracked this down in code as follows.

The logged error stems from here:
https://github.com/kubermatic/kubermatic/blob/efcd9b123fa4b751ee3756d15663639ed1fb5fb4/cmd/etcd-launcher/main.go#L561-L564

Inside the `resources.GetEtcdRestoreS3` method called above, we can find the next piece of the error message here:
https://github.com/kubermatic/kubermatic/blob/efcd9b123fa4b751ee3756d15663639ed1fb5fb4/pkg/resources/resources.go#L1260-L1263

And here we have the `BackupCABundleConfigMapName` method called above:
https://github.com/kubermatic/kubermatic/blob/efcd9b123fa4b751ee3756d15663639ed1fb5fb4/pkg/resources/resources.go#L1176-L1178

It appears the code implicitly wants to access the `cluster-<cluster-id>-ca-bundle` configmap in the `kube-system` namespace. Thus I think the error is that this permission isn't granted when the etcd-launcher feature is enabled in a cluster.

However, I wonder - why would it fetch that configmap from the `kube-system` namespace? Isn't the `ca-bundle` configmap in the cluster's own namespace (here `cluster-2wsfk6pbjv`) identical, requiring less privileges?

Anyway, I don't think this can be fixed in the configuration, so I think I hit a bug in the etcd-launched :)

### LINKED ISSUE #7544: Etcd backup restore missing perissions to access s3-settings configmap
When using the new backup and restore feature (https://docs.kubermatic.com/kubermatic/v2.17/cheat_sheets/etcd/backup-and-restore/), during the restore phase, the etcd pods are crashlooping because their service account doesnt have access to the `s3-settings` configmap on `kube-system`.

`{"level":"info","time":"2021-08-19T15:59:50.939Z","caller":"etcd-launcher/main.go:559","msg":"restoring datadir from backup","backup-name":"test-backups-2021-08-19t17-26-14"}
{"level":"fatal","time":"2021-08-19T15:59:50.944Z","caller":"etcd-launcher/main.go:98","msg":"failed to restore datadir from backup","error":"failed to get s3 client: failed to get CA bundle ConfigMap: configmaps \"cluster-mg4z4wp4lg-ca-bundle\" is forbidden: User \"system:serviceaccount:cluster-mg4z4wp4lg:etcd-launcher\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""}`

Adding a clusterrole and clusterrolebinding giving permission fixes the issue and the restore finishes succesfully.

### PR DESCRIPTION
**Pull request by moelsayed**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6711
Fixes #7544
Fixes #7505

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
The Spec for the user-cluster etcd Statefulset is updated. This will cause the etcd pods  for user-clusters to be restarted on KKP upgrade. 
```

### CODE REVIEW

**Review by moadqassem — COMMENTED** [review]
/approve 
/lgtm

**Comment by xrstf** [comment]
/override pre-kubermatic-opa-e2e 

Not relevant to this PR.

**Pull request merged**
