### PR TITLE
[EE] remove support for deprecated static datacenters.yaml

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Support for "dynamic datacenters", i.e. what we call today the `Seed` CRD, was added back in KKP 2.13. As it was experimental, it had to be enabled explicitly via `-dynamic-datacenters`.

With the advent of the KKP Operator, using Seeds became required (the operator always set the CLI flags) and support for the old `datacenters.yaml` became tied to the lifetime of the old `kubermatic` Helm chart.

2.18 ended shipping the deprecated chart and it's now time to get rid of all CLI flags, conversion code etc. for handling the `datacenters.yaml`.

**Does this PR introduce a user-facing change?**:
```release-note
[BREAKING] `-dynamic-datacenters` was effectively already always true when using the KKP Operator and has now been removed as a flag. Support for handling a `datacenters.yaml` has been removed.
```

### CODE REVIEW

**Comment by xrstf** [comment]
cc @shaase-ctrl

**Comment by shaase-ctrl** [comment]
Very good @xrstf

**Pull request merged**
