### PR TITLE
Make `etcd-launcher` a multi-tool for etcd cluster management

### LINKED ISSUE #12109: Prepare etcd templates for distroless image in 3.5.7 version
### Description of the feature you would like to add / User story

Since version [3.5.7](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md#security) all etcd images are built upon distroless base images.
We should check and update all our etcd templates and related jobs, like etcd-defragger to not exec `/bin/sh` and come up with alternatives to prepare KKP for etcd bump.

### Additional information

Currently, KKP is using etcd in version 3.5.6.

### How is your environment configured?

- KKP version: v2.22.1

### LINKED ISSUE #12203: Update etcd to v3.5.9
### Description of the feature you would like to add / User story

etcd v3.5.8 has [some important bug fixes related to Kubernetes](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md), concretely:

> Fix [Watch response traveling back in time when reconnecting member downloads snapshot from the leader](https://github.com/etcd-io/etcd/pull/15515)

We should update etcd to pick those bug fixes.

### Solution details

- Ensure we deploy etcd v3.5.8 or newer for all Kubernetes versions
  - as of June 2023, the preferred version to go to is **v3.5.9**

### Additional information

We might need to fix #12109 before addressing this issue.

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
This PR updates `etcd-launcher` to become a multi-tool for operating etcd clusters. The reason behind this is that our auxiliary containers (defragmentation and checking health before starting the kube-apiserver) no longer work with etcd 3.5.7+ as the base image changed to distroless, which means no shell for us anymore.

This is the first of two PRs, the second one will be updating etcd past version 3.5.6 with the new etcd-launcher in place already. 

**Which issue(s) this PR fixes**:

Fixes #12109

**What type of PR is this?**
/kind cleanup
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
/hold

missing a fix for #12109.

**Comment by embik** [comment]
The update etcd 3.5.6 to 3.5.7 seemingly breaks DNS resolution and I have absolutely no idea why.

**Comment by xrstf** [comment]
This had nothing to do with DNS, but with distroless not having a shell, which does not break etcd, but our apiserver Deployment:

>  Warning  Failed       18s (x3 over 36s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

etcd itself is healthy.

**Comment by embik** [comment]
/hold cancel

This hold is obsolete, this is WIP anyway.

**Pull request closed without merging**
