### PR TITLE
Add an endpoint for deleting Machine Deployments

### LINKED ISSUE #2215: Create an endpoint for deleting MachineDeploments
**User Story**
In order to introduce MachineDeployment support, we're going to need an API endpoint for the UI to delete MachineDeployments

The new endpoint shall be DELETE `/api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/nodesets/{nodeset_id}`, analogous to the existing DELETE `/api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/nodes/{node_id}` endpoint. Instead of a `Machine` CRD, it will delete a `MachineSet` CRD.

**Acceptance criteria**

 * A DELETE `/api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/nodesets/{nodeset_id}` endpoint exists, and deletes a MachineDeployment corresponding to the provided `nodeset_id`.
 * There is a unit test for the functionality

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**: It adds an endpoint for deleting Machine Deployments. Besides that it also contains update for generating unique selectors for Machine Deployments during their creation (as it was missing in #2339 /cc @alvaroaleman).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Fixes #2215

**Special notes for your reviewer**: I am currently preparing unit tests. I have done manual test using Dashboard. MachineDeployment, MachineSet, Machine and Nodes seem to be deleted correctly after deletion of MachineDeployment:

https://github.com/kubermatic/dashboard-v2/compare/create-md?expand=1#diff-656f0718f18ffb3e2b0413c67636627c

Release notes will be added in last PR.

**Documentation**: n/a

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Modulo some testing, LGTM

**Review by alvaroaleman — APPROVED** [review]

**Comment by maciaszczykm** [comment]
@mrIncompetent Can you take a look?

**Comment by mrIncompetent** [comment]
I'll do that first tomorrow morning :)

**Comment by maciaszczykm** [comment]
Thank you, I don't want to interrupt you, just pinging :)

**Review by mrIncompetent — APPROVED** [review]
Nice! I love the fact that we test the interaction with the client cluster as well!

**Pull request merged**
