### PR TITLE
removes unused /v1/user endpoint

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: removes unused /v1/user endpoint

Release note:
```release-note
NONE
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
@kgroschoff confirmed that this endpoint is not used by the dashboard.

**Comment by mrIncompetent** [comment]
I'm not sure if we should remove it. We maybe should rather implement it in the dashboard?
It will tell the current logged in user.
That way we could show what others could use to invite a user?

**Comment by p0lyn0mial** [comment]
if we want to implement it, then we have to slightly change the paths, for example:

* to see the list of members of the given project, the client would have to call
   `GET /api/v1/project/{project_id}/users`

**Comment by mrIncompetent** [comment]
This endpoint is about returning the currently logged in user. So exactly whats stored inside the openid-connect-token. That's a common pattern - some call it the `/me` endpoint.

What does this has to do with the projects?

**Comment by p0lyn0mial** [comment]
What would be the use case for that ? To display information about the user ?

**Comment by mrIncompetent** [comment]
Correct, we can display information about the user.
Also when you want to add me to your project, what would you enter?
Not all users know their email address which is configured in the Auth system (Thinking about LDAP or custom implementations)

**Comment by p0lyn0mial** [comment]
yes, you are absolutely right :) 

However could we remove this endpoint and add a new one right after (I'll add an issue for that). ?
For my own personal goal. I'd like to change the api resource we are returning to the client :)

**Review by mrIncompetent — APPROVED** [review]

**Comment by p0lyn0mial** [comment]
created an issue https://github.com/kubermatic/kubermatic/issues/1596

**Pull request merged**
