### PR TITLE
upgrade go-git to v5.8.0

### PR DESCRIPTION
**Pull request by SimonTheLeg**
**What this PR does / why we need it**:

We have experienced with Apps sometimes the issue described here https://github.com/go-git/go-git/issues/328, which is supposed to be fixed in v5.8.0

**Which issue(s) this PR fixes**:

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix an issue in Applications, which resulted in "empty git-upload-pack given" errors for git sources
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
Can we add a release note please?

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/hold for release note. @SimonTheLeg remove the hold once the description is updated.

**Comment by pkprzekwas** [comment]
Keep in mind that this upgrade can be affected by: https://github.com/kubermatic/kubermatic/pull/11604

**Comment by SimonTheLeg** [comment]
@pkprzekwas I think this was re-introduced in 5.6.1

https://github.com/go-git/go-git/pull/655

**Comment by xrstf** [comment]
🎉 Awesome! :-)

**Pull request merged**
