### PR TITLE
bump Dex to 2.35.3

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
After the failed attempt to update Dex to 2.35.x in #11131, a new Dex release 2.35.2 fixes the original problem we encountered. Since 2.35.1+ is strongly recommended by upstream, we might need to backport this into all supported KKP releases.

/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update Dex to 2.35.3
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by wurbanski** [comment]
would you mind adding the tests to this chart while you're at it? pretty please ;)

**Comment by xrstf** [comment]
Can dooo.

**Comment by wurbanski** [comment]
thank you very much! 

/lgtm

**Comment by xrstf** [comment]
@wurbanski can you take a look again pls?

**Pull request merged**
