### PR TITLE
Adjust the memory requests/limits for VerticalPodAutoscaler components

### PR DESCRIPTION
**Pull request by archups**
**What this PR does / why we need it**:
Adjust memory requests/limits for VPA admission-controller and updater component, to avoid encountering of the OOMKilled issue.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Increase the default resources for VPA components to prevent OOMs
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
Please:

1. Give a reason for increasing the _default_ values. Some setups might run into OOM issues, that is sort of expected and why you can configure this in your `KubermaticConfiguration`. But it's not clear from the PR description why it's updated for everyone.
2. Give a release note, this is a user-facing change.

**Comment by archups** [comment]
Thank you @embik  for reviewing and feedback.

Here are the 2 reasons based on which the values adjustment in general is proposed : 
- Monitoring metrics data collected from customer production environment - real-time scenario/usecase.
- Checked the VPA repo https://github.com/kubernetes/autoscaler/tree/vpa-release-0.14/vertical-pod-autoscaler/deploy the values defined in the respective manifest are already on the higher side then what we have configured as defaults.

**Review by embik — APPROVED** [review]
/approve

**Comment by archups** [comment]
> @archups why backport this to `release/v2.23` but not `release/v2.24`?

my bad.. missed it. I created now cherry-pick PR for `release/v2.24` as well. Thank you @embik :)

**Pull request merged**
