### PR TITLE
downgrade Elastic Stack to 6.7 to allow rolling upgrades later

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Performing rolling upgrades to 7.0 from anything but 6.7 is [not supported](https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html). To not force customers to restart their logging cluster, we postpone our 7.0 upgrade to Kubermatic 2.11 and instead ship 2.11 with 6.7 (i.e. this PR is supposed to be cherry-picked into 2.10).

This PR also improves the index-pattern setup logic to not run into an endless loop and replaces the old deprecated `elasticsearch.url` property with the new `elasticsearch.hosts`.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cherry-pick release/v2.10

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]
/lgtm 
/approve

**Comment by mrIncompetent** [comment]
@xrstf Can you create a cherry pick PR for v2.10 ?

**Comment by xrstf** [comment]
yes

**Pull request merged**
