### PR TITLE
Use k8c.io/reconciler

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Many, many moons ago we wrote our reconciling framework and over the years it has served us very well.

So well in fact that other repos (OSM, MC, dashboard) started to import our reconciling framework, which was never intended.

To combat this, I have now finally pulled the plug and moved the framework into https://github.com/kubermatic/reconciler so that it can be easily re-used (and it's so cheap to generate your own reconcilers that there should never be a need to import another repo's reconcilers).

So this PR removes the reconciling framework from KKP and uses the new upstream library. Since it ships with a bunch of default reconcilers already, we only have to define a few custom ones here.

Naming has changed a little bit:

* `....Creator` is now `....Reconciler`.
* `Named....CreatorGetter` is now `Named....ReconcilerFactory`.

/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/retest

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
