### PR TITLE
Update controller-runtime to 0.18.1

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This updates KKP to the new controller-runtime version. There is one major change that affected us: the generics support in the controller. Manually setting up Watch() calls means you have to use typed generic stuff, which is _really_ verbose and a lot of boilerplate. I tried it with 3 controlllers and then quickly gave up. The code became unreadable.

It's much smarter to finally migrate everything to the controller builder, an abstraction we never used because back when KKP was written, the builder didn't support what we needed and then every time we created a new controller, we simply copy&pasted an existing one.

So this PR refactors every single controller in KKP to use the controller builder, which is a really nice interface and works perfectly for every controller in KKP.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update to controller-runtime 0.18.1
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
@kron4eg rebased 😁

**Review by cnvergence — APPROVED** [review]
/approve

**Pull request merged**
