### PR TITLE
CSI driver for DigitalOcean

### LINKED ISSUE #10367: Implement support for DigitalOcean CSI driver

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What does this PR do / Why do we need it**:
Implement support for DigitalOcean CSI driver.

**Does this PR close any issues?**:
Fixes #10367

**Special notes for your reviewer**:
CCM support for DigitalOcean should be covered under https://github.com/kubermatic/kubermatic/issues/8847

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
CSI driver for DigitalOcean 
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
It seems like my last-moment changes caused some issues, I've moved this back to WIP.

**Comment by ahmedwaleedmalik** [comment]
/test pre-kubermatic-e2e-do-centos-1.24

Looks like a flake 😨

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
