### PR TITLE
add elasticsearch lifecycle hooks

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
This follows the best practices described in the ES docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html

Instead of moving data, this just deactivates the shard allocation, which should be enough for our use case.

**Release note**:
```release-note
Add lifecycle hooks to the Elasticsearch StatefulSet
```

### CODE REVIEW

**Comment by kron4eg** [comment]
/lgtm
/approve
/hold

Hold to let @xrstf see it too

**Comment by xrstf** [comment]
/hold cancel

Love it!

**Pull request merged**
