### PR TITLE
add missing owner reference on cluster namespace

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
add missing owner reference on cluster namespace

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by metalmatze — DISMISSED** [review]
Extract to func due to using it in two places now?

**Review by guusvw — DISMISSED** [review]
LGTM

**Comment by mrIncompetent** [comment]
@metalmatze Yep

**Review by guusvw — APPROVED** [review]
LGTM

**Pull request merged**
