### PR TITLE
Fix validation methods to work with Packet clouds

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**: Fixes ValidateCloudSpec method to accept PacketCloudSpec.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Related to #3419.

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
Thanks :) 

Looks like we need to add it here as well: https://github.com/kubermatic/kubermatic/blob/fe4d5fffe5194c1dd2850b01a7c83b7c6cc925fd/api/pkg/validation/cluster.go#L103

**Comment by maciaszczykm** [comment]
@nikhita True :)

**Review by nikhita — APPROVED** [review]
/lgtm

**Review by nikhita — APPROVED** [review]
/lgtm

**Comment by maciaszczykm** [comment]
I had to ignore `gocyclo` check for `ValidateCloudSpec`. I think we can create validation methods for each cloud provider if it is not okay. At the moment it would be nice to have it working as it blocks me with UI implementation.

**Pull request merged**
