### PR TITLE
added run.kubermatic.io to drone ci pipeline

### LINKED ISSUE #1753: Add run.kubermatic.io to the kubermatic/kubermatic & kubermatic/secrets pipeline
**User Story**
Deployment of the new kubermatic code to `run.kubermatic.io` must be managed by our droneCI pipeline, defined in `kubermatic/kubermatic` and `kubermatic/secrets`

**Acceptance criteria**
Deploy only new tagged releases to `run.kubermatic.io` automatically

**Definition of Done**
After new release tag it created `run.kubermatic.io` will get new version of the kubermatic code

### PR DESCRIPTION
**Pull request by glower**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1753

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
The drone.yaml gets generated by the .drone.jsonnet

**Comment by glower** [comment]
Added the config to .drone.jsonnet, generated new drone.yaml 
Connected with: https://github.com/kubermatic/secrets/pull/149

**Comment by alvaroaleman** [comment]
Do we really want to deploy master there?

**Comment by glower** [comment]
No, only tagged releases.
in the chart I have
```
    when:
      branch: release/*
```
Is this correct?

**Comment by mrIncompetent** [comment]
@glower can you set it to only deploy when merged to `release/v2.7` ?
We should strictly specify a release, otherwise we risk deploying a old minor version as we just cherry-picked something into the old release branch

**Comment by glower** [comment]
Yes, you are right, will fix it

**Comment by glower** [comment]
done

**Review by mrIncompetent — APPROVED** [review]

**Comment by alvaroaleman** [comment]
ping bot

**Comment by alvaroaleman** [comment]
Actually this should be targeted at `release/v2.7` and not be in `master` at all

**Comment by alvaroaleman** [comment]
@glower Talked to @mrIncompetent , we'll be putting this into master so having it in the next release is easier

**Review by alvaroaleman — APPROVED** [review]

**Comment by mrIncompetent** [comment]
ping @glower

**Comment by mrIncompetent** [comment]
ping @glower

**Pull request merged**
