### PR TITLE
change the node_dc/seed_dc label in InitNodeDeploymentFailures metric to `datacenter`

### PR DESCRIPTION
**Pull request by kdomanski**
**What this PR does / why we need it**:
Inconsistency between the metric's definition and actually applied label leads to a panic.

```release-note
NONE
```

/assign @alvaroaleman

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]
/lgtm
/approve

**Comment by nikhita** [comment]
Just bumping to check if the context for `pull-kubermatic-e2e-aws-coreos-1.15` will go green with a sync

**Comment by alvaroaleman** [comment]
/override pull-kubermatic-e2e-aws-coreos-1.15

as its green anyways

**Pull request merged**
