### PR TITLE
Refactor alertmanager Chart

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This applies the same changes to the Alertmanager chart as we just did for Prometheus in #3347. To give user clusters time to reconcile a fallback service is provided and slated to be removed in the first follow-up release to 2.11. The fallback is installed unconditionally because it's such a short-term solution, even though it prevents the Chart from being installed multiple times inside the same namespace.

**Which issue(s) this PR fixes**:
Relates to #3238

**Does this PR introduce a user-facing change?**:
```release-note
BREAK: refactored Alertmanager Helm chart for master-cluster monitoring, see documentation for migration notes 
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

Need to merge the migration.enabled=true flag first.

**Comment by xrstf** [comment]
/hold cancel

The required migration config has been merged to the secrets repo.

**Review by kron4eg — APPROVED** [review]
/lgtm
/approve

**Comment by xrstf** [comment]
/assign @alvaroaleman 

mrIncompetent is busy today, so maybe you can jump in :-)

**Pull request merged**
