### PR TITLE
Add more description for OpenStack

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This is a copy of Sebastian Schmitt's work in #13461, but adapted to fit in our build logic. Got no reaction on the original PR for some time, so adopting it is quicker now.

**What type of PR is this?**
/kind documentation

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by mohamed-rafraf — APPROVED** [review]

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
