### PR TITLE
Update Go to 1.19.1

### PR DESCRIPTION
**Pull request by xmudrii**
**What does this PR do / Why do we need it**:

This PR updates Go to 1.19.1 for all jobs and images used by KKP.

**Does this PR introduce a user-facing change?**:
```release-note
KKP is now built using Go 1.19.1
The `quay.io/kubermatic/util:2.2.0` Docker image does not ship with `yq3` and `yq4` anymore, but only `yq` (version 4.x).
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
@xmudrii Do we really need this for KKP 2.21?

**Comment by xrstf** [comment]
I would vote that yes, we should go to Go 1.19. There's still a full month of QA and that should be enough to find any critical issues.

**Comment by ahmedwaleedmalik** [comment]
> I would vote that yes, we should go to Go 1.19. There's still a full month of QA and that should be enough to find any critical issues.

Then we have a decision. I just want us to be consistent everywhere so I'd love if OSM, MC, KubeOne, and KKP are on the same version for Go. Although it's something that'd be nice to have; not mandatory.

**Comment by xmudrii** [comment]
This is on hold until further notice because Go 1.19 breaks Swagger generation (https://github.com/go-swagger/go-swagger/issues/2759).

**Comment by xrstf** [comment]
We're not patiently waiting for go-swagger/go-swagger/pull/2808 to be finished before we can progress. I don't think there's enough pressure to go to Go 1.19 for us at the moment in order to justify some workarounds in our codebase.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve 〽️

**Pull request merged**
