### PR TITLE
cluster cleanup: don't disable updates on PV, PVC and PDBs

### PR DESCRIPTION
**Pull request by nikhita**
This prevents cluster deletion since we use finalizers.

Ref: https://github.com/kubermatic/kubermatic/pull/3863

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
cleaned up a few stale clusters

/retest

**Comment by alvaroaleman** [comment]
Needs cherrypick but only after https://github.com/kubermatic/kubermatic/pull/3865 merged, so I will wait for that, then request the cherrypick

**Comment by alvaroaleman** [comment]
oh nvm, already in there

**Pull request merged**
