### PR TITLE
update machine-controller to v1.5.1

### PR DESCRIPTION
**Pull request by kdomanski**
```release-note
Updated machine controller to `v1.5.1`
```

/assign @alvaroaleman

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@kdomanski You also need to update the const which we use for the machine-controllers docker image tag in `pkg/resources/machine-controller`

**Comment by alvaroaleman** [comment]
This failed multiple times with all tests failing, this is almost guaranteed to not be a flake

**Comment by alvaroaleman** [comment]
/lgtm cancel
Something is wrong, we now import multiple versions of the Azure stuff

**Comment by kdomanski** [comment]
How do you figure that?

**Comment by alvaroaleman** [comment]
> How do you figure that?

By looking at the `Gopkg.lock`, there are only additions for azure, nothing removed

**Comment by kdomanski** [comment]
The updated Azure SDK for some reason removed certain API functions from the `2018-04-01` API, so I had to switch to the `2018-06-01` API in the cloud provider package. The machine controller didn't use any of the removed stuff, so it remained on `2018-04-01`, which is why both are in the dependency graph.

**Comment by alvaroaleman** [comment]
So why dont we use the 2018-06-01 version everywhere?

**Comment by kdomanski** [comment]
Because the update to the machine-controller came first and only later when updating kubermatic it turned out that some API calls were removed.

Note that this is API versions, not library versions.

**Comment by alvaroaleman** [comment]
Perfectly fine but the API versions seem to pull in the lib versions and I'd prefer to not have two of them. Would you be ok with doing the bump to the version that actually works on the machine-controller and then updating this to have only one version imported?

**Pull request merged**
