### PR TITLE
addons/kubelet-configmap: allow configuring QPS

### PR DESCRIPTION
**Pull request by kdomanski**
**What this PR does / why we need it**:
Addresses immediate requirements of kubermatic/customer-projects#256, thus reducing the pressure for #4777

```release-note
The QPS settings of Kubeletes can now be configured per-cluster using addon Variables
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
I _think_ we don't use this configmap unless kubeadm was used to join the nodes

**Comment by kdomanski** [comment]
All providers now optionally support dynamic kubelet config.

**Pull request merged**
