### PR TITLE
Sync v2.14 with current master

### PR DESCRIPTION
**Pull request by lsviben**
**What this PR does / why we need it**: Sync v2.14 with the current master. Adds dynamic datacenter and logout functionality and endpoints

**Does this PR introduce a user-facing change?**:

```release-note
Added dynamic datacenter and logout endpoints
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Related to https://github.com/kubermatic/dashboard/issues/2437.

**Comment by zreigz** [comment]
I've tested it with the UI
/lgtm
/approve

**Comment by zreigz** [comment]
@kdomanski PTAL

**Comment by kdomanski** [comment]
/hold
Why are you backporting features?

**Comment by zreigz** [comment]
because the UI requires this: datacenter management and logout

**Pull request closed without merging**
