### PR TITLE
[WIP] Replace the metrics-server with the prometheus metrics-adapter

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Replace the metrics-server with the prometheus metrics-adapter.

This PR has the following advantages:
- We have the cAdvisor metrics in Prometheus so we can utilize them (Dashboards / Alerts)
- With the cAdvisor metrics in Prometheus we avoid the overhead of the metrics-server own scraping(Scrapes the kubelet every 30sec). 
- Since the prometheus-metrics-adapter only talks to Prometheus, we can avoid having to run the OpenVPN sidecars - Reducing the number of containers per cluster by 4.

For concerns about stability/support:
RedHat uses it for OpenShift 4

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
/hold

Need to check what happens when Prometheus is not available & Update the resource requests/limits.

**Comment by xrstf** [comment]
Can you please extend your PR with reasons as to why you made this change? Is the Prometheus adapter faster? Uses less resources? Is the metrics-server deprecated?

**Comment by mrIncompetent** [comment]
@xrstf my fault, just extracted that changes from a testing PR of mine and haven't spent much time since then on this PR.

I've updated the PR description!

**Comment by alvaroaleman** [comment]
Some openshift folks mentioned on Kubecon barcelona that they want to rewrite the adapter. Should we close this PR @mrIncompetent ?

**Comment by mrIncompetent** [comment]
I've watched the recording.
They only mentioned that they want to rework the configuration & that they want to move it to a different org ?
Unless they mentioned something outside of the recording i would keep this PR until i have some time to test & polish this

**Comment by mrIncompetent** [comment]
Closing as RedHat is currently writing a new version from scratch

**Pull request closed without merging**
