### PR TITLE
Add support for Kubernetes 1.31

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
It's that time of the year again, a new Kubernetes release is out. This PR configures KKP to allow provisioning 1.31 clusters.

**What type of PR is this?**
/kind feature

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Add support for Kubernetes 1.31
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
@ahmedwaleedmalik FYI, the LoadBalancer tests are a bit flaky on OpenStack, failures are to be expected. I wonder if we should increase the timeout to deal with it. I have however seen all 1.27 to 1.31 tests for OpenStack pass at least _once_ 😁

**Comment by ahmedwaleedmalik** [comment]
> @ahmedwaleedmalik FYI, the LoadBalancer tests are a bit flaky on OpenStack, failures are to be expected. I wonder if we should increase the timeout to deal with it. I have however seen all 1.27 to 1.31 tests for OpenStack pass at least _once_ 😁

All good, we can increase timeout IMO.

I wanted to run VCD tests since MC tests for it failed due to some known issues. But ended up running all the tests. The KubeVirt tests issue is also known so all good.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve 🚀

**Comment by ahmedwaleedmalik** [comment]
/hold

@xrstf you'll have to rebase and update the fixtures

**Pull request merged**
