### PR TITLE
define a readiness probe for the kubermatic API server

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
This PR adds a readiness probe to the Kubermatic API server pod.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
Please also bump the chart version.

**Comment by mrIncompetent** [comment]
@xrstf 

> Please also bump the chart version.

Done with https://github.com/kubermatic/kubermatic/pull/3804/commits/708a0eb6a83b29e66a191e1e096186cfc9ef00be

**Comment by alvaroaleman** [comment]
I want haz cherrypick.
/cherrypick release/v2.11

/meow cherry

**Pull request merged**
