### PR TITLE
deploy user-mla iap on dev

### PR DESCRIPTION
**Pull request by SimonTheLeg**
**What type of PR is this?**

/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by SimonTheLeg** [comment]
@wurbanski @xrstf So the initial issue was that we have an if condition that checks if the value file contains europe, but the key was renamed. Theoretically adapting the if-statement would fix that.
But if I understand our current setup correctly, then we do not have our asia region anymore so from my side I would propose get rid of the clause completely. Wdyt?

**Comment by wurbanski** [comment]
> But if I understand our current setup correctly, then we do not have our asia region anymore so from my side I would propose get rid of the clause completely. Wdyt?

It's true at this exact moment but we might have another seed which could have it's own config sooner than later, so I'd keep the option of "defaulting" that we run now. but @xrstf  is likely more aware of the changes to come.

however until we figure that out:
/lgtm
/hold

**Comment by SimonTheLeg** [comment]
okay I propose we merge this for now. We can still simplify the if-statement in a separate PR 
/unhold

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
