### PR TITLE
update Websocket endpoint for the Web terminal

### LINKED ISSUE #10131: Update WEB terminal endpoint
- endpoint creates Pod
 - open WEB socket connection with the Pod

### PR DESCRIPTION
**Pull request by zreigz**
**What does this PR do / Why do we need it**: The endpoint will create the Pod on the user cluster and wait until the Pod running.

**Does this PR close any issues?**:
Fixes #10131

```release-note
NONE
```

### CODE REVIEW

**Review by hbernardo — APPROVED** [review]
/lgtm
/approve

**Comment by zreigz** [comment]
@hbernardo @imharshita I have to remove the previous source code for Pod creation and e2e test fro it

**Comment by zreigz** [comment]
@imharshita @hbernardo PTAL, now everything is fine

**Pull request merged**
