### PR TITLE
Use kubermatic api for all conformance tests

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/test pull-kubermatic-e2e-packet-coreos-1.14
/test pull-kubermatic-e2e-hetzner-ubuntu-1.14
/test pull-kubermatic-e2e-openstack-coreos-1.14
/test pull-kubermatic-e2e-vsphere-coreos-1.14
/test pull-kubermatic-e2e-azure-coreos-1.14
/test pull-kubermatic-e2e-gcp-coreos-1.14
/test pull-kubermatic-e2e-do-centos-1.14

Lets create some load :)

**Comment by alvaroaleman** [comment]
pull-kubermatic-e2e-packet-coreos-1.14

**Comment by alvaroaleman** [comment]
Hetzner is broken because of
```
Warning  Failed   7s (x2 over 20s)  kubelet, md-hetzner-ubuntu-1.14.2-0-6d698c796c-6gvxj  Failed to pull image "docker.iohetznercloud/hcloud-csi-driver:1.0.0": rpc error: code = Unknown desc = Error response from daemon: Get https://docker.iohetznercloud/v2/: dial tcp: lookup docker.iohetznercloud: no such hos
```

WIll create a separate PR to fix that up.

**Comment by alvaroaleman** [comment]
finaaaaalllyyy
/override pull-kubermatic-e2e-hetzner-ubuntu-1.14 

/pony green
/meow
/assign @nikhita

**Comment by nikhita** [comment]
Lgtm, but looks like we missed this test :)

/test pull-kubermatic-e2e-azure-coreos-1.15

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
