### PR TITLE
add endpoints to get vSwitches for alibaba provider

### LINKED ISSUE #6870: Add a new endpoint to get available vSwitch list for Alibaba provider
**User Story**

During cluster creation, the vSwitch ID is empty with suggestions. 
Add a new endpoint to get available vSwitch list for Alibaba provider

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: add endpoints to get vSwitches for Alibaba provider

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6870

```release-note
NONE
```

### CODE REVIEW

**Comment by zreigz** [comment]
@kgroschoff PTAL, you can also extend UI to display values from those endpoints.

**Review by kgroschoff — COMMENTED** [review]
/lgtm

Will take care about adding it to the ui.

**Pull request merged**
