### PR TITLE
[release/v2.19] Switch vcenter datastore used for CI

### PR DESCRIPTION
**Pull request by mate4st**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

Manual cherrypick of: https://github.com/kubermatic/kubermatic/pull/11361

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
I am not sure if these are flakes or actual issues. It's weird that the custom-datastore test worked, but the other 2 that relied on the default datastore config stuff failed..

**Review by embik — APPROVED** [review]
/approve

**Pull request merged**
