### PR TITLE
[release/v2.14] Add Support for Kubernetes 1.18 (#5325)

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This backports the Kubernetes 1.18 support (#5325) into the 2.14 release branch.

**Does this PR introduce a user-facing change?**:
```release-note
Add support for Kubernetes 1.18, drop support for Kubernetes < 1.15.
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold cancel

wrong window

**Comment by kdomanski** [comment]
I'll trust you that this is the same exact change as the original PR which you cherry-picked here.
/lgtm
/approve

**Pull request merged**
