### PR TITLE
Add Seed level MLA settings

### LINKED ISSUE #6904: Expose Seed level MLA configuration
Currently, user cluster MLA can be enabled/disabled on the cluster level:
```go
type MLASettings struct {
	// MonitoringEnabled is the flag for enabling monitoring in user cluster.
	MonitoringEnabled bool `json:"monitoringEnabled,omitempty"`
	// LoggingEnabled is the flag for enabling logging in user cluster.
	LoggingEnabled bool `json:"loggingEnabled,omitempty"`
}
```

The goal of this task is to introduce Seed level MLA configuration, that would allow enabling/disabling MLA on the Seed level. Global MLA admin settings will be handled in a separate task.

### PR DESCRIPTION
**Pull request by rastislavs**
**What this PR does / why we need it**:
Adds Seed level MLA settings. For now, the settings only allow to explicitly enable the user-cluster MLA (Monitoring, Logging & Alerting) stack on the Seed level (as the user-cluster MLA stack needs to be installed in Seed manually at this point).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6904

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Expose MLA options in the Seed CRD and API object
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/approve 

From the API perspective.

**Review by moadqassem — COMMENTED** [review]
/approve
/lgtm

**Review by moadqassem — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
