### PR TITLE
Openshift console: Fix login

### LINKED ISSUE #4880: Access to OpenShift Console not working
**User Story**

Using the `OpenConsole` button results in the following error message:
`did not get an OAuth code back from Openshift OAuth server<a href="/api/v1/projects/hd8tsh8xjf/dc/europe-west3-c/clusters/wthlsngrd6/openshift/console/proxy/auth/callback?code=&amp;state=">Found</a>.`

**Acceptance criteria**

OpenShift Console should be shown

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

When moving the management of the bootstrap secret into the usercluster controller, i started syncing the password hash rather than the password. This obviously does not work, hence this PR changes the whole thing to:

* Store the password encrypted via the UID of the CA secret that is in the seed in the usercluster secret
* Decrypt it and sync that into the seed

Fixes #4880 

~A further improvement could probably be move the reconciling of the secret inside the usercluster controller from the usercluster resource controller into the openshift-seed-syncer and then just check if the value in the seed when hashed matches whats in the usercluster. This is a bit tricky thought, as it ties the creation of two secrets together.~

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by xrstf** [comment]
We could rot13 it for added protection and a :white_check_mark: on the next audit.

/lgtm

**Comment by alvaroaleman** [comment]
/hold

Lets encrypt the raw password rather than storing it in plaintext

**Comment by alvaroaleman** [comment]
/hold cancel
@xrstf Updated the PR to not store the password in plaintext in the usercluster, PTAL

**Comment by xrstf** [comment]
I'm not sure the UIDs are a good source of crypto randomness, but it should be good enough(tm).

/lgtm

**Pull request merged**
