### PR TITLE
Source OpenStack CSI addon from upstream Helm chart

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This PR replaces the previous Openstack CSI driver with one generated from the upstream Helm chart. It also adds new Prowjobs for all supported Kube versions.

Additionally I cleaned up the secompProfile detection to reduce code duplication. The new code also accepts Pods where instead the Pod having a seccompProfile, it's also valid for each individual container to have one instead.

Lastly, I added the `enabled` flag to the Cilium CNI in order for it to output the security context on the hubble-ui Deployment. This solves half of the TODO comment; the hubble-generate-certs Job continues to not have any option for configuring the security context.

There is no migration needed for the CSI driver because the new Deployments/DaemonSets have `openstack-csi-` as their prefix, so they do not collide with the previous resources. We rely on the addon controller's `--prune` usage to make sure the old resources are automatically deleted.

part of #13597

**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Use upstream Cinder CSI Helm chart as the source for the OpenStack CSI addon.
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by wurbanski** [comment]
/lgtm
on the helm part, no clue about conformance tester

**Review by cnvergence — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
/override pre-kubermatic-e2e-openstack-ubuntu-1.31

LoadBalancers are known to be extremely unreliable at the moment. Previous tests in this PR have shown this to work, plus we will immediately after this is merged tag beta.1 and then run the full conformance tests anyway.

**Pull request merged**
