### PR TITLE
do not return a RequeueAfter and an error at the same time

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Since controller-runtime https://github.com/kubernetes-sigs/controller-runtime/pull/2451, a warning will be logged if a controller returns an error _and_ a non-zero result (i.e. a result with a RequeueAfter).

> {"level":"error","time":"2023-10-19T07:08:27.325Z","logger":"kkp-kubernetes-controller","caller":"kubernetes/cluster_controller.go:272","msg":"Reconciling failed","cluster":"kkp-1714890477536284672-mxd69","error":"failed to remove finalizers [kubermatic.k8c.io/cleanup-credentials-secrets] from Cluster /kkp-1714890477536284672-mxd69: clusters.kubermatic.k8c.io \"kkp-1714890477536284672-mxd69\" not found","errorCauses":[{"error":"failed to remove finalizers [kubermatic.k8c.io/cleanup-credentials-secrets] from Cluster /kkp-1714890477536284672-mxd69: clusters.kubermatic.k8c.io \"kkp-1714890477536284672-mxd69\" not found"}]}
> {"level":"info","time":"2023-10-19T07:08:27.325Z","caller":"controller/controller.go:266","msg":"Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler","controller":"kkp-kubernetes-controller","object":{"name":"kkp-1714890477536284672-mxd69"},"namespace":"","name":"kkp-1714890477536284672-mxd69","reconcileID":"62372ca4-c5cd-4937-bd8c-ead545e32340"}

This PR therefore adjusts all controllers to return errors "standalone", as an error itself will already trigger a reconciliation (with exponential backoff). Also, since controller-runtime already logs reconciling errors, I also removed all dedicated log statements. We lose a bit context and niceness, but at least every error isn't logged twice anymore.

**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/override pre-kubermatic-test-integration

Test is failing because the DC is offline. None of the integration tests have anything to do with reconciling.

**Review by embik — APPROVED** [review]
/approve

**Review by moadqassem — APPROVED** [review]
/approve

**Review by wozniakjan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
