### PR TITLE
remove unused and broken symlink

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Remove unused and broken symlink. 
Unused when https://github.com/kubermatic/infra/pull/246 got merged.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
/hold 
waiting for https://github.com/kubermatic/infra/pull/246 to be merged

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Comment by nikhita** [comment]
/hold cancel 
https://github.com/kubermatic/infra/pull/246 has merged

**Pull request merged**
