### PR TITLE
Remove -kubermatic suffix from Prometheus Chart

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
We want to install some of our charts multiple times into a cluster, especially Prometheus. In #3252 we started to make this easier by putting the release name into each identifier of the Prometheus chart (e.g. `prometheus-kubermatic-{{ .Release.Name }}`.

This was a good start, but leads to "stuttering" and ugly names, like a role being named `prometheus-kubermatic-prometheus` (guess which part is the release name). Having a `kubermatic` inside the names is only a hack someone made a long time ago to allow running a "Loodse Prometheus" next to the one used for Kubermatic. Considering that we "publish" the monitoring stack in github.com/kubermatic/monitoring and use it for non-Kubermatic customers, we should also think about not putting `kubermatic` anywhere into the charts.

This PR attemps to rectify all these issues by doing a "light" version of what many popular Helm charts already do: Use the release name unless the `nameOverride` variable is set. This allows us to for example install Prometheus as `prometheus-master` (release name) Into `monitoring-master` namespace and still have the resources be named `prometheus-config`, `prometheus-rules` etc.

For our dev master/seed cluster, we would have this configuration:

1. (seed prometheus): release name: `prometheus-seed`, namespace `monitoring`, name override `prometheus`
    * We would change the release name from `prometheus` to `prometheus-seed` because it makes the distinction to the master clearer *and* we can easily run this new release along the old (see below).
2. (master prometheus): release name: `prometheus-master`, namespace `monitoring-master`, name override `prometheus`

The biggest, gigantic, downside to this is that we lose data because the PVCs are not named `prometheus-kubermatic-db-[statefulset-name]-[index]` anymore, but `db-[statefulset-name]-[index]` (the name of the StatefulSet is already unique enough, no need to duplicate it into the PVC name). This means that customers "lose" their data (in the sense that it becomes inaccessible). A migration path could be that customers run Prometheus twice and keep the old for the duration of their retention period.

The Grafana and Alertmanager charts would need the same treatment, but at worst we lose configured silences.

**Which issue(s) this PR fixes**:
Relates to #3238

**Does this PR introduce a user-facing change?**:
```release-note
BREAK: refactored Prometheus Helm Chart for Master-Cluster monitoring, see documentation for migration notes 
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

If we ever decide that we actually want this, we must update the postsubmit Prow job to deploy this as a different chart or else all things fall apart.

**Review by kron4eg — APPROVED** [review]
/lgtm
/approve

**Comment by xrstf** [comment]
I have extended this PR with a more-or-less automated way to migrate existing configurations. By setting `prometheus.migration.enabled=true` in your values.yaml, the chart will *not* deploy the StatefulSet, but instead a Job that creates the PVCs for the new StatefulSet (`db-promtheus-0` and `db-prometheus-1`) and then rsyncs the data from `prometheus-kubermatic-db-prometheus-kubermatic-N` to `db-prometheus-N`. Once this job has finished, you disable the migration flag and deploy again and voila, you get a new StatefulSet that uses the new PVCs and boots up just fine.

At first I wanted to do this via an initContainer on the StatefulSet, but there is no way to retrieve the old PVC names and have them be mounted to the pods. Having a dedicated Job is the only halfway sane way of doing this.

The migration job will ensure that the target volume is empty and will create a lockfile so that once the volumes for replica 0 have been migrated, subsequent runs of the migration job would skip this volume (the job should never run more than once, but for safety sake there's a lockfile).

It's not a zero-effort migration, but this is something we can document easily:

```
helm upgrade --install --set prometheus.migration.enabled=true prometheus .
(wait....)
helm upgrade --install prometheus .
```

**Comment by mrIncompetent** [comment]
@alvaroaleman @xrstf @kron4eg 

Why is this PR not progressing ?

**Comment by xrstf** [comment]
I ran a test by installing the Prometheus chart under a new name into a new namespace, letting it scrape a bit of data for a few minutes, then performing the two migration steps and ended up with a working installation containing the pre-migration data.

Color me somewhat confident that this could work.

**Comment by xrstf** [comment]
/hold cancel

Let's do this!

**Pull request merged**
