### PR TITLE
Update to Go 1.20.2

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
KKP 2.22 has sailed, time to bump Go :)

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update to Go 1.20.2
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
Seems like this is blocked by https://github.com/golang/go/issues/58592 and we need to wait for Go 1.20.2.

**Review by embik — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
/override pre-kubermatic-opa-e2e

Hetzner blocking downloads again.

**Comment by xrstf** [comment]
/override pre-kubermatic-test-integration

vsphere VPN is down

**Pull request merged**
