### PR TITLE
Expose ApplicationInstallation status in api

### LINKED ISSUE #10366: Get/List of AppInstalls Should Include Statusfield
The statusfield is required in order to display the status traffic light in FE

### PR DESCRIPTION
**Pull request by SimonTheLeg**
Signed-off-by: Simon Bein <simontheleg@gmail.com>

**What does this PR do / Why do we need it**:

**Does this PR close any issues?**:
Fixes #10366 

**Special notes for your reviewer**:

I am not 100% sure if that is the right call to add the swagger annotation into the `apis/apps.kubermatic` package, but this was the only way I got the enum to work properly. And in this case I think the enum is important to build on top of it

image

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by lsviben** [comment]
@SimonTheLeg something is wrong with the swagger. I think the Time in the ApplicationStatus is conflicting with the Time already in swagger. 

You need to create an API type for the ApplicationStatus and convert between them to solve this :/

**Comment by lsviben** [comment]
/hold 
to stop the retest spam

**Comment by SimonTheLeg** [comment]
okay should be good to go now :)

**Comment by lsviben** [comment]
/hold cancel

looks like some test is still failing

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
