### PR TITLE
use zap in s3-exporter

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This replaces glog with zap in the s3-exporter and updates the Docker image to be based on Alpine 3.10.

**Special notes for your reviewer**:
I have no yet released the 0.4 Docker image.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/lgtm
/approve
/hold

So you can create an image

**Comment by xrstf** [comment]
Docker Image has been published.

**Review by kron4eg — APPROVED** [review]
/approve

**Pull request merged**
