### PR TITLE
fix changing user/password for OpenStack cluster credentials

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: the UI changes only user/password for the OpenStack credentials. The rest credentials were overridden with an empty string during patch operation but should stay untouched

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/cherrypick release/v2.14

Third time's the charm, cross fingers!

**Comment by zreigz** [comment]
> /cherrypick release/v2.13

@xrstf It works for v2.13 (the code base is slightly different here), we had regression

**Pull request merged**
