### PR TITLE
getting uninitialised projects doesn't produce errors

### LINKED ISSUE #2078: Adjust error messages for GET projects endpoint
**User Story**
Current status: On project creation the user gets a success message (`POST` request) and afterwards an error message (`GET` request), which is confusing as the error tells that one project isn't initialized, but the endpoint should return a list of all projects.
`{"error":{"code":503," message":"Project is not initialized yet"}}` 
for `GET https://dev.kubermatic.io/api/v1/projects`

Suggestion: Either the project that isn't initialized yet should not be included in the list OR the status field of the project should contain this information.

**Acceptance criteria**
`GET` list of projects shouldn't return error messages that contain informations about only one project.

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: before the API explicitly checked the status field and responded with 503 HTTP error. It seems like we could relax the validation when a caller just wants to read projects.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2078

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
however getting a cluster when a project wasn't initialised will produce 503 error, I think this is quite nice behaviour, WDYT ?

**Review by maciaszczykm — APPROVED** [review]

**Comment by maciaszczykm** [comment]
> however getting a cluster when a project wasn't initialised will produce 503 error, I think this is quite nice behaviour, WDYT ?

I agree on that one. It seems strange to have clusters within project that is not yet initialized.

**Comment by p0lyn0mial** [comment]
@mrIncompetent do we want to cherry-pick it into `v.2.8` ?

**Comment by mrIncompetent** [comment]
@p0lyn0mial can you elaborate a bit on the scenarios where this causes errors?

**Comment by p0lyn0mial** [comment]
@mrIncompetent 
GETting a specific project `/v1/project/{project_id}` or a list of projects `/v1/project` doesn't produce `503` Service Unavailable anymore, there was a special case in API for that `if project.Status != Active; return 503`

**Comment by mrIncompetent** [comment]
@p0lyn0mial yes, please cherry pick this into v2.8

**Pull request merged**
