### PR TITLE
OpenVPN multi-arch image

### LINKED ISSUE #7140: OpenVPN multi-arch image
User Story
As part of #6584, We would like to run KKP user clusters on the arm64 platform. This is part of that epic issue to have multi-arch images for the OpenVPN component of KKP.

Acceptance criteria
The OpenVPN component runs on arm64 machines as well as amd64 machines with the same image.

### PR DESCRIPTION
**Pull request by mlavacca**
**What this PR does / why we need it**:
OpenVPN has been set as an external dependency from [this](https://github.com/kubermatic/openvpn) repo, that provides multi-arch images. Its version has also been updated to `2.5.2-r0`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7140 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]

**Review by kron4eg — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
