### PR TITLE
Upgrade to Go 1.19.3

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:
Upgrade to Go 1.19.3.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Upgrade to Go 1.19.3.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
Rebased to include latest changes from main branch that include the fix for CCM migration tests.

**Review by xrstf — APPROVED** [review]
Please remember the postsubmits.

/approve

**Comment by xrstf** [comment]
/hold cancel

@ahmedwaleedmalik sorry, my PR changed the go.mod 😁

**Pull request merged**
