### PR TITLE
bump to Go 1.23.1

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
It's that time again. The sister PR is https://github.com/kubermatic/infra/pull/2818.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update to Go 1.23.1
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

needs #13710 first because the -3 images do not contain 1.27 test binaries anymore.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
