### PR TITLE
Seed dc cleanup

### LINKED ISSUE #5561: datacenters - clean up artificial seed datacenter
Datacenter LIST API returns also an artificial datacenter that represents the seed in which these datacenters reside. This is not needed as seeds have their own endpoints. 

Also we can clean up the residual unnecessary code in the datacenter api struct.

### PR DESCRIPTION
**Pull request by lsviben**
**What this PR does / why we need it**:
Removes the artificial "seed" datacenter from datacenter API lists results. Also simplifies the datacenter API struct by removing the unused LegacyObjectMeta fields.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5561 

**Does this PR introduce a user-facing change?**:

```release-note
Fake "seed" datacenters will not be returned in the results of datacenter API lists.
```

### CODE REVIEW

**Comment by lsviben** [comment]
@maciaszczykm  @zreigz , this should be merged only after Dashboard migrates to getting the seed names through the new seed names endpoint

**Comment by maciaszczykm** [comment]
/hold

I will cancel hold once the UI will be ready.

**Comment by maciaszczykm** [comment]
@lsviben Frontend does no longer use seeds from /dc endpoint:  https://github.com/kubermatic/dashboard/pull/2429/files#diff-5b18615bff053d5a80bd9cf215be3bfeR41

**Pull request merged**
