### PR TITLE
Improve cluster-backup controller

### LINKED ISSUE #13181: "Failed to undeploy cluster backup components" on new clusters
### What happened?

When creating a new user cluster in KKP v2.25.0-rc.0, the very early phases of cluster creation often see events on the cluster regarding cluster backup components:

> failed to undeploy cluster backup user-cluster components: failed to undeploy cluster backup user-cluster resources: failed to delete cluster backup user-cluster resource: failed to get API group resources: unable to retrieve the complete list of server APIs: apps/v1: Get "https://apiserver-external.cluster-a5pvzhh49r.svc.cluster.local./apis/apps/v1": dial tcp 10.240.27.81:443: connect: operation not permitted

>failed to undeploy cluster backup user-cluster components: failed to get user cluster client: Secret "internal-admin-kubeconfig" not found

This doesn't seem to have any impact and vanishes as soon as more components of the user cluster are up, but I feel like this code path should be more vigilant in checking the cluster status before trying to get clients.

No cluster backup is intended to be used.

### Expected behavior

These warnings do not show up.

### How to reproduce the issue?

- Create new user clusters on KKP v2.25.0-rc.0

### How is your environment configured?

- KKP version: v2.25.0-rc.0
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This PR does 4 things:

* it undoes the "put controller name into the global pkg/resources package" change from #13396 -- it's super weird for one special controller to for some reason have its name be globally recognized and defined outside of its own package.
* instead of handling the managedBy label in each reconciler func, an ObjectModifier is now used to transparently inject the label.
* reconciling only happens if the control plane is healthy; 99% of this controller's logic happens inside the user-cluster, so there is no need to try anything without the user cluster being up and running.
* cleanup ("undeploying") happens only to clusters with a special label. This is so that the controller is not undeploying components again and again and again and again and again from all clusters (those with the feature explicitly disabled or, more frequently, those clusters where no backup feature was ever configured). It's a label and not a finalizer because this kind of cleanup does not need to block anything.

Do note that in #13396 we fixed the "do not remove Velero CRDs if they were not installed by KKP"-bug, _BUT_ I think we didn't do it justice: If a user installs Velero manually and then the feature is enabled, KKP will take over the CRDs by reconciling them and applying the label. When then the feature is disabled, KKP will remove the CRDs again. I was told this is expected, but I wanted to note it down.

Fixes #13181

**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Fix misleading errors about undeploying the cluster-backup components from newly created user clusters.
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by judge-red** [comment]
Can this be backported to 2.25, please? We would like to have this patch in a 2.25 release before upgrading from 2.24 in order to avoid confusion with our end users (and thus support tickets).

**Comment by xrstf** [comment]
I'd say yes, this could be backported. It's a but more than just the fix for the erroneous error message, but still IMHO safe enough.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
