### PR TITLE
Open NodePort range in openstack

### LINKED ISSUE #7080: Open NodePorts managed openstack security group

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
Replaces and simplified version of #7081

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7080

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Open NodePort range in openstack
```

### CODE REVIEW

**Comment by kron4eg** [comment]
@xmudrii @irozzo-1A so I've tried to cherrypick this to both 2.17 (successfully) and 2.16 (unrealistic, too much changes). It means at best we can have this fix for 2.17+.

**Review by xmudrii — APPROVED** [review]

**Pull request merged**
