### PR TITLE
Update machine controller

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Update machine controller to v0.10.7

**Release note**:
```release-note
Update machine controller to v0.10.7
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@kdomanski We changed the way we install Docker in the latest machine-controller release and now we hit the AWS userdata limit. So this pr will likely not pass tests

/hold

**Comment by mrIncompetent** [comment]
Closed as the above mentioned version is buggy

**Pull request closed without merging**
