### PR TITLE
Remove CloudControllerReconcilledSuccessfully (typo) condition

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This removes one old, forgotten condition name and fixes a bunch of other, smaller typos.

I am still hesitant to integrate `typos` and replace codespell, as `typos` also has a bunch of false positives that are hard(er) to write sane exclude rules for. Even though it's an IMHO much superior spell checker than codespell.

**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Remove `CloudControllerReconcilledSuccessfully` (double L) Cluster condition, which was deprecated in KKP 2.21 and has since been replaced with `CloudControllerReconciledSuccessfully` (single L).
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by embik — APPROVED** [review]
/approve

**Review by wozniakjan — APPROVED** [review]
/approve

**Review by SimonTheLeg — APPROVED** [review]

**Pull request merged**
