### PR TITLE
bump gatekeeper to 3.1.0

### PR DESCRIPTION
**Pull request by lsviben**
**What this PR does / why we need it**:
Bumps gatekeeper from the `3.1.0-beta.9` to a stable `3.1.0`

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by lsviben** [comment]
@xrstf sorry i should have put it on hold earlier, some things are not working correctly after the bump. I need to make changes first. 

But before that i am currently working on some e2e tests that should discover such stuff automatically

**Comment by lsviben** [comment]
Closing in favor of https://github.com/kubermatic/kubermatic/pull/6706

**Pull request closed without merging**
