### PR TITLE
bump Dex to 2.35.1

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
An update for all Dex <= 2.34 versions is recommended: https://github.com/dexidp/dex/security/advisories/GHSA-vh7g-p26c-j2cw

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update Dex to 2.35.1 (contains [security fix](https://github.com/dexidp/dex/security/advisories/GHSA-vh7g-p26c-j2cw))
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
Even though I tried to avoid it by running the api-e2e test, this upgrade seems to have broken for us. Most likely because our dev environment runs on GKE (https://github.com/dexidp/dex/issues/2676).

I personally would simply revert this and wait for an upstream fix, rather than telling every customer to start creating a Service Account that they technically not needed before and not need now?

**Pull request merged**
