### PR TITLE
Allow specyfing replicas and tolerations in stateful set settings #12525

### LINKED ISSUE #12525: StatefulSetSettings should allow specyfing replicas and tolerations just like DeploymentSettings
### Description of the feature you would like to add / User story

As a KKP admin
I would like to change the number of replicas (and, while at it, the tolerations) of StatefulSet components
in order to have more influence what's running in a cluster namespace (and where it's running).

Alternatively, as a KKP admin,
I would like to set `enable: false` on the prometheus componentsOverride
in order disable prometheus (i.e. creation of the StatefulSet)

### Solution details

[StatefulSetSettings](https://docs.kubermatic.com/kubermatic/v2.23/references/crds/#statefulsetsettings) should support specifying `replicas` and `tolerations` just like
[DeploymentSettings](https://docs.kubermatic.com/kubermatic/v2.23/references/crds/#deploymentsettings) do. And components who can be configured through `componentsOverride`/[componentsettings](https://docs.kubermatic.com/kubermatic/v2.23/references/crds/#componentsettings) which use `StatefulSetSettings` should obey these additional parameters.

- add `replicas` and `tolerations` to `StatefulSetSettings`, identical to `DeploymentSettings`
- make sure all components who can be configured through `StatefulSetSettings` obey these new parameters (currently that's only prometheus)
- maybe the `UserClusterPrometheusAbsent` alert needs to be adopted to not fire if `replicas=0`

### Alternative approaches

imho the above makes most sense, since `DeploymentSettings` already allow for this, as do `ControllerSettings`.

However, adding a `enable: false` flag to `prometheus` in the the `ComponentSettings` would also work for my personal use case.

- add `enable` flag to `ComponentSettings.prometheus`
- don't deploy (or delete) the `prometheus` StatefulSet from a UC namespace if `enable=false`
- maybe the `UserClusterPrometheusAbsent` alert needs to be adopted to not fire if `enable=false`

### Use cases

We often have UCs used for intensive development/testing, which generate a lot of metrics, causing prometheus to run out of memory - which then also triggers alerts. We can increase the memory through the `componentsOverride` but since these UCs are non-productive, that's just a waste of resources. Even running prometheus at all is sometimes a waste of resources. Thus we'd like to being able to either set `replicas=0` or `enable=false` and not have prometheus deployed.

### PR DESCRIPTION
**Pull request by julioc-p**
**What this PR does / why we need it**:
This PR allows to change settings of prometheus in the user clusters (replicas and tolerations )using componentsOverride. It also disables the alert for absence of prometheus instances when they were manually scaled down.

**Which issue(s) this PR fixes**:
Fixes #12525

**What type of PR is this?**
/kind feature

Optionally add one or more of the following kinds if applicable:
/kind api-change

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Add spec.componentsOverride.prometheus to allow overriding Prometheus replicas and tolerations

```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by embik — APPROVED** [review]
This is looking like a great PR, @julioc-p! The alert changes are pretty clever.

One thing I'd like you to confirm/verify is what happens if you chose to turn on HA mode, e.g. run two Prometheus instances. I'm mainly asking because this usually requires adding some external labels to mark that its similar data coming from a different Prometheus instance. See https://promlabs.com/blog/2023/08/31/high-availability-for-prometheus-and-alertmanager-an-overview/ for some details.

However, I think we could do this is a follow-up you can test on dev, so you don't need to spin up another instance.

/approve

**Comment by wurbanski** [comment]
> One thing I'd like you to confirm/verify is what happens if you chose to turn on HA mode, e.g. run two Prometheus instances. I'm mainly asking because this usually requires adding some external labels to mark that its similar data coming from a different Prometheus instance. See https://promlabs.com/blog/2023/08/31/high-availability-for-prometheus-and-alertmanager-an-overview/ for some details.

I think it will be a little problematic if we go for >1 replicas but as you said, we can test that later on dev. (but please do!)

/approve

**Pull request merged**
