### PR TITLE
add isDefault flag to ruleGroup

### LINKED ISSUE #8452: Add default flag for RuleGroups
We need to be able to distinguish rulegroup applied by admin and users rulegroup, for that we need to add `default` flag to rulegroup

### PR DESCRIPTION
**Pull request by aborilov**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8452 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
What's the status on this PR?

**Comment by zreigz** [comment]
@rastislavs do you know what is about. Should we continue with this?

**Comment by rastislavs** [comment]
IIRC this flag was requested by @kgroschoff for better UI integration.
@kgroschoff is this still needed?

**Comment by kgroschoff** [comment]
Yes I think this is still needed, as otherwise the user might try to delete an admin rule group from the cluster view (Monitoring, Logging & Alerting tab) and wonders afterwards, why it is appearing again.
Without this flag the ui has no idea, which rulegroups are from admins. Once we have this information, we can disable the edit/delete actions for this rulegroup via the ui and display a hint, that this is an admin rulegroup. (similar to what we're doing with opa constraints: https://docs.kubermatic.com/img/kubermatic/v2.19/ui/disabled-default-constraint-cluster-view.png )

**Pull request closed without merging**
