### PR TITLE
Fix kubermatic openstack e2e tests

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
Fixes the openstack e2e tests.

**Special notes for your reviewer**:
the test `pre-kubermatic-e2e-openstack-ubuntu-1.19` is passing

**Does this PR introduce a user-facing change?**:
There should be two new fields in the UI for the openstack cloud provider for InstanceReadyCheckPeriod and InstanceReadyCheckTimeout  

```release-note
None
```

### CODE REVIEW

**Review by floreks — APPROVED** [review]
/lgtm

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
