### PR TITLE
Upgrade test

### LINKED ISSUE #2629: E2E testing: Verify upgrading Kubermatic does not break existing clusters
**User Story**

As a Kubermatic operator I want to make sure that upgrading Kubermatic does not break existing clusters

**Acceptance criteria**

* There is an e2e testcase that creates and conformance tests a cluster with a configurable base revision of Kubermatic, then updates Kubermatic to a configurable different version and runs the conformance tests again
* A presubmit that executes this is added

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2629

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
/lgtm
/approve

/hold 
in case you want this not to be merged yet

**Comment by alvaroaleman** [comment]
> in case you want this not to be merged yet

No, tests are green

/hold cancel

**Pull request merged**
