### PR TITLE
Migration for custom OSPs from seed to user clusters

### LINKED ISSUE #11679: Migration for custom OSPs from seed to user clusters
We need to migrate custom OSPs, from `kubermatic` namespace, to the user clusters.

- [x] Custom OSPs should be synced from kubermatic namespace to `kube-system` namespace in user clusters.
- [x] We should use CustomOperatingSystemProfiles CRD to store custom OSPs in KKP.
- [x] Transform existing custom OSPs to CustomOperatingSystemProfiles.
- [x] Remove OSP and OSC from user cluster namespaces. 
- [x] Remove OSM webhooks from KKP and just rely on the webhooks that OSM ships.

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:
Revamp custom OSP handling in KKP. Use a dedicated API resource `CustomOperatingSystemProfile` to avoid CRD conflicts. 

This PR does the following things:
1. Remove webhooks for OSP and OSC from seed. We now rely on the webhooks that OSM ships.
2. Refactor `operating-system-profile-synchronizer`
   1. Switch to using `CustomOperatingSystemProfile`.
   2. Instead of creating OSPs in user-cluster namespace. We now convert CustomOperatingSystemProfile to OperatingSystemprofile and create that resource in the `kube-system` namespace of the user cluster.

**Migration for Seed**:
  1. Convert OSPs from seed namespaces to CustomOperatingSystemProfiles CRs
  2. Delete the OSPs from seed namespace
  3. Check if it's a KubeOne installation; check for `operating-system-manager` deployment in `kube-system` namespace.
  4. If it's a KubeOne installation then we don't do anything further.
  5. If not, then we delete OSP and OSC CRDs.

**Migration for User Clusters**:
  1. Move non-default OSPs from the user cluster namespace to `kube-system` namespace in the user cluster.
  2. Delete default and custom OSPs from the user cluster namespace
  6. Delete all OSCs from the user cluster namespace; they will be re-created by OSM again in the user cluster itself.

**Which issue(s) this PR fixes**:

Fixes #11679

**What type of PR is this?**

/kind cleanup
/kind design

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
* CustomOperatingSystemProfile CRD is introduced for maintaining custom OSPs at the seed level. For more information https://docs.kubermatic.com/kubermatic/v2.22/tutorials-howtos/operating-system-manager/usage/#custom-operatingsystemprofiles
* OSP and OSC resources have been moved to user clusters. KKP will take care of migrating the existing resources. 
* [ACTION REQUIRED] Custom OperatingSystemProfiles should now be created for the kind `CustomOperatingSystemProfile` instead of `OperatingSystemProfile` in the seed namespace.
```

**Documentation**:

```documentation
https://github.com/kubermatic/docs/pull/1352
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/hold
PR is ready to be reviewed/merged. I'll remove the hold myself.

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
