### PR TITLE
Remove projects-migrator

### PR DESCRIPTION
**Pull request by alvaroaleman**
The projects migrator runs outside of leader election and doesn't
properly respect the worker-name label everywhere.

We only support upgrading Kubermatic from one version to the next and
that implies that everyone who upgrades to 2.12 already had the
projects-migrator run succcessfully.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

/assign @mrIncompetent

### CODE REVIEW

**Comment by alvaroaleman** [comment]
The requirement got documented in https://github.com/kubermatic/docs/pull/154

**Comment by nikhita** [comment]
/assign @zreigz 
for approval

**Pull request merged**
