### PR TITLE
Dont re-build binaries and docker image if they already exist

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Avoids building the binaries and docker image if the tag we want to build already exists. This speeds up re-tests significantly.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/assign @xrstf 

The broken openshift test is due to AWS wanting us to accept the license term for some random image we don't even use when selecting centos ([ref](https://github.com/kubermatic/kubermatic/pull/3413#issuecomment-489402731), [sample pr on machine-controller with all AWS CentOS tests failing](https://github.com/kubermatic/machine-controller/pull/520)), hence overriding the context.

Good thing thought: The failed re-run shows the change of the PR in action: https://prow.loodse.com/view/gcs/prow-data/pr-logs/pull/kubermatic_kubermatic/3415/pull-kubermatic-e2e-aws-openshift-3.11/1124985841718923264

/override pull-kubermatic-e2e-aws-openshift-3.11

**Comment by xrstf** [comment]
/lgtm
/approve no-issue

Very nice :-)

**Pull request merged**
