### PR TITLE
fix client api generation for golang v1.13

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: Fix client API generation for golang v1.13

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
According to this bug https://github.com/go-swagger/go-swagger/issues/2063 the schema validation was skipped. It happens for go v1.13. Our CI uses go v1.12 and everything works fine. There is still a problem with `verify-swagger.sh` which use the command `swagger validate` and cannot be skipped for this step.

```release-note
NONE
```

### CODE REVIEW

**Comment by zreigz** [comment]
I also tried update go-swagger for master branch (and new version) but it hangs for `swagger generate spec` command.
Update all dependencies helps but our code can not be compiled. So we have to wait until they fix it for new golang version.

**Comment by alvaroaleman** [comment]
Okay, so this effectively blocks us from moving to go 1.13?

**Comment by zreigz** [comment]
yes, `verify-swagger.sh` won't work. My PR fix only the problem to generate API client locally to go forward with PRs.

**Comment by alvaroaleman** [comment]
> yes, verify-swagger.sh won't work. My PR fix only the problem to generate API client locally to go forward with PRs.

Okay, thanks for the heads-up.
/lgtm
/approve

**Pull request merged**
