### PR TITLE
Minio 2019-10-12T01-39-57Z

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
No breaking changes, but a couple of security fixes.

**Does this PR introduce a user-facing change?**:
```release-note
Update Minio to RELEASE.2019-10-12T01-39-57Z
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

Monitoring endpoint is only available with credentials, need to check what this means exactly for us.

https://github.com/minio/cookbook/blob/master/docs/how-to-monitor-minio-with-prometheus.md

**Review by kron4eg — APPROVED** [review]
/lgtm

**Comment by xrstf** [comment]
Metrics can now be retrieved anonymously and since we never did, I now took the time to add a very, very basic Grafana dashboard for Minio,

**Review by kron4eg — APPROVED** [review]
/lgtm

**Pull request merged**
