### PR TITLE
Upgrade Anexia CCM to v1.5.0

### PR DESCRIPTION
**Pull request by LittleFox94**
**What this PR does / why we need it**:

Title says it all, upgrade Anexia CCM to v1.5.0.

**What type of PR is this?**
/kind feature
/kind chore

**Documentation**:
```documentation
NONE
```

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update Anexia CCM (cloud-controller-manager) to version 1.5.0
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/retest

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
