### PR TITLE
Move cluster-exposer in-tree

### PR DESCRIPTION
**Pull request by alvaroaleman**
Co-authored-by: Lukasz Zajaczkowski <zreigz@gmail.com>
Co-authored-by: Alvaro Aleman <alvaroaleman@users.noreply.github.com>

**What this PR does / why we need it**:

This PR moves the [cluster-exposer](https://github.com/kubermatic/cluster-exposer) inside the main kubermatic repo, so we can develop and version it together with the rest of the codebase and the CI scripting.

There is one differenence: The whole portforwarding has been removed, because:

* Importing k8s.io/kubernetes is very explicitly not supported: 
https://github.com/kubernetes/kubernetes#to-start-using-kubernetes
* There is no necesity to do it in the first place, because the nodeports of the kind cluster can be made available via a simple iptables rule: https://github.com/kubermatic/kubermatic/pull/4811/files#diff-ce57344c55a72dd2b7cd95bbce5b6695R132

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

/assign @zreigz @floreks

### CODE REVIEW

**Comment by zreigz** [comment]
@alvaroaleman looks really good, what about Makefile and Dockerfile to create and push the `cluster-exposer` image?

**Comment by alvaroaleman** [comment]
@zreigz the idea is to not do that anymore and just build it during the tests

**Pull request merged**
