### PR TITLE
Initialize the vsphere govmoni client with a ca-bundled soap client

### LINKED ISSUE #6863: Cluster Validation Webhook ignores CA Bundle for vSphere
**Bug Report**
At the customer we have the following environment:
- Custom CA-Bundle
- vSphere is secured behind a custom certificate (CA is included in CA Bundle)
- KKP `weekly-2021-13`

Related to #6859, we add the CA to the CA Bundle and the Machine Controller respects it and creates the machines. Unfortunately it's seams the Cluster validation webhook implementation doesn't consider CA bundle at got this error:
```
Error 400 invalid cluster: invalid cloud spec: failed to create vCenter session: Post "https://xxxxx/sdk": x509: certificate signed by unknown authority 
```
image

This error get produced when a cluster gets created at the UI and blocks the cluster creation.

@shaase-ctrl Please prio this, so we can remove the `insecure=true` flag.

Just for the ref, the CA Bundle is valid:
image

**Acceptance criteria**
- Cluster Validation respects CA bundle at cluster creation

### PR DESCRIPTION
**Pull request by lsviben**
**What this PR does / why we need it**:
Fix the vSphere client issue where it doesnt use the provided CA bundle. Based on https://github.com/vmware/govmomi/issues/1200. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6863 

**Special notes for your reviewer**:
WIP until @toschneck  confirms if fix works

**Does this PR introduce a user-facing change?**:

```release-note
fix KKP vSphere client not using the provided custom CA bundle
```

### CODE REVIEW

**Comment by toschneck** [comment]
@lsviben tested it and the patched api server image worked

**Comment by lsviben** [comment]
Same change needs to be done for MC: https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/vsphere/client.go#L40-L57

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
