### PR TITLE
[release/v2.13] keep most recent backup on cluster deletion (#5262)

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Backports #5262 into the 2.13 release branch.

**Does this PR introduce a user-facing change?**:
```release-note
When a user cluster is deleted, the most recent etcd backup is kept until manual cleanup.
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

The tests are clearly not flaky, something is going on here.

**Comment by kdomanski** [comment]
I see weird things like:
```
2020-04-14 07:59:49.806292 I | embed: rejected connection from "127.0.0.1:38630" (error "tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage", ServerName "")
WARNING: 2020/04/14 07:59:49 grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate". Reconnecting...
2020-04-14 08:00:03.413151 I | embed: rejected connection from "127.0.0.1:38952" (error "tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage", ServerName "")
WARNING: 2020/04/14 08:00:03 grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate". Reconnecting...
2020-04-14 08:00:08.864277 I | embed: rejected connection from "10.244.0.26:51070" (error "tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage", ServerName "")
WARNING: 2020/04/14 08:00:08 grpc: addrConn.createTransport failed to connect to {10.244.0.26:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate".
```

**Comment by xrstf** [comment]
We recently (#5261) added ClientAuth to the etcd cert stuff, but this should not have been backported to 2.13 and it worked just fine in k8s/oc in our master branch.

**Comment by kdomanski** [comment]
image

**Comment by xrstf** [comment]
Further investigation shows this being logged by the Openshift workers when they boot up:

```
supervise.sh: + yum install -y kernel irqbalance microcode_ctl systemd selinux-policy-targeted setools-console dracut-network passwd openssh-server openssh-clients podman skopeo runc containernetworking-plugins nfs-utils NetworkManager dnsmasq lvm2 iscsi-initiator-utils sg3_utils device-mapper-multipath xfsprogs e2fsprogs mdadm cryptsetup chrony logrotate sssd shadow-utils sudo coreutils less tar xz gzip bzip2 rsync tmux nmap-ncat net-tools bind-utils strace bash-completion vim-minimal nano authconfig policycoreutils-python iptables-services bridge-utils biosdevname container-storage-setup cloud-utils-growpart ceph-common cri-o cri-tools podman glusterfs-fuse
supervise.sh: Loaded plugins: fastestmirror
supervise.sh: Loading mirror speeds from cached hostfile
supervise.sh: * base: d36uatko69830t.cloudfront.net
supervise.sh: * extras: d36uatko69830t.cloudfront.net
supervise.sh: * updates: d36uatko69830t.cloudfront.net
supervise.sh: https://cbs.centos.org/repos/paas7-crio-113-candidate/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
supervise.sh: Trying other mirror.
supervise.sh: To address this issue please refer to the below wiki article
supervise.sh: https://wiki.centos.org/yum-errors
supervise.sh: If above article doesn't help to resolve this issue please use https://bugs.centos.org/.
supervise.sh: One of the configured repositories failed (CRI-O),
supervise.sh: and yum doesn't have enough cached data to continue. At this point the only
supervise.sh: safe thing yum can do is fail. There are a few ways to work "fix" this:
supervise.sh: 1. Contact the upstream for the repository and get them to fix the problem.
supervise.sh: 2. Reconfigure the baseurl/etc. for the repository, to point to a working
supervise.sh: upstream. This is most often useful if you are using a newer
supervise.sh: distribution release than is supported by the repository (and the
supervise.sh: packages for the previous distribution release still work).
supervise.sh: 3. Run the command with the repository temporarily disabled
supervise.sh: yum --disablerepo=crio ...
supervise.sh: 4. Disable the repository permanently, so yum won't use it by default. Yum
supervise.sh: will then just ignore the repository until you permanently enable it
supervise.sh: again or use --enablerepo for temporary usage:
supervise.sh: yum-config-manager --disable crio
supervise.sh: or
supervise.sh: subscription-manager repos --disable=crio
supervise.sh: 5. Configure the failing repository to be skipped, if it is unavailable.
supervise.sh: Note that yum will try to contact the repo. when it runs most commands,
supervise.sh: so will have to try and fail each time (and thus. yum will be be much
supervise.sh: slower). If it is a very temporary problem though, this is often a nice
supervise.sh: compromise:
supervise.sh: yum-config-manager --save --setopt=crio.skip_if_unavailable=true
supervise.sh: failure: repodata/repomd.xml from crio: [Errno 256] No more mirrors to try.
```

**Pull request merged**
