### PR TITLE
Persist comments in Application's values fields

### LINKED ISSUE #12941: Return the ApplicationValues as a string in the API for enabling containing comments

### PR DESCRIPTION
**Pull request by SimonTheLeg**
Signed-off-by: Simon Bein <simontheleg@gmail.com>
**What this PR does / why we need it**:

This PR allows a user to have comments in the values section of their Applications.

**Which issue(s) this PR fixes**:

Fixes #12941

**What type of PR is this?**

/kind feature
/kind api-change

**Special notes for your reviewer**:
Basically the field changes from a deferred runtime.Extension to a string. In order to make sure that the yaml entered by the user is still valid yaml, the validation webhook has been extended.

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Comments are now possible and persisted in the values section of ApplicationDefinitions and ApplicationInstallations
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/lgtm
/milestone KKP 2.25 

🚀

**Comment by ahmedwaleedmalik** [comment]
@SimonTheLeg seems like we have merge conflicts

/lgtm cancel

**Comment by ahmedwaleedmalik** [comment]
/hold
WTF did I just do :D This PR shouldn't be merged as https://github.com/kubermatic/kubermatic/pull/13075 is the one that should go in

**Comment by SimonTheLeg** [comment]
Closed in favor of https://github.com/kubermatic/kubermatic/pull/13075

**Pull request closed without merging**
