### PR TITLE
chore: deprecate old cilium and hubble addon configs

### PR DESCRIPTION
**Pull request by cnvergence**
**What this PR does / why we need it**:
As Cilium is now deployed as a Application https://github.com/kubermatic/kubermatic/issues/11356, we can start to deprecate old configs from addons

**What type of PR is this?**

/kind chore 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Deprecate v1.11 and v1.12 Cilium and Hubble KKP Addons, as Cilium CNI is managed by Applications from version 1.13
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
This is not deprecating old versions, it's directly removing them. Please deprecate them by updating https://github.com/kubermatic/kubermatic/blob/f8133499f6beda2f33f13c50ff7896794d320c87/pkg/cni/version.go#L49 and  moving versions to `deprecatedCNIPluginVersions` instead.

**Review by embik — CHANGES_REQUESTED** [review]
Don't remove the manifests for v1.11 and v1.12; we have to deprecate them (as you did with the latest commit) and then remove them in the release after 2.25.

**Comment by embik** [comment]
Missing a release note, then we are good to go.

**Comment by cnvergence** [comment]
done

**Review by embik — APPROVED** [review]
/approve

**Comment by cnvergence** [comment]
ptal @wozniakjan

**Review by wozniakjan — APPROVED** [review]
/approve

**Pull request merged**
