### PR TITLE
give the initContainer of kubermatic access to private quay.io repo

### PR DESCRIPTION
**Pull request by glower**
**What this PR does / why we need it**:

For CFi we need to create custom addon with some secrets stored in the docker image. So we need to have access to the credentials. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Added  access to the private quay.io repos from the kubermatic helm template
```

### CODE REVIEW

**Comment by glower** [comment]
Don't know if this is a right way, but did work for me

**Review by mrIncompetent — APPROVED** [review]

**Review by mrIncompetent — CHANGES_REQUESTED** [review]
Release note is missing

**Comment by glower** [comment]
Added Release note

**Comment by mrIncompetent** [comment]
The release note must be in the block.

> 1. Enter your extended release note in the below block. If the PR requires additional action from users switching to the new release, include the string "action required".
> 2. If  no release note is required, just write "NONE".

**Comment by glower** [comment]
now it is correct

**Review by mrIncompetent — APPROVED** [review]

**Pull request merged**
