### PR TITLE
Upgrade Anexia CCM to v1.5.4

### PR DESCRIPTION
**Pull request by eiabea**
**What this PR does / why we need it**:
Upgrade Anexia CCM to v1.5.4.

**What type of PR is this?**
/kind cleanup
/kind feature

**Special notes for your reviewer**:
Release notes: https://github.com/anexia-it/k8s-anexia-ccm/releases/tag/v1.5.4

Please backport to kkp `v2.21`

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update Anexia CCM (cloud-controller-manager) to version 1.5.4
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/test pre-kubermatic-e2e-anexia-flatcar-1.25
/approve

**Comment by LittleFox94** [comment]
@ahmedwaleedmalik did you see our wish to backport this to 2.21? :)

I'd also wish for a backport to 2.22, no clue why @eiabea didn't write that as well ^^

**Comment by ahmedwaleedmalik** [comment]
> @ahmedwaleedmalik did you see our wish to backport this to 2.21? :)
> 
> I'd also wish for a backport to 2.22, no clue why @eiabea didn't write that as well ^^

I was waiting for the Anexia tests to pass. Seems like for 2.21 you'll have to manually backport it; create a PR.

**Comment by LittleFox94** [comment]
alright, thanks @ahmedwaleedmalik 

@eiabea please go on and create a backport PR for 2.21 :)

**Pull request merged**
