### PR TITLE
Fix defaulting for Kubernetes dashboard

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What does this PR do / Why do we need it**:

```
KubernetesDashboard KubernetesDashboard `json:"kubernetesDashboard,omitempty"`

type KubernetesDashboard struct {
	Enabled *bool `json:"enabled,omitempty"`
}
```

The code snippet above was giving us nightmares during webhook conversions. Using a pointer to boolean with `omitempty` is not viable since it's difficult to set it to false. 

```
KubernetesDashboard *KubernetesDashboard `json:"kubernetesDashboard,omitempty"`

type KubernetesDashboard struct {
	Enabled bool `json:"enabled,omitempty"`
}
```

Switching the code to this form makes more sense since `KubernetesDashboard` should have been the optional field instead of `KubernetesDashboard.Enabled`. This makes determining whether defaulting should happen for this field, or if it was explicitly set to `false` viable.

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by xrstf — CHANGES_REQUESTED** [review]
Please describe your thoughts behind this PR, what this fixes and stuff.

**Comment by xrstf** [comment]
You removed all the cluster defaulting tests and don't even want to explain why?

**Comment by ahmedwaleedmalik** [comment]
> You removed all the cluster defaulting tests and don't even want to explain why?

Updated the description and reverted the removal of tests, it was a mistake.

**Review by xrstf — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
/test 
pre-kubermatic-opa-e2e

**Pull request merged**
