### PR TITLE
Update swagger to 0.29.0

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
This PR bumps Swagger and because Swagger is a monster, it also pulls in a whole slew of other updates.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

prioritize other PRs to get merged first

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by xrstf** [comment]
/hold

prioritizing

**Pull request merged**
