### PR TITLE
add registry_mirrors to seed node settings

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This is required if you want to run a registry mirror in your cluster.

**Does this PR introduce a user-facing change?**:
```release-note
Add `registry_mirrors` to Seed node settings
```

### CODE REVIEW

**Review by moadqassem — COMMENTED** [review]
/approve 
/lgtm

**Comment by lsviben** [comment]
> @xrstf: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pre-kubermatic-opa-e2e	[ee6fdad](https://github.com/kubermatic/kubermatic/commit/ee6fdadbf54f9bb8de123cdad8d5bda9c98439ec)	[link](https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_kubermatic/6667/pre-kubermatic-opa-e2e/1369259424094359552)	`/test pre-kubermatic-opa-e2e`
> [Full PR test history](https://public-prow.loodse.com/pr-history?org=kubermatic&repo=kubermatic&pr=6667)

ehh i ran it like 10 times without flakes on my PR :(. Ill check what could be wrong

**Comment by xrstf** [comment]
/override pre-kubermatic-etcd-launcher-e2e

This is just randomly flaking.

**Pull request merged**
