### PR TITLE
Only enable node metrics from kube-state-metrics

### LINKED ISSUE #2201: enable only nodes metrics in user-cluster namespaced kube-state-metrics
**User Story**
kube-state-metrics exposes tons of metrics we don't intend to use, to lower pressure on prometheus

**Acceptance criteria**
* [ ] user-custer namespaced kube-state-metrics launched with additional flag `--collectors nodes`

re #1903

### PR DESCRIPTION
**Pull request by thetechnick**
**What this PR does / why we need it**:
Only enable node metrics from kube-state-metrics, because we do not care about the rest.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2201

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
kube-state-metrics enable only node stats
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]

**Comment by mrIncompetent** [comment]
Could you elaborate about why we don't care about the rest?

IMO we should have as many metrics as possible and only filter during the prometheus federation using special recording rules.

Otherwise we prevent customers from using those metrics - as they might find them useful.
We explicitly made the Prometheus config "configurable"

**Comment by kron4eg** [comment]
The idea behind this was to protect (user-cluster level) prometheus from metrics explosion (since metrics cardinality is unbounded), and we don't use it in anyway in our (user-cluster level) prometheus level, including scraping /federate from datacenter level prometheus.

But yeah, I can see how custom prometheus config federate on `/federate?match[]={__name__=~"kube_node_status_.*"}` for example.

If you feel this is unneeded change, please close it along with #2201

**Comment by mrIncompetent** [comment]
Would it be simpler to just reduce the retention to ~1h on the user cluster Prometheus to reduce the needed memory?

**Comment by kron4eg** [comment]
@mrIncompetent yes, that was another idea we had at seed team

@thetechnick please create another PR with user-cluster prometheus param set as 
```
--storage.tsdb.min-block-duration=15m
--storage.tsdb.max-block-duration=30m
--storage.tsdb.retention=1h
```

**Pull request closed without merging**
