### PR TITLE
AWS: Reduce number of API calls during reconciling

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Currently we always do some AWS calls during reconciling, even if everything is there:

* We _always_ request the  VPC
* We _always_ tag our resouces, even if they are already tagged

This PR makes Kubermatic omit those calls if possible

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
None
```

/assign @mrIncompetent 

Should we cherrypick this into release/v2.9?

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@mrIncompetent Should we cherrypick that to release/v2.9?

**Comment by mrIncompetent** [comment]
> @mrIncompetent Should we cherrypick that to release/v2.9?

:+1:

**Pull request merged**
