### PR TITLE
Cleanup metrics-server ExternalName service from user-cluster

### PR DESCRIPTION
**Pull request by PratikDeoghare**
**What this PR does / why we need it**:
Cleanup ExternalName service from user-cluster. It is no longer in use. 

Followup to this PR https://github.com/kubermatic/kubermatic/pull/5185

**Does this PR introduce a user-facing change?**:
```
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/retest

@PratikDeoghare For your next PR, please fork the repo into your Github account first. :)

**Comment by PratikDeoghare** [comment]
We are moving metric-server to user-cluster so this cleanup is unnecessary now. 

cc @rastislavs

**Pull request closed without merging**
