### PR TITLE
Allow setting the default number of replicas for controlplane components

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Allows setting the default number of replicas for controlplane components. Defaults the number of apiserver replicas to two, as requested by the sebastian.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
[BREAKING] The default number of apiserver replicas was increased to 2. You can revert to the old behavior by setting `.Kubermatic.apiserverDefaultReplicas` in the `values.yaml`
```

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

Lgtm on the what the PR does, but out of curiosity:

> Defaults the number of apiserver replicas to two, as requested by the sebastian.

Why are we doing this?

**Comment by nikhita** [comment]
Ooops requires rebase :woman_facepalming:

**Comment by alvaroaleman** [comment]
> Why are we doing this?

Because that makes the api much more ha. For the controllers it doesn't matter as much, as they are not doing anything without the leader lock anyways

**Comment by alvaroaleman** [comment]
Also, a downtime of the API is something ppl notice instantly as `kubectl` doesn't work anymore, downtime of the controller-manager or scheduler just results in parts of the reconciling not happening instantly anymore

**Pull request merged**
