### PR TITLE
Bring back vsphere.ValidateCredentials for use in kubermatic-api

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
What it says on the title. This was removed in #11665 but we need it in kubermatic/dashboard, thus this PR brings it back.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by moadqassem — APPROVED** [review]
/approve 
/lgtm

**Comment by ahmedwaleedmalik** [comment]
@embik if this is required only for API then why can't we move it there?

**Comment by embik** [comment]
> @embik if this is required only for API then why can't we move it there?

Because `newSession` is a private, non-trivial function in the cloud provider implementation. I don't want to duplicate and potentially de-sync that in the kubermatic-api.

Plus, we should start treating our exported functions in kubermatic/kubermatic as public interfaces now that we have several repositories importing it, so removing exported functions is pretty bad practice.

**Comment by ahmedwaleedmalik** [comment]
> Because newSession is a private, non-trivial function in the cloud provider implementation

It already exists in the dashboard repo https://github.com/kubermatic/dashboard/blob/main/modules/api/pkg/provider/cloud/vsphere/provider.go#L81 or am I missing something?

**Comment by ahmedwaleedmalik** [comment]
/hold 
For a short discussion

**Comment by embik** [comment]
> > Because newSession is a private, non-trivial function in the cloud provider implementation
> 
> It already exists in the dashboard repo https://github.com/kubermatic/dashboard/blob/main/modules/api/pkg/provider/cloud/vsphere/provider.go#L81 or am I missing something?

Okay, that should probably be de-duplicated at some point. We should make sure the API uses credentials the same way that controllers later on will use. I stand by the second part of my comment though:

> we should start treating our exported functions in kubermatic/kubermatic as public interfaces now that we have several repositories importing it, so removing exported functions is pretty bad practice.

**Comment by ahmedwaleedmalik** [comment]
> kubermatic/kubermatic as public interfaces now that we have several repositories importing it

It's just dashboard as far as I know?

> we should start treating our exported functions in kubermatic/kubermatic as public interfaces now that we have several repositories importing it, so removing exported functions is pretty bad practice.

For now, please move this piece of code to dashboard; where it's supposed to be consumed. You can create a dedicated ticket for a long-term convention and we can further discuss it over there.

**Comment by embik** [comment]
cc @moadqassem again.

**Comment by embik** [comment]
/hold cancel

as per the discussions yesterday.

**Pull request merged**
