### PR TITLE
Use dep ensure -vendor-only to prevent different packages

### PR DESCRIPTION
**Pull request by mrIncompetent**

### CODE REVIEW

**Comment by mrIncompetent** [comment]
fyi: @guusvw @metalmatze @realfake @chaosaffe @scheeles

**Comment by metalmatze** [comment]
Does this make it just faster, right? 👍

**Comment by mrIncompetent** [comment]
@metalmatze Yes, but this also prevents dep to get missing depenencies - which are not specified in the .lock file.
The .lock file only contains really used imports.

**Comment by metalmatze** [comment]
I thought that this was the normal behaviour. 😳 
Good to know!

**Review by lbb — COMMENTED** [review]
👍

**Review by guusvw — APPROVED** [review]

**Comment by guusvw** [comment]
:+1:

**Comment by mrIncompetent** [comment]
Finally someone approved :+1:

**Pull request merged**
