### PR TITLE
Cleanup tests, improve logging

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This PR is a collection of a few random maintenance commits. Just take a look at the commit log for more info.

NB: The change regarding the `if !isInternal...` was done because reading a positive statement ("if something") is easier to understand than a negative. This PR is the only occasion to make such a tiny change, it wouldn't be worth its own PR :grin: 

**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
```
    mla_test.go:138: error while getting Grafana org: HTTP error 404: returns {"message":"Organization not found","traceID":"00000000000000000000000000000000"}
```

Is this a flake?

**Comment by embik** [comment]
Looks like the error is consistent @xrstf, but I'm not sure why.

**Comment by xrstf** [comment]
The dualstack tests have no meaning here and were just to counter-test #11232.

/override pre-kubermatic-dualstack-e2e-equinix-rockylinux
/override pre-kubermatic-dualstack-e2e-hetzner

**Review by embik — APPROVED** [review]

**Pull request merged**
