### PR TITLE
fluentbit: set retry limit to 10

### PR DESCRIPTION
**Pull request by toschneck**
**What this PR does / why we need it**:
Fix Retry errors for log-shipper to prevent unnecessary `FluentbitManyFailedRetries` alerts

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
@toschneck please bump the chart version.

**Comment by toschneck** [comment]
thx for bumping the version :+1:

**Pull request merged**
