### PR TITLE
Remove redundant error handling packages

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
* github.com/pkg/errors offers no big value over Go's native `%w` placeholder for us.
* github.com/hashicorp/go-multierror was only used a a fancy `[]error`, so it can go away.

This gets rid of 2 more MPL packages (MPL is always just an exception in our codebase, and fewer exceptions are good).

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
@xmudrii PTAL

**Comment by xrstf** [comment]
@xmudrii PTAL

**Comment by xrstf** [comment]
@embik care to jump in? :)

**Review by embik — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by xmudrii** [comment]
/hold
Looks like it’s not a flake.

**Comment by xrstf** [comment]
@xmudrii PTALA

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
