### PR TITLE
Add Support for Kubernetes 1.18

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This does what it says on the tin, i.e. add support for Kubernetes 1.18. For reviewing I strongly recommend to go commit-by-commit, so you can skip aa6dc60f34dcfc ("rebuild test fixtures for 1.15-1.18").

**Does this PR introduce a user-facing change?**:
```release-note
Add support for Kubernetes 1.18, drop support for Kubernetes < 1.15.
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]
/lgtm

/hold to let other people see it

**Comment by xrstf** [comment]
/hold cancel
/override pre-kubermatic-e2e-kubevirt-centos-1.18
/override pre-kubermatic-test-integration

Tests are overridden they were unrelated / only down because of other issues.

**Pull request merged**
