### PR TITLE
Fix externalcluster swagger and noderole endpoint

### PR DESCRIPTION
**Pull request by imharshita**
Signed-off-by: Harshita sharma <harshita.sharma6174@gmail.com>

**What this PR does / why we need it**:
Fix externalcluster swagger and endpoint:
- Changes req types as some fields are not required to be provided by the user in the req.
- Changes NodeRole endpoint to `NoCredential` because NodeRoles are only required to create a NodePool on a existing cluster

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Replace GET "api/v2/providers/eks/noderoles" endpoint with
"/api/v2/projects/{project_id}/kubernetes/clusters/{cluster_id}/providers/eks/noderoles" endpoint to list EKS NodeRoles
```

**Documentation**:

```documentation
TBD
```

### CODE REVIEW

**Comment by xrstf** [comment]
Please fill out the PR template.

**Comment by xrstf** [comment]
Thank you for filling out the template :)

**Review by hbernardo — APPROVED** [review]
/lgtm
/approve

**Comment by lsviben** [comment]
You should add to the release note that you are removing the `/providers/eks/noderoles` endpoint to replace it with the new one

**Comment by imharshita** [comment]
> You should add to the release note that you are removing the `/providers/eks/noderoles` endpoint to replace it with the new one

ptal

**Pull request merged**
