### PR TITLE
Allow enabling PSPs

### PR DESCRIPTION
**Pull request by bashofmann**
**What this PR does / why we need it**:
Make additional admission plugins configurable per cluster. This can be used to for example enable Pod Security Policies on a per cluster level. See #4053.

What is still missing to make this complete:
* Dashboard support to easily activate and deactivate PodSecurityPolicy (we can provide a PR for this as well)
* Adding PodSecurityPolicies and corresponding RBAC bindings for all addons
* e2e tests

**Does this PR introduce a user-facing change?**:

```release-note
Pod Security Policies can now be enabled
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@bashofmann What is the reason you went for allowing any additional admission plugin instead of just PSPs?

**Comment by bashofmann** [comment]
> @bashofmann What is the reason you went for allowing any additional admission plugin instead of just PSPs?

@alvaroaleman I was thinking that it's better to make this API more generic, so that we don't have to create a new dedicated field every time we want to make another admission plugin configurable, but I'm also fine with doing it differently, however you prefer.

**Comment by alvaroaleman** [comment]
> @alvaroaleman I was thinking that it's better to make this API more generic, so that we don't have to create a new dedicated field every time we want to make another admission plugin configurable, but I'm also fine with doing it differently, however you prefer.

Then we also need an extended validation that it isn't already in the list. I'd tend to prefer just making this a binary option for now, we can still make it extensible later on if we actually have that usecase or WDYT?

**Comment by bashofmann** [comment]
What about `UsePodSecurityPolicyAdmissionPlugin`?

**Comment by alvaroaleman** [comment]
/lgtm
/approve

@bashofmann Do you already have the necesary changes for the addons?

**Comment by bashofmann** [comment]
I'm not allowed to see the test results. Is the failing `pull-kubermatic-canary-deployment-ci-kubermatic-io` something I need to fix?

**Comment by alvaroaleman** [comment]
No, the job currently has issues, we'll trigger a re-run once thats fixed

**Comment by bashofmann** [comment]
> @bashofmann Do you already have the necesary changes for the addons?

Yes, I'll try to make a PR for this (as well as for the UI integration) later today or on Monday.

**Comment by alvaroaleman** [comment]
/hold
Until the test is fixed

**Comment by alvaroaleman** [comment]
/retest
/hold cancel

> Yes, I'll try to make a PR for this (as well as for the UI integration) later today or on Monday.

Perfect! Lets add and verify a presubmit that runs with PSPs enabled on that PR then :)

**Pull request merged**
