### PR TITLE
Add TenantID to OpenStack CloudSpec

### LINKED ISSUE #3619: Add support for OpenStack TENANT_ID
**User Story**
In some environments the tenant name is not unique and will lead to errors.
To avoid this, the tenant ID must be used.

**Acceptance criteria**
- [ ] OpenStack clusters can be created by specifying the tenant ID instead of the name

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Add TenantID to OpenStack CloudSpec.

Fixes #3619

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/assign @nikhita

### CODE REVIEW

**Comment by mrIncompetent** [comment]
API/UI issue: https://github.com/kubermatic/kubermatic/issues/3750

**Comment by nikhita** [comment]
Looks like this needs to be added at some more places:

- https://github.com/kubermatic/kubermatic/blob/master/api/pkg/resources/machinecontroller/deployment.go#L162 (`OS_TENANT_ID`)
- https://github.com/kubermatic/kubermatic/blob/master/api/pkg/presets/manager.go#L110 (and manager_test.go)
- https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/v1/provider/openstack.go#L383
- https://github.com/kubermatic/kubermatic/blob/master/api/pkg/validation/cluster.go#L254

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Comment by nikhita** [comment]
/assign @zreigz
for approval

**Pull request merged**
