### PR TITLE
propagate ca bundle to metering cron jobs

### PR DESCRIPTION
**Pull request by mate4st**
**What this PR does / why we need it**:

Uses the ca-bundle of KKP for metering cron jobs.

This is useful if metering is configured with minio that uses a custom cert. 

**What type of PR is this?**

**Special notes for your reviewer**:

This relies on the fact that the ca-bundle file is called `ca-bundle.pem`. I am not 100% if this is always true

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add support for ca-bundle to metering cronjobs. 
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by WeirdMachine** [comment]
> /cherry-pick release/v2.21

@akash-gautam thanks for reminding me. I am taking care of the backport

**Pull request merged**
