### PR TITLE
Add monitoing and dashboard for envoy-agent and nodeport-proxy

### LINKED ISSUE #7124: Tunneling expose strategy: expose and scrape envoy-agent metrics
- Change agent envoy configuration to expose Prometheus metrics and add annotations to scrape.
- Defining relevant metrics and prepare Grafana dashboard
- Define alerting rules
- Verify node-port proxy monitoring

### PR DESCRIPTION
**Pull request by mate4st**
**What this PR does / why we need it**:

Adding monitoring for envoy-agent together with federation to Seed MLA Prometheus.

Adding Grafana Dashboard Nodeport Proxy for Metrics regarding envoy nodeport proxy and envoy-agent.

Most metrics are available with `Tunneling` expose strategy. For instance the envoy-agent is only deployed with Tunneling.

**Which issue(s) this PR fixes**:

Fixes #7124 

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add monitoring and dashboard for envoy-agent and nodeport-proxy
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by WeirdMachine** [comment]
pre-kubermatic-e2e-aws-ubuntu-1.27

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
