### PR TITLE
Disable master alerts for non-master clusters

### LINKED ISSUE #3873: Promtheus charts: Disable master alerts if `values.kubermatic.ismaster` is defined and has a value of false
**User Story**

As a kubermatic operator I do not want to have master alerts in my seeds, as they will permanently go off.

**Acceptance criteria**

* If the key `.Values.Kubermatic.IsMaster` is defined and has a value of `false`, our prometheus chart doesn't deploy any alerts for Kubermatic master components anymore

### PR DESCRIPTION
**Pull request by moelsayed**
**What this PR does / why we need it**:
Disable master alerts for non-master clusters.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3873

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
I'm not really sure that trading the "change the list of ruleFiles" step when setting up a non-master cluster for "change this isMaster flag" is worth it, tbh. While it is definitly easier to just flip a single switch (especially because you can do that easily via `--set ....`), it hardcodes another layer of abstraction into the Prometheus chart. Prometheus so far did not really care about master vs. seeds, it only cared for a list of rules files to load (that we have one for masters and one for seeds is just coincidence).

**Comment by moelsayed** [comment]
@xrstf TBH, I am not very happy with the solution either. The prometheus values file is well commented and it's possible to achieve this by commenting a single line. But, I wasn't sure if there is a specific requirement to do this with a switch.

If there is no explicit requirement for this, I am perfectly fine with just adding a comment about this in the `ruleFiles` section and avoid the extra complexity.

**Comment by xrstf** [comment]
I would do exactly that, just add an even more expressive comment than I left originally and wait for someone to complain that managing the rule files is too hard. :)

**Pull request merged**
