### PR TITLE
Deleted obsolete hack/gen-api-docs.sh

### PR DESCRIPTION
**Pull request by kron4eg**
This script dates back to
https://github.com/kubermatic/kubermatic/pull/376 and is expected to use
https://github.com/yvasiyarov/swagger which is long ago unmaitained, so
farewell.

Signed-off-by: Artiom Diomin <kron82@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by xmudrii — CHANGES_REQUESTED** [review]
The `./docs/api-docs.md` document is referring to this script, so we should either remove or update it.

**Comment by kron4eg** [comment]
@xmudrii deleted outdated doc too

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
