### PR TITLE
Make nginx chart configurable

### PR DESCRIPTION
**Pull request by mrIncompetent**

### CODE REVIEW

**Review by guusvw — DISMISSED** [review]
Could you please provide a little bit more documentation? =p

**Comment by scheeles** [comment]
Shouldn't this be configurable or at least 3 (for prod)

**Comment by mrIncompetent** [comment]
Sure, using preemtible machines lead to the fact that the nginx is not available x times a day (x beeing the number of nodes)

**Comment by mrIncompetent** [comment]
Why 3?

**Comment by scheeles** [comment]
With 3, one can be updated, one can be down on a preemtible instance and we still have running

**Comment by scheeles** [comment]
I would make it configurable with the value in the value.yaml.

**Review by metalmatze — APPROVED** [review]
0.9.0-beta.19 is already available, but should be fine anyway.

**Pull request merged**
