### PR TITLE
Update KubeOne image to the latest commit image

### PR DESCRIPTION
**Pull request by imharshita**
**What this PR does / why we need it**: Update kubeone image to the latest commit image

**Which issue(s) this PR fixes**: 

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — CHANGES_REQUESTED** [review]
You need to update the dependency here as well for it to properly work https://github.com/kubermatic/kubermatic/blob/main/go.mod#L80.

Also, please add a `TODO` that this image tag needs to be replaced with a semver tag before the release.

**Comment by embik** [comment]
Please give some reasoning for updating the image to a tag so close to release. It's not clear why we should be doing this right now. Is this a dependency between KKP and KubeOne where we can only release KKP 2.22.0 once KubeOne 1.6.0 is out?

**Comment by imharshita** [comment]
> Please give some reasoning for updating the image to a tag so close to release. It's not clear why we should be doing this right now. Is this a dependency between KKP and KubeOne where we can only release KKP 2.22.0 once KubeOne 1.6.0 is out?

As for the kubeone-kkp integration we create pods which should have the latest kubeone image for things to work, so but can't we just use the latest tag instead of waiting for the kubeone release to release KKP

**Comment by imharshita** [comment]
We will wait for the KubeOne release 1.6 to use the same in kkp

**Comment by ahmedwaleedmalik** [comment]
> We will wait for the KubeOne release 1.6 to use the same in kkp

Thanks for the update. I hope you are confident enough with this because the changeset between what's currently running and what you'll update it to after the KubeOne release is not that small. But nonetheless `sgtm`.

https://github.com/kubermatic/kubeone/compare/v1.5.3...main

**Comment by imharshita** [comment]
@ahmedwaleedmalik @embik updated with latest commit

**Review by embik — APPROVED** [review]
as per sig-release, we want to include 1.6 support in KKP 2.22 after all, so lgtm.

**Pull request merged**
