### PR TITLE
Update to latest OSM for Flatcar torcx fix

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
This incorporates a fix for Flatcar that is required to support new Flatcar versions. See https://github.com/kubermatic/operating-system-manager/pull/357.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
/retest

Please be a flake, please be a flake, please be a flake ...

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
