### PR TITLE
registeres UserProjectBinding CRD

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: registeres UserProjectBinding CRD

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
#1966

**Special notes for your reviewer**:
the CRD type was added in this pull https://github.com/kubermatic/kubermatic/pull/1965

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
the build fails on a test `TestGetUsersForProject/scenario_2:_get_a_list_of_user_for_a_project_'foo'_for_external_user`

```
TestGetUsersForProject/scenario_2:_get_a_list_of_user_for_a_project_'foo'_for_external_user
err="forbidden: The user \"Alice2\" doesn't belong to the given project = foo2InternalName"
--- FAIL: TestGetUsersForProject (1.01s)
    --- FAIL: TestGetUsersForProject/scenario_1:_get_a_list_of_user_for_a_project_'foo' (0.51s)
        user_test.go:200: Expected response body to be 
            [{"id":"john","name":"john","creationTimestamp":"0001-01-01T00:00:00Z","email":"john@acme.com","projects":[{"id":"fooInternalName","group":"owners-foo"}]},{"id":"alice","name":"Alice","creationTimestamp":"0001-01-01T00:00:00Z","email":"alice@acme.com","projects":[{"id":"fooInternalName","group":"viewers-foo"}]},{"id":"bob","name":"Bob","creationTimestamp":"0001-01-01T00:00:00Z","email":"bob@acme.com","projects":[{"id":"fooInternalName","group":"editors-foo"}]}] 
            got 
            [{"id":"bob","name":"Bob","creationTimestamp":"0001-01-01T00:00:00Z","email":"bob@acme.com","projects":[{"id":"fooInternalName","group":"editors-foo"}]},{"id":"john","name":"john","creationTimestamp":"0001-01-01T00:00:00Z","email":"john@acme.com","projects":[{"id":"fooInternalName","group":"owners-foo"}]},{"id":"alice","name":"Alice","creationTimestamp":"0001-01-01T00:00:00Z","email":"alice@acme.com","projects":[{"id":"fooInternalName","group":"viewers-foo"}]}]
```

**Comment by p0lyn0mial** [comment]
@glower I think this is ordering issue ?

**Comment by kdomanski** [comment]
Got a fix in https://github.com/kubermatic/kubermatic/pull/1828/commits/ec571610e97d562c24be6d7ebbe8bf83c8b2deaa

**Comment by p0lyn0mial** [comment]
@kdomanski thanks for the fix ! But I'd rather that our API doesn't provide stable responses (at least for the time being). It is okay if the clients will sort the responses how they want. WDYT ?

**Review by mrIncompetent — APPROVED** [review]

**Comment by kdomanski** [comment]
@p0lyn0mial Sure, no need to sort it if the test is already fixed on the other side.

**Pull request merged**
