### PR TITLE
Add Prometheus and Node Exporter alerts again

### LINKED ISSUE #1489: Add node-exporter & prometheus alerts back
These alerts are currently missing after moving away from the Prometheus Operator based approach:

https://github.com/prometheus/node_exporter/pull/941
https://github.com/tomwilkie/prometheus/blob/mixin/prometheus-mixin/alerts/alerts.libsonnet

### PR DESCRIPTION
**Pull request by metalmatze**
**What this PR does / why we need it**:
We currently don't alert on Prometheus and Node metrics. We did previously and want to do that again.

**Which issue(s) this PR fixes**:
Closes #1489 

```release-note
NONE
```

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by p0lyn0mial** [comment]
should we merge this or close ?
the pull has been approved 19 days ago :)

**Comment by metalmatze** [comment]
Oh. I thought this is already merged. Please merge it. Thank you. Otherwise I'll do it on Monday.

**Comment by p0lyn0mial** [comment]
> Oh. I thought this is already merged. Please merge it. Thank you. Otherwise I'll do it on Monday.

Do you promise it won't explode ? :)

**Comment by mrIncompetent** [comment]
That broke the kubermatic-prometheus as the rules are invalid:
```
[henrik@henrik-pc monitoring]$ make check-rules
promtool check rules prometheus/rules/rules.yaml
Checking prometheus/rules/rules.yaml
  FAILED:
groupname: "node.rules" is repeated in the same file

make: *** [Makefile:16: check-rules] Error 1
```

Before a new attempt gets made here, a CI check needs to exist which validates the rules.

**Comment by mrIncompetent** [comment]
PR to revert this: https://github.com/kubermatic/kubermatic/pull/1675

**Comment by metalmatze** [comment]
Damn. I've experienced this issue on my private cluster already. :see_no_evil: 
I'll try to figure something out. It happens by node-exporter mixins and kubernetes-mixins using this name for the group. :expressionless:

**Pull request merged**
