### PR TITLE
Refactor repository to be CE-only

### PR DESCRIPTION
**Pull request by xrstf**
### Welcome to KKP 3!

Greetings, fellow traveller! You just stumbled upon KKP 3's first ever pull request :)

But in all seriousness, KKP 3 will be split into 2 different Git repositories, one for the CE and one for the EE, at least when it comes to the "backend":

* kubermatic/kubermatic (CE)
* kubermatic/kubermatic-ee (EE)

This however will not happen in the dashboard, which will remain a single repository that supports both CE and EE at the same time (maybe with different build flags).

To facilitate this split, I created a new `v3` branch in this repo and then `sed`ed a lot to replace all the `v2` with `v3`. Once that was done, I pushed the v3 branch to Github and started workin on the actual refactoring, as besides just incrementing the version number, _maaaaaany_ things change in KKP 3:

* Seeds do not exist anymore, instead each datacenter is its own CRD.
* Separation between master/seed cluster will be removed entirely in CE.
* Some features have been declared to be EE-only and their code needs to be moved to the new EE repo.

This PR is the result of refactoring the repo. I opened it mainly because I wanted to see how well our Prowjobs can already cope. The PR is not really meant to be reviewed.

In parallel, there is a `v3` branch in the EE repo already and the EE code has been moved there (for now it's a copy; reducing code duplication will be a long process in the future months/years).

**What type of PR is this?**
/kind cleanup
/kind feature
/kind design
/kind api-change
/kind deprecation
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Remove concept of seeds, replace with dedicated Datacenter CRD; remove master/seed separation; remove most of the EE code
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by embik — APPROVED** [review]

**Comment by xrstf** [comment]
/override pre-kubermatic-mla-e2e

MLA e2e has not yet been refactored.

**Pull request merged**
