### PR TITLE
WIP - Make tunneling default expose strategy

### PR DESCRIPTION
**Pull request by mate4st**
**What this PR does / why we need it**:

With the [GA of Tunneling](https://github.com/kubermatic/kubermatic/commit/e9719f577d65ab903cff506d5a9c70b5e8726d36) we want to use it as out default expose strategy.

In comparison to NodePort our current default expose strategy it offers are more unified and centralized endpoint where user clusters connect to. Only requiring port 6443 and 8088 via a load balancer service.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Tunneling is now the default expose strategy.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
Just checking in here, what's the impact on existing installations that will be upgraded? Do we explicitly default this field so once you created a KKP setup, it's set and therefore won't be defaulted again?

**Comment by WeirdMachine** [comment]
> Just checking in here, what's the impact on existing installations that will be upgraded? Do we explicitly default this field so once you created a KKP setup, it's set and therefore won't be defaulted again?

Yep we do not set the default explicitly in the CR so this will break all clusters if exposeStrategy is not set explicitly.

**Comment by embik** [comment]
> > Just checking in here, what's the impact on existing installations that will be upgraded? Do we explicitly default this field so once you created a KKP setup, it's set and therefore won't be defaulted again?
> 
> Yep we do not set the default explicitly in the CR so this will break all clusters if exposeStrategy is not set explicitly. Do you have an Idea how to get around this?

No idea yet, but we should be aware of this before merging it; we shouldn't be breaking existing installations :D Let's maybe take a look together once we have a minute.

**Comment by xrstf** [comment]
Yeah please note down, in detail, why we are changing such a central, important default value. Are the others not good enough anymore? Are they buggy? Slow? Does the new one work for all scenarios?

**Comment by WeirdMachine** [comment]
No easy solution for this as we need to somehow explicitly set the expose strategy for the Kubermatic configuration for existing installations.

Ref: https://github.com/kubermatic/kubermatic/issues/12290

**Pull request closed without merging**
