### PR TITLE
Conformance Tester: add flatcar to supported OS list for GCP and VCD

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Both GCP and VCD now support flatcar; updating the compatibility matrix for conformance tester accordingly.

**Which issue(s) this PR fixes**:

For reference https://github.com/kubermatic/kubermatic/issues/13158

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

/cc @Skarlso

### CODE REVIEW

**Comment by xrstf** [comment]
Should we add optional Prowjobs for these combos, so we can verify that it works before merging?

**Comment by ahmedwaleedmalik** [comment]
> Should we add optional Prowjobs for these combos, so we can verify that it works before merging?

Done.

**Comment by ahmedwaleedmalik** [comment]
/retest 
Seems like a flake

**Comment by ahmedwaleedmalik** [comment]
We have an outdated template for flatcar on VCD. The containerd version on it is way below our threshold of 1.6.* due to which kubelet doesn't come up. Unfortunately, we can't update the template at the moment due to some internal limitations.

Flatcar support for VCD was an externally contributed feature and we got a confirmation from the authors that this is working for them.

@xrstf we can override `pre-kubermatic-e2e-vmware-cloud-director-flatcar-1.29` and come back to this when we are able to update the templates.

**Comment by xrstf** [comment]
/override pre-kubermatic-e2e-vmware-cloud-director-flatcar-1.29 
/approve
/lgtm

**Pull request merged**
