### PR TITLE
[release/v2.25] Applications: discover if a release is stuck and rollback if necessary

### PR DESCRIPTION
**Pull request by SimonTheLeg**
**What this PR does / why we need it**:

Manual cherry-pick of #13301 

**What type of PR is this?**

/bugfix

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Addressing inconsistencies in helm that lead to an Application stuck in "pending-install"
```

**Documentation**:

```documentation
NONE
```
Signed-off-by: Simon Bein <simontheleg@gmail.com>

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/retitle [release/v2.25] Applications: discover if a release is stuck and rollback if necessary

**Comment by xrstf** [comment]
/override pre-kubermatic-dualstack-e2e-aws-canal
/override pre-kubermatic-dualstack-e2e-aws-cilium

Both are failing because there is no Rockylinux AMI in AWS eu-west-1, which seemingly can happen (see a previous issue: https://bugs.rockylinux.org/view.php?id=1684).

**Pull request merged**
