### PR TITLE
Add the changelogs for v2.17.2, v2.17.1, v2.16.11 releases

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

Add the changelogs for v2.17.2, v2.17.1, v2.16.11 releases.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/assign @moadqassem

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]
/approve

**Comment by xmudrii** [comment]
/hold cancel
The releases are out.

**Pull request merged**
