### PR TITLE
Use Operator for e2e Tests

### LINKED ISSUE #4727: Kubermatic Operator: Use on CI
**User Story**
For running e2e tests, we do not want to use the Helm chart anymore, but instead deploy the operator and a KubermaticConfiguration and let it do its magic.

This is part of #4723.

**Acceptance criteria**
* [ ] E2E tests are running inside a Kubermatic installation provisioned by the operator.

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This PR extends our e2e tests to be able to deploy Kubermatic either using the Helm chart or the new Kubermatic Operator. A new environment variable, `KUBERMATIC_USE_OPERATOR` toggles between the two. We support both for e2e tests because we still support the Helm chart for existing customers.

**Which issue(s) this PR fixes**:
Fixes #4727

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
For reference, because I will soon remove the dummy `-operator` test jobs: They actually passed:

screenshot-2020-01-09-152427

**Review by kron4eg — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
