### PR TITLE
 Upgrade CRDs to apiextensions/v1

### LINKED ISSUE #6692: Migrate CRDs from deprecated apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1
**User Story**
Apiextensions.k8s.io/v1beta1 is deprecated since Kubernetes 1.19 https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#deprecation and is getting removed in 1.22. 

Migrate Kubermatic CRDs to apiextensions.k8s.io/v1.

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This changes the API version we use to define our CRDs. v1beta1 has been deprecated a long time and is not available in Kubernetes 1.22 anymore.

I also moved the CRDs to the operator, as the old `kubermatic` chart is deprecated and we must make steps away from it, otherwise we will never be able to get rid of it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6692

**Does this PR introduce a user-facing change?**:
```release-note
Update CRDs to use apiextensions/v1 (Kubernetes 1.19+)
```

### CODE REVIEW

**Review by moadqassem — COMMENTED** [review]
Great Job! 
/approve 
/lgtm

**Review by xmudrii — APPROVED** [review]

**Pull request merged**
