### PR TITLE
Use Athens instead of homegrown go cache

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Previously we uploaded the compiled Go packages to Minio in order to speed up download and compilation time. For now we replce the cache with a local proxy, so the download times are sped up a bit. The compilation time however will increase until we maybe re-create a caching mechanism for it.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]

**Comment by xrstf** [comment]
/override pre-kubermatic-canary-deployment-ci-kubermatic-io

The dashboard is currently broken, so the canary deployment fails with a ImagePullBackoff.

**Pull request merged**
