### PR TITLE
Update to Go 1.18.1

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
This bumps the Go version we use for our CI jobs.

**Does this PR introduce a user-facing change?**:
```release-note
Update to Go 1.18.1
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Review by kron4eg — APPROVED** [review]
:tada:

**Comment by ahmedwaleedmalik** [comment]
> @ahmedwaleedmalik you do not need to continually /test all, the PR was in the merge queue and prow was processing it as normal. No need to intervene.

It was in the merge queue for about an hour 🤷

**Comment by xrstf** [comment]
That's normal. Your /test all changed nothing ;-)

**Comment by ahmedwaleedmalik** [comment]
> That's normal. Your /test all changed nothing ;-)

Maybe it didn't. Although it was stuck at `re-testing 17 jobs` or something similar. IMO that is a step before it gets queued in the merge pool. But anyways will leave it up to prow to do it's magic ;)

**Comment by xrstf** [comment]
Seeing how this PR is now retested AGAIN, i think your /test all actually made Prow re-test every job based on an old baseref, and so effectively delayed merging it by another 2 hours. ^^

**Pull request merged**
