### PR TITLE
convert the resource RBAC controller to controller-runtime

### LINKED ISSUE #4012: migrate the RBAC controller to the controller-runtime

### PR DESCRIPTION
**Pull request by kdomanski**
Re-creating #5495. Switching the source repo to public messed-up my fork and I had to re-fork.

Fixes #4012

```release-note
NONE
```

### CODE REVIEW

**Comment by kdomanski** [comment]
Remaining cleanup (for another PR):
- move
```go
rmapping, err := c.mgr.GetRESTMapper().RESTMapping(gvk.GroupKind())
		if err != nil {
			panic(err)
		}
```
deeper down the call stack, because the outside functions often don't need both Kind and Resource


- remove `resourcesController` field from `clusterProvider`
- replace all panics in rmpaper with returned errors
- rename `resourcesController` to `resourcesReconciler` and clean up
- wire a c.ctx to the resource controller and replace context.TODO()
- remove clusterProviders from projectController

**Comment by youssefazrak** [comment]
Looks good. I will let @zreigz review from his side.

**Pull request merged**
