### PR TITLE
Correctly close port-forwarders

### LINKED ISSUE #4862: Resource leak when creating Kubernetes dashboard connections from UI
**User Story**

Connecting to the Kubernetes dashboard from the Kubermatic UI increases the memory usage of the kubermatic-api pod with each connection. The kubermatic-api eventually becomes unresponsive. The memory consumption of the kubermatic-api does not decrease anymore.

**Acceptance criteria**

- Resources should be freed properly
- Creating new dashboard connections should be restricted rather than the kubermatic-api becoming unresponsive

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

So far, we close the individual listeners in the portforwarding but not the underlying spdy connection to the kubelet, resulting in memory leaking.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4862

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
A memory leak in the port-forwarding of the Kubernetes dashboard and Openshift console endpoints was fixed
```

### CODE REVIEW

**Comment by floreks** [comment]
Nice catch!

/lgtm
/approve

**Comment by alvaroaleman** [comment]
/hold

This results in `E1216 10:54:14.571486       1 portforward.go:409] error closing listener: close tcp4 127.0.0.1:32977: use of closed network connection` which isn't a real problem but will irritate ppl

**Comment by alvaroaleman** [comment]
/hold cancel
PTAL

**Comment by kdomanski** [comment]
@alvaroaleman Does this allow us to revert #4524 ?

**Comment by alvaroaleman** [comment]
> @alvaroaleman Does this allow us to revert #4524 ?

Yeah i think so, when testing this the mem usage never went above 50m

**Pull request merged**
