### PR TITLE
remove 2.21->2.22 migration code

### LINKED ISSUE #10847: remove migration code in installer that relates to 2.21
Some migration code was necessary to upgrade from 2.20 to 2.21. we should remove this code now. Migration code was implemented in the following PR:
 

#10694
#10824 
 #9981

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This removes all migration code from the installer/operator related to the 2.22 release.

/kind cleanup

Fixes #10847

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
/hold

Helsinki is full.

**Review by vgramer — CHANGES_REQUESTED** [review]
would be great if you remove these functions too: https://github.com/kubermatic/kubermatic/blob/0744cf344a7160dc59e75e3ada26569791d7bf11/pkg/install/stack/kubermatic-master/stack.go#L284-L301

**Review by vgramer — APPROVED** [review]
/lgtm

**Comment by xrstf** [comment]
@vgramer Sorry, did a random search and found yet more random migration code :grin:

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
