### PR TITLE
create a new type for cluster template instances

### LINKED ISSUE #7231: Create cluster template instance CRD
**User Story**
Create a new CRD type for cluster template instances
**Acceptance criteria**

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: create a new type for cluster template instances

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7231

**Special notes for your reviewer**:

**Documentation**:

```release-note
NONE
```

### CODE REVIEW

**Review by mfranczy — APPROVED** [review]
/lgtm
/approve

**Comment by zreigz** [comment]
@mfranczy forgot register a new type PTAL

**Review by jiachengxu — APPROVED** [review]

**Pull request merged**
