### PR TITLE
Cleanup CSI addon, update Hetzner CSI

### LINKED ISSUE #3312: Fix & Update Hetzner CSI components
**User Story**
We currently deploy the hetzner CSI components into each Hetzner cluster.
Within the e2e tests it showed that storage does not work.

**Acceptance criteria**
- [ ] Storage works inside Hetzner clusters
- [ ] All Hetzner related CSI components have been updated to the latest version
- [ ] A manual e2e test has been executed & the logs have been commented on this issue to proof it works

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
The new-ish `csi` addon was added with only Openstack support, yet we already had veeeery old hetzner CSI stuff in the `default-storage-class` addon. This PR cleans this up by moving the Hetzner CSI into the `csi` addon, keeping the StorageClass where it was.

To keep the addon organized, I also propose recursive directory scanning. All found YAML files are rendered into one gigantic manifest and then applied anyway.

Fixes #3312.

**Does this PR introduce a user-facing change?**:
```release-note
Update Hetzner CSI, move to `csi` addon
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

Needs https://github.com/kubermatic/kubermatic/pull/6588 first

**Comment by rastislavs** [comment]
/lgtm
/approve

I really like the recursive directory scanning idea!

**Pull request merged**
