### PR TITLE
Fix hetzner CSI addon so it comes up

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

So E2E tests pass on hetzner

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold

So I can update the tag to non-dev

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

/pony lgtm

**Comment by alvaroaleman** [comment]
@nikhita Can you re-lgtm? :grimacing:

**Comment by nikhita** [comment]
Sorry :woman_facepalming: 

/lgtm

**Pull request merged**
