### PR TITLE
Synchronize cluster ssh keys to machines during runtime adding daemonset

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** 
Fixes #4781

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
No

```release-note
None
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@moadqassem Can you please split this cleanly into two commits:

1. ) Re-Revert of #4781
2. ) Additional changes you made to fix the issue we saw on Friday

**Comment by moadqassem** [comment]
@alvaroaleman I will, just wanted it to pass first, clean it and ask for review

**Comment by alvaroaleman** [comment]
> @alvaroaleman I will, just wanted it to pass first, clean it and ask for review

So please remove the 24 commits from this PR and instead just use `git revert`

**Pull request closed without merging**
