### PR TITLE
fix: add metering prometheus to mirror-images

### PR DESCRIPTION
**Pull request by cnvergence**
**What this PR does / why we need it**:
Add metering Prometheus image to mirror-images.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add images for metering prometheus to mirror-images.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

@cnvergence please add a release note. We should also backport this PR to the relevant branches.

**Comment by cnvergence** [comment]
need to fix tests, as they are failing on empty default seed.Spec.Metering config

**Comment by ahmedwaleedmalik** [comment]
> need to fix tests, as they are failing on empty default seed.Spec.Metering config

/lgtm cancel

Ah, it was looking to me like the test should pass now

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
