### PR TITLE
pass ip family info in machine deployment

### LINKED ISSUE #9617: Integrate Azure dual-stack machine-controller API in KKP
Integrate https://github.com/kubermatic/machine-controller/issues/1251 into KKP

Also test dual-stack end-to end on all supported OS platforms.

### PR DESCRIPTION
**Pull request by PratikDeoghare**
**What does this PR do / Why do we need it**:
Pass IP family information in machine deployment.

**Does this PR close any issues?**:
Fixes #9617 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by PratikDeoghare** [comment]
/retest

Not sure how the change is breaking these exact tests. Lemme try retest one more time.

**Comment by PratikDeoghare** [comment]
Removing reviewers to avoid  spamming their inboxes.

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
