### PR TITLE
[WIP] Expose metrics via Kubermatic API

### LINKED ISSUE #874: Expose per cluster Prometheus metrics via Kubermatic's API

### PR DESCRIPTION
**Pull request by metalmatze**
**What this PR does / why we need it**:
We want to expose predefined metrics to the Kubermatic Dashboard.
The display will then show metrics for the users cluster.

**Which issue(s) this PR fixes**:
Closes #874 

**Special notes for your reviewer**:
Not really sure about where to put a lot of code yet.
I've removed the `ctx context.Context` which was passed into the Router but not used anywhere. This not how to use context anyway :wink: 

I've also renamed the `prometheus-address` to `internal-address` for the internal metrics and health checks.  This is to avoid confusion with the new `prometheus-url` which points the Kubermatic API to the correct Prometheus to talk to.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by mrIncompetent — COMMENTED** [review]
except for CI failing, LGTM

**Review by mrIncompetent — DISMISSED** [review]

**Comment by metalmatze** [comment]
@j3ank @KrissiWi 
```
{"metrics":[{"name":"Machines","value":1},{"name":"Machines (1h)","values":[1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}]}
```
This is what the current JSON being returned looks like. Is this something you can work with? Do we need to improve something?
A metric object can either have `value` or `values`. The first being a single `float64` and the latter is an array of `float64`. Right now we return values for the last hour. Do you think that 24h might be better?

**Comment by mrIncompetent** [comment]
One of the things i just realized:
This API must be optional. There might not be a Prometheus running in the cluster.

**Comment by KrissiWi** [comment]
Do you really mean me? I dont understand a word

**Comment by metalmatze** [comment]
Oops. Nope, that was by mistake. I wanted to ping @kgroschoff :joy: Sorry.

**Comment by kgroschoff** [comment]
@metalmatze Looks good so far. 
I can't get the measure of the timeframe which would make sense. Trust you with that. 😉 

I only have one thing to 'mention':
Array with only the values is fine, but for longer periods I think it might be useful to have a timestamp for each value. IF this is possible AND interesting for users - I don't know which informations are relevant. But I think as a user I'd like to know for how long my machines were down (just an example) if we display more than 1h. So values could contain multiple arrays. :sweat_smile:
What do you think @j3ank ?

**Comment by metalmatze** [comment]
Rebased.
PTAL @mrIncompetent

**Review by mrIncompetent — APPROVED** [review]

**Pull request merged**
