### PR TITLE
October Dependency Update

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This is one of those "let's hieve our Dependencies into this month"-style PRs. I updated Kube dependendies, Kubermatic apps etc., but left updating

* cloud provider SDKs
* KubeVirt to 1.0
* Mergo to 1.0
* Helm to 3.13.0 because we need helm/helm#12445

for dedicated PRs.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
The Flatcar tests fail with

> failed to fetch config: unable to translate 2.x ignition to 3.1: error at $.storage.files.8.path: path conflicts with systemd unit or dropin

**Comment by xrstf** [comment]
The dualstack failures are unrelated to this PR (see #12690).

/override pre-kubermatic-dualstack-e2e-aws-canal
/override pre-kubermatic-dualstack-e2e-aws-cilium

**Review by embik — APPROVED** [review]
/approve

**Review by embik — APPROVED** [review]
/approve

**Review by embik — APPROVED** [review]
/approve

**Review by wozniakjan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
