### PR TITLE
Add coredns PDB

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Add coredns PDB.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
/hold

Need to update the image

**Comment by mrIncompetent** [comment]
/assign @alvaroaleman 

cc @bashofmann

**Review by alvaroaleman — COMMENTED** [review]
/lgtm
/approve

**Comment by mrIncompetent** [comment]
@alvaroaleman the image tag has been updated.

/hold cancel

**Review by alvaroaleman — COMMENTED** [review]
/lgtm
/approve no-issue

**Pull request merged**
