### PR TITLE
[release/v2.20] KubeVirt fix CI for DC

### PR DESCRIPTION
**Pull request by hdurand0710**
Signed-off-by: Helene Durand <helene@kubermatic.com>

**What this PR does / why we need it**:
Fixes the CI for KubeVirt e2e tests with the new KubeVirt DC infra cluster.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind failing-test

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
KubeVirt switch infra cluster to DC for e2e tests.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by hdurand0710** [comment]
oki, KubeVirt tests are fixed.
We were missing:
- adaptation to KubeVirt infra DC cluster
- retrofit of https://github.com/kubermatic/kubermatic/pull/11572
- changed namespace to "default" to ccm (infra namespace)

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Comment by hdurand0710** [comment]
needs a sig-crd approval, does not exists any more.... ?

**Comment by lsviben** [comment]
> needs a sig-crd approval, does not exists any more.... ?

sig-crd was merged into sig-cluster-management so anybody from there can approve

**Comment by hdurand0710** [comment]
> > needs a sig-crd approval, does not exists any more.... ?
> 
> sig-crd was merged into sig-cluster-management so anybody from there can approve

sure, but sig-crd was existing in this branch....

**Pull request merged**
