### PR TITLE
Update OSM to latest image

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
[This](https://github.com/kubermatic/operating-system-manager/commit/29ee9d78677d8cde84ff3a46a9c5a9b9b761025f) ideally is the last change in OSM before the release so I'd like for us to run all the cloud provider tests etc for release testing against this/latest image.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by moadqassem — APPROVED** [review]
/approve
/lgtm

**Comment by ahmedwaleedmalik** [comment]
cc @kubermatic/sig-release-managers

**Pull request merged**
