### PR TITLE
Update kube-state-metrics addon to v2.13.0

### LINKED ISSUE #13493: usercluster-mla kube-state-metrics pdb prevents node-rotation
### What happened?

If usercluster-mla is enabled on user-clusters and if we have enabled the kube-state-metrics addon (which is mandatory for usercluster-mla dashboards to function), if we try to rotate the machine deployment, one node from old machine deployment gets stuck. Specifically, the node which is running kube-state-metric pod cannot get cordoned and removed until we kill the ksm pod manually.

This happens due to [PDB for KSM](https://github.com/kubermatic/kubermatic/blob/main/addons/kube-state-metrics/pdb.yaml#L21) which does not allow pod strength to go below 1.

### Expected behavior

Just like all the other pods, ksm pod should also get evicted from old node and moved to new node. The old node then can get recycled.

### How to reproduce the issue?

1. enable usercluster-mla on a user-cluster
2. install kube-state-metrics addon
3. force restart the machine deployment / upgrade k8s version so that MD gets rotated.
4. wait for all old nodes to get removed.
5. Observe that one old node remains where ksm pod is running

### How is your environment configured?

- KKP version: 2.25.6
- Shared or separate master/seed clusters?: shared and dedicated

### What cloud provider are you running on?
Azure, VSphere

### What operating system are you running in your user cluster?
Ubuntu 22.04

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This gives the kube-state-metrics addon some long overdue love. Thankfully everything can be configured with Helm values, though they are large enough to not inline them into the Makefile anymore (`--set '...=...'`), so I followed the same pattern as KubeOne and used a `helm-values` file (notably, no `.yaml` file extension to make KKP not parse it as a Kube manifest).

For the NetworkPolicy I saw 2 options

* continue to define it ourselves in a standalone YAML file
* use the policy created by the upstream Helm chart

I opted for the 2nd solution, to stay as close as possible to upstream. Unfortunately this meant I needed another way to surround the NetworkPolicy with an `{{ if }}` block. The best tool I can think of the perform a multi-line change to a text file is `patch`, so `git apply` is used with hopefully strict enough flags to make the patch only ever apply super duper precisely.

Besides using the upstream Helm chart, I also made a quite significant version bump.

part of #13597, fixes #13493

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update `kube-state-metrics` addon to v2.13.0.
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
pre-kubermatic-e2e-openstack-ubuntu-1.30

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
