### PR TITLE
Remove CoreOS support in KKP

### LINKED ISSUE #6379: Remove CoreOS support from the KKP

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
Remove CoreOS operating system from KKP.

**Which issue(s) this PR fixes**
Fixes kubermatic/kubermatic#6379

**Does this PR introduce a user-facing change?**:

```release-note
Remove CoreOS Support
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]

**Comment by floreks** [comment]
@zreigz will be more familiar with those parts of the API than I.

/assign @zreigz

**Pull request merged**
