### PR TITLE
UserCluster MLA e2e test rate limit

### LINKED ISSUE #8240: UserCluster MLA e2e test rate limits
Test that rate limits from MLA settings added to shared configmap

### PR DESCRIPTION
**Pull request by aborilov**
**What this PR does / why we need it**: Test MLA monitoring rate limits

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8240 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by jiachengxu — APPROVED** [review]
/approve
/lgtm

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
