### PR TITLE
[ release/v2.9] Bump dashboard to V1.1.2

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
* Fixed a bug that could cause the Image of a NodeDeployment to be changed on edit
* Fixed a bug that resulted in the clusters being displayed twice in the overview page
* Fixed bug with missing version in the footer
```

/assign @maciaszczykm

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Last 7 commits were added to the Dashboard's release (comparing to v1.1.1):
https://github.com/kubermatic/dashboard-v2/commits/release/v1.1

These 3 might get into release notes too:
- https://github.com/kubermatic/dashboard-v2/pull/1096
- https://github.com/kubermatic/dashboard-v2/pull/1095
- https://github.com/kubermatic/dashboard-v2/pull/1094

WDYT?

/approve
/lgtm
/hold

**Comment by alvaroaleman** [comment]
@maciaszczykm Sure but

* kubermatic/dashboard-v2#1095
* kubermatic/dashboard-v2#1094

don't have a relase note. What would you put as release note there?

I'll also later create a PR against kubermatic/kubermatic#master that contains the whole changelog for 2.9.3 which will end up being sent to customers

**Comment by alvaroaleman** [comment]
/hold cancel

Lets have the discussion of release notes on the changelog PR: https://github.com/kubermatic/kubermatic/pull/2895

**Pull request merged**
