### PR TITLE
Update Grafana to 9.4.3

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This performs a long overdue Grafana update. I will work on the dashboards in a separate PR once this is deployed to dev.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update Grafana to 9.4.3
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
While we're at it, do we want to sync the MLA Grafana version as well? https://github.com/kubermatic/kubermatic/blob/main/charts/mla/grafana/Chart.yaml

**Comment by xrstf** [comment]
I am super uncomfortable to do any upgrades in the MLA stack, that is totally @kubermatic/sig-app-management's territory. The MLA Grafana is tied into KKP and who knows what could break.

**Comment by embik** [comment]
> I am super uncomfortable to do any upgrades in the MLA stack, that is totally @kubermatic/sig-app-management's territory. The MLA Grafana is tied into KKP and who knows what could break.

Can we at least try and see where we end up with the MLA e2e test? I personally find it super awkward that we ship different Grafana versions. We can ask @wurbanski for some input as well.

**Review by ahmedwaleedmalik — APPROVED** [review]
We can take care of updating the MLA chart in a separate PR.

/approve

**Comment by wurbanski** [comment]
Late to the party, but agree - let's update and do it in separate PR. Also @xrstf nothing to be afraid of - everything has tests ;-)

**Pull request merged**
