### PR TITLE
[release/v2.21] Use eu-west-1 for AWS E2E tests

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

Manual cherry-pick of #12306 to the release/v2.22 branch

I don't think we even use spot instances on this branch, but let's backport this change for the sake of consistency

**What type of PR is this?**

/kind failing-test

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
> E0525 08:55:28.909126       1 machine_controller.go:390] Failed to reconcile machine "md-ubuntu-8d68d475d-rkfrx": failed to create machine at cloudprovider, due to failed create instance at aws, due to InvalidSubnetID.NotFound: The subnet ID 'subnet-0373d73f016db25c7' does not exist

Currently fails because of this.

**Comment by xmudrii** [comment]
I’ll look into this later
/lgtm cancel

**Pull request merged**
