### PR TITLE
Conformance tests: Fix bogus nil error logging

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```
/assign @xrstf

### CODE REVIEW

**Comment by xrstf** [comment]
I think the old version, while being unfortunately phrased, still served as a nice ".Delete() call in the code is done" marker. Can we add a log line if `err == nil`? And if we can, I think we would agree that one log line with an optional err that can be nil would be sufficient and we end up with the code we already had.

Thoughts? :-)

**Comment by alvaroaleman** [comment]
@xrstf done

**Comment by xrstf** [comment]
Beauty!

/lgtm

**Pull request merged**
