### PR TITLE
shfmt all our shell scripts

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
like gofmt but for shell

https://github.com/mvdan/sh#shfmt

```release-note
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
As a follow up we probably need to include `make shfmt-check` in pipeline.

**Comment by alvaroaleman** [comment]
@kron4eg maybe bring this up in the dev meeting? Generally it seems there is not much interest thought, so in doubt we should refrain from using this, as it will force everyone to install stuff without a clear benefit

**Comment by kron4eg** [comment]
Yeah, will do.

**Pull request closed without merging**
