### PR TITLE
Remove Openshift support

### LINKED ISSUE #6403: Remove Openshift Support
**User Story**
As a user I do not need Openshift Support.

**Acceptance criteria**
Clean the code of the Openshift support.

### PR DESCRIPTION
**Pull request by moelsayed**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6403

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
OpenShift support is removed. 
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by maciaszczykm** [comment]
/hold

This cannot be done at the moment as UI still have OpenShift support. First UI have to be adjusted.

cc @shaase-ctrl @floreks @kgroschoff

**Comment by maciaszczykm** [comment]
I'll check if I can remove it quickly.

**Comment by maciaszczykm** [comment]
/approve

@moelsayed You can remove hold once https://github.com/kubermatic/dashboard/pull/3100 will be merged.

**Comment by moelsayed** [comment]
@maciaszczykm Awesome, thank you!

**Pull request merged**
