### PR TITLE
[release/v2.24] Bump github.com/go-git/go-git/v5 from 5.8.0 to 5.11.0 (#12930)

### PR DESCRIPTION
**Pull request by SimonTheLeg**
Manual cherry-pick of https://github.com/kubermatic/kubermatic/pull/12930, due to conflicts in go.mod, which prevented automatic cherry-pick

Bumps [github.com/go-git/go-git/v5](https://github.com/go-git/go-git) from 5.8.0 to 5.11.0.
- [Release notes](https://github.com/go-git/go-git/releases)
- [Commits](https://github.com/go-git/go-git/compare/v5.8.0...v5.11.0)

---
updated-dependencies:
- dependency-name: github.com/go-git/go-git/v5 dependency-type: direct:production ...

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update go-git. This enables Applications to work with private Azure DevOps Git repositories
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by dharapvj — APPROVED** [review]

**Review by embik — APPROVED** [review]
/approve

**Comment by embik** [comment]
@SimonTheLeg one nit before merging, can we please add a release note? Given that this is supposed to fix something that end users experience, I think this should have a release note of some form.

**Comment by SimonTheLeg** [comment]
That is a really good point. Added a release note

**Comment by embik** [comment]
Thanks!

**Comment by dharapvj** [comment]
How about cherry picking this to 2.23 as well, if it is not too much of work?

**Pull request merged**
