### PR TITLE
Enable storage and LB e2e tests for GCP

### LINKED ISSUE #3504: Verify and enable GCP cloud provider functionality in e2e tests
**User Story**

As a user I want to use LoadBalancers and PVs with GCP

**Acceptance criteria**

* The storage  e2e test is activated for GCP: https://github.com/kubermatic/kubermatic/blob/9a190facdc1c9a1ecce8c6a8a91046df8cd09d68/api/cmd/conformance-tests/runner.go#L996
* The LB e2e test is activated for GCP: https://github.com/kubermatic/kubermatic/blob/9a190facdc1c9a1ecce8c6a8a91046df8cd09d68/api/cmd/conformance-tests/runner.go#L1004
* Any fixes necesary to make the two pass are made

/cc @nikhita 
xref https://github.com/kubermatic/kubermatic/issues/3234

### PR DESCRIPTION
**Pull request by nikhita**
Fixes https://github.com/kubermatic/kubermatic/issues/3504

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
> msg="Successfully validated PVC support" 

:tada: 

Created https://github.com/kubermatic/machine-controller/pull/565 for LBs

**Comment by nikhita** [comment]
> "Successfully validated LB support" 

:tada:

**Comment by nikhita** [comment]
/assign @alvaroaleman 

If this lgty, I will push the `v0.2.14` addons image.

**Comment by alvaroaleman** [comment]
/lgtm
/approve
/hold

very, very nice :)

**Comment by nikhita** [comment]
Image pushed: https://quay.io/repository/kubermatic/addons?tab=tags

Will update the PR after https://github.com/kubermatic/kubermatic/pull/3587 merges, and run the test once again

**Comment by nikhita** [comment]
GCP test is green :heavy_check_mark:

**Pull request merged**
