### PR TITLE
Set up kind with Cilium as CNI

### LINKED ISSUE #12350: Enable NetworkPolicies in kind setup used by e2e tests
KKP supports setting up NetworkPolicies for e.g. the kube-apiserver. Since our e2e tests run within kind, NetworkPolicies have no effect there (see #842). As such, we fail to identify issues with NetworkPolicies in PRs.

https://github.com/kubermatic/machine-controller/pull/1304 has an example of installing a custom CNI into kind. Perhaps plain Calico or Canal can help us here to enable `NetworkPolicy` support.

## Acceptance Criteria

- The `kind` set up for all e2e tests is capable of enforcing `NetworkPolicies`.
- KKP e2e tests have the apiserver network policies feature enabled, so they get applied as part of KKP reconciling.

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
We ran into issues with Cilium as CNI that were unexpected (#12874). I think it's past time we ran e2e tests with Cilium in the mix, since it is becoming our "main" CNI.

**Which issue(s) this PR fixes**:

Fixes #12350

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
/hold

so this can be discussed.

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
