### PR TITLE
[release/v2.23] Added missing description to the KKP CRDs Specs (#12680)

### PR DESCRIPTION
**Pull request by archups**
This is an manual cherry-pick of https://github.com/kubermatic/kubermatic/pull/12680

---------

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind documentation

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
https://docs.kubermatic.com/kubermatic/v2.23/references/crds/
```

### CODE REVIEW

**Comment by archups** [comment]
/lgtm 
/approve

cc @kubermatic/sig-release-managers

**Review by embik — APPROVED** [review]
/approve

**Pull request merged**
