### PR TITLE
[release/v2.20] Add support for Kubernetes 1.23

### LINKED ISSUE #9833: Backport Kubernetes 1.23 support to release/v2.20
### Description of the feature you would like to add / User story

As a KKP 2.20 user
I would like to be able to use Kubernetes 1.23 for a user cluster
in order to have a sufficient amount of Kubernetes versions supported by upstream available

### Solution details

- Kubernetes 1.23 support should be backported to the `release/v2.20` branch
- Changes made after the initial 1.23 support PR also potentially need backporting, like the vSphere CSI driver update

### Alternative approaches

- Not supporting 1.23 in KKP 2.20: Not feasible because by June, only Kubernetes 1.22 will be supported from the Kubernetes versions offered in KKP 2.20.

### PR DESCRIPTION
**Pull request by embik**
**What does this PR do / Why do we need it**:

Cherry-picking/backporting Kubernetes 1.23 support to KKP 2.20. Key changes from the cherry-picked PRs:

- Hetzner CCM is only updated for Kubernetes 1.23
- vSphere CSI/CCM is only updated for Kubernetes 1.23

**Does this PR close any issues?**:
Fixes #9833

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
- Add support for Kubernetes 1.23
- Update cluster-autoscaler (1.20 to 1.20.2, 1.21 to 1.21.2, 1.22 to 1.22.2)
```

### CODE REVIEW

**Comment by embik** [comment]
/hold

I don't want this to merge yet.

**Comment by embik** [comment]
The Equinix Metal / Packet e2e test fails because of:

```
The facility ewr1 has no provisionable t1.small.x86 servers matching your criteria
```

Since it was working yesterday (see job history), I think it's reasonable to assume this PR works for Equinix Metal, when the needed capacity is available from them.

**Review by xrstf — APPROVED** [review]
Good luck!

/approve

**Pull request merged**
