### PR TITLE
[release/v2.19] Update to etcd 3.5.3 for Kubernetes 1.22+

### PR DESCRIPTION
**Pull request by embik**
**What does this PR do / Why do we need it**:

Manual cherry-pick of #9604 (courtesy of fixture updates). Please see original PR for details.

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
For Kubernetes 1.22 and higher, etcd is updated to v3.5.3 to fix data consistency issues as reported by upstream developers
```

### CODE REVIEW

**Comment by embik** [comment]
/hold

Let's not jump the gun on merging this and pushing it out. We want to verify this works.

**Comment by embik** [comment]
/hold cancel

e2e tests look stable enough with this.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
