### PR TITLE
Drop metrics from kube-state-metrics initContainer

### PR DESCRIPTION
**Pull request by cbeneke**
**What this PR does / why we need it**:

#3427 added a scrape annotation for the kube-state-metrics server scraping all pods. Since prometheus 2.11 this includes initContainers, breaking the upness alerts on the kube-state-metrics server

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:
This might be resolvable in many ways, but since the scrape label is very restricted (one or all), it seemed for me the most elegant version to drop the labels in relabelling

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
Thanks :) Is this preventitive? The user-cluster Prometheus is still running on 2.9.2 IIRC.

**Comment by cbeneke** [comment]
Sorry, forgot to mention. Yes it is, we are using 2.11 in our stack for the performance boost. Just wanted to play this back ;)

**Pull request merged**
