### PR TITLE
Add mla options to admin settings

### LINKED ISSUE #7007: Add Admin Settings for MLA options
Add Admin Settings for MLA:
- enable/enforce logging
- enable/enforce monitoring

### PR DESCRIPTION
**Pull request by kgroschoff**
**What this PR does / why we need it**:
Add mla options to admin settings

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7007 

**Special notes for your reviewer**:
/

**Does this PR introduce a user-facing change?**:

```release-note
Added mla options to admin settings
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]
/approve

**Review by xmudrii — APPROVED** [review]
/approve

**Pull request merged**
