### PR TITLE
[release/v2.21] Anexia: allow extended disk configuration in AnexiaNodeSpec

### PR DESCRIPTION
**Pull request by LittleFox94**
**What this PR does / why we need it**:

This extends `apiv1.AnexiaNodeSpec` to allow extended disk configuration introduced in machine-controller with https://github.com/kubermatic/machine-controller/pull/1402.

Without this, Kubermatic API returns a 500 when trying to do any `MachineDeployment` operation on a cluster which has a `MachineDeployment` with the new `disks` attribute (and thus without the old `diskSize` attribute).

Backport of #10816 

**What type of PR is this?**
/kind bug
/kind feature
/kind api-change

It's a bug (500 error) because of a new feature, which causes and api-change

**Special notes for your reviewer**:

Comments on the machine-controller PRs:
* https://github.com/kubermatic/machine-controller/pull/1405#issuecomment-1220500780
* https://github.com/kubermatic/machine-controller/pull/1402#issuecomment-1220506220

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Extend disk configuration for provider Anexia
```

**Documentation**:

```documentation

```

### CODE REVIEW

**Comment by LittleFox94** [comment]
/retest

... oops

**Comment by LittleFox94** [comment]
If I read the failure correctly, it needs #10918 backported to release/v2.21 and this branch rebased on that backport

I could cherry-pick that commit into this branch here, but it's very unrelated changes and I'd like to avoid that - but it's your repo :)

**Comment by ahmedwaleedmalik** [comment]
@LittleFox94 Ha seems like your PRs have been having a really bad time due to our vSphere infrastructure. I'm taking care of backporting https://github.com/kubermatic/kubermatic/pull/10918. I'll re-run the failing tests on your PRs once the backports are in.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
