### PR TITLE
Fix prometheus alertmanager queries for KubeClientCertificateExpiration

### PR DESCRIPTION
**Pull request by cedi**
**What this PR does / why we need it**:
In the alert-manager config there is a problem where

`apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0`
and
`histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"} [5m]))) < 604800`
are joined together by `and`.

However the first portion contains a label `instance` while the second
portion of the query does a `sum(` doesn't include the `instance` label
and therefore prometheus cannot join together those two queries.

This patch adds the instance label to the histogram query in order to
make this alert work.
This can cause an production outage, since you wont be alerted
on a expiring certificate in time.

The current query is this:
Screenshot 2020-07-23 at 11 19 42

While the query submitted in this PR is this:
Screenshot 2020-07-23 at 11 16 18

**Which issue(s) this PR fixes** *
No issue opened on the Kubermatic repository

**Special notes for your reviewer**:
None

**Documentation**:
None

**Does this PR introduce a user-facing change?**:
```release-note
Fixing the KubeClientCertificateExpiration Prometheus Alert which did not alert in for expiring certificates
```

### CODE REVIEW

**Comment by xrstf** [comment]
Looks good! Please just bump the chart version and we can get this merged :)

/approve

**Comment by cedi** [comment]
bumped the Prometheus Chart Version from 2.2.23 to 2.2.24

**Review by xrstf — CHANGES_REQUESTED** [review]
You got sniped and some other PR bumped the chart version before this got merged. Please bump again :-)

**Comment by xrstf** [comment]
/retest

This should make the verify job's logs available to you without having to authenticate.

**Comment by cedi** [comment]
Big sorry for the delay! I'll open a new MR with the correct version.I think I just messed this MR up.
New MR: #5737

**Pull request closed without merging**
