### PR TITLE
fix data race condition

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: fix data race condition for unit tests. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Just for my understanding, why was this issue happening and why does this change fix it?

**Comment by zreigz** [comment]
I was able to reproduce this data race condition every time and output pointed out those two places all the time.
I didn't discover the root cause. I discovered that adding `time.Local = time.UTC` in any init function cause the problem

**Pull request merged**
