### PR TITLE
Add missing AWS AssignPublicIP 

### PR DESCRIPTION
**Pull request by kgroschoff**
**What this PR does / why we need it**:
Add missing AWS AssignPublicIP, as it seems it wasn't recognized and related endpoints only returned `assignedPublicIP: null` even though it was send via frontend.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to https://github.com/kubermatic/dashboard-v2/issues/1814

**Special notes for your reviewer**:
/

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@kgroschoff should this be cherrypicked to 2.12?

**Comment by kgroschoff** [comment]
yeah, I guess this would make sense 👍 

/cherrypick release/v2.12

**Pull request merged**
