### PR TITLE
Add API endpoints for Nutanix cloud resources

### LINKED ISSUE #8679: Add KKP API endpoints to query Nutanix data
The KKP API needs several endpoints to query Nutanix for data. What is needed (as far as I can say):

- Endpoint to get Nutanix Clusters
- Endpoint to get Nutanix Projects
- Endpoint to get Nutanix Subnets

### PR DESCRIPTION
**Pull request by embik**
**What does this PR do / Why do we need it**:

This adds a couple of API endpoints that return information from Nutanix: Nutanix clusters, projects and subnets. These three are needed for supporting auto-completion the Kubermatic dashboard.

**Does this PR close any issues?**:
Fixes #8679

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Add endpoints to v2 KKP API to query Nutanix clusters, projects and subnets
```

### CODE REVIEW

**Comment by embik** [comment]
/cherry-pick release/v2.19

For when this gets merged.

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
