### PR TITLE
fix vsphere periodic tests failure

### PR DESCRIPTION
**Pull request by mlavacca**
**What does this PR do / Why do we need it**:
Investigate and fix vSphere e2e tests failures.

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:
Changes:
* Vsphere CSI addon folder now triggers vsphere e2e tests (to spot these kind of issues as fast as possible in the future)
* Fixed Typo in the mounted secret (the secret wasn't mounted because not found)
* Added seccomp profile to pass the seccomp conformance tests (just copied and past from all other addons)

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by mlavacca** [comment]
/hold
vSphere infra is down

**Comment by xrstf** [comment]
/override pre-kubermatic-e2e-vsphere-ubuntu-1.21 

vCenter is offline.

**Pull request merged**
