### PR TITLE
enable operator on dev

### LINKED ISSUE #4728: Kubermatic Operator: Use on dev/cloud
**User Story**
This is the final step of the migration from the Helm chart to the new operator. This step involves setting up the operator on the two master clusters, adjusting the postsubmit deploy jobs to just patch the KubermaticConfiguration to the newer version, and removing the Kubermatic chart from master and seed clusters.

This is part of #4723.

**Acceptance criteria**
* [ ] The Kubermatic chart is not installed on any master/seed cluster for dev/cloud.
* [ ] A single Kubermatic Operator runs in each master cluster.

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This enables the Kubermatic Operator **instead of** Helm on dev.kubermatic.io.

**Which issue(s) this PR fixes**:
Fixes #4728

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

This needs to be properly prepared.

**Review by kron4eg — APPROVED** [review]
/lgtm 
/approve

**Review by kron4eg — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
