### PR TITLE
Bump minor Go dependencies

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
This PR does a lot of `go get` calls to update minor dependencies.

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
/unhold

Since my PR is merged now :P

**Comment by xrstf** [comment]
@ahmedwaleedmalik had to rebase, please re-review :)

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve ⚡

**Pull request merged**
