### PR TITLE
Fixup chart sync script

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Fixes up the sync script. Note that this makes the script incopatible with drone as it only supports https cloning whereas Prow only supports ssh cloning. To make that obvious I've removed the drone step.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/hold
@alvaroaleman Since this removes the drone part, let's merge this once https://github.com/kubermatic/infra/pull/141 lgty.

/lgtm
/approve

**Comment by alvaroaleman** [comment]
Canceling the hold because this job is never executed on the `master` branch anyways and we need this change in `release/v2.9`

/hold cancel

**Comment by nikhita** [comment]
i'll create a PR.

**Pull request merged**
