### PR TITLE
Remove support for k8s 1.17 and update versions

### PR DESCRIPTION
**Pull request by irozzo-1A**
**What this PR does / why we need it**:
Remove 1.17 from default supported kubernetes versions and update patch versions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Drop Kubernetes 1.17 support and update default versions.
```

### CODE REVIEW

**Comment by irozzo-1A** [comment]
ref: #6886

**Review by kron4eg — APPROVED** [review]

**Comment by irozzo-1A** [comment]
@xrstf could you please `/override pre-kubermatic-e2e-openstack-centos-1.21`? I'm going to create an issue to track that and we will investigate it in parallel, but I don't want to delay the release of the alpha version to proceed with the QA.

**Comment by irozzo-1A** [comment]
ref: #6886

**Pull request merged**
