### PR TITLE
Deactivate automatic deployment to dev on commit to arbitrary branch

### PR DESCRIPTION
**Pull request by mrIncompetent**

### CODE REVIEW

**Comment by scheeles** [comment]
What the reason for it?
Shouldn't we better to setup the staging system for "stable" branches

**Comment by guusvw** [comment]
I'm fine with that, or @scheeles approach, dev/staging/prod, but I think, we need one stable system, which is not the prod system.

**Comment by mrIncompetent** [comment]
@scheeles we have a staging system but we are effectively not using it. It would make more sense that everyone runs kubermatic locally for development.
Right now dev is broken on a regular basis.
Also it would reduce the maintenance overhead for us if we only have to maintain a single cluster.

**Review by guusvw — APPROVED** [review]
Agree with @mrIncompetent

**Comment by scheeles** [comment]
The reason for the mono repo was that we can deploy in sync config and code. 

Agree we should have one stable system but I also deploy dev as an unstable system. 
Alternative we switch in a future to an annotation based setup. e.g. @kubebot e2e or @kubebot deploy

**Comment by scheeles** [comment]
btw. can't we deploy per branch a seperate namespace

**Comment by guusvw** [comment]
There is a GitHub Hook event triggered when a branch is deleted https://developer.github.com/v3/activity/events/types/#deleteevent
We can extend Jenkins or write an own simple application, that removes the deprecated namespace.

**Comment by mrIncompetent** [comment]
Wouldn't it be cleaner to create a new Cluster via dev.kubermatic.io & deploy the build into that cluster?
That way we can have a really independent Cluster where we can also deploy the config without breaking dev

**Pull request merged**
