### PR TITLE
Revert "cluster-template: add custom annotations to user clusters (#1…

### PR DESCRIPTION
**Pull request by yaa110**
…1569) (#13502)"

This reverts commit bffa556b8e47db38ca8c76f03432064796dc4384.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
Please set the release-note in this and the original PR to NONE.

**Comment by embik** [comment]
Why are we reverting?

**Comment by xrstf** [comment]
See the original issue and the comments on it.

**Comment by yaa110** [comment]
I accidentally deleted the source branch. Please review the new PR: https://github.com/kubermatic/kubermatic/pull/13651

**Pull request closed without merging**
