### PR TITLE
Elasticsearch exporter

### LINKED ISSUE #2663: Deploy Elasticsearch-Exporter
**User Story**
To ensure quick help when Elasticsearch has issues, we should provide an option to monitor elasticsearch. There is https://github.com/justwatchcom/elasticsearch_exporter so it should be easy to extend the Helm chart and add scraping rules for Prometheus.

**Acceptance criteria**
* [x] elasticsearch_exporter is running inside the logging namespace.
* [x] new metrics are ingested by Prometheus
* [x] an alerting rule is triggered when shards become unavailable / Kibana dies

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This extends the elasticsearch chart to deploy the elasticsearch-exporter app to monitor the cluster's health. The PR also adds a couple of basic Prometheus alerts.

**Which issue(s) this PR fixes**:
Fixes #2663

**Release note**:
```release-note
add elasticsearch-exporter to logging stack to improve monitoring
```

### CODE REVIEW

**Comment by kron4eg** [comment]
@xrstf did anyone asked for this?

**Comment by xrstf** [comment]
We had an issue for it because our own ES stack kept dying and now we have a customer who had similar trouble and would have benefited from a better monitoring of the stack.

**Pull request merged**
