### PR TITLE
Docker suffix bump after golang 1.20.3 patch

### PR DESCRIPTION
**Pull request by pkprzekwas**
**What this PR does / why we need it**:
Updates Golang version in docker images.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/release/issues/11

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update golang version to 1.20.3.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
@pkprzekwas can we update the release note to mention the Go update?

**Review by embik — APPROVED** [review]

**Comment by ahmedwaleedmalik** [comment]
/hold

To make way for:
- https://github.com/kubermatic/kubermatic/pull/12130
- https://github.com/kubermatic/kubermatic/pull/12147

**Comment by ahmedwaleedmalik** [comment]
/unhold 
🟢

**Pull request merged**
