### PR TITLE
Update to controller-runtime 0.17.1

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This bumps us to Kubernetes 1.29 and controller-runtime 0.17.1.

Lovingly, this _FINALLY_ allows us to get rid of the v12 client-go, which also allows us to remove all those replace directives. I checked with `go version -m _build/kubermatic-operator` and the correct k8s.io module versions were indeed present in the binaries.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update to Kubernetes 1.29 / controller-runtime 0.17.1
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
@ahmedwaleedmalik I think I know _exactly_ what you tried in your PR and what you saw when you re-tested the RBAC controller and yes, that made me :flushed: as well.. :grin:

**Comment by xrstf** [comment]
/hold

not yet clear if we want this for KKP 2.25

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
