### PR TITLE
Fix import order

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This fixes the import order in all Go source files using https://github.com/xrstf/gimps.

To run it yourself, just `go get go.xrstf.de/gimps` and run it in the repo root: `gimps .`

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]

**Review by kgroschoff — COMMENTED** [review]
/approve

**Review by moadqassem — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
