### PR TITLE
consumes cloud providers APIs without presenting secrets.

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: allows to consume cloud providers APIs without presenting the credentials. For example getting the list of flavours(sizes). Those EPs are needed to maintain backward compatibility where the dashboard was sending request to providers after creating a cluster. This didn't work because we stopped sending the credentials from API.

**Special notes for your reviewer**: we manually tested cluster creation, deletion and edition, we also tested "Add Node" functionality (after cluster creation) for DigitalOcean and Openstack providers.

Marcin is going to issue a separate pull that has necessary changes for the dashboard.

**Release note**:

```release-note
Communicating with cloud providers APIs no longer requires providing additional credentials.
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
release note is missing

**Review by mrIncompetent — APPROVED** [review]

**Review by maciaszczykm — APPROVED** [review]

**Comment by p0lyn0mial** [comment]
do we want to cherry-pick it into `3.8` and master ?

**Comment by mrIncompetent** [comment]
> do we want to cherry-pick it into 3.8 and master ?

Yes

**Comment by p0lyn0mial** [comment]
does it mean we have to maintain backward compatibly and we cannot remove the old endpoints ? Note that those endpoints can only be used by the old version of our dashboard (before UM), the new dashboard has completely different code base.

**Comment by mrIncompetent** [comment]
> does it mean we have to maintain backward compatibly and we cannot remove the old endpoints ? Note that those endpoints can only be used by the old version of our dashboard (before UM), the new dashboard has completely different code base.

Right, we don't have to backport it to master. 
But to v2.8, as we have not dropped the old endpoints there and should provide at least some degree of backwards compatibility.

**Comment by p0lyn0mial** [comment]
> But to v2.8, as we have not dropped the old endpoints there and should provide at least some degree of backwards compatibility.

okay, sounds reasonable, can I just tag the pull and the bot will take over ?

**Comment by p0lyn0mial** [comment]
I did manual cherry-pick https://github.com/kubermatic/kubermatic/pull/2156

**Pull request merged**
