### PR TITLE
Conformance tests: Enable monitor mode

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Fixes cleanup when the job receives a signal:

```
$ cat test.sh 
#!/bin/bash

set -o monitor

trap 'echo FOO' EXIT
echo "sleeping"
sleep 1000

$ docker run --rm -v $PWD:/script -e ENTRYPOINT_OPTIONS='{"args":["/script/test.sh"],"process_log":"/log","marker_file":"/marker"}' gcr.io/k8s-prow/entrypoint:v20190301-1278de5-with-bash /entrypoint
sleeping
{"component":"entrypoint","level":"error","msg":"Entrypoint received interrupt: terminated","time":"2019-03-06T21:13:02Z"}
FOO
{"component":"entrypoint","level":"error","msg":"Process did not exit before 15s grace period","time":"2019-03-06T21:13:17Z"}
{"component":"entrypoint","error":"os: process already finished","level":"error","msg":"Could not kill process after grace period","time":"2019-03-06T21:13:17Z"}
{"component":"entrypoint","error":"process aborted","level":"error","msg":"Error executing test process","time":"2019-03-06T21:13:17Z"}

vs

$ cat test.sh 
#!/bin/bash

#set -o monitor

trap 'echo FOO' EXIT
echo "sleeping"
sleep 1000

$ docker run --rm -v $PWD:/script -e ENTRYPOINT_OPTIONS='{"args":["/script/test.sh"],"process_log":"/log","marker_file":"/marker"}' gcr.io/k8s-prow/entrypoint:v20190301-1278de5-with-bash /entrypoint
sleeping
{"component":"entrypoint","level":"error","msg":"Entrypoint received interrupt: terminated","time":"2019-03-06T21:27:58Z"}
{"component":"entrypoint","level":"error","msg":"Process did not exit before 15s grace period","time":"2019-03-06T21:28:13Z"}
{"component":"entrypoint","error":"process aborted","level":"error","msg":"Error executing test process","time":"2019-03-06T21:28:13Z"}
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Also manually verified that this actually fixes the issue (hence the failure above):

```
$ k delete pod d16205e9-4056-11e9-9b9d-0a580a28008b

# logs from other terminal
time="2019-03-06T21:36:17Z" level=info msg="Successfully created 3 machine(s)!" cloud-provider=aws cluster=prow-e2e-dh5nw5g2 kubeconfig=/tmp/e2e-home-977074612/prow-e2e-dh5nw5g2-kubeconfig scenario=aws-coreos-1.11.6 version="{1.11.6}" worker=11 worker-name=1103407170910687232
time="2019-03-06T21:36:17Z" level=info msg="Waiting for nodes to become ready..." cloud-provider=aws cluster=prow-e2e-dh5nw5g2 kubeconfig=/tmp/e2e-home-977074612/prow-e2e-dh5nw5g2-kubeconfig scenario=aws-coreos-1.11.6 version="{1.11.6}" worker=11 worker-name=1103407170910687232
{"component":"entrypoint","level":"error","msg":"Entrypoint received interrupt: terminated","time":"2019-03-06T21:36:31Z"}
Wed Mar  6 21:36:31 UTC 2019 Starting cleanup
addon.kubermatic.k8s.io/canal labeled
addon.kubermatic.k8s.io/dashboard labeled
addon.kubermatic.k8s.io/default-storage-class labeled
addon.kubermatic.k8s.io/dns labeled
addon.kubermatic.k8s.io/kube-proxy labeled
addon.kubermatic.k8s.io/kubelet-configmap labeled
addon.kubermatic.k8s.io/openvpn labeled
addon.kubermatic.k8s.io/rbac labeled
cluster.kubermatic.k8s.io "prow-e2e-dh5nw5g2" deleted
cluster.kubermatic.k8s.io/prow-e2e-dh5nw5g2 labeled
release "kubermatic-1103407170910687232" deleted
clusterrolebinding.rbac.authorization.k8s.io "prow-1103407170910687232-kubermatic" deleted
clusterrolebinding.rbac.authorization.k8s.io "prow-1103407170910687232-tiller" deleted
namespace "prow-kubermatic-1103407170910687232" deleted
mv: cannot stat '/reports/*': No such file or directory
Wed Mar  6 21:36:34 UTC 2019 Finished cleanup
rpc error: code = Unknown desc = Error: No such container: e53df094e626e4bfc89062ff06463b35c728008b7a9f5a162da25921090f5e67
```

/cherrypick release/v2.9
/retest

**Comment by alvaroaleman** [comment]
/assign @nikhita 
CC @mrIncompetent

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

For additional context: https://kubernetes.slack.com/archives/CDECRSC5U/p1551908444109100 :)

**Pull request merged**
