### PR TITLE
Add api-server cilium network policy in seed cluster

### LINKED ISSUE #12874: api-server fails due to NetworkPolicy seed-apiserver-allow with Cilium
### What happened?

After upgrading to KKP `v2.24.0`, the user cluster api-server fails with the below error.
```
k logs -n cluster-espbj2d78g  apiserver-54f99cfff7-kkjf4 -c etcd-running -f
{"level":"error","time":"2023-11-30T10:43:46.518Z","caller":"etcd-launcher/main.go:116","msg":"Operation failed: failed to initialize etcd cluster configuration: failed to get API group resources: unable to retrieve the complete list of server APIs: kubermatic.k8c.io/v1: Get \"https://10.96.0.1:443/apis/kubermatic.k8c.io/v1\": dial tcp 10.96.0.1:443: i/o timeout."}
```

This is due to new network policy seed-apiserver-allow (https://github.com/kubermatic/kubermatic/pull/12569).

After pausing the cluster and removing the ipBlocks and, for example, only port 6443, it works.
```
  egress:
  - ports:
    - port: 6443
      protocol: TCP
  podSelector:
    matchLabels:
      app: apiserver
  policyTypes:
  - Egress
```

### Expected behavior

Running api-server

### How to reproduce the issue?

Upgrade to v2.24.0

### How is your environment configured?

- KKP version: v2.24.0
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### PR DESCRIPTION
**Pull request by cnvergence**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/12874

**What type of PR is this?**

/kind bug
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
If the seed cluster is using Cilium as CNI, create CiliumClusterwideNetworkPolicy for api-server connectivity.
```

**Documentation**:

```documentation
TBD
```

### CODE REVIEW

**Comment by embik** [comment]
Have you tried this out? As mentioned, I don't believe it will work. I went down that route in #12886 and had to revert in #12892. The error I saw is the one below, and I assume the same happens with `CiliumClusterwideNetworkPolicy`:

```
E1208 09:54:37.914205       1 runtime.go:79] Observed a panic: reflect.unexportedTypePanic{(*reflect.rtype)(0x48f6dc0), (*reflect.rtype)(0x462cd20), (*reflect.rtype)(0x47462a0), (*reflect.rtype)(0x4735600), (*reflect.rtype)(0x48236c0), (*reflect.rtype)(0x40277c0), (*reflect.rtype)(0x3f06340), (*reflect.rtype)(0x4527b60), (*reflect.rtype)(0x3e51240)} (an unexported field was encountered, nested like this: *v2.CiliumNetworkPolicy -> v2.CiliumNetworkPolicy -> *api.Rule -> api.Rule -> api.EndpointSelector -> *labels.Requirements -> labels.Requirements -> labels.Requirement -> string)
[...]
k8s.io/apimachinery/third_party/forked/golang/reflect.Equalities.DeepEqual(0x462cd20?, {0x48f6dc0?, 0xc0024e8140?}, {0x48f6dc0?, 0xc0027bda40?})
	k8s.io/apimachinery@v0.28.3/third_party/forked/golang/reflect/deep_equal.go:273 +0x2d
k8c.io/reconciler/pkg/compare.DeepEqual({0x7f44ed8df298?, 0xc0024e8140}, {0x7f44ed8df298?, 0xc0027bda40})
	k8c.io/reconciler@v0.5.0/pkg/compare/compare.go:40 +0x70
k8c.io/reconciler/pkg/reconciling.EnsureNamedObject.waitUntilUpdateIsInCacheConditionFunc.func4({0x5182280, 0xc000236bd0})
	k8c.io/reconciler@v0.5.0/pkg/reconciling/ensure.go:188 +0x16
[...]
{"level":"info","time":"2023-12-08T09:54:37.914Z","caller":"runtime/panic.go:914","msg":"Observed a panic in reconciler: an unexported field was encountered, nested like this: *v2.CiliumNetworkPolicy -> v2.CiliumNetworkPolicy -> *api.Rule -> api.Rule -> api.EndpointSelector -> *labels.Requirements -> labels.Requirements -> labels.Requirement -> string","controller":"kkp-kubernetes-controller","object":{"name":"kkp-1733060727322710016-q5tbw"},"namespace":"","name":"kkp-1733060727322710016-q5tbw","reconcileID":"62059d23-5efe-4d87-bf68-05b9294971a4"}
```

**Comment by cnvergence** [comment]
@embik uh, thanks for the heads-up
I will drop the use of the reconciler then

**Review by embik — APPROVED** [review]
/approve

**Pull request merged**
