### PR TITLE
Constraint get list from user cluster

### LINKED ISSUE #6143: OPA Integration - Constraint GET and LIST endpoint to take Constraints directly from user cluster
**User Story**
Currently GET and LIST endpoint get and list the Kubermatic Constraint CRDs. Those dont have the status data that the user cluster Gatekeeper Constraints have. To make life easier, change get and list to get them directly from the user cluster so that all the data is filled.

### PR DESCRIPTION
**Pull request by lsviben**
**What this PR does / why we need it**:
Changes the Constraint GET and LIST endpoints to get/list the constraints directly from the user cluster so that the status information is available. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6143 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lsviben** [comment]
@zreigz PTAL

**Comment by zreigz** [comment]
Please solve the conflict first

**Comment by lsviben** [comment]
> Please solve the conflict first

rebased

**Pull request merged**
