### PR TITLE
Fix GCP FailedToCreateRoute issue

### LINKED ISSUE #5025: GCP: some AZ's create FailedToCreateRoute errors
**User Story**
After some investigation I figured out that some availability zones  constellation produce the following error at the kubelet  of the worker nodes:
`FailedToCreateRoute      6m12s                  route_controller                        Could not create route 3467f96c-40f8-4523-a2f9-0a87adbc3954 172.25.4.0/24 for node test-tobi-6d6bb77b59-jw9l6 after 287.400348ms: instance not found`

This only happens on some AZ not all. At dev.kubermatic.io the error is reproducible by the following steps:
1. Create GCP cluster with node deployment in az `europe-west3-a`, type e.g. `n1-standard-2`
2. Wait until the node is come up completely, it took a while until the kubelet post the error. Wait at least 5min.
3. check the node state: `kubectl describe node xxx`

*machinedeployment:*
```
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  annotations:
    machinedeployment.clusters.k8s.io/revision: "3"
  creationTimestamp: "2020-02-01T20:35:56Z"
  finalizers:
  - foregroundDeletion
  generation: 4
  name: test-tobi
  namespace: kube-system
  resourceVersion: "24249"
  selfLink: /apis/cluster.k8s.io/v1alpha1/namespaces/kube-system/machinedeployments/test-tobi
  uid: d92848af-6902-4903-8710-2079ea27009e
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      machine: md-n8zgmmc9bz-2sswd5txn7
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine: md-n8zgmmc9bz-2sswd5txn7
    spec:
      metadata:
        creationTimestamp: null
        labels:
          system/cluster: n8zgmmc9bz
          system/project: t24hvctglz
      providerSpec:
        value:
          cloudProvider: gce
          cloudProviderSpec:
            assignPublicIPAddress: true
            diskSize: 25
            diskType: pd-ssd
            machineType: n1-standard-2
            multizone: false
            network: global/networks/default
            preemptible: false
            regional: false
            serviceAccount: ""
            subnetwork: ""
            tags:
            - kubernetes-cluster-n8zgmmc9bz
            - system-cluster-n8zgmmc9bz
            - system-project-t24hvctglz
            zone: europe-west3-a
          operatingSystem: coreos
          operatingSystemSpec:
            disableAutoUpdate: false
            disableLocksmithD: true
            disableUpdateEngine: false
          sshPublicKeys:
      versions:
        kubelet: 1.15.9
status:
  availableReplicas: 2
  observedGeneration: 4
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2

```
*kubectl describe node*
```
Name:               test-tobi-6d6bb77b59-jw9l6
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=n1-standard-2
                    beta.kubernetes.io/os=linux
                    container-linux-update.v1.coreos.com/group=stable
                    container-linux-update.v1.coreos.com/id=coreos
                    container-linux-update.v1.coreos.com/reboot-needed=false
                    container-linux-update.v1.coreos.com/version=2303.3.0
                    failure-domain.beta.kubernetes.io/region=europe-west3
                    failure-domain.beta.kubernetes.io/zone=europe-west3-a
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=test-tobi-6d6bb77b59-jw9l6
                    kubernetes.io/os=linux
                    machine-controller/owned-by=5d8ec7fc-786b-45c1-bb0e-e7389c0b6173
                    ntt-cost-center=1111111111
                    system/cluster=n8zgmmc9bz
                    system/project=t24hvctglz
                    x-kubernetes.io/distribution=container-linux
Annotations:        cluster.k8s.io/machine: kube-system/test-tobi-6d6bb77b59-jw9l6
                    container-linux-update.v1.coreos.com/last-checked-time: 1580599135
                    container-linux-update.v1.coreos.com/new-version: 0.0.0
                    container-linux-update.v1.coreos.com/reboot-in-progress: false
                    container-linux-update.v1.coreos.com/reboot-needed: false
                    container-linux-update.v1.coreos.com/status: UPDATE_STATUS_IDLE
                    flannel.alpha.coreos.com/backend-data: {"VtepMAC":"ee:19:df:9d:6f:96"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.156.0.7
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4IPIPTunnelAddr: 172.25.4.1
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sun, 02 Feb 2020 00:12:04 +0100
Taints:             node.kubernetes.io/network-unavailable:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  test-tobi-6d6bb77b59-jw9l6
  AcquireTime:     <unset>
  RenewTime:       Sun, 02 Feb 2020 00:19:45 +0100
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   True    Sun, 02 Feb 2020 00:19:43 +0100   Sun, 02 Feb 2020 00:19:43 +0100   NoRouteCreated               RouteController failed to create a route
  MemoryPressure       False   Sun, 02 Feb 2020 00:19:25 +0100   Sun, 02 Feb 2020 00:12:04 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Sun, 02 Feb 2020 00:19:25 +0100   Sun, 02 Feb 2020 00:12:04 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Sun, 02 Feb 2020 00:19:25 +0100   Sun, 02 Feb 2020 00:12:04 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Sun, 02 Feb 2020 00:19:25 +0100   Sun, 02 Feb 2020 00:12:24 +0100   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:   10.156.0.7
  ExternalIP:   35.246.226.91
  InternalDNS:  test-tobi-6d6bb77b59-jw9l6.europe-west3-a.c.test-00-tng-k8c.internal
  Hostname:     test-tobi-6d6bb77b59-jw9l6
Capacity:
  attachable-volumes-gce-pd:  127
  cpu:                        2
  ephemeral-storage:          22977180Ki
  hugepages-1Gi:              0
  hugepages-2Mi:              0
  memory:                     7652496Ki
  pods:                       110
Allocatable:
  attachable-volumes-gce-pd:  127
  cpu:                        1800m
  ephemeral-storage:          19028285405
  hugepages-1Gi:              0
  hugepages-2Mi:              0
  memory:                     7345296Ki
  pods:                       110
System Info:
  Machine ID:                 7eb03260e835ca84a425ec6fb9d892ec
  System UUID:                7eb03260-e835-ca84-a425-ec6fb9d892ec
  Boot ID:                    7f0db520-0923-4061-9789-d9295bc0cfdc
  Kernel Version:             4.19.86-coreos
  OS Image:                   Container Linux by CoreOS 2303.3.0 (Rhyolite)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://18.6.3
  Kubelet Version:            v1.15.9
  Kube-Proxy Version:         v1.15.9
PodCIDR:                      172.25.4.0/24
ProviderID:                   gce://test-00-tng-k8c/europe-west3-a/test-tobi-6d6bb77b59-jw9l6
Non-terminated Pods:          (5 in total)
  Namespace                   Name                                  CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                                  ------------  ----------  ---------------  -------------  ---
  kube-system                 canal-dq4gl                           250m (13%)    0 (0%)      0 (0%)           0 (0%)         7m44s
  kube-system                 container-linux-update-agent-s6gq4    0 (0%)        0 (0%)      0 (0%)           0 (0%)         7m44s
  kube-system                 kube-proxy-shzxf                      75m (4%)      250m (13%)  50Mi (0%)        250Mi (3%)     7m44s
  kube-system                 node-exporter-b4kpn                   20m (1%)      45m (2%)    48Mi (0%)        96Mi (1%)      7m44s
  kube-system                 node-local-dns-pfwlj                  25m (1%)      0 (0%)      5Mi (0%)         0 (0%)         7m24s
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                   Requests    Limits
  --------                   --------    ------
  cpu                        370m (20%)  295m (16%)
  memory                     103Mi (1%)  346Mi (4%)
  ephemeral-storage          0 (0%)      0 (0%)
  attachable-volumes-gce-pd  0           0
Events:
  Type     Reason                   Age                    From                                    Message
  ----     ------                   ----                   ----                                    -------
  Normal   NodeHasSufficientMemory  7m44s (x8 over 7m57s)  kubelet, test-tobi-6d6bb77b59-jw9l6     Node test-tobi-6d6bb77b59-jw9l6 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    7m44s (x8 over 7m57s)  kubelet, test-tobi-6d6bb77b59-jw9l6     Node test-tobi-6d6bb77b59-jw9l6 status is now: NodeHasNoDiskPressure
  Warning  FailedToCreateRoute      7m36s                  route_controller                        Could not create route 3467f96c-40f8-4523-a2f9-0a87adbc3954 172.25.4.0/24 for node test-tobi-6d6bb77b59-jw9l6 after 281.596196ms: instance not found
  Warning  FailedToCreateRoute      7m26s                  route_controller                        Could not create route 3467f96c-40f8-4523-a2f9-0a87adbc3954 172.25.4.0/24 for node test-tobi-6d6bb77b59-jw9l6 after 218.860946ms: instance not found
  Warning  FailedToCreateRoute      7m16s                  route_controller                        Could not create route 3467f96c-40f8-4523-a2f9-0a87adbc3954 172.25.4.0/24 for node test-tobi-6d6bb77b59-jw9l6 after 265.533296ms: instance not found
  Normal   Starting                 7m14s                  kube-proxy, test-tobi-6d6bb77b59-jw9l6  Starting kube-proxy.
  Warning  FailedToCreateRoute      7m6s                   route_controller                        Could not create route 3467f96c-40f8-4523-a2f9-0a87adbc3954 172.25.4.0/24 for node test-tobi-6d6bb77b59-jw9l6 after 287.400348ms: instance not found
  Warning  FailedToCreateRoute      6m56s                  route_controller                        Could not create route 3467f96c-40f8-4523-a2f9-0a87adbc3954 172.25.4.0/24 for node test-tobi-6d6bb77b59-jw9l6 after 285.154405ms: instance not found
  Warning  FailedToCreateRoute      6m46s                  route_controller                        Could not create route 3467f96c-40f8-4523-a2f9-0a87adbc3954 172.25.4.0/24 for node test-tobi-6d6bb77b59-jw9l6 after 274.074778ms: instance not found
  Warning  FailedToCreateRoute      6m36s                  route_controller                        Could not create route 3467f96c-40f8-4523-a2f9-0a87adbc3954 172.25.4.0/24 for node test-tobi-6d6bb77b59-jw9l6 after 230.141079ms: instance not found
  Warning  FailedToCreateRoute      6m26s                  route_controller                        Could not create route 3467f96c-40f8-4523-a2f9-0a87adbc3954 172.25.4.0/24 for node test-tobi-6d6bb77b59-jw9l6 after 286.556739ms: instance not found
  Warning  FailedToCreateRoute      6m16s                  route_controller                        Could not create route 3467f96c-40f8-4523-a2f9-0a87adbc3954 172.25.4.0/24 for node test-tobi-6d6bb77b59-jw9l6 after 236.28354ms: instance not found
  Warning  FailedToCreateRoute      2m35s (x22 over 6m6s)  route_controller                        (combined from similar events): Could not create route 3467f96c-40f8-4523-a2f9-0a87adbc3954 172.25.4.0/24 for node test-tobi-6d6bb77b59-jw9l6 after 262.880914ms: instance not found

```

**Potential solution:**
The error seams to be similar to this one in kubeone https://github.com/kubermatic/kubeone/pull/732. If I configure the configmap `cloud-config` manual, and add `regional = true` the nodes came up successful.

*Workaround steps*
1. Set cluster to pause
2. edit configmap `cloud-config` and set `regional = true`
3. ensure `api-server` and `controller-manager` pods of the user cluster restarts to load the update cloud-config (delete pods)
4. delete the `machine` object

I'm not sure if this fix is the best, but at least a starting point.

**Acceptance criteria**
- [ ] Kubermatic support deployments support any zone a GCP deployment

### PR DESCRIPTION
**Pull request by moelsayed**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5025

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]

**Comment by toschneck** [comment]
@moelsayed / @kdomanski can we please backport this to 2.13 and 2.14 as bugfix ? It's a present bug there as well

**Pull request merged**
