### PR TITLE
Retry timed out request in api e2e tests

### PR DESCRIPTION
**Pull request by irozzo-1A**
**What this PR does / why we need it**:
This PR is an attempt to fix the following issue occurring during our e2e tests:

>     credentials_test.go:146: error reading response: Get "http://localhost:8080/api/v1/providers/azure/sizes": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by irozzo-1A** [comment]
```
E1121 10:37:41.740736   10974 portforward.go:385] error copying from local connection to remote stream: read tcp4 127.0.0.1:8080->127.0.0.1:41400: read: connection reset by peer
```

This seems to trigger the condition, and retrying the request does not seem to address the problem. I need to dig a bit more into this.

**Comment by irozzo-1A** [comment]
> ```
> E1121 10:37:41.740736   10974 portforward.go:385] error copying from local connection to remote stream: read tcp4 127.0.0.1:8080->127.0.0.1:41400: read: connection reset by peer
> ```
> 
> This seems to trigger the condition, and retrying the request does not seem to address the problem. I need to dig a bit more into this.

After double-checking the timeout seems to be related to the Azure API endpoint used to list VM sizes takes long time to reply. The test sets the timeout to 10s, reducing it to 5s (even with retry) makes the timeout triggering systematically. It would be interesting to understand why it's taking so long to get an answer, but having `10s` seems to be effective to reduce failures.

**Comment by irozzo-1A** [comment]
/hold

I saw we have already a client with retry logic

**Review by youssefazrak — APPROVED** [review]

**Pull request merged**
