### PR TITLE
Add VNet resource group for Azure

### LINKED ISSUE #6316: Create API option for network resource group

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/kubermatic/issues/6316
Related to https://github.com/kubermatic/kubermatic/issues/6042

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Added VNet resource group for Azure.
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/assign @kron4eg @xmudrii 

PTAL as I need approval from sig-cluster-management.

**Comment by maciaszczykm** [comment]
/assign @zreigz 

For approval from the API side.

**Comment by kron4eg** [comment]
letting @zreigz time to see

**Pull request merged**
