### PR TITLE
remove toleration from kubevirt csi as its deployed in seed cluster

### PR DESCRIPTION
**Pull request by mate4st**
**What this PR does / why we need it**:

This should not tolerate the master as it is deploed in the seed cluster

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

```documentation
NONE
```

### CODE REVIEW

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Comment by mfranczy** [comment]
Good catch.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
