### PR TITLE
Fix Node Deployments update method

### LINKED ISSUE #2632: Scaling down node deployment doesn't remove machines
**Description**
- create a cluster with a default number of replicas: 3
- go to `Node deployments` and click the edit icon.
- scale down to 2 replicas
- wait until new replicas are created: `Replicas 2/2`

After those steps the command: `kubectl get machine -n kube-system` returns:

```
NAME                                                             KIND
machinedeployment-kubermatic-n2kl97fxf4-vhzgt-784bd8dbf6-7z4jz   Machine.v1alpha1.cluster.k8s.io
machinedeployment-kubermatic-n2kl97fxf4-vhzgt-784bd8dbf6-xqbb2   Machine.v1alpha1.cluster.k8s.io
machinedeployment-kubermatic-n2kl97fxf4-vhzgt-7f654d77ff-2qjz2   Machine.v1alpha1.cluster.k8s.io
machinedeployment-kubermatic-n2kl97fxf4-vhzgt-7f654d77ff-ftv2k   Machine.v1alpha1.cluster.k8s.io
machinedeployment-kubermatic-n2kl97fxf4-vhzgt-7f654d77ff-jrj49   Machine.v1alpha1.cluster.k8s.io

```
**Expected result**
Should be only 2 machines

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**: Fixes Node Deployments update method. Previously it `spec.selector` was changed and MachineDeployment was losing old MachineSet, now the field remain untouched.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Fixes #2632

**Special notes for your reviewer**: n/a

**Documentation**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/cc @mrIncompetent 

Please take a look on the release note, do you think that we need one here?

**Comment by maciaszczykm** [comment]
Tested it locally:

```
maciaszczykm @ ~ $ cp Downloads/kubeconfig-admin-cfkf9b7t7l .kube/config 

maciaszczykm @ ~ $ k get machinedeployment -n kube-system
NAME                          AGE
kubermatic-cfkf9b7t7l-gq96x   1m

maciaszczykm @ ~ $ k get machine -n kube-system
NAME                                           AGE
kubermatic-cfkf9b7t7l-gq96x-55cf444dd8-b52fx   1m
kubermatic-cfkf9b7t7l-gq96x-55cf444dd8-dd85k   1m
kubermatic-cfkf9b7t7l-gq96x-55cf444dd8-zn6dk   1m

maciaszczykm @ ~ $ echo "Scale in the UI to 2"
Scale in the UI to 2

maciaszczykm @ ~ $ k get machinedeployment -n kube-system
NAME                          AGE
kubermatic-cfkf9b7t7l-gq96x   2m

maciaszczykm @ ~ $ k get machine -n kube-system
NAME                                           AGE
kubermatic-cfkf9b7t7l-gq96x-55cf444dd8-dd85k   2m
kubermatic-cfkf9b7t7l-gq96x-55cf444dd8-zn6dk   2m
```

**Comment by alvaroaleman** [comment]
@maciaszczykm Do we need a release note for fixing an issue that was never part of a release?

**Comment by maciaszczykm** [comment]
@alvaroaleman Good point.

**Pull request merged**
