### PR TITLE
[release/v2.21] KubeVirt add custom netpolicies

### PR DESCRIPTION
**Pull request by hdurand0710**
Signed-off-by: Helene Durand <helene@kubermatic.com>

**What this PR does / why we need it**:
Manual cherry-pick of https://github.com/kubermatic/kubermatic/pull/11666 and https://github.com/kubermatic/kubermatic/pull/11640

**Which issue(s) this PR fixes**:

Fixes 

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
KubeVirt: add custom Network Policies. Fix LB issue (default `cluster-isolation` NetworkPolicy blocking outside cluster incoming traffic).
```

**Documentation**:

```documentation
TBD
```

### CODE REVIEW

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by embik** [comment]
/hold

tests are broken.

**Pull request merged**
