### PR TITLE
Fetch chart dependencies on dev before installing logging and monitoring

### PR DESCRIPTION
**Pull request by wurbanski**
**What this PR does / why we need it**:
Fixes deployments on dev cluster after adding dependencies to the charts.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
Do we need to think about how this affects the official KKP installation process? I assume customers would face the same error as the dev installation script when following the KKP documentation (as it doesn't include the actions taken by the new ci script). Do we need to vendor the chart dependencies into git maybe?

**Comment by wurbanski** [comment]
Installer takes care of downloading the dependencies (since #8202) - is non-installer method still recommended? if yes, then we should add this to documentation.

**Comment by embik** [comment]
Ah never mind my comment then, I wasn't aware of that!

**Comment by xrstf** [comment]
Yes, we should document the manual installation, it's important for customers with non-standard requirements (e.g. those who do not want to use nginx, but .... öhm ..... IIS?).

**Review by xrstf — APPROVED** [review]
/approve

**Comment by wurbanski** [comment]
> Yes, we should document the manual installation, it's important for customers with non-standard requirements (e.g. those who do not want to use nginx, but .... öhm ..... IIS?).

I'll create follow-up issue for that (#8275)

**Pull request merged**
