### PR TITLE
MLA: Update grafana dashboard schemas

### PR DESCRIPTION
**Pull request by wurbanski**
**What this PR does / why we need it**:
This PR fixes the issue with dashboards asking to be saved but unable to be saved because they were provisioned from files.

**Which issue(s) this PR fixes**:

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:
-

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
mla: grafana kubernetes dashboard won't repeatedly ask to be saved 
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by wozniakjan — COMMENTED** [review]
@wurbanski the diff is generated by grafana auto-conversion?

/lgtm

**Comment by wurbanski** [comment]
@wozniakjan yes, just open the old version, try to save, export, save to file...

**Comment by xrstf** [comment]
The 2.22 backport would have been best-effort, so I'm not further investigating the 2.22 backport unless there's a stronger need for it.

**Pull request merged**
