### PR TITLE
Gatekeeper adjustable resource limits

### LINKED ISSUE #8166: Gatekeeper-Audit Deployment is not adjusting to Cluster Size
If you enable Gatekeeper in a User Cluster and the Cluster is heavily utilized or  a lot of constrains are in place, you run into the issue that the gatekeeper-audit deployment (namespace: "gatekeeper-system")  will eventually fail with OOMKilled.

This was recognized by the Gatekeeper developers in the following issues as well.

https://github.com/open-policy-agent/gatekeeper/issues/339
https://github.com/open-policy-agent/gatekeeper/issues/780 

The case is a strict limit to the deployed resources. If you change the limits & requirements in the deployment it will get overwritten by the crd it seems. 

What did you expect to happen:
Either an upscaling of the gatekeeper-audit deployment  or the possibility to adjust the limits for the deployment  in order to match the requirements

KKP Version: 2.18.2
Enviroment: VSphere
UserCluster: 16 Nodes a 6 CPU 16 Gig Mem

### PR DESCRIPTION
**Pull request by lsviben**
**What this PR does / why we need it**:
Adds option to set custom resource limits for the Gatekeeper deployments on the user cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8166 

**Does this PR introduce a user-facing change?**:

```release-note
Added option to set custom Gatekeeper controller and audit resource limits as part of OPAIntegration settings in the Cluster object.
```

### CODE REVIEW

**Comment by mfranczy** [comment]
@lsviben could you rebase and squash commits?

**Comment by lsviben** [comment]
> @lsviben could you rebase and squash commits?

rebased. Commits get squashed on merge so no need. But if you insist, i can do it

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
