### PR TITLE
Anexia: update CloudControllerManager to v1.4.3

### PR DESCRIPTION
**Pull request by LittleFox94**
**What does this PR do / Why do we need it**:

Update Anexia CloudControllerManager to version 1.4.3, fixing some issues - release notes are here: https://github.com/anexia-it/k8s-anexia-ccm/releases/tag/v1.4.3

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Update Anexia CCM (cloud-controller-manager) to version 1.4.3
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by LittleFox94** [comment]
Thanks for the fast merge :)

We'd love to have our CCM updated in 2.20 as well, would such a PR be accepted?

**Pull request merged**
