### PR TITLE
[release/v2.16]Allow loose RPF for calico

### LINKED ISSUE #6853: Canal fails to deploy on VM with rp_filter sets to 2
**User Story**
Canal (Calico + Flannel) is deployed on user clusters.
If those VMs are running a newer version of systemd, the `rp_filter` will be set by default to 2 instead of 1 for all the interfaces ([See this change](https://github.com/systemd/systemd/blob/v240/sysctl.d/50-default.conf#L24-L25)).

This is technically not an issue. The problem comes from the version of Canal we are delivering on user clusters (v3.8.0). This version, up to the v3.11, doesn't support `rp_filter` being set to 2. Only to 0 or 1. This prevents the canal pods from being ready and thus having a non-working cluster.

The fix from Canal comes in the v3.12 ([see this issue and the linked PR](https://github.com/projectcalico/felix/issues/2082)). Long-term solution is to update Canal to v3.12 or later but for the moment, we can deploy a quick fix to solve this issue without having to do a tricky upgrade of the CNI.
The workaround is to remove the `rp_filter` check from Calico by setting an env variable `FELIX_IGNORELOOSERPF` to `true` in the Canal's DaemonSet. 

Canal is currently deployed using the Addons controller. 
You can find the Addons here: https://github.com/kubermatic/kubermatic/tree/master/addons
The Canal manifest is here: https://github.com/kubermatic/kubermatic/tree/master/addons/canal

**Acceptance criteria**
- Canal pod is ready in VMs having rp_filter set to 2.

### PR DESCRIPTION
**Pull request by moelsayed**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6853

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Adds `FELIX_IGNORELOOSERPF=true` to `calico-node` container env to allow running on nodes with `net.ipv4.conf.*.rp_filter = 2` set.
```

### CODE REVIEW

**Comment by irozzo-1A** [comment]
ref: https://github.com/kubermatic/kubermatic/issues/6853
@youssefazrak

**Comment by youssefazrak** [comment]
btw @moelsayed why is this not pushed to the master branch?
We can then cherry-pick for specific releases.

**Comment by youssefazrak** [comment]
@jiachengxu could you please have a look and lgtm accordingly?

**Comment by moelsayed** [comment]
@youssefazrak I am assuming we prefer to upgrade calico in master?

**Comment by moelsayed** [comment]
/hold
I want to do one more test.

**Comment by irozzo-1A** [comment]
> @youssefazrak I am assuming we prefer to upgrade calico in master?

I think it's safer having this on master, we did not plan to update CNI for the 2.17 release.

**Comment by youssefazrak** [comment]
@moelsayed Agree with Iacopo here, let's be on the safe side and have it on the master as well.

**Pull request merged**
