### PR TITLE
[WIP] refactors handlers directory

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: Mean to starts discussion about `handlers` directory refactoring.

**Special notes for your reviewer**: Perhaps we are not going to merge this pull as the directory changes quite frequently instead I'd like to phase it by creating many small pulls.

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
I decided to group by the resource. Top level directories are `cluster`, `dc`, `ssh`, `node`, `project` and `provider`. I think that I'd also like to create a `middleware` directory. I'd like to also rename some files for example `routes_v1.go` to `routes.go` as that file will be withing `v1` directory.

We could also split `user.go` file as it contains `users` and `members` (project) related functionality.

```
├── v1
│   ├── cluster
│   │   ├── cluster.go
│   │   ├── cluster_test.go
│   │   ├── kubeconfig.go
│   │   ├── kubeconfig_test.go
│   │   ├── upgrade.go
│   │   └── upgrade_test.go
│   ├── dc
│   │   ├── datacenter.go
│   │   └── datacenter_test.go
│   ├── node
│   │   ├── node_v1.go
│   │   └── node_v1_test.go
│   ├── project
│   │   ├── project.go
│   │   └── project_test.go
│   ├── provider
│   │   ├── azure.go
│   │   ├── digitalocean.go
│   │   ├── openstack_fixtures_test.go
│   │   ├── openstack.go
│   │   ├── openstack_test.go
│   │   ├── vsphere.go
│   │   └── vsphere_test.go
│   ├── routes_v1.go
│   ├── routes_v1_optional.go
│   ├── ssh
│   │   ├── ssh.go
│   │   └── ssh_test.go
│   └── user
│       ├── user.go
│       └── user_test.go
└── v1alpha
    └── routes_v1_alpha.go
├── authentication.go
├── authentication_test.go
├── handler.go
├── handler_test.go
├── request.go
├── routing.go
├── routing_test.go
```

**Comment by p0lyn0mial** [comment]
I think I could start by creating a pull that creates `v1/providers` directory and moves appropriate files to it.

**Comment by zreigz** [comment]
I also do major changes in this package changing tests package for _test. It quite impossible to change the whole package in one PR. Maybe we should make changes partially. Instead of changing all packages only just one. It would be easier to test it and verify if everything works. We could merge small changes without any problems

**Comment by p0lyn0mial** [comment]
> Instead of changing all packages only just one.

I fully agree, in fact i'm planning to issue a large number of small pulls.

**Pull request closed without merging**
