### PR TITLE
Add support for preset deletion

### PR DESCRIPTION
**Pull request by Happy2C0de**
**What this PR does / why we need it**:
This PR adds support to delete providers from a given preset AND if there is only a single provider left in the preset, the preset gets fully deleted.

This is a very smooth and user friendly implementation how one can delete a preset from KKP via the API. This can also be added to the Dashboard in an upcoming PR if needed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
None

**Special notes for your reviewer**:
- Added DeletePreset function and the whole swagger models.
- Because the API endpoint looks as follows: `/api/v2/providers/<provider>/presets` it makes sense to keep the provider based functionality. Accordingly, if one calls `DELETE /api/v2/providers/<provider>/presets/<preset_name>` the implementation will only remove the given provider (in the case when there is more than one provider configured). If there is only one provider, the preset gets fully deleted.  This makes sense because a preset with no provider is forbidden.

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Add support to remove a preset provider via the REST API
```

### CODE REVIEW

**Review by kron4eg — COMMENTED** [review]
/approve

**Comment by Happy2C0de** [comment]
@kron4eg 
Can we backport this to release/v2.18 ?

**Comment by Happy2C0de** [comment]
@kron4eg 
Thank you for the feedback.
I see your point. ATM, users cannot update the `requiredEmails` nor can users recreate a preset via the API what makes the Preset API not really usable. The two merged PRs fix this issue(/bug?) such that presets can be dynamically adjusted.
That's why I asked, but discuss it internally and decide how you would like to proceed. 👍 
Thanks a lot!

**Comment by zreigz** [comment]
@Happy2C0de thanks for your contribution. We have to discuss this extension with our product manager to decide if it's should be in the current release or later.
Definitely from the API perspective, it's a very valuable functionality.

**Comment by Happy2C0de** [comment]
Thank you for the feedback @zreigz 
I see your point with feature vs bugfix. Discuss it internally and decide what's reasonable in this situation. 👍 
In either case, I am looking forward to see this API endpoint in KKP. 🚀

**Pull request merged**
