### PR TITLE
Add retry for docker pull command

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**: https://prow.loodse.com/view/gcs/prow-data/logs/post-kubermatic-deploy-offline/1155846609490153473 is one of the sample jobs that failed due to image not being uploaded to the registry. This adds the retry mechanism for `docker pull` so we can reduce the number of the failures for now. Later we should sync the job/create pipeline.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
This would mean that for customers that use the `image-loader` they have to wait up to 15 mins when something is wrong.

What about instead wrapping the `image-loader` call in the `hack/ci/ci-deploy-offline.sh` script in retries?

**Comment by maciaszczykm** [comment]
@alvaroaleman the whole call?

**Comment by alvaroaleman** [comment]
Yeah why not, I mean it could also fail for any other reason, retrying wont harm as no one is sitting aside and watching it anyways

**Comment by maciaszczykm** [comment]
PTAL @alvaroaleman

**Pull request merged**
