### PR TITLE
Use build images based on Go 1.21.3

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
This PR updates to Go 1.21.3 images. Also see https://github.com/kubermatic/infra/pull/2446. This Go release fixes a CVE related to HTTP/2.

In addition, I ran into issues with a newer Helm version because of invalid `values.yaml` in the `mla/minio` chart. So I stuffed the fixes into this PR.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update to Go 1.21.3
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
/hold

needs postsubmits updated.

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
