### PR TITLE
Update Vault to 1.1.3

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This updates Vault to the latest stable version across all Docker images. The Helm version has also been bumped because we use 2.13 everywhere else already.

From my simple tests, using 1.1.3 locally works perfectly fine when using vault.loodse.com as the server.

This PR also downgrades mc because the current Minio release does not (yet?) have a companion mc release and our Minio deployments keep failing because they cannot init their backup container. To prevent future fuckups, I added explicit calls to print each app's version.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

Hold until #3614 is merged, because that other PR would bump the util image to 1.0.0-3 first.

**Comment by kron4eg** [comment]
why do we even need to update vault? Our vault is running at 0.11.4 version. So why bother here?

**Comment by xrstf** [comment]
> why do we even need to update vault

Same reasons as for other updates we do. Bugfixes, improvements, ... -- and if we ever want to update the Vault server, it's good to know we have recent enough clients floating around.

**Pull request merged**
