### PR TITLE
Remove Optional MLA Health status when feature is disabled

### LINKED ISSUE #8155: Remove MLA health status fields from Cluster CR when feature is disabled
**User Story**

In the following scenario:
- enable OPA or logging or monitoring -> all good, status are present in the `Cluster.Status.ExtendedHealth` (monitoring/logging/gatekeeperAudit/gatekeeperController, mlaGateway)
- disable OPA or logging or monitoring -> the KKP UI does not show the status, which is good, but they are still present in the Cluster.Status.ExtendedHealth . We do not remove them from the struct when disabling the feature. 

Even if the UI does not show the OPA/monitoring/logging status in the UI if the feature is disabled, those fields should be removed from the Cluster CR when the feature is disabled for this cluster.

**Acceptance criteria**
OPA, monitoring, logging, mlaGateway health status are removed from the Cluster CR when the feature is disabled (after having been enabled).

### PR DESCRIPTION
**Pull request by hdurand0710**
Signed-off-by: Helene Durand <helene@kubermatic.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8155 

**Special notes for your reviewer**:
This PR handles the correct **removal** of the health status fields **if the corresponding feature is disabled** inside the `Cluster` CR:
- .extendedHealth.alertmanagerConfig
- .extendedHealth.monitoring
- .extendedHealth.logging
- .extendedHealth.mlaGateway
- .extendedHealth.gatekeeperAudit
- .extendedHealth.gatekeeperController

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
if you don't mind, I want to wait for #8171 to merge before this
/hold

**Comment by hdurand0710** [comment]
I'm rebasing after #8171 merge. Will re-push.

**Comment by hdurand0710** [comment]
Rebase after after #8171  done.

**Review by kron4eg — APPROVED** [review]
/approve

**Review by jiachengxu — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
