### PR TITLE
Use go v1.12.12 for test-binaries image

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://groups.google.com/forum/#!msg/golang-announce/R3XK-Wf-Mtk/B2Hc62kuCgAJ
Contains the following security fixes: https://groups.google.com/forum/#!topic/golang-announce/lVEm7llp0w0

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @alvaroaleman

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Looks good, did you push that image?

**Comment by nikhita** [comment]
No, wanted to wait for lgtm. Will push now.

**Comment by nikhita** [comment]
Pushed :heavy_check_mark:

**Comment by nikhita** [comment]
We should bump prow to have `/honk` :stuck_out_tongue:

**Comment by alvaroaleman** [comment]
> We should bump prow to have /honk

Does it have more search terms available?

/pony kitten

**Comment by nikhita** [comment]
> Does it have more search terms available?

Sadly no :(

**Pull request merged**
