### PR TITLE
add helm-exporter and Prometheus alarm if a release is stuck/failed

### LINKED ISSUE #3031: deploy helm-exporter
[helm-exporter](https://github.com/helm/charts/tree/master/stable/helm-exporter) will help to detect early that there are some problems it deploys.

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This adds a new monitoring chart for the Helm-Exporter. It can provide us with release-related information and serves as the basis for a simple alert that fires after 15 minutes if a release is not in status `DEPLOYED`.

**Which issue(s) this PR fixes**
Fixes #3031

**Does this PR introduce a user-facing change?**:
```release-note
Added Helm-Exporter to fire alarms if a chart is stuck/failed
```

### CODE REVIEW

**Comment by xrstf** [comment]
/assign @alvaroaleman 

Please take a look at the updated `deploy.sh`.

**Review by kron4eg — APPROVED** [review]
/approve no-issue

**Comment by kron4eg** [comment]
oh well, there is an issue actually referenced 🤷‍♂️

**Pull request merged**
