### PR TITLE
Update machine controller to v1.1.0

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Update machine controller to v1.1.0.

This introduces the extendes openshift config which is necessary to fix the `manage-security-groups` bug.

**Release note**:
```release-note
Update the machine-controller to v1.1.0
```

### CODE REVIEW

**Comment by kdomanski** [comment]
Need to update fixtures due to https://github.com/kubermatic/machine-controller/pull/467

**Comment by mrIncompetent** [comment]
> Need to update fixtures due to kubermatic/machine-controller#467

Done with https://github.com/kubermatic/kubermatic/pull/3018/commits/f6f179b4af97ebbd59b5f0314c0c4f220bcf724e

**Pull request merged**
