### PR TITLE
[release/v2.12] Update machine-controller to v1.8.2

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

Update machine-controller to v1.8.2 to fix the Docker daemon/CLI version incompatibility.

**Does this PR introduce a user-facing change?**:
```release-note
Update machine-controller to v1.8.2 to fix the Docker daemon/CLI version incompatibility
```

/hold
~machine-controller v1.8.2 is still not released~

### CODE REVIEW

**Comment by xmudrii** [comment]
/hold cancel
machine-controller v1.8.2 is now released

**Comment by xmudrii** [comment]
/hold
to prevent the automatic retests
the machine-controller image push didn't succeed

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
