### PR TITLE
Add a GET endpoint to get Seed settings

### LINKED ISSUE #6998: Create an endpoint for getting MLA seed settings
Currently, our seed endpoints are only available for KKP admins. MLA can be configured on a per seed basis, and for MLA UI integration, a `GET` endpoint needs to be implemented to retrieve MLA seed settings in the user cluster creation page:
```
GET /api/v2/seeds/{seed_name}/settings
```

### PR DESCRIPTION
**Pull request by jiachengxu**
**What this PR does / why we need it**:
This PR adds a `GET` endpoint for getting Seed settings:
```
GET /api/v2/seeds/{seed_name}/settings
```
Currently, it only contains the MLA seed level option since this is needed in the user cluster creation UI to show/hide the MLA options. We can add more options to it in the future if needed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6998 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Add a v2 endpoint to get seed settings:
GET /api/v2/seeds/{seed_name}/settings
```

### CODE REVIEW

**Comment by zreigz** [comment]
you need to run hack/update-swagger.sh again

**Comment by jiachengxu** [comment]
Thanks @zreigz, now it should be fixed

**Comment by zreigz** [comment]
/lgtm
cc @kgroschoff please approve if works for you

**Pull request merged**
