### PR TITLE
[release/v2.20] Override resource requirements for nodeport-proxy for user clusters

### LINKED ISSUE #8826: Limits not configurable for customer cluster Nodeport-Proxy-Envoy - Test Release 2.20
### What happened?
I have at least one cluster where the nodeport-proxy-envoy is using ~70mb of memory,
as we have a hardcoded limit if 64, in get constant OOMs.

### What should happen?
In the same way that we can set this for the seeds, we would need that in the cluster overrides too
### Environment

- KKP Version: 2.18.5
- Shared or separate master/seed clusters?: seperate 
- Master/seed cluster provider: Openstack

### PR DESCRIPTION
**Pull request by embik**
**What does this PR do / Why do we need it**:

Backports #8859 to `release/v2.20`, includes conversion code for the old CRDs.

**Does this PR close any issues?**:
Fixes #8826

**Special notes for your reviewer**:

- **Q**: Is this going to work if the field doesn't exist in the previous CRD (someone uses 1.19.0 to upgrade to 1.20.0, for example)?

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Support custom pod resources for NodePort-Proxy pod for the user cluster.
```

### CODE REVIEW

**Review by moadqassem — APPROVED** [review]
/approve
/lgtm

**Comment by embik** [comment]
/hold

I wanted to try this feature out on dev but cannot get it to work, so I'm looking into it.

**Comment by embik** [comment]
Needs #9016.

**Comment by embik** [comment]
/hold cancel

needs another lgtm now since I cherry-picked another commit from `master`.

**Comment by embik** [comment]
@xrstf this also needs an `/approve` from SIG CRD (so, like 50% you).

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
