### PR TITLE
Remove experimental notice for Nutanix

### PR DESCRIPTION
**Pull request by embik**
**What does this PR do / Why do we need it**
The Nutanix cloud provider implementation is now feature-complete for the initial support, and we shouldn't mark it as "do not use" anymore.

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
Signed-off-by: Marvin Beckers <marvin@kubermatic.com>

### CODE REVIEW

**Comment by embik** [comment]
/cherry-pick release/v2.20

not sure this can be automatically cherry-picked due to the generated content, but let's see.

**Review by kron4eg — APPROVED** [review]
/approve

**Pull request merged**
