### PR TITLE
updated changelog for v2.10.1

### PR DESCRIPTION
**Pull request by kdomanski**
**Documentation**:
https://github.com/kubermatic/docs/pull/138

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
There was a tiny bug that prevented the controlllers from getting triggered on changes from objects in the cluster-ns, do we want to mention it?

**Comment by kdomanski** [comment]
Link?

**Comment by alvaroaleman** [comment]
* https://github.com/kubermatic/kubermatic/pull/3442
* https://github.com/kubermatic/kubermatic/pull/3490

**Comment by kdomanski** [comment]
Nah, I think we're good here.

**Pull request merged**
