### PR TITLE
KubeVirt: activate storage tests

### PR DESCRIPTION
**Pull request by hdurand0710**
Signed-off-by: Helene Durand <helene@kubermatic.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by hdurand0710** [comment]
Working as expected

```
{"level":"info","time":"2022-11-30T13:06:35.980Z","caller":"tests/storage.go:65","msg":"Testing storage support...","scenario":"kubevirt-centos-containerd-1.25.4","cluster":"kkp-1597929860439740416-zmr8n"}
[789](https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_kubermatic/11469/pre-kubermatic-e2e-kubevirt-centos-1.25/1597929860439740416#1:build-log.txt%3A789)
{"level":"info","time":"2022-11-30T13:06:36.023Z","caller":"tests/storage.go:76","msg":"Creating a StatefulSet with PVC...","scenario":"kubevirt-centos-containerd-1.25.4","cluster":"kkp-1597929860439740416-zmr8n"}
[790](https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_kubermatic/11469/pre-kubermatic-e2e-kubevirt-centos-1.25/1597929860439740416#1:build-log.txt%3A790)
{"level":"info","time":"2022-11-30T13:06:36.068Z","caller":"tests/storage.go:151","msg":"Waiting until the StatefulSet is ready...","scenario":"kubevirt-centos-containerd-1.25.4","cluster":"kkp-1597929860439740416-zmr8n"}
[791](https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_kubermatic/11469/pre-kubermatic-e2e-kubevirt-centos-1.25/1597929860439740416#1:build-log.txt%3A791)
{"level":"info","time":"2022-11-30T13:07:54.079Z","caller":"tests/storage.go:169","msg":"Successfully validated storage support","scenario":"kubevirt-centos-containerd-1.25.4","cluster":"kkp-1597929860439740416-zmr8n"}
```

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

great!

**Pull request merged**
