### PR TITLE
Revert CA bundle for apps

### PR DESCRIPTION
**Pull request by pkprzekwas**
**What this PR does / why we need it**:
Revert "provide CA bundle to Helm/Git operations in applications (#12514)"
This reverts commit b48fb36ed1ae0853dcfa654ad54dc2edbf868d0a.

Unfortunately we need to revert this due to issue with Helm client - https://github.com/kubermatic/kubermatic/issues/12724. 

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind regression

**Special notes for your reviewer**:
This revert should be temporary. Once the issue with Helm Client is resolved we should bring the code back to the main branch.

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by embik — APPROVED** [review]
/approve

**Comment by SimonTheLeg** [comment]
just for your info @dharapvj because you initally requested this feature. It is moved out at the moment because it breaks the funtionality for apps in general. This will be until the upstream issue at helm is fixed, for which I am currently looking into getting the tests to pass for the PR that is already out

**Pull request merged**
