### PR TITLE
Add `GroupProjectBinding` CRD

### LINKED ISSUE #9999: GroupProjectBinding CRD
- Make sure its unique
- Groups cant have the same name as the default groups (viewers, editors…)
- GroupsProjectBindings will need to be also defended by RBACs (similar as Clusters), and the RBACs rules added to the rbac-controller

### PR DESCRIPTION
**Pull request by embik**
**What does this PR do / Why do we need it**:
This extracts the `GroupProjectBinding` CRD from #9960 and adds it as a standalone PR. That way, we can work on various aspects of the overarching epic (#9897) without relying on a single PR.

I've changed the `.spec.project` field to `.spec.projectID` from the old PR, because that is what the field is named in `UserProjectBindings` and the dashboard also shows this as the ID, not the name:

Screenshot 2022-06-23 at 11 53 37

That's a bit confusing because the Kubernetes API resource `Project` uses this as `.metadata.name`, but I want to keep it consistent with existing fields as much as possible.

**Does this PR close any issues?**:
Fixes #9999

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Add `GroupProjectBinding` CRD
```

### CODE REVIEW

**Comment by xrstf** [comment]
How do we prevent stale group information in User objects?

**Comment by embik** [comment]
> How do we prevent stale group information in User objects?

That's a very good question I don't have an answer to. Let me remove that part from the PR, we should add it when we also add the KKP API functionality.

**Comment by lsviben** [comment]
> > How do we prevent stale group information in User objects?
> 
> That's a very good question I don't have an answer to. Let me remove that part from the PR, we should add it when we also add the KKP API functionality.

The KKP is the only one which will use the Group info in User, and it will be the one which sets it on every login. 

It will make more sense with the whole KKP API changes :)

**Pull request merged**
