### PR TITLE
update Grafana to 6.2.1

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This updates Grafana to the latest stable version with many improvements, none of which are really critical for us. There are no backwards incompatible changes.

**Does this PR introduce a user-facing change?**:
```release-note
update Grafana to 6.2.1
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

It seems the new version has trouble refreshing larger dashboards, with many panels failing. Maybe Prometheus is overloaded but maybe something in Grafana changed that puts more load on Prometheus. Need to investigate if this is actually caused by the update.

**Comment by xrstf** [comment]
Downgrading to 6.1.6 again makes all the dashboards work as expected. I think 6.2.0 has some regressions and we should not merge it just yet.

**Comment by xrstf** [comment]
Waiting for resolution in https://github.com/grafana/grafana/issues/17247

**Comment by xrstf** [comment]
/hold cancel

Grafana 6.2.1 fixes our issue and we can now finally get this merged @kron4eg

**Review by kron4eg — APPROVED** [review]
/approve no-issue

@xrstf I’ll lgtm after rebase

**Review by kron4eg — APPROVED** [review]
/lgtm

**Pull request merged**
