### PR TITLE
Document Go templating for custom Prometheus rules/scape configs

### LINKED ISSUE #7542: Create dynamic scrape config for user cluster prometheus
**User Story**
Hi,
we've been trying to create a custom scrape config for user cluster prometheuses and we need to add service discovery config like:
      _**kubernetes_sd_configs:
          - api_server: https://apiserver-external.cluster-xxxxxx.svc.cluster.local.**_
Since this is configured in kubermaticconfiguration or in kubermatic values file we need to pass variable for user cluster name.
We saw there is 'address.internalURL: apiserver-external.cluster-xxxxxx.svc.cluster.local.' in user cluster definition. Is there posibility to take value of user cluster name or value address.internalURL to pass in user cluster prometheus scrape config?

**Acceptance criteria**
Create dynamic scrape config with user cluster inernal_URL.

It would be valuable to know where is default scrape config for user cluster prometheus.

Thanks guys,

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
Prometheus configs were templated since forever, but nobody (inlcuding me) knew about it. This PR improves the documentation and treats the templating data for Prometheus the same way we treat the data for addons.

This PR moves both generators into `codegen/`, but keeps them as 2 separate programs because one needs the `vendor` folder, one doesn't and I didn't have the time and energy to see if we can merge the two (maybe someone else wants to?).

**Does this PR close any issues?**:
Fixes #7542

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/lgtm
/approve

**Comment by xrstf** [comment]
@ahmedwaleedmalik can you take another look pls? :)

**Comment by xrstf** [comment]
@ahmedwaleedmalik Can you take another look? :)

**Comment by xrstf** [comment]
@ahmedwaleedmalik we made it! finally! :-)

**Pull request merged**
