### PR TITLE
Update k8s version defaults

### PR DESCRIPTION
**Pull request by imharshita**
Signed-off-by: Harshita sharma <harshita.sharma6174@gmail.com>

**What this PR does / why we need it**:
- Update k8s version defaults

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Updating supported kubernetes versions for EKS and AKS clusters
```

**Documentation**:

```documentation
Done
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Comment by embik** [comment]
Please update the release note to mention _which_ versions are supported.

**Pull request merged**
