### PR TITLE
[release/v2.22] Upgrade Anexia CCM to v1.5.3

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Manual backport for #11923 and #12125. 

**What type of PR is this?**
/kind cleanup
/kind feature

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update Anexia CCM (cloud-controller-manager) to version 1.5.3
```

**Documentation**:

```documentation
NONE
```

cc @marioreggiori for awareness.

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
cc @kubermatic/sig-release-managers

**Review by embik — APPROVED** [review]

**Comment by ahmedwaleedmalik** [comment]
> /lgtm

Forgot that it's my own PR. @embik you accidentally removed the `lgtm` label.

**Comment by embik** [comment]
Damn GitHub. Thanks for letting me know @ahmedwaleedmalik.

**Pull request merged**
