### PR TITLE
[WIP] add deployer script for charts

### PR DESCRIPTION
**Pull request by toschneck**
**What this PR does / why we need it**:
Help the enduser deploy and upgrade kubermatic quickly.
This need to get maintained per verison. thats we we need this.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Quickwin until our operator is there.

**Documentation**:
Could also use this script there. If so please create an issue for thsi.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@thz @toschneck who is supposed to use it? Why do we duplicate scripts? Our CI scripts are not meant to be used by customers

**Comment by toschneck** [comment]
@alvaroaleman That's why I copied and transformed it to a separate one, what can used by our consultants. It Would make it easier to deploy and upgrade kubermatic more quickly. After we have the operator in place we probably can get rid of it again. Currently every helm command step by step is a little bit of a pain, what could be reduced by this script. 

Due to the point, there could be some version specific code, I don't want to keep it the customer-projects repo. 
If you have a better short term helper to reduce the installation steps, feel free to replace it. Currently I see it like, some starting point is better then nothing

**Comment by alvaroaleman** [comment]
@toschneck Yeah but if you just copy it, no one will take care and it will rot and get out of sync.

Can you instead please adjust `hack/ci/ci-sync-charts.sh` to copy it into the `config/` folder and do the necesary adjustments?

**Comment by toschneck** [comment]
@alvaroaleman ok will take a look, how we could solve this (after my vacation)

**Comment by alvaroaleman** [comment]
@toschneck any plans of fixing this up or can we close it?

**Comment by xrstf** [comment]
This is now hopelessly out of date and obsoleted by the Kubermatic Operator + Installer.

**Pull request closed without merging**
