### PR TITLE
Increase resources of prometheus on cloud eu to 4GiB of memory

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes prometheus-kubermatic crashlooping

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
Why would we not update the cloud values.yaml in our secrets repo instead? This PR is putting non-build-related configuration into an unexpected place IMHO.

**Comment by mrIncompetent** [comment]
> Why would we not update the cloud values.yaml in our secrets repo instead? This PR is putting non-build-related configuration into an unexpected place IMHO.

I agree with @xrstf here - the values.yaml is the correct place.
The only things we should override in the CI are the commit hashes, which we want to deploy

**Comment by xrstf** [comment]
I've created kubermatic/secrets#201 to replace this.

**Comment by alvaroaleman** [comment]
Valid objection, closing this one

**Pull request closed without merging**
