### PR TITLE
Update dex page styling

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**: Updates dex styling towards the one that was proposed in https://github.com/kubermatic/dashboard-v2/issues/1575. At the moment we cannot apply the background as it is too big to contain it in the same secret.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Related to https://github.com/kubermatic/dashboard-v2/issues/1575.

**Special notes for your reviewer**: Change is already deployed to the dev (at least when creating the PR).

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Updated dex page styling.
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
Zrzut ekranu 2019-09-23 o 15 42 21
Zrzut ekranu 2019-09-23 o 15 42 16

**Comment by maciaszczykm** [comment]
An update: 

Zrzut ekranu 2019-09-24 o 12 35 09

**Comment by xrstf** [comment]
> At the moment we cannot apply the background as it is too big to contain it in the same secret.

How much space would we need? Is minifying the SVG a viable approach? Has the background image been compressed with a tool like `pngout` to shrink it down?

**Comment by maciaszczykm** [comment]
@xrstf It's done right now. SVG took much less space than the JPEG that we were using previously.

**Comment by xrstf** [comment]
Can't Touch This

/lgtm

**Pull request merged**
