### PR TITLE
conformance script: build both the base and target of upgrade test

### PR DESCRIPTION
**Pull request by kdomanski**
**What this PR does / why we need it**:
Some upgrade tests in pre-submits fail because they assume the images for base version to be present in the CI's registry. This commit ensures that the base has been built, just like it is already being ensured for the upgrade target.

https://prow.loodse.com/view/gcs/prow-data/pr-logs/pull/kubermatic_kubermatic/3712/pull-kubermatic-e2e-upgrade-2.10-2.11/1145711157407911936

```release-note
NONE
```

### CODE REVIEW

**Comment by kdomanski** [comment]
@alvaroaleman `pull-kubermatic-e2e-upgrade-2.10-2.11` is configured to only run on the `release/v2.11` branch

**Comment by alvaroaleman** [comment]
Okay. We need this change at least in the release/v2.11 branch, right?

**Pull request merged**
