### PR TITLE
Added OpenAPI nodes endpoint (#424)

### LINKED ISSUE #424: Add OpenAPI docs to the ssh-keys the nodes endpoint
TODO:
- [x] `GET /api/v1/dc/{dc}/cluster/{cluster}/node`
- [x] `POST /api/v1/dc/{dc}/cluster/{cluster}/node`
- [x] `DELETE /api/v1/dc/{dc}/cluster/{cluster}/node/{node}`
- [x] `GET /api/v1/dc/{dc}/cluster/{cluster}/k8s/nodes`
- [x] `GET /api/v1/ssh-keys`
- [x] `POST /api/v1/ssh-keys`
- [x] `DELETE /api/v1/ssh-keys/{meta_name}`

### PR DESCRIPTION
**Pull request by andriisoldatenko**
Fixed #424
- GET /api/v1/dc/{dc}/cluster/{cluster}/node
- POST /api/v1/dc/{dc}/cluster/{cluster}/node
- DELETE /api/v1/dc/{dc}/cluster/{cluster}/node/{node}

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@mrIncompetent @guss please review

**Comment by mrIncompetent** [comment]
Does the generated openapi documentation tell what the response body look like?

**Comment by andriisoldatenko** [comment]
@mrIncompetent Do you mean examples of usage?
image

**Comment by andriisoldatenko** [comment]
I think you can try it out and see response.

**Comment by mrIncompetent** [comment]
I would rather have a response example - as this is normal in every API documentation.
@guusvw any thoughts on this?

**Comment by andriisoldatenko** [comment]
@mrIncompetent yes you are right if we talk about create docs for read by user, but OpenAPI focus mostly to generate clients/servers for your API...

**Comment by mrIncompetent** [comment]
@andriisoldatenko After discussing this with @scheeles @guusvw we want response & request body to be documented as well.

**Comment by andriisoldatenko** [comment]
@mrIncompetent okey, I'll take a look inside OpenAPI docs, how to add it. thanks.

**Comment by mrIncompetent** [comment]
We're using now master instead of develop.
Please rebase your branch and open the PR against master

**Pull request closed without merging**
