### PR TITLE
add node-exporter addon

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
We want to provide node dashboards for the user cluster nodes, so we need to install node-exporter into the user clusters. This PR adds a simple daemonset, identical to our current Helm chart.

**Which issue(s) this PR fixes**:
Relates to #3022

**Special notes for your reviewer**:
I am very unsure about the labelling here. Some of our addons are using the deprecated `kubernetes.io/cluster-service: "true"`, some are not. Many are using `k8s-app` labels, even though from a short look it's only the Prometheus Operator guys pushing hard for these labels. The canonical documentation seems to recommend the labels I have applied, but I'm not 100% sure.

On that note, some addons have references to `kubermatic`, which kind of breaks our whitelabelling (no pun intended) guidelines, as this is visible to the customers, no?

**Release note**:
```release-note
In order to provide Grafana dashboards for user cluster resource usage, the node-exporter is now deployed by default as an addon into user clusters.
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@xrstf Do we also want to enable them by default in the chart? Also should we maybe extend the release note to explain _why_ we add it/What it is needed for?

**Comment by xrstf** [comment]
> Do we also want to enable them by default in the chart?

Good catch, yes.

> Also should we maybe extend the release note to explain why we add it/What it is needed for?

Can do.

**Comment by alvaroaleman** [comment]
/approve

LGTM modulo the addon image tag

**Pull request merged**
