### PR TITLE
do not deploy PodSecurityPolicy in mla grafana

### PR DESCRIPTION
**Pull request by mate4st**
**What this PR does / why we need it**:

Disable PodSecurityPolicy in MLA Grafana deployment to allow Support for k8s 1.25+.

If someone already updated to K8s 1.25 with PodSecurityPolicy enabled you need to manually remove the grafana helm deployment that are stored as secrets in the MLA namespace.  This is because helm is not able to build the previous release that contains the PodSecurityPolicy as the CRD is not available anymore. 

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Disable PodSecurityPolicy in MLA Grafana deployment
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — COMMENTED** [review]
Please update the default values in the readme as well https://github.com/kubermatic/kubermatic/tree/main/charts/mla/grafana

**Review by embik — APPROVED** [review]
/approve

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
