### PR TITLE
Update prometheus to v2.9.2

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Update prometheus to v2.9.2

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
/cherrypick release/v2.10

### CODE REVIEW

**Review by alvaroaleman — COMMENTED** [review]
/lgtm
/approve

**Comment by xrstf** [comment]
I replaced the release notes with NONE because I will soon create a PR to update seed-prometheus to 2.9.2 as well.

**Pull request merged**
