### PR TITLE
Enable dynamic presets in API run script

### PR DESCRIPTION
**Pull request by irozzo-1A**
- Add dynamic-presets flag to `run-api.sh`.
- Makes PPROF port overridable for `run-controller.sh`.

```release-note
NONE
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]
/lgtm
/approve

**Comment by xrstf** [comment]
@irozzo-1A Can you please restore the `release-note` block in your PR description? As described in https://github.com/kubermatic/kubermatic/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by kron4eg** [comment]
@irozzo-1A I've added on PR comment:

    ```release-note
    NONE
    ```

**Pull request merged**
