### PR TITLE
fix listing security groups

### LINKED ISSUE #8447: [AWS] Listing security groups does not take selected VPC into account
Currently the `/api/v1/providers/aws/{dc}/securitygroups` endpoint ignores VPC selected by the user and lists all available security groups. It often ends up in error during cluster creation if users actually selects the security group.

https://github.com/kubermatic/kubermatic/blob/18c98aefc7ad2c9713e3bb34cd62f7e61d17ae5a/pkg/handler/v1/provider/aws.go#L115-L125

image

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: fix listing security groups

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8447

```release-note
NONE
```

### CODE REVIEW

**Comment by zreigz** [comment]
@floreks the UI also needs to set the VPC in the header. I think right now it's missing

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
