### PR TITLE
Fix machine controller for Openshift

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

This PR fixes the machine-controller deployment to work with Openshift. Previously, it had the `http-prober` as command and the original command as arg to the `http-prober`.

Openshift now added more args to the initial machine-controller args, resulting in those args being passed to the `http-prober` instead of the machine-controller.

This PR fixes that by splitting the MachineController Deployment into a `DeploymentCreator` and a `DeploymentCreatorWithoutInitWrapper` and using the latter for Openshift.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

/assign @nikhita

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Comment by nikhita** [comment]
Why were e2e tests not run on this PR?

**Comment by alvaroaleman** [comment]
@nikhita Could you re-lgtm, I had to fix some test fixtures? :grimacing:

**Pull request merged**
