### PR TITLE
Move OSM to user clusters

### LINKED ISSUE #11678: Move OperatingSystemProfiles and OperatingSystemConfigs to user cluster
**User Story** 
The CRDs and CRs for OSP and OSC should be moved from the user-cluster namespace to the actual user cluster.
For details: https://github.com/kubermatic/kubermatic/issues/11585

**Acceptance Criteria**
- [x] OSP and OSC are moved to user clusters
- [x] Investigate if we need to recreate OSC. In general, OSM will automatically recreate them.
- [x] Update docs

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:
OperatingSystemProfiles and OperatingSystemConfigs have been moved to the user clusters from the user-cluster namespaces. For detailed context: https://github.com/kubermatic/kubermatic/issues/11585

**Which issue(s) this PR fixes**:

Fixes #11678

**What type of PR is this?**

/kind design
/kind chore

**Special notes for your reviewer**:
IMO we don't need any actions from users for this. Handling for custom OSPs will change against https://github.com/kubermatic/kubermatic/issues/11679

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
OperatingSystemProfiles and OperatingSystemConfigs have been moved to the user clusters
```

**Documentation**:

```documentation
https://github.com/kubermatic/docs/pull/1354
```

### CODE REVIEW

**Review by Waseem826 — APPROVED** [review]

**Comment by ahmedwaleedmalik** [comment]
/hold
`pre-kubermatic-test-integration` are failing because of vSphere.

**Comment by ahmedwaleedmalik** [comment]
@xrstf  can we override `pre-kubermatic-test-integration`? It's failing due to vSphere, an unrelated issue.

**Pull request merged**
