### PR TITLE
Enable Loki compactor retention and rotation

### PR DESCRIPTION
**Pull request by moelsayed**
**What this PR does / why we need it**:
Our current configuration doesn't enable Loki compactor. This PR enables the compactor by default to rotate old file and avoid running out of disk space.
**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Enable Loki Compactor rotation and set retention to 1 month by default. 
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by dharapvj** [comment]
👏 👏 👏

**Comment by wurbanski** [comment]
> and maybe even how to override it?

well, we don't document any other features of Loki that the end user might want to customize using the chart to be fair :P 
we're using an upstream loki chart which is a bit outdated at this moment so we might want to work on that later anyway...

**Comment by wurbanski** [comment]
/lgtm

(please extend the release note in the description, it will be applied to the release note even if you do it later @moelsayed)

**Comment by moelsayed** [comment]
@dharapvj No need to remove files to enable this. We did that while working on it because we had ran out of space and Loki was failing to start. Normally that should be the case.

**Pull request merged**
