### PR TITLE
[release/v2.17] Add Kubernetes Namespace to dex and update Kubermatic Logo

### PR DESCRIPTION
**Pull request by mate4st**
This is a cherry-pick of #7343

```release-note
Explicitly set the namespace for Dex pods in the oauth chart. This fixes the problem with KKP installation failing on Kubernetes 1.21 clusters.
```

### CODE REVIEW

**Comment by xmudrii** [comment]
/hold
until #7347 is not merged

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
