### PR TITLE
update the name of the controller in run_controller.sh

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: updates the name of the controller in the `run_controler.sh` script

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: sorry, I missed that one :(

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by mrIncompetent — CHANGES_REQUESTED** [review]
Can you add a go build in the scripts? 

Same for the run api script.

**Comment by p0lyn0mial** [comment]
> Can you add a go build in the scripts?

How about extending Makefile ? We would add additional steps `run-controller` and `run-api` respectively. The new steps would depend on the `build` step.

**Comment by mrIncompetent** [comment]
A make-target is fine i guess. Asking @metalmatze as he actually ran into an issue with the script

**Comment by metalmatze** [comment]
I don't really care if they are little bash scripts or Makefile targets :grin:

**Review by mrIncompetent — APPROVED** [review]

**Pull request merged**
