### PR TITLE
Generate rules for namespace prometheus

### LINKED ISSUE #1533: Move alerts for Kuberentes master components to namespace Prometheus
Right now we only have alerts in the Kubermatic Prometheus.
It would be easier to just have those alerts in the namespaced Cluster Prometheus as this one only sees its cluster metrics, thus making it easy to use upstream alerts without changing them.

### PR DESCRIPTION
**Pull request by metalmatze**
**What this PR does / why we need it**:
The Prometheus inside cluster namespaces alerts in all metrics available. See this comment for further and more detailed information: https://github.com/kubermatic/kubermatic/issues/1533#issuecomment-410750918

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Closes #1533

**Special notes for your reviewer**:

**Release note**:

```release-note monitoring
The customer cluster Prometheus inside its namespace alerts on its own now.
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
Do we now have duplicate alerts?
From the kubermatic Prometheus and the user-cluster Prometheus?

**Comment by metalmatze** [comment]
Yes. We do have duplicates right now. 
The machine-controller alerts will only live inside the namespace and thus need to be removed from the kubermatic one. :+1: 
The etcd alerts need to be disabled from the kubermatic one until they are fixed for the seed clusters etcds.

**Comment by metalmatze** [comment]
The integration tests are broken, as the prometheus configmap now contains the jsonnet-based generated rules. I don't think it's a path to go down to, when copying the generated yaml into fixtures now, but what do you think?
@mrIncompetent @pkavajin

**Comment by mrIncompetent** [comment]
> The integration tests are broken, as the prometheus configmap now contains the jsonnet-based generated rules. I don't think it's a path to go down to, when copying the generated yaml into fixtures now, but what do you think?

Please run the relevant test with the `-update` flag. It will update the relevant fixture.

**Comment by mrIncompetent** [comment]
When the fixtures are updated: :+1:

**Comment by metalmatze** [comment]
Fixtures have been updated. PTAL @mrIncompetent :relaxed:

**Review by mrIncompetent — APPROVED** [review]

**Pull request merged**
