### PR TITLE
Revert "fix json name for securityGroupId (#4344)"

### PR DESCRIPTION
**Pull request by alvaroaleman**
This reverts commit 7a264ae13cfaf964edb979c612a95662f841937f.

This change caused us to drop the existing `securityGroupID` field on all AWS
clusters because the tag got renamed, causing us to not recognize the existing field.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/assign @zreigz @kgroschoff @kdomanski 
CC @thz , I hope this didn't rolled out anywhere other than on cloud, where this change results us in now not being able to delete any AWS cluster, as we are unable to cleanup the security group as we don't know the name anymore.

Please _never rename json tags_ on the Kubermatic cluster CRD (or any CRD for that matter). This causes us to lose information.

Doing this on the API types is okay because those do not get persistet. Its a completely different story for the CRDs, as they are used to persist data.

If you must rename a field for whatever reason, please add a new field and a migration that copies the value of the old field to the new one. You may then remove the old field in the Kubermatic release after the Kubermatic release with the migration.

**Comment by alvaroaleman** [comment]
Also as a general rule of thumb: We do not do incompatible API changes just because the UI does not use the correct name for a field. Changes like this break every client generated from our swagger spec for no good reason.

**Comment by zreigz** [comment]
Good point, sorry for that. We will change only the UI part and it will work.

**Pull request merged**
