### PR TITLE
[release/v2.10] Disable query-level logging for usercluster DNS

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Analogous to https://github.com/kubermatic/kubermatic/pull/3563

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

/hold

to upgrade the tag

### CODE REVIEW

**Comment by mrIncompetent** [comment]
@alvaroaleman You want to use `v0.2.8-1` as final tag ?

**Comment by alvaroaleman** [comment]
> You want to use v0.2.8-1 as final tag ?

Yeah, unless you have a better idea. We can not use v0.2.9, as that was already used somewhen for kubermatic#master

**Comment by mrIncompetent** [comment]
Ping :)

**Comment by alvaroaleman** [comment]
@mrIncompetent Updated the tag

**Pull request merged**
