### PR TITLE
Correctly handle long user ID's

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:

This PR will change the way we handle the UserID.
We will now always hash the user ID we get from the token(`sub`) as and store it as userID on the internal user object.
This requires all user labels on all clusters, to only contain the hash instead of the raw id - for this a migration was added.

Also:
When creating the selector for listing the clusters, we now correctly build the selector - catching an error in case we create an invalid selector.
In the old code, an error was simply ommited, resulting in an empty selector - which will list everything.

**Release note**:
```release-note bugfix
Fixed handling of very long user IDs
```

### CODE REVIEW

**Review by alvaroaleman — DISMISSED** [review]

**Review by p0lyn0mial — DISMISSED** [review]

**Comment by p0lyn0mial** [comment]
@mrIncompetent dep failed

**Comment by mrIncompetent** [comment]
> @mrIncompetent go dep failed

Thanks for mentioning @kdomanski just mentioned we're already on dep v0.5.0 in this branch.

**Comment by mrIncompetent** [comment]
I did a quick test on dev:
- Create a cluster with v2.7.3
- Run migration
- Run this branch
- validate that the cluster gets shown

Worked.

**Review by alvaroaleman — APPROVED** [review]

**Comment by multi-io** [comment]
Looks good to me too.

**Review by p0lyn0mial — APPROVED** [review]

**Pull request merged**
