### PR TITLE
Expose audit logging in cluster API object

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Exposed audit logging in cluster API object.
```

### CODE REVIEW

**Comment by kdomanski** [comment]
@kubermatic-bot ping

**Comment by alvaroaleman** [comment]
@kdomanski its waiting to get retested as something else is currently being retested, check https://prow.loodse.com/tide

**Pull request merged**
