### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
I stumbled upon this unused piece of code while looking for GitOps TODOs.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
@floreks PTAL

**Comment by xrstf** [comment]
@floreks PTAL

**Pull request merged**
