### PR TITLE
[Doc]:FIx the bad URL of the code of conduct file

### LINKED ISSUE #5537: [Doc]: Fixing the bad URL of the code-of-conduct file
**User Story**

Thanks for you guys made the amazing project and at the same time, I and my colleagues are going to develop multiple cloud management platforms (maybe with the service mesh)and scheduler the applications to the aim nodes. Not only includes containers but also includes non-container and raw-binary like particularly nomad features. So, I find `kubermatic` project and trying to get some lessons from the project and I see the URL was broken, So I fix that.

**Acceptance criteria**

Click the `CONTRIBUTING.md` label and transfer to the right page.

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5537

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
Thanks :) Can we instead keep the link style, as we did for all other footnotes?

/ok-to-test
/approve

**Comment by Aisuko** [comment]
> Thanks :) Can we instead keep the link style, as we did for all other footnotes?
> 
> /ok-to-test
> /approve

For sure, Done.

**Pull request merged**
