### PR TITLE
Build correct path to files to prevent duplications

### LINKED ISSUE #13108: Logs duplication
### What happened?

When it is more than one pod of service on one node logs from that pod are duplicated.

### Expected behavior

Logs are not duplicated when more than one pod of service is running on the node.

### How to reproduce the issue?

Run more than one pod on node from one service

### How is your environment configured?

- KKP version: 2.24.1
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?
Does not matter

### Additional information

The issue is related to miss configuration in path builder for target. The related issue is https://github.com/grafana/loki/issues/6140.

### PR DESCRIPTION
**Pull request by dzubchik**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #13108 

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Resolved an issue where logs were duplicated when multiple pods from the same service were deployed on the same Kubernetes node.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by dzubchik** [comment]
@xrstf the PR body has been updated according to the template

**Comment by embik** [comment]
> @xrstf the PR body has been updated according to the template

Quick note, the `NONE` for the documentation is outside of the code block, so it needs to be slightly adjusted :-)

**Comment by wurbanski** [comment]
Hi @dzubchik, thanks for the contribution!

Can you provide an example workflow that we could use to replicate the issue and show what's  the current outcome of the logs and the expected one? I'm having trouble reproducing the issue at the moment.  Thanks in advance!

**Comment by xrstf** [comment]
It's hard for me to fully understand the impact of this PR and what exactly it's solving. I read the upstream issue but it's sadly still not clear to me and I fear merging this might break other things.

Can you provide us with sample manifests that reproduce the workload that causes issues?

**Comment by dzubchik** [comment]
It costs me almost 2 days to discover this problem. The reproduction is simple as a pie - run deployment in such way, that more that one pod is located on node. The core problem in service path building as you see. 

The log files are located in directory /var/log/pods/namespace_pod_name_docker-uuid/container_name/0.log. When you try to generate path as it was before __meta_kubernetes_pod_annotation_kubernetes_io_config_hash is empty, so the path would be like /var/log/pods/*/container_namer/*.log. When you have multiple pods, for each of them it will start send logs for all pods. The sample of logs where problem is seen:

```
ts=2024-02-20T16:17:02.164536344Z caller=filetargetmanager.go:301 level=debug component=logs logs_config=default msg="new target" labels="{__address__=\"172.25.8.121:8080\", __meta_kubernetes_pod_container_id=\"containerd://5681a7d8b851a46866ab8838cb4e3cf4b1627ff02a65c5527a456e0ed65fa86f\", __meta_kubernetes_pod_container_image=\"123.dkr.ecr.eu-central-1.amazonaws.com/foo-server-edge:1.1.1\", __meta_kubernetes_pod_container_init=\"false\", __meta_kubernetes_pod_container_name=\"foo-server\", __meta_kubernetes_pod_container_port_name=\"http\", __meta_kubernetes_pod_container_port_number=\"8080\", __meta_kubernetes_pod_container_port_protocol=\"TCP\"}"
ts=2024-02-20T16:17:02.164589336Z caller=filetargetmanager.go:361 level=info component=logs logs_config=default msg="Adding target" key="/var/log/pods/*/foo-server/*.log:{app=\"foo-server\", container=\"foo-server\", job=\"bar/foo-server\", job_test=\"kubernetes-pods-app\", namespace=\"bar\", node_name=\"supernode\", pod=\"foo-server-58f57b988c-s7v7p\"}"
ts=2024-02-20T16:17:02.164600642Z caller=filetargetmanager.go:301 level=debug component=logs logs_config=default msg="new target" labels="{__address__=\"172.25.8.121:3000\", __meta_kubernetes_pod_container_id=\"containerd://5681a7d8b851a46866ab8838cb4e3cf4b1627ff02a65c5527a456e0ed65fa86f\", __meta_kubernetes_pod_container_image=\"123.dkr.ecr.eu-central-1.amazonaws.com/foo-server-edge:1.1.1\", __meta_kubernetes_pod_container_init=\"false\", __meta_kubernetes_pod_container_name=\"foo-server\", __meta_kubernetes_pod_container_port_name=\"metrics\", __meta_kubernetes_pod_container_port_number=\"3000\", __meta_kubernetes_pod_container_port_protocol=\"TCP\"}"
ts=2024-02-20T16:17:02.164737963Z caller=filetargetmanager.go:301 level=debug component=logs logs_config=default msg="new target" labels="{__address__=\"172.25.8.120:8080\", __meta_kubernetes_pod_container_id=\"containerd://8246717e5cd5b84fdc0160293987a5acc78d5c03195baa2b4b0155a7f5691cf8\", __meta_kubernetes_pod_container_image=\"123.dkr.ecr.eu-central-1.amazonaws.com/foo-server-edge:1.1.1\", __meta_kubernetes_pod_container_init=\"false\", __meta_kubernetes_pod_container_name=\"foo-server\", __meta_kubernetes_pod_container_port_name=\"http\", __meta_kubernetes_pod_container_port_number=\"8080\", __meta_kubernetes_pod_container_port_protocol=\"TCP\"}"
ts=2024-02-20T16:17:02.164787231Z caller=filetargetmanager.go:361 level=info component=logs logs_config=default msg="Adding target" key="/var/log/pods/*/foo-server/*.log:{app=\"foo-server\", container=\"foo-server\", job=\"bar/foo-server\", job_test=\"kubernetes-pods-app\", namespace=\"bar\", node_name=\"supernode\", pod=\"foo-server-58f57b988c-7mbnj\"}"
ts=2024-02-20T16:17:02.164799347Z caller=filetargetmanager.go:301 level=debug component=logs logs_config=default msg="new target" labels="{__address__=\"172.25.8.120:3000\", __meta_kubernetes_pod_container_id=\"containerd://8246717e5cd5b84fdc0160293987a5acc78d5c03195baa2b4b0155a7f5691cf8\", __meta_kubernetes_pod_container_image=\"123.dkr.ecr.eu-central-1.amazonaws.com/foo-server-edge:1.1.1\", __meta_kubernetes_pod_container_init=\"false\", __meta_kubernetes_pod_container_name=\"foo-server\", __meta_kubernetes_pod_container_port_name=\"metrics\", __meta_kubernetes_pod_container_port_number=\"3000\", __meta_kubernetes_pod_container_port_protocol=\"TCP\"}"
ts=2024-02-20T16:17:02.164841982Z caller=filetarget.go:313 level=info component=logs logs_config=default msg="watching new directory" directory=/var/log/pods/bar_foo-server-58f57b988c-s7v7p_db6d0f7b-496e-4299-9beb-51fb0cd506cf/foo-server
ts=2024-02-20T16:17:02.164857635Z caller=filetarget.go:313 level=info component=logs logs_config=default msg="watching new directory" directory=/var/log/pods/bar_foo-server-58f57b988c-7mbnj_7bddedc2-a12d-4fcf-8a1c-3cfd8e8f3543/foo-server
ts=2024-02-20T16:17:02.164946938Z caller=filetarget.go:368 level=debug component=logs logs_config=default msg="tailing new file" filename=/var/log/pods/bar_foo-server-58f57b988c-7mbnj_7bddedc2-a12d-4fcf-8a1c-3cfd8e8f3543/foo-server/0.log
ts=2024-02-20T16:17:02.165018207Z caller=filetarget.go:368 level=debug component=logs logs_config=default msg="tailing new file" filename=/var/log/pods/bar_foo-server-58f57b988c-s7v7p_db6d0f7b-496e-4299-9beb-51fb0cd506cf/foo-server/0.log
ts=2024-02-20T16:17:02.165023737Z caller=tailer.go:147 level=info component=logs logs_config=default component=tailer msg="tail routine: started" path=/var/log/pods/bar_foo-server-58f57b988c-7mbnj_7bddedc2-a12d-4fcf-8a1c-3cfd8e8f3543/foo-server/0.log
ts=2024-02-20T16:17:02.16502893Z caller=log.go:168 component=logs logs_config=default level=info msg="Seeked /var/log/pods/bar_foo-server-58f57b988c-7mbnj_7bddedc2-a12d-4fcf-8a1c-3cfd8e8f3543/foo-server/0.log - &{Offset:41879969 Whence:0}"
ts=2024-02-20T16:17:02.165040931Z caller=tailer.go:147 level=info component=logs logs_config=default component=tailer msg="tail routine: started" path=/var/log/pods/bar_foo-server-58f57b988c-s7v7p_db6d0f7b-496e-4299-9beb-51fb0cd506cf/foo-server/0.log
ts=2024-02-20T16:17:02.165048542Z caller=log.go:168 component=logs logs_config=default level=info msg="Seeked /var/log/pods/bar_foo-server-58f57b988c-s7v7p_db6d0f7b-496e-4299-9beb-51fb0cd506cf/foo-server/0.log - &{Offset:26305195 Whence:0}"
ts=2024-02-20T16:17:02.165090271Z caller=filetarget.go:313 level=info component=logs logs_config=default msg="watching new directory" directory=/var/log/pods/bar_foo-server-58f57b988c-7mbnj_7bddedc2-a12d-4fcf-8a1c-3cfd8e8f3543/foo-server
ts=2024-02-20T16:17:02.165104188Z caller=filetarget.go:313 level=info component=logs logs_config=default msg="watching new directory" directory=/var/log/pods/bar_foo-server-58f57b988c-s7v7p_db6d0f7b-496e-4299-9beb-51fb0cd506cf/foo-server
ts=2024-02-20T16:17:02.165117067Z caller=filetarget.go:368 level=debug component=logs logs_config=default msg="tailing new file" filename=/var/log/pods/bar_foo-server-58f57b988c-7mbnj_7bddedc2-a12d-4fcf-8a1c-3cfd8e8f3543/foo-server/0.log
ts=2024-02-20T16:17:02.165140416Z caller=filetarget.go:368 level=debug component=logs logs_config=default msg="tailing new file" filename=/var/log/pods/bar_foo-server-58f57b988c-s7v7p_db6d0f7b-496e-4299-9beb-51fb0cd506cf/foo-server/0.log
ts=2024-02-20T16:17:02.165171071Z caller=tailer.go:147 level=info component=logs logs_config=default component=tailer msg="tail routine: started" path=/var/log/pods/bar_foo-server-58f57b988c-s7v7p_db6d0f7b-496e-4299-9beb-51fb0cd506cf/foo-server/0.log
ts=2024-02-20T16:17:02.165164203Z caller=log.go:168 component=logs logs_config=default level=info msg="Seeked /var/log/pods/bar_foo-server-58f57b988c-7mbnj_7bddedc2-a12d-4fcf-8a1c-3cfd8e8f3543/foo-server/0.log - &{Offset:41879969 Whence:0}"
ts=2024-02-20T16:17:02.16519141Z caller=tailer.go:147 level=info component=logs logs_config=default component=tailer msg="tail routine: started" path=/var/log/pods/bar_foo-server-58f57b988c-7mbnj_7bddedc2-a12d-4fcf-8a1c-3cfd8e8f3543/foo-server/0.log
ts=2024-02-20T16:17:02.165187Z caller=log.go:168 component=logs logs_config=default level=info msg="Seeked /var/log/pods/bar_foo-server-58f57b988c-s7v7p_db6d0f7b-496e-4299-9beb-51fb0cd506cf/foo-server/0.log - &{Offset:26305195 Whence:0}"
```

Take a look on line 2 and 5. For each target path is incorrect. Moreover, if you have multiple containers in different pods named the same the effect would be the same. Hope this helps.

**Comment by dzubchik** [comment]
@wurbanski, do you have enough data for this issue? To observe the incorrect behavior, you can examine Loki and attempt to filter logs from a specific pod. However, ensure there's another pod on the same node from the same deployment. After filtering by pod, try applying a filter by filename. You'll notice there are two options available, although only one is expected. The issue occurs similarly when the process is reversed - choose filename and then pod name.

**Comment by wurbanski** [comment]
@dzubchik thank you - see, you kept mentioning pods from the same `service` which didn't really make sense to me, now that I know you meant `deployment` we can try to reproduce it and see if it breaks anything else. 

Please give us some time to verify the change. We're currently in the process of finishing KKP 2.25 release so this might have to be delayed until the patch release.

Thank you.

**Comment by dzubchik** [comment]
Yeh, my bad. Sorry for putting you on a wrong track.

**Comment by xrstf** [comment]
Okay, for reference, I reproduced this by applying this highly complex professional log generator Deployment:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: chatty

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quack
  namespace: chatty
spec:
  replicas: 8
  selector:
    matchLabels:
      app: quack
  template:
    metadata:
      labels:
        app: quack
    spec:
      containers:
      - name: main
        image: ubuntu:latest
        command:
          - /bin/bash
          - -c
          - |
            while true; do
              echo "$(date): $HOSTNAME is still here…"
              sleep 2
            done
        resources:
          requests:
            cpu: 5m
            memory: 8Mi
```

and then looked into Loki, where I found (my cluster has 3 nodes):

2024-03-04T16-12-56

**Comment by wurbanski** [comment]
/milestone KKP 2.25

@dzubchik Thank you, we've confirmed that your fix removes the duplicate lines and we'll get it merged for the next release.

**Pull request merged**
