### PR TITLE
Anexia: update CloudControllerManager to v1.4.2

### PR DESCRIPTION
**Pull request by LittleFox94**
**What does this PR do / Why do we need it**:

Update Anexia CloudControllerManager to version 1.4.2, fixing some issues - release notes are here: https://github.com/anexia-it/k8s-anexia-ccm/releases/tag/v1.4.2

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Update Anexia CCM (cloud-controller-manager) to version 1.4.2
```

### CODE REVIEW

**Review by embik — APPROVED** [review]
/approve

@LittleFox94 thanks! I've taken the liberty to slightly adjust the release note to be more in line with our usual style, but we really appreciate the contribution.

**Comment by LittleFox94** [comment]
Many thanks for the fast merge @embik, I'll try to match the changelog style next time :)

**Pull request merged**
