### PR TITLE
Use reconciling framework in more places

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This refactors two more places to use the reconciling framework instead of hand-rolling the code.

/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
@hbernardo PTAL

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
