### PR TITLE
Update Grafana to 10.4, refresh dashboards

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This performs a long overdue version bump to the Seed MLA Grafana. I then went through all of the dashboards and

* Removed the bogus "80 red" threshold, which is basically a copy-paste mistake from me which then made its way into pretty much all of the panels in most dashboards, but was completely useless.
* Removed unnecessary copy-pasted overrides for non-existent timeseries.
* Styling has been harmonized across dashboards.
* The KKP Controller-Manager dashboard has been fixed to not include kube-controllers anymore.

Also, I deleted the mysterious "Prometheus Exporter" dashboard. It was introduced in #4682 by me, but for the life of me, I cannot find any single source for `prom_exporter_pod_cpu_usage` metric it was based on. I can only guess that this is from one of my own exporters, given that the original datasource was "Prometheus xrstf". Anyway, there is no "Prometheus Exporter" and so the dashboard was just entirely pointless.

Since we do not use any of the custom panel plugins anymore, we can finally get rid of the custom plugins image and are 1 step closer to using upstream Grafana :-) The quay.io repo can/must stay, but the image sources can be removed. Thankfully someone recently added labels to our images, so you can still figure out from the quay.io images where they once came from. :-)

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
* Update seed-MLA Grafana to 10.4.1
* Update seed-MLA Grafana dashboards: more consistent styling, do not use deprecated Chart panels anymore
* Remove all custom Grafana plugins (`grafana-piechart-panel`, `farski-blendstat-panel`, `michaeldmoore-multistat-panel` and `vonage-status-panel`): most are deprecated or soon defunct and none of the KKP dashboard use any of these panel types
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by wurbanski** [comment]
Monumental work but I'll be honest - I don't read dashboards in JSON that well - can I see it live somewhere at the moment?

**Comment by xrstf** [comment]
@wurbanski dev grafana currenly still has it deployed, but only until the next PR is merged.

**Comment by wurbanski** [comment]
The dashboards look very nice and there are no errors that very often showed up after upgrades.

/lgtm

**Pull request merged**
