### PR TITLE
Bump controller-runtime to 0.14.1 / k8s 1.26.1

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This PR bumps ctrl-runtime to 0.14, Kubernetes 1.26 (to match what ctrl-runtime is using) and also machine-controller (required to make it compatible with ctrl-runtime 0.14).

99% of this PR is just adjusting to the new generics-based set implementation.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update codebase to Kubernetes 1.26
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
This is on hold because the generated CRDs are broken, due to https://github.com/kubernetes/kubernetes/pull/114585 -- backport (https://github.com/kubernetes/kubernetes/pull/114617) is merged, but 1.26.1 is not yet released.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
/retest 
FFS

**Pull request merged**
