### PR TITLE
Bump deprecated apiVersions

### PR DESCRIPTION
**Pull request by cbeneke**
**What this PR does / why we need it**:

Kubernetes 1.16 and ongoing will remove some deprecated apiVersions. This commit ensures new versions are used. This is the list of deprecated apiVersions:

* Ingress: extensions/v1beta1 -> networking.k8s.io/v1beta1 (Delete in v1.19)
* NetworkPolicy: extensions/v1beta1 -> networking.k8s.io/v1 (Delete in v1.16)
* PodSecurityPolicy: extensions/v1beta1 -> policy/v1beta1 (Delete in v1.16)
* DaemonSet, Deployment, and ReplicaSet: extensions/v1beta1, apps/v1beta1, or apps/v1beta2-> apps/v1 API (Delete in v1.16)
* PriorityClass: scheduling.k8s.io/v1alpha1, scheduling.k8s.io/v1beta1 -> scheduling.k8s.io/v1 (Delete in v1.17)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:
* apps/v1 now enforces selector to be set

**Documentation**:

* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#deprecations-and-removals (Subpoint API)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/test all
/assign @xrstf 

What will be the minimum kubernetes version after this got merged?

**Comment by xrstf** [comment]
Love it! If @mrIncompetent has no objections, we can merge this :)

/approve

**Comment by bashofmann** [comment]
> What will be the minimum kubernetes version after this got merged?

See https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/. 

If I read this correctly, because of "DaemonSet, Deployment, StatefulSet" changes 1.9 and because of the Ingress changes 1.14

**Comment by alvaroaleman** [comment]
Okay, then lets please remove the Ingress change, we can not rely on everyone using Kubermatic having a 1.14+ seed. Other than that, lgtm.

**Comment by cbeneke** [comment]
Rebased against master and reverted Ingress apiVersion bump

**Comment by alvaroaleman** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
