### PR TITLE
fix allowedregistry list overwriting

### LINKED ISSUE #7746: Multiple AllowedRegistries produce just one item in the Default Constraint registry list
Create 2 different Allowedregistries with different registryPrefixes. 

Expected result is that the resulting default constraint will have 2 items in the list, but instead it has 1, they overwrite each other.

### PR DESCRIPTION
**Pull request by lsviben**
**What this PR does / why we need it**:
Fixes a bug where 2 or more allowedRegistries produced just one item in the allowedRegistry Default Constraint parameters. 
Which was happening because of a bad casting that made the set of registries always empty. 

Additionally, eases up the DefaultConstraint reconciliation, so that users can set filtering and matching without it being overwritten.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7746 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mfranczy — APPROVED** [review]
/lgtm
/approve

**Review by jiachengxu — APPROVED** [review]

**Pull request merged**
