### PR TITLE
Update AWS SDK

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
This updates the AWS SDK we use.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/assign @nikhita

### CODE REVIEW

**Comment by nikhita** [comment]
The changes lgtm technically but out of curiosity, why are we bumping the version?

**Comment by mrIncompetent** [comment]
> The changes lgtm technically but out of curiosity, why are we bumping the version?

Mainly for the improved inline docs :)

**Review by nikhita — APPROVED** [review]
Cool :)

/lgtm
/approve

**Pull request merged**
