### PR TITLE
Fix STS tokens generated for EKS clusters

### LINKED ISSUE #11038: Generated Kubeconfig for EKS not valid due to invalid token
### What happened?
Generate Kubeconfig for EKS not valid and throwing error as Unauthorized

### How is your environment configured?

- KKP version:
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
This fixes the tokens generated for accessing EKS (no, really, this is all that is needed).

Reference: https://github.com/weaveworks/eksctl/pull/5016/files#diff-73c5fd3d701e0ae7a76ddde1b6319a989fd7ebae87a9f1f2241d9c73d9dd1d17R71

**Which issue(s) this PR fixes**:

Fixes #11038

**What type of PR is this?**
/kind bug
/kind regression

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

Signed-off-by: Marvin Beckers <marvin@kubermatic.com>

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by embik** [comment]
/hold

To prevent further retests.

**Pull request merged**
