### PR TITLE
Feature/revoke admin token

### PR DESCRIPTION
**Pull request by lbb**
**What this PR does / why we need it**:
Generate a new Admin token endpoint, when called it will preroll all clusters and change the token required to gain access (Authorisation)
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by lbb** [comment]
Tested thoroughly.

**Review by mrIncompetent — CHANGES_REQUESTED** [review]
Naming is bad: a put and then using a method-style-name? Please keep to rest.
Also I doubt that this will work with multiple seed clusters. Afaik the api only speaks to the master seed at the moment.

**Comment by lbb** [comment]
@mrIncompetent Yeah good catch (we need to talk to the seed directly), as you said I shall not introduce a new phase should I also pass the seed config to the kubermatic-api?

**Comment by mrIncompetent** [comment]
Maybe we should just delete the token via the api.
The controller should react on the missing token in the running phase.

As we want to get rid of the phases, this might be a good start.

So things to cover:
- check token in running phase
- check that the admin token is included in the token csv-configmap
- recreate the configmap when needed
- recreate all deployments which depend on the configmap.
(Maybe we add a label with the revision of the configmap to the deployment?)

Though I would like to discuss this next week when I'm back as I don't have my laptop with me

**Comment by lbb** [comment]
So we should put this PR on hold?

**Comment by mrIncompetent** [comment]
Or you can already try to implement it in a more controller centric way

**Comment by mrIncompetent** [comment]
@realfake Can we close this one?
Or you working in this branch?

**Comment by lbb** [comment]
As you prefer, but can be locked.

**Comment by mrIncompetent** [comment]
I just realized that we should probably stick to this here, as it introduces the endpoints.

**Comment by mrIncompetent** [comment]
As https://github.com/kubermatic/kubermatic/pull/748 got merged, we can now simply resetting the admin-token in the cluster struct :)

**Comment by mrIncompetent** [comment]
Instead of having a separate endpoint why don't we have a general `PUT /api/v1/cluster/foo` endpoint?
We just need to make sure, that certain fields are allowed to be updated.
It would give us more flexibility and we would stick to the REST pattern

**Comment by mrIncompetent** [comment]
Probably invalid due to https://github.com/kubermatic/kubermatic/pull/785

**Comment by mrIncompetent** [comment]
Possible via https://github.com/kubermatic/kubermatic/pull/785 which has been merged.
@realfake can you take care of deleting the branch?
Or is there anything left you would like to keep?

**Pull request closed without merging**
