### PR TITLE
Mark kubelet-configmap addon for continuous reconciliation

### LINKED ISSUE #4979: enforcement of default addons in user cluster
**User Story**
As Kubermatic operator I want to enforce that some addons are placed in the cluster. Even if the user cluster admin deletes a addon it should get recreated.

Currently Kubermatic only recreates the addons when a cluster definition is changed. In my opinion the addon controller should continuously check if there is a diff between addon config and addon deployment
This behavior was tested at the  `weekly-2020-03` version. 

**Acceptance criteria**
- [ ] default addons get enforced
- [ ] a deleted default addon in the user cluster get created immediately

### PR DESCRIPTION
**Pull request by kron4eg**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4979

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Mark kubelet-configmap addon for continuous reconciliation
```

### CODE REVIEW

**Comment by xmudrii** [comment]
I'm a bit worried that this is a breaking change. What if users have customized their kubelet-configmaps? This is a valid use case if they want to adjust some Kubelet properties. There are two important questions that we should answer and document:

- Is this going to affect the existing clusters and nodes?
- Are users still able to adjust their Kubelet configuration without having to build a new addons image?

**Comment by kron4eg** [comment]
@xmudrii very good point! Seems like mashing together kubelet-config and kubeadm-config was not so good idea and we are going to need to extract kubeadm config into own addon.

**Comment by kron4eg** [comment]
I'm closing this PR as that will break existing expectations.

New issue #7141 has been created to address the problem at hand here, but using the other way around.

**Pull request closed without merging**
