### PR TITLE
MLA Gateway health status

### LINKED ISSUE #8095: MLA Gateway health status
Propagate health status of MLA Gateway which is running in the cluster namespace in the Seed cluster to Cluster.Status

### PR DESCRIPTION
**Pull request by sankalp-r**
Signed-off-by: Sankalp Rangare <sankalprangare786@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8095 

**Special notes for your reviewer**:
This PR adds a new health status for MLAGateway in the `Cluster` `.extendedHealth`:

- mlaGateway

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Add MLAGateway health status in the /health API-endpoint:
- . extendedHealth. mlaGateway
```

### CODE REVIEW

**Review by jiachengxu — APPROVED** [review]
/approve

**Comment by hdurand0710** [comment]
I'll rebase when this one is merged to fix #8155 including this field.

**Review by hdurand0710 — APPROVED** [review]

**Pull request merged**
