### PR TITLE
Make inherited labels a status rather than a top-level attribute

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Moves the inheritedLabels attribute on the cluster from the top level to status, as Kube objects should only contain spec, status and metadata: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```
/assign @maciaszczykm

### CODE REVIEW

**Comment by maciaszczykm** [comment]
The change looks good, but it will probably cause null pointers in the frontend. We have to fix it at the same time. Am I right, @floreks?

**Comment by alvaroaleman** [comment]
@maciaszczykm I don't think so, the only api-visible change this introduces is that a nil map will not be serialized with a value of `null` anymore but instead just omitted. I would expect javascript to treat a json field with a value of `null` equaly to an absent field.

**Comment by maciaszczykm** [comment]
@alvaroaleman Just checked the frontend, it should work as we have null checks for inherited labels field. We have to solve it quickly anyways as the frontend feature will not work until we will port it to use inherited labels from status instead.

/lgtm
/approve

**Comment by floreks** [comment]
All good. No need to update frontend as external object sent to the frontend has not changed.

**Comment by maciaszczykm** [comment]
Ah, I see. I looked at wrong structure 😓

**Pull request merged**
