### PR TITLE
Update Prometheus

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This PR updates Prometheus to the latest stable version. According to the changelog since 2.3, no breaking changes happened, *but* the TSDB for 2.4 is incompatible with 2.3, so *we cannot downgrade/rollback after deploying this* without also wiping the volume.

Alertmanager was also updated with no significant changes mentioned in its changelog.

**Release note**:
```release-note
Updated Prometheus to `v2.6.0` and Alertmanager to `v0.15.3`
```

### CODE REVIEW

**Comment by xmudrii** [comment]
/lgtm
/approve
/hold
if Nico wants to take a look otherwise unhold

**Comment by thetechnick** [comment]
/lgtm
/unhold

looks quite unspectacular

**Review by thetechnick — APPROVED** [review]

**Comment by xmudrii** [comment]
Let's make sure it's not a flake
/retest

**Comment by xmudrii** [comment]
Seems flaky :eyes: 
/test pull-kubermatic-e2e-aws-coreos-1.13

**Comment by xmudrii** [comment]
/test pull-kubermatic-e2e-aws-coreos-1.13

Strange, let's try this again

**Comment by xmudrii** [comment]
For some reason Tide got stuck. Let's try to close and reopen the PR, hopefully that is not going to remove approved status. If this doesn't help, let see with the testing team in the morning.

**Pull request merged**
