### PR TITLE
update Velero to 1.0.0

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This updates Velero to the new stable version. Since the manifests have been removed from the upstream distribution and been replaced with `velero install`, I added a tiny script to at least automatically extract the CRDs in the hopes of never having useless diffs because someone manually copies them over into our chart.

Upgrades from 0.11 are supposed to be easy and require no user interaction. As documented in Kubermatic 2.10, users are strongly supposed to replace Ark 0.x with Velero 0.11, so we have a good basis to update to Velero 1.0 in Kubermatic 2.11.

**Does this PR introduce a user-facing change?**:
```release-note
update Velero to 1.0
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

I have not yet actually deployed this to dev to test the upgrade path.

**Comment by xrstf** [comment]
/hold cancel

Let's do this.

**Review by kron4eg — APPROVED** [review]
/lgtm
/approve

/hold

@xrstf please unhold it once you're ready

**Comment by xrstf** [comment]
I deployed it on dev already and it didn't break stuff more than it was broken before. But I wanted to fix stuff before merging and then noticed that doing Prometheus properly (see Thanos PR) is a better way to fix [our] Velero setup.

So I would like to do Thanos first and Velero second.

**Comment by xrstf** [comment]
/hold cancel

Seems to work just fine, let's get this deployed.

**Review by kron4eg — APPROVED** [review]
/approve no-issue

**Pull request merged**
