### PR TITLE
Extend helm script used in CI for automated testing

### PR DESCRIPTION
**Pull request by wurbanski**
**What does this PR do / Why do we need it**:
This makes the helm rendering test script more verbose in case of errors in rendering.

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
Is this supposed to solve anything? Is this just for aiding in debugging?

**Comment by wurbanski** [comment]
> Is this supposed to solve anything? Is this just for aiding in debugging?

Seeing what's the problem in the CI is a good thing in general, I think. But it's not an active issue anywhere, just to make life easier.

**Review by xrstf — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
/override pre-kubermatic-test-integration

vCenter is down.

**Pull request merged**
