### PR TITLE
Update customer cluster etcd to v3.4.1

### PR DESCRIPTION
**Pull request by shahbazn**
**What this PR does / why we need it**:

- Update customer cluster etcd to v3.4.1
- With etcd >= 3.4.0, snapshot command no longer accepts comma separated list of endpoints. So this PR updates the backup cronjob accordingly
- Remove `time` from backup controller. it is not in the image anymore

```release-note
Update customer cluster etcd to v3.4.1
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@shahbazn Thanks for the PR. Since when is etcd 3.4.1 supported? Can we gate this by cluster version instead of unconditionally upgrading all etcds?

**Comment by shahbazn** [comment]
@alvaroaleman [here](https://kubernetes.io/blog/2019/08/30/announcing-etcd-3-4/) is the announcement form Friday, August 30, 2019. AFAIK it works with all supported k8s versions within kubermatic

**Comment by alvaroaleman** [comment]
> @alvaroaleman here is the announcement form Friday, August 30, 2019. AFAIK it works with all supported k8s versions within kubermatic

Thats just an announcement of the etcd release, it doesn't really mention anything about Kubernetes compatibility.

Can you try and find out for which Kubernetes Version etcd 3.4 is officially supported? Issues with the etcd <-> apiserver communication are oft very subtile, just because a happy path works doesn't mean there are no issues.

**Comment by alvaroaleman** [comment]
@shahbazn So I asked about the compatibility [in the Kubernetes Slack](https://kubernetes.slack.com/archives/C0EG7JC6T/p1572902478428100) and the answer was basically "we don't know if it works or not pre 1.17". Hence I'd like to only use etcd 3.4.X for 1.17+ clusters

**Pull request closed without merging**
