### PR TITLE
Upgrade Anexia CCM to v1.5.2

### PR DESCRIPTION
**Pull request by marioreggiori**
**What this PR does / why we need it**:
Upgrade Anexia CCM to v1.5.2.

**What type of PR is this?**
/kind cleanup

**Special notes for your reviewer**:
- Release notes: https://github.com/anexia-it/k8s-anexia-ccm/releases/tag/v1.5.2
- Please backport to v2.21 & v2.20 after this PR was accepted.

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update Anexia CCM (cloud-controller-manager) to version 1.5.2
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
Hey @marioreggiori, thanks for the contribution. We are in a critical phase of code freeze for the next KKP release, so it will likely take a few days until we can accept this PR.

**Comment by xrstf** [comment]
@marioreggiori I am a little bit worried about 

> instances: panic on 401 responses from engine to slow down requests with invalid token @marioreggiori (https://github.com/anexia-it/k8s-anexia-ccm/pull/155)

in the CCM changelog. Won't this mean that if a user has provided bad credentials, the CCM will crashloop and alert _the admin_, who can do nothing about this? While the user (cluster creator) cannot see the issue and/or fix it, as the CCM is running out-of-cluster.

**Comment by LittleFox94** [comment]
> @marioreggiori I am a little bit worried about
> 
> > instances: panic on 401 responses from engine to slow down requests with invalid token @marioreggiori ([anexia-it/k8s-anexia-ccm#155](https://github.com/anexia-it/k8s-anexia-ccm/pull/155))
> 
> in the CCM changelog. Won't this mean that if a user has provided bad credentials, the CCM will crashloop and alert _the admin_, who can do nothing about this? While the user (cluster creator) cannot see the issue and/or fix it, as the CCM is running out-of-cluster.

That's a valid concern and good point.

The change made sense in our environment, where an automation for user clusters manages both the service user for our API and the KKP user cluster - meaning this case only happens when this automation is overridden in some way. This does not make that much sense in a scenario were CCM is used in a KKP that is not managed by our automations ..

It was built this way because we didn't find another quick fix when this scenario happened and practically DoS'd our API. Right now we don't see anyone use KKP not managed by our automations, so in practice it's not a critical issue - we will try to come up with a better fix for this though, does this give you some peace of mind?

**Comment by xrstf** [comment]
Ok, fair enough :)

/approve
/lgtm
/retest

**Comment by marioreggiori** [comment]
We are still working on Kubernetes v1.26 support. Would it be possible to target v1.25 for now when testing?

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
@xrstf let's override pre-kubermatic-e2e-anexia-flatcar-1.26 for now

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/retest

**Pull request merged**
