### PR TITLE
Update OSM to latest commit

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Pin OSM to latest [commit](https://github.com/kubermatic/operating-system-manager/commit/07720b8706ee5b2f1bbf6c30b818c69b9135c148).

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Review by xrstf — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
Needs https://github.com/kubermatic/operating-system-manager/pull/276 to work

**Pull request merged**
