### PR TITLE
Removes NodeCSR from user-controller-manager

### LINKED ISSUE #5216: Replace Kubermatic NodeCSRApprover with machine-controller implementation
**User Story**

Right now, we have the NodeCSRApprover controller implemented both in Kubermatic and `machine-controller`. Having a controller that does the same thing implemented in two different places makes it hard to keep them in sync. We should consider switching to the machine-controller implementation and removing the Kubermatic one.

**Acceptance criteria**

* Kubermatic uses the NodeCSRApprover controller from `machine-controller`
* The NodeCSRApprover controller is removed from Kubermatic

### PR DESCRIPTION
**Pull request by imharshita**
Signed-off-by: Harshita <harshita.sharma6174@gmail.com>

**What this PR does / why we need it**:
Removes NodeCSR from user-controller-manager

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5216

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Removes NodeCSR from User Cluster Controller Manager and Enables NodeCSR from Machine Controller
```

### CODE REVIEW

**Comment by imharshita** [comment]
Testing is going on

**Review by moadqassem — COMMENTED** [review]
/retest

**Review by moadqassem — COMMENTED** [review]
/approve
/lgtm

**Review by xmudrii — APPROVED** [review]

**Pull request merged**
