### PR TITLE
Backport monitoring features

### PR DESCRIPTION
**Pull request by thetechnick**
**What this PR does / why we need it**:
Backports PRs #2145, #2130, #2177, #2195, #2219 and #2191 to kubermatic v2.8.
@bashofmann would like to see #2219 cherry-picked to v2.8.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
Prometheus user cluster pod scraping
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
Looks basically good from my point of view. 
Would be great if @alvaroaleman could have quick look over it as well.

cc @bashofmann

**Comment by alvaroaleman** [comment]
@thetechnick To me this _looks_ good buts its a huge amount of change so there is a reasonable chance something slipped. Did you locally test if it does what it is supposed to do?

**Comment by thetechnick** [comment]
@alvaroaleman
@mrIncompetent Did ask me the same question in slack:

I have started all components locally and created a new cluster on Hetzner. I did not notice any errors.
User cluster node monitoring works directly after install and when adding the pod annotation `kubermatic.io/port: "10055"` to the dns deployment the will be scraped and discovered by prometheus.

The only issue I have seen, is that one of the Hetzner nodes did not come up, but this must be an issue with hetzner or the machine controller.

PS: next time I will directly add my manual test results to the PR description.

**Comment by thetechnick** [comment]
@bashofmann FYI: This PR would delay the release of `v2.8.0`, but because of your request, we targeted this feature/PR to be released in form of a `v2.8.1` release.

Release dates are TBD, I will try to keep you updated :)

**Review by alvaroaleman — APPROVED** [review]

**Comment by bashofmann** [comment]
Awesome, thanks for backporting this. Releasing this with 2.8.1 is perfectly fine, as long as we don't have to wait 3 months to have it in 2.9 :)

**Review by mrIncompetent — APPROVED** [review]

**Pull request merged**
