### PR TITLE
Remove update cluster endpoint

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**: Removes update cluster endpoint as it is replaced by patch endpoint and not used at the moment (see: https://github.com/kubermatic/dashboard-v2/pull/833/files#diff-656f0718f18ffb3e2b0413c67636627cL63).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: n/a

**Special notes for your reviewer**: n/a

**Documentation**: n/a

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by p0lyn0mial — APPROVED** [review]
I'm really happy that we don't have to maintain that custom `UpdateCloudSpec` method anymore. Thanks !

Please add a release note.

**Comment by p0lyn0mial** [comment]
@maciaszczykm please don't forget to remove unused fields from public cloud specs.

for example https://github.com/kubermatic/kubermatic/blob/master/api/pkg/api/v1/types.go#L328

**Comment by maciaszczykm** [comment]
@p0lyn0mial Can I do it from separate pull request? It has to be done very precisely to avoid errors on the dashboard side.

**Comment by p0lyn0mial** [comment]
> @p0lyn0mial Can I do it from separate pull request? It has to be done very precisely to avoid errors on the dashboard side.

sure.

**Pull request merged**
