### PR TITLE
Update Anexia CCM to 1.5.6

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Just for completeness sake :grin: 

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update Anexia CCM to 1.5.6
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/test pre-kubermatic-e2e-anexia-flatcar-1.30

Just checking, not sure if this CI job was functional

**Comment by xrstf** [comment]
I think we can override the tests here, we haven't run them in ages and i'm 50% sure they wouldn't work.

**Comment by ahmedwaleedmalik** [comment]
> I think we can override the tests here, we haven't run them in ages and i'm 50% sure they wouldn't work.

Yeah we should override, I just wanted to check whether they are functional, irrespective of your changes.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
