### PR TITLE
[release/v2.21] use unordered comparison of vsphere networks & fix flakiness documentation generation (#11048, #10985)

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:

Manual cherry-pick of #11048 and #10895.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by vgramer — APPROVED** [review]
/lgtm

**Comment by embik** [comment]
@lsviben good call, done!

**Pull request merged**
