### PR TITLE
mark application tests that rely on external programs as integration tests

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
The `TestDownloadChart` and `TestBuildDependencies` tests rely on external programs and have shown to be a little bit flaky, with errors like

> helm.go:146: can not push chart '/tmp/TestDownloadChart2542123695/001/examplechart-0.1.0.tgz' to oci registry: failed to do request: Head "http://localhost:37937/v2/helm-charts/examplechart/blobs/sha256:e56aefc9e936f19dc3859b9807e03a9f1ff6adf34685672c800ae411663d9f96": dial tcp [::1]:37937: connect: connection refused

I think it would be nice if unit tests only fail if there's an actual problem. :) So I simply moved the tests into the other existing integration tests.

**What type of PR is this?**
/kind cleanup
/kind failing-test

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by vgramer — COMMENTED** [review]
/lgtm

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
@xrstf vcenter seems down unfortunately.

**Pull request merged**
