### PR TITLE
 Remove already replaced endpoints

### LINKED ISSUE #2536: Enforce apiserver-kubelet version relationships
A minor version of Kubernetes typically supports a specific range of kubelet versions connected to it.

At several occasions our customers ran into trouble when they upgraded the control plane while older nodes were still attached, which resulted in incompatible apiserver-kubelet version pairing.

This epic describes enforcement of these version constraints (as described by Kubernetes release notes) during cluster/node creation and upgrade.

### LINKED ISSUE #2866: Add an endpoint to return possible kubelet versions for a specific control plane version
**User Story** I'd like to have an endpoint that is not only able to return possible kubelet versions for a cluster (using its control plane versions) but also for specific control plane versions. It can be used when user would like to modify control plane and kubelet versions at once and can be built like already existing endpoint.

**Acceptance criteria** New endpoint is available and there are tests for it.

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What this PR does / why we need it**:  Removes already replaced endpoints.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: Fixes #2866. Fixes #2536.

**Special notes for your reviewer**: Do not merge before https://github.com/kubermatic/dashboard-v2/pull/1128.

/hold

**Documentation**: n/a

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/hold cancel

@p0lyn0mial PTAL

**Comment by p0lyn0mial** [comment]
thx :)

/lgtm
/approve

**Pull request merged**
