### PR TITLE
Add support for DigitalOcean CCM

### LINKED ISSUE #8847: Add support for DigitalOcean CCM in KKP
### What would you like to be added? / User Story
As a user, I would like to be able to use LoadBalancers natively within clusters running on DigitalOcean.
For this reason, integration with out-of-tree [digitalocean-cloud-controller-manager](https://github.com/digitalocean/digitalocean-cloud-controller-manager) is required.

### Acceptance criteria
KKP uses digitalocean's cloud controller manager to support integration with the provider.

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>
Co-Authored-By: Sang Woo Bae <sang@kubermatic.com>

**What this PR does / why we need it**:
This PR adds support for DigitalOcean CCM([digitalocean-cloud-controller-manager](https://github.com/digitalocean/digitalocean-cloud-controller-manager)).

**Which issue(s) this PR fixes**:

Fixes #8847

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add support for DigitalOcean external CCM
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/override pre-kubermatic-test-integration

vSphere/VPN is broken yet again.

**Review by xrstf — CHANGES_REQUESTED** [review]
> {"level":"error","time":"2022-11-30T18:32:38.480Z","logger":"kkp-kubernetes-controller","caller":"kubernetes/cluster_controller.go:273","msg":"Reconciling failed","cluster":"kkp-1598020224408358912-56qg6","error":"failed to reconcile cluster: failed to ensure Deployment cluster-kkp-1598020224408358912-56qg6/digitalocean-cloud-controller-manager: failed to create *v1.Deployment 'cluster-kkp-1598020224408358912-56qg6/digitalocean-cloud-controller-manager': Deployment.apps \"digitalocean-cloud-controller-manager\" is invalid: spec.template.spec.containers[2].name: Duplicate value: \"openvpn-client\"","errorCauses":[{"error":"failed to reconcile cluster: failed to ensure Deployment cluster-kkp-1598020224408358912-56qg6/digitalocean-cloud-controller-manager: failed to create *v1.Deployment 'cluster-kkp-1598020224408358912-56qg6/digitalocean-cloud-controller-manager': Deployment.apps \"digitalocean-cloud-controller-manager\" is invalid: spec.template.spec.containers[2].name: Duplicate value: \"openvpn-client\""}]}

**Comment by ahmedwaleedmalik** [comment]
Unfortunately during rebase, I unknowingly dropped some of my changes. Everything should be fine now.

**Pull request merged**
