### PR TITLE
Update MC/OSM, migrate/cleanup cloud-config code

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This PR started out by wanting to bump MC/OSM in KKP. However we made a few changes in MC that are causing some more work:

* https://github.com/kubermatic/machine-controller/pull/1802
* https://github.com/kubermatic/machine-controller/pull/1812

These PRs have removed the `ini` package KKP was using to escape some values in the generated cloud-configs. However I dug a bit deeper than just resurrecting the `ini` package.

---

In general we had 4 places with code that generates cloud-configs:

* machine-controller (MC)
* operating-system-manager (OSM)
* KKP (pkg/resources/cloudconfig)
* KKP (pkg/resources/csi)

The code in MC was removed because we do not need it anymore. OSM still has the code, but from what I've been told, this is only because of in-tree CCMs and once OSM doesn't care about Kube versions with potential in-tree CCMs, the cloud-config code should probably also be removed from OSM. Ultimatly only KKP should create cloud-configs is the guidance I got and under which I made this PR :grin:

This left KKP with 2 locations where we generate cloud-configs.

---

But additionally, there was a drift between the cloud-config code in KKP and in MC, for example here:

* https://github.com/kubermatic/machine-controller/blob/ec6b90321786f4fe1974fed3a41a742e43a9b0a5/pkg/cloudprovider/provider/openstack/types/cloudconfig.go
* https://github.com/kubermatic/kubermatic/blob/de2d0cd3e9dd152adb17b984ba8d7ae51929b1cb/pkg/resources/cloudconfig/openstack/cloudconfig.go
* KKP supports `enable-ingress-hostname`, MC does not.

Or here:

* https://github.com/kubermatic/machine-controller/blob/ec6b90321786f4fe1974fed3a41a742e43a9b0a5/pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
* https://github.com/kubermatic/kubermatic/blob/de2d0cd3e9dd152adb17b984ba8d7ae51929b1cb/pkg/resources/csi/vsphere/config.go
* MC supports `ip-family`, KKP does not.

In this PR, I have attempted to create a superset of cloud-configs, e.g. the latest and greatest and bestest we had.

---

Additionally, KKP has 2 cloud-configs:

* the "regular" cloud-config, which lives on the seed cluster and is consumed by the CCM
* the "CSI" cloud-config, which lives in the user cluster and is consumed by the CSI driver

Personally unless I'm missing something, the term "CSI cloud config" is highly misleading and it should be something like "usercluster cloud-config": CCM and CSI can have different options. Usually the CSI has its own section in the cloud-config for additional configuration. However from what I've seen, CCM and CSI never conflict with each other, so you can (and KKP does) have a single cloud-config that can be used by both CCM and CSI. This means the cloud-configs are identical to each other and the only difference between the two is the clusters they live in.

At first I thought the CSI cloud-config, since it lives in the usercluster, was not supposed to contain/leak credentials, but looking at the code, this is not true. The CSI cloud-config is identical to the CCM one.

---

So taking all of this in, I decided to consolidate and clean up the cloud-config code a bit.

* I moved it all to `pkg/resources/cloudconfig/<providername>`, i.e. `pkg/resources/csi` still has the reconcilers and stuff, but doesn't contain any `ini` code generation.
* I chose to remove the ini templates and instead use a Go API to construct the ini files.
  * This is because I remember we had bugs in the ini code (which is why we now have the `iniEscape` function). It irks me to constuct data structures using string concatenation or templating, it reminds me of dark times in my PHP background when we printf()'ed JSON strings.
  * _However_ gopkg/ini is really not good at outputting ini. The library is clearly written to only _read_ ini, not write it. For example there is code in the library to map an ini file to a struct, but the (seemingly much easier) other way around (generate ini from a struct) is not supported.
  * I tested gopkg/ini at first, but it doesn't do _ANY_ escaping/quoting. Even if your password is `foo"bar" ; not a comment`, the library will just output it verbatim and then fail to parse it again because oh wonder, there's an inline comment in it. Plus you cannot distinguish `foo = true` between the boolean `true` or the string `"true"`.
  * gopkg/ini also has to be configured to allow "shadowed" values, i.e. multiple identical keys, which we use for vSphere tags, for example.
  * Because of this and since I already replaced the templating with a Go API, I chose to write a super duper micro mini API in KKP to generate properly escaped ini files. This API is only meant to generate the cloud-configs and so lives in pkg/resources/cloudconfig. IMHO this is still superior to using text templates.
* All providers have a `ForCluster()` function that returns the raw CloudConfig data struct, which then has a `String()` function to render it in whatever format is necessary.
* There is no distinction in the naming between CSI and CCM cloud-configs anymore. There is no `CloudConfigCSIToSomething` function anymore, because there is only 1 cloud-config, we just have it in 2 places (seed cluster + user cluster).

Looking at each provider individually, I changed:

* AWS
  * removed unused `KubernetesClusterTag` from the Go struct (was never rendered into the cloud-config)
* GCP
  * removed unused `RHSMOfflineToken` field from Go struct (was never rendered into the cloud-config)
* OpenStack
  * the `{{- if semverCompare "~1.9.10 || ~1.10.6 || ~1.11.1 || >=1.12.*" .Version }}` conditions have been removed since we exclusively deal with Kubernetes >= 1.27 nowadays anyway
  * Note that gcfg or at least OpenStack is peculiar. Having `lb-provider = ""` in the cloud-config is differnt from omitting that line alltogether. I got tricked a number of times thinking a field is loooooong removed and pointless, but nope, some defaulting magic deep in the CCM/CSI might still require it.
* VMWareCloudDirector
  * uses yaml.Marshal() instead of Go templating to generate the YAML file
* vSphere
  * add `ip-family` to Global and VirtualCenter sections (was present in MC, but never in KKP)
  * add `cluster-id` to Global section (was only present in the CSI vSphere cloud-config, now it's in "both")

---

Finally, I copy-pasted the KubeletFlags parsing code from MC into KKP. Half of the KubeletFlags code was removed in MC, but KKP needed that removed half.

---

NB: This is purposefully not updating MC to its latest commit, because that would also pull in controller-runtime 0.19 and Kube 1.31 dependencies. We should do that in a follow-up PR.

**What type of PR is this?**
/kind chore

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
`cloud-config` handling for CCM/CSI was moved from machine-controller to KKP and cleaned up; adding `Global.ip-family` field to vSphere CSI cloud-config
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
vSphere is failing with

> {"level":"error","time":"2024-08-22T14:40:47.847Z","logger":"machine-controller","caller":"machine/controller.go:388","msg":"Reconciling failed","machine":"kube-system/e2e-wjnzf-9c9b6ffb9-pmjk7","error":"An error of type = InvalidConfiguration, with message = failed to create cloned vm: 'error when waiting for result of clone task: Insufficient disk space on datastore 'Datastore0-truenas'.' occurred"}

For reference, the generated cloud-config (anonymized) in this test was:

```ini
[Global]
user = "........."
password = "........"
port = "443"
insecure-flag = true
working-dir = "kkp-1826626743272738816-kz2lm"
datacenter = "Hamburg"
datastore = "Datastore0-truenas"
server = "10.10.0.100"
cluster-id = "kkp-1826626743272738816-kz2lm"

[Disk]
scsicontrollertype = "pvscsi"

[Workspace]
server = "10.10.0.100"
datacenter = "Hamburg"
folder = "/Hamburg/vm/Kubermatic-dev/kkp-1826626743272738816-kz2lm"
default-datastore = "Datastore0-truenas"
resourcepool-path = ""

[VirtualCenter "10.10.0.100"]
user = "........."
password = "........"
port = "443"
datacenters = "Hamburg"
```

**Comment by xrstf** [comment]
Dualstack failures are also unrelated (cf. https://github.com/kubermatic/kubermatic/pull/13615#issuecomment-2304476176)

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

Generally speaking, this is a relatively big change so I'd suggest to add a release note to make this change trackable from release notes. cc @xrstf @xmudrii

**Comment by ahmedwaleedmalik** [comment]
Whoopsies, needs rebase 

```
# k8c.io/kubermatic/v2/pkg/resources/cloudconfig
pkg/resources/cloudconfig/secret.go:118:29: not enough arguments in call to kubevirt.ForCluster
	have (*"k8c.io/kubermatic/v2/pkg/apis/kubermatic/v1".Cluster)
	want (*"k8c.io/kubermatic/v2/pkg/apis/kubermatic/v1".Cluster, *"k8c.io/kubermatic/v2/pkg/apis/kubermatic/v1".Datacenter)
```

**Comment by ahmedwaleedmalik** [comment]
/lgtm cancel

to avoid retries

**Comment by xrstf** [comment]
When you think you pressed Ctrl-S to save, but nooo, your keyboard disagreed with you.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
