### PR TITLE
Add OIDC support to the K8S Dashboard integration

### LINKED ISSUE #10014: Deprecate and remove old ".../dashboard/proxy" endpoints
For security reasons, it would be best to simply remove old `.../dashboard/proxy` endpoints. Old logic does not take into account detailed user privileges. The user is only mapped to one of the predefined roles. New logic will use the RBAC feature available on the cluster details view.

### LINKED ISSUE #10016: Handle new OIDC flow for the Kubernetes Dashboard
It required introduction of 2 new endpoints:
- `api/v2/dashboard/login`
- `api/v2/projects/{projectID}/clusters/{clusterID}/dashboard/proxy`

### Login Endpoint
It will be responsible for redirecting users to the configured OIDC provider and extracting the user-specific token that can be further used by the K8S Dashboard to authenticate against the user cluster API server. It will then redirect to the `proxy` endpoint and pass the token.

#### Required query parameters
- clusterID
- projectID
- userID (check if it could be read from the bearer token used to authenticate against KKP API server)

### Proxy Endpoint
It will work almost the same as currently with the only difference that it will use the provided token to authenticate.

### Required query parameters
- token (bearer token accepted by the user cluster API server)
- userID (check if it could be read from the bearer token used to authenticate against KKP API server)

### PR DESCRIPTION
**Pull request by floreks**
**What does this PR do / Why do we need it**:
This PR changes the way Kubernetes Dashboard proxy integration works. It is now based on the OIDC flow and the authorization token returned from the identity provider. Thanks to the KKP Dashboard RBAC management it is now possible to dynamically configure per-user privileges inside K8S Dashboard.

**NOTE**: When this gets merged it will effectively break the `Open Dashboard` button in the KKP UI until other issues/PRs related to this epic will be done.

##### What's Changed
- Removed old dashboard proxy endpoints (ref: #10014):
  - `/api/v2/projects/{project_id}/clusters/{cluster_id}/dashboard/proxy`
  - `/api/v1/projects/{project_id}/clusters/{cluster_id}/dashboard/proxy`
- Added new endpoints to handle proxy calls
  - `api/v2/dashboard/login` - Handles the OIDC redirect and callback parts. Required parameters:
    - `projectID` and `clusterID` - used for the initial request to this endpoint
    - `state` and `code` - those are returned by the identity provider after successful authentication
  - `api/v2/projects/{project_id}/clusters/{cluster_id}/dashboard/proxy` - Required parameters:
    - `token` - bearer token retrieved from the identity provider after successful authentication
- Updated KKP - K8S Dashboard version compatibility matrix

##### Preview
https://user-images.githubusercontent.com/2285385/173351067-aeaf9695-47b4-4411-bebd-312329590936.mp4

**Does this PR close any issues?**:
Related to #9804
Fixes #10016
Fixes #10014

**Special notes for your reviewer**:
In order to test this locally:
1. Alter our dex configuration (`kubermaticIssuer` client) to whitelist the `redirectURI`: `http://localhost:8080/api/v2/dashboard/login`
  - `kubectl -n oauth edit configmap dex`
  - `kubectl -n oauth rollout restart deployment dex`
image
3. Create and wait for any cluster to start (using our dev env).
4. Run the API locally, i.e. `make clean && FEATURE_GATES=OIDCKubeCfgEndpoint=true KUBERMATIC_EDITION=ee KUBERMATIC_DEBUG=false ./hack/run-api.sh`
5. There are 2 ways to test the "frontend" part now:
  - run the KKP dashboard using `npm run start:local` after checking out this PR: https://github.com/kubermatic/dashboard/pull/4585
  - go to the `http://localhost:8080/api/v2/dashboard/login?clusterID=<clusterID>&projectID=<projectID>`. Make sure to replace `clusterID` and `projectID` with values of the created cluster. You will also need to get the authorization bearer token and inject it into the request to the API (i.e. using requestly chrome extension).

**NOTE**: The first step will not be required once #10015 will be done.

**Does this PR introduce a user-facing change?**:

```release-note
Removed the `/api/v1/projects/{project_id}/clusters/{cluster_id}/dashboard/proxy` endpoint.
Updated the `/api/v2/projects/{project_id}/clusters/{cluster_id}/dashboard/proxy` to use the OIDC based authentication flow to access K8S Dashboard.
Added the `api/v2/dashboard/login` endpoint to initiate the OIDC login flow.
```

### CODE REVIEW

**Comment by floreks** [comment]
Feel free to take over in case of any issues or more linter errors. I have tried to clean everything up. In case of any questions, you can always cc me :slightly_smiling_face:.

**Comment by ahmedwaleedmalik** [comment]
Had to rebase due to the DCO errors.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
/retest
FLAKEEEEEE

**Comment by ahmedwaleedmalik** [comment]
@floreks I tested this at my end and it didn't work.
Screenshot 2022-06-16 at 11 59 17 AM
 
Are you sure we need both of these? 
https://github.com/kubermatic/kubermatic/blob/7610842cb2f056f42a9781d46b57c38ced824c38/pkg/handler/v2/kubernetes-dashboard/login.go#L94
https://github.com/kubermatic/kubermatic/blob/7610842cb2f056f42a9781d46b57c38ced824c38/pkg/handler/v2/kubernetes-dashboard/login.go#L192

Also, I had to rebase this PR since as soon as I pushed a commit in your branch we ended up with DCO failures https://github.com/kubermatic/kubermatic/pull/10072#event-6811333744

Did the rebase mess something up?

**Comment by floreks** [comment]
`http://localhost:8080/api/v2/dashboard/login?clusterID=<clusterID>&projectID=<projectID>` should be the default API port.

You are using `localhost:8000` from what I can see :)

**Comment by ahmedwaleedmalik** [comment]
@floreks I'm testing it using the dashboard :) 
```
run the KKP dashboard using npm run start:local after checking out this PR: https://github.com/kubermatic/dashboard/pull/4585
```

So that call is being proxied to `8080` anyways :)

**Comment by floreks** [comment]
Everything should work then as in the video preview. You'd have to check the logs to see what happens.

**Pull request merged**
