### PR TITLE
test vSphere folder creation & adapt code to match common structure

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
This PR will introduce a integration test for the vSphere folder creation. 
Also it will move some vSphere SDK specific code out of the `provider.go` to keep it smaller/more readable.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Can we run the Vsphere presubmit when we change something there?

As an aside we could write integration tests that just call the cloud providers `initialize` and `cleanup`

**Comment by mrIncompetent** [comment]
> As an aside we could write integration tests that just call the cloud providers initialize and cleanup

Like a single test, that tests every provider "happy-path" ? 
That would be super dope

**Comment by mrIncompetent** [comment]
Testing if i can trigger a test that has `run_if_changed` configured & does not match here.

/test pull-kubermatic-user-cluster-prometheus-config-validation

**Comment by mrIncompetent** [comment]
@alvaroaleman Objections in merging this one?

**Pull request merged**
