### PR TITLE
fix CCM migration test flags

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
I made an oversight in #11639 and for some reason we didn't run the ccm-migration tests in that PR.

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
/hold 
to avoid retries

**Comment by xrstf** [comment]
/override pre-kubermatic-ccm-migration-aws-e2e

unrelated flake

/override pre-kubermatic-ccm-migration-vsphere-e2e

vsphere is broken

**Comment by xrstf** [comment]
/override pre-kubermatic-test-integration

vSphere strikes again.

/override pre-kubermatic-mla-e2e

flaking

**Pull request merged**
