### PR TITLE
more realistic resource requests for Elasticsearch

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Judging from our dev cluster, the default resource usage for Elasticsearch is higher than what we define. This leads to bad scheduling decisions.

Starting with Java 10, more container-centric options are available. The newest is `-XX:+UseContainerSupport`, which supersedes `-XX:+UseCGroupMemory*`. With this the JVM is smart enough to figure out the resources the container is assigned. The only thing we then set is the percentage of memory to use for the heap, which we set to 80% (determined using a 12-sided dice, thrown 17 times and then averaged).

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
Wha size of heap (-Xmx, -Xms and -xx:NewSize) are those images using? Is it possible to change them?

**Comment by xrstf** [comment]
We are setting `-Xms=HEAP_SIZE -Xmx=HEAP_SIZE` and HEAP_SIZE is configured using our values.yaml (256MB for master nodes, 1024MB for data nodes). Any other JVM option would have to be set explicitly and we don't do that.

**Comment by kron4eg** [comment]
@xrstf so... are you going to align `logging.elasticsearch.master.heapSize` and `logging.elasticsearch.data.heapSize` with those new `requests.memory`?

**Comment by xrstf** [comment]
Our ES stack runs on OpenJDK 12, so container support is enabled by default. It seems that setting the heap size explicitly is not the optimal solution, we could rather just set a percentage of memory to use and let Java do its thing. It just requires that we have proper container limits set.

**Comment by kron4eg** [comment]
oh wow, that's awesome

**Review by kron4eg — APPROVED** [review]
/approve no-issue

NOW I like it 👍 💯

**Pull request merged**
