### PR TITLE
user cluster prometheus proxy api

### PR DESCRIPTION
**Pull request by multi-io**
**What this PR does / why we need it**:

This adds an authenticated reverse proxy API for the user cluster Prometheus instances, reachable via `/api/v3/dc/<dc>/cluster/<cluster>/prometheus/query[_range]?<params>`. We want to use this to display dashboards in the UI.

Is this of interest to you guys? We could add a boolean "enable this" flag to the CLI if needed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
User cluster Prometheus reverse proxy API
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
@multi-io hi, thanks for the PR, tomorrow we would like to join the meeting and discuss your use case.

**Comment by multi-io** [comment]
hi @p0lyn0mial, sure OK, let's talk tomorrow.

**Comment by p0lyn0mial** [comment]
@multi-io should we close this issue ?

**Comment by multi-io** [comment]
@p0lyn0mial yeah, can be closed. Sorry for the late reply.

**Pull request closed without merging**
