### PR TITLE
Update osm version

### PR DESCRIPTION
**Pull request by moadqassem**
**What does this PR do / Why do we need it**:
Bumping OSM version to `v0.3.9` which solves some issues with flatcar and amzn-linux provisioning. In addition to fixing some other minor issues. 
**Does this PR close any issues?**:

Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/lgtm

**Comment by xrstf** [comment]
/override pre-kubermatic-test-integration

vCenter has problems.

**Pull request merged**
