### PR TITLE
Retry starting setup-network-environment and kubelet on DigitalOcean

### PR DESCRIPTION
**Pull request by metalmatze**
This is still WIP...

Restarting setup-network-environment on failure works fine for me on my nodes. But sadly ones the setup-network-environment is up after a few retries the kubelet isn't started automatically and says it's dependencies aren't started, because it seems to doesn't know that the setup-network-environment was retried and now is up and running. 😕 

Any ideas on how to trigger kubelet restart after setup-network-environment is up at a 2 or 3 retry?
I've tried WantedBy & PartOf (as you can see below)

@mrIncompetent @realfake

### CODE REVIEW

**Comment by mrIncompetent** [comment]
Doesn't the kubelet then also need the restart flag?

**Comment by metalmatze** [comment]
It already has the flag:
https://github.com/kubermatic/kubermatic/pull/543/files#diff-b94dc196db3caf655ad4b15feb74c3baR86

**Comment by metalmatze** [comment]
I've pushed a little `bootstrap.sh` script that replaces the 2 unit files.
With this the kubelet fails the first few times but then manages to download and start itself.

Two things are open for tomorrow:

1. Use curl or wget and not both
2. Version files that are downloaded and copy or symlink to non versioned file.
    2.1 Decide if copy or symlink is better

**Comment by mrIncompetent** [comment]
Looks good so far, can you then also apply this to the openstack & aws nodeclass?

**Comment by metalmatze** [comment]
In this PR too? Or should I create following ones?

**Comment by mrIncompetent** [comment]
For simplification in this pr i would say. Unless its easiert for you to create new ones

**Comment by metalmatze** [comment]
No. I can append that this one. No Problem. :blush:

**Comment by metalmatze** [comment]
I've resolved all remaining "problems" and is good to merge from my side. :+1:

**Review by mrIncompetent — APPROVED** [review]

**Pull request merged**
