### PR TITLE
Add information about inherited labels to the cluster

### PR DESCRIPTION
**Pull request by floreks**
**What this PR does / why we need it**:
Add inherited labels to the cluster object, so we can find out which labels should not be editable.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by floreks** [comment]
@alvaroaleman PTAL

**Comment by alvaroaleman** [comment]
@floreks could you please add some tests for this?

**Comment by floreks** [comment]
@alvaroaleman adjusted test to check if labels are properly inherited.

**Review by alvaroaleman — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
