### PR TITLE
Add defaulting for Deployment containers

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Adds defaulting for Deployment containers to prevent reconciliation loops because someone forgot to set ImagePullPolicy/TerminationMessagePath/TerminationMessagePolicy

If you are okay with this approach I would probably like to even expand it further. Right now its too simple to get this wrong and too easy to miss in reviews.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

/assign @mrIncompetent

### CODE REVIEW

**Comment by mrIncompetent** [comment]
Great idea!

Though to have this re-usable we could treat them as wrappers (Like you already do), but maybe have them not generated? And instead generate the usage of it.

I'm thinking of something like:
- Define typed wrappers in https://github.com/kubermatic/kubermatic/blob/master/api/pkg/resources/reconciling/wrapper.go
- Define wrappers in codegen via `reconcileFunctionData` https://github.com/kubermatic/kubermatic/blob/master/api/codegen/reconcile/main.go#L49
- The typed wrappers would be applied here: https://github.com/kubermatic/kubermatic/blob/master/api/pkg/resources/reconciling/zz_generated_reconcile.go#L214

So we can define a list of wrappers for each type, which then get applied to the Reconcile* funcs.

My main intention behind is to keep the static code as small as possible in the codegen. As maintaining static code as "text" is harder.

WDYT?

**Comment by alvaroaleman** [comment]
SGTM

**Comment by alvaroaleman** [comment]
/hold

If the tests pass, I'll remove the relevant properties from the existing Deployment Resources to make sure this actually works

**Comment by alvaroaleman** [comment]
@mrIncompetent Updated, PTAL

**Pull request merged**
