### PR TITLE
add new dex Helm chart to replace the oauth chart

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This is the first step in ridding us of our own home grown `oauth` Helm chart and instead use the superior upstream Dex Helm chart.

The chart was originally named "oauth" based on its intended purpose instead of the underlying software, similar to our `iap` chart. This however is a naming scheme we never really consistently applied and besides oauth/iap, all other Helm charts are simply named based on the software they contain.

My plan is that admins will have to re-install Dex anyway, because making Helm adopt our existing chart would be very tedious and really not needed: Dex is basically stateless, so removing one Helm release and then installing a new one should be no big issue.

And since we're re-installing Dex anyway, I think this is the perfect opportunity to finally get rid of the `oauth` name and instead call it `dex` from now on. This means installing into a new namespace and so technically both the old and new Dex could temporarily live side-by-side on a cluster (_technically_ because the nginx admission webhook will reject 2 Ingresses with the same hostname/path). This would allow admins to first install the new Dex, see if the Pods run fine and then flip the Ingress hosts to direct traffic to the new Dex. Afterwards the `oauth` namespace can be deleted entirely.

In the recent SIG App meeting we have discussed the migration path as outlined by the docs PR linked below. The short form is that we keep both charts for now to allow admins to migrate over time. Since we use `dex` as the top-level key in the Helm values we cannot distinguish based on "is `oauth` defined or `dex`?", that's why a new key, `useNewDexChart`, has been introduced to toggle between the charts. Additionally, admins can use the `--remove-oauth-release` flag on the installer to remove the previous `oauth` release. Personally I expect most admins to just manually remove the release when they're done (why run the installer twice?), but the option is cheap to have and now it's there if someone wants it.

part of #8465

**What type of PR is this?**
/kind deprecation

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Add new `dex` Helm chart to replace the `oauth` Chart; the new chart uses the official upstream Dex chart, but is preconfigured for use in KKP.
```

**Documentation**:
```documentation
https://github.com/kubermatic/docs/pull/1712
```

### CODE REVIEW

**Comment by xrstf** [comment]
My current notes for migrating from oauth to dex:

# value changes

* dex.replicas -> dex.replicaCount
* dex.env -> dex.envVars
* dex.extraVolumes -> dex.volumes
* dex.extraVolumeMounts -> dex.volumeMounts
* x dex.certIssuer (set dex.ingress.annotation manually)
* dex.ingress:
   * class -> className ("non-existent" not supported anymore, use dex.ingress.enabled)
   * host+path -> hosts section
   * scheme -> tls section

# config

* dex.connectors -> dex.config#connectors
* dex.clients -> dex.config#staticClients
* dex.staticPasswords -> dex.config#staticPasswords (must also set dex.config#enablePasswordDB=true)
* dex.expiry -> dex.config#expiry
* dex.frontend -> dex.config#frontend
* dex.grpc -> dex.config#grpc

**Comment by dharapvj** [comment]
Since many customer customize the dex login page from branding perspective.

I feel that we should add dex chart with `ingress.enabled: false` and declare deprecation of old oauth chart. We should ask customer to manually switch ingress to newly installed dex service instead maybe - to test things out?

**Comment by xrstf** [comment]
@dharapvj In https://github.com/kubermatic/docs/pull/1712 I laid out a possible migration plan (and we merged it already :D). My idea was that a separate (temporary) Ingress would allow better verification if the new Dex is up and running. Do you see issues with that? I mean, the other (your) way of having only one Ingress at a time would also work, but is it better or worse than the other method? ^^

**Comment by dharapvj** [comment]
Hey @xrstf - i think the migration path that you have suggested - both dex coexisting is better and less disruptive 💯 

Lets go with that approach!

**Review by wurbanski — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
