### PR TITLE
splits rbac generator into two controllers

### LINKED ISSUE #2929: Refactor RBAC Generator controller
**Description** The controller actually consists of many more controllers, at the time of writing there are three. To improve readability the controller could be split up.

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**:simply splits `rbac generator` into two controllers

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2929 

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold

I want to test it before merging.

**Review by zreigz — APPROVED** [review]
looks clear for me
/lgtm

**Pull request merged**
