### PR TITLE
Respect nodelocal-dns configuration in kubelet-configmap addon

### LINKED ISSUE #4967: put node-local DNS address into the kubelet dynamic config maps
**User Story**
A user is working exclusively with kubeadm clusters, which are using dynamic kubelet configuration from addon `kubelet-configmap`. The field `clusterDNS` within that map does not respect the node-local DNS setting.

**Acceptance criteria**
- [ ] When the `nodelocal-dns-cache` addon is enabled, its address is filled in the `clusterDNS` field in `kubelet-configmap` addon

### PR DESCRIPTION
**Pull request by moelsayed**
**What this PR does / why we need it**:
Respect `nodelocal-dns` configuration in `kubelet-configmap` addon
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4967

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by irozzo-1A — APPROVED** [review]
LGTM

**Review by kron4eg — APPROVED** [review]
/lgtm

**Pull request merged**
