### PR TITLE
Implements HTTP endpoints for ssh keys of a cluster

### LINKED ISSUE #1372: Write endpoint to manage cluster ssh keys
Write endpoints to:
- List ssh keys of a cluster
- Assign a ssh key to a cluster
- Remove a ssh key from a cluster

The endpoint should be implemented for the project/user-management implementation.
No need to also cover the old way

child of #966

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: Implements HTTP endpoints for ssh keys of a cluster

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1372

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
I haven't implemented "delete" endpoint, wasn't sure about the use case ?

Also maybe we should detach the keys when the cluster is actually removed ?

**Comment by mrIncompetent** [comment]
> I haven't implemented "delete" endpoint, wasn't sure about the use case ?

If a member of a team leaves the company, you don't want this ssh key to be deployed into the nodes.
"Delete" in this case means removing the relation between the cluster and the key.

> Also maybe we should detach the keys when the cluster is actually removed ?

Yes. We're missing the cleanup since ages... I guess we could do it inside the delete-cluster endpoint?
I would like to avoid moving this behavior into the cluster-controller. The controller has nothing todo with ssh-keys at the moment


Awesome work!

**Comment by p0lyn0mial** [comment]
> Yes. We're missing the cleanup since ages... I guess we could do it inside the delete-cluster endpoint?

Yes :)

> If a member of a team leaves the company, you don't want this ssh key to be deployed into the nodes.
"Delete" in this case means removing the relation between the cluster and the key.

sgtm

**Review by mrIncompetent — APPROVED** [review]

**Comment by p0lyn0mial** [comment]
I will follow up the remainders. 

Thanks for the review.

**Comment by mrIncompetent** [comment]
@p0lyn0mial This PR seems to have introduced a flakey test:
`TestListSSHKeysAssignedToClusterEndpoint`

Affected builds so far:
https://drone.loodse.com/kubermatic/kubermatic/1897/10
https://drone.loodse.com/kubermatic/kubermatic/1881/10

**Comment by p0lyn0mial** [comment]
thanks for letting me know.

**Pull request merged**
