### PR TITLE
Avoid re-creating addon resources when cluster was deleted

### LINKED ISSUE #3488: Make addon-controller ignore clusters with deletion timestamp
**User Story**
Currently when cluster is being deleted addons-controller constantly recreated resources back and cloud resources that was created from addons end up orphaned (LBs/PVs).

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Otherwise addons may re-create LB/PV resoruces we are trying to cleanup

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3488

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

/assign @mrIncompetent 
/CC @kron4eg

### CODE REVIEW

**Comment by kron4eg** [comment]
@alvaroaleman should this be cherrypicked into `release/v2.10`?

**Review by kron4eg — COMMENTED** [review]
/lgtm
/approve

**Comment by alvaroaleman** [comment]
Yes it should.

/cherrypick release/v2.10
/retest

**Comment by alvaroaleman** [comment]
/override pull-kubermatic-lint

When going to the lint job result, it shows as passed but is still pending here

**Pull request merged**
