### PR TITLE
Use secrets for credentials for Azure 

### PR DESCRIPTION
**Pull request by nikhita**
Follow up of https://github.com/kubermatic/kubermatic/pull/3836
/hold

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zreigz** [comment]
everything works fine :)
/approve

**Comment by nikhita** [comment]
/test pull-kubermatic-e2e-azure-coreos-1.15

Looks like a flake, was green before

**Comment by nikhita** [comment]
Test is green.

/hold cancel

Needs lgtm label.

**Pull request merged**
