### PR TITLE
Fix go.sum after machine-contoller upgrade

### PR DESCRIPTION
**Pull request by irozzo-1A**
**What this PR does / why we need it**:
Fix build

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by xrstf — APPROVED** [review]
/approve

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by xrstf** [comment]
You got merge-sniped by #6132.

**Pull request closed without merging**
