### PR TITLE
Define PDB for Elasticseasrch

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This attempts to stabilize the ES cluster on systems with premtible nodes by forbidding too many unavailable nodes.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
GKE preemption has nothing to do with EvictionAPI. It just kills the whole node, after 30 seconds after initial signal. https://cloud.google.com/compute/docs/instances/preemptible#preemption_process

What I mean is — this change wouldn't help preemptive nodes in no way.

**Comment by xrstf** [comment]
You are slightly wrong. On *our* GKE setups we have Henrik's [preemtible-manager](https://github.com/kubermatic/infra/tree/master/apps/preemtible-manager), which drains and then deletes all nodes that are older than 6 hours. Having a PDB will make sure that when it's draining the second node, this will hang/wait until the just killed ES pod is rescheduled.

**Comment by kron4eg** [comment]
Didn't know about preemtible-manager, that changes the game completely.

/shrug
/lgtm
/approve

**Pull request merged**
