### PR TITLE
Upgrade Anexia CCM to v1.5.3

### PR DESCRIPTION
**Pull request by marioreggiori**
**What this PR does / why we need it**:
Upgrade Anexia CCM to v1.5.3.

**What type of PR is this?**
/kind cleanup
/kind feature

**Special notes for your reviewer**:
Release notes: https://github.com/anexia-it/k8s-anexia-ccm/releases/tag/v1.5.3

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update Anexia CCM (cloud-controller-manager) to version 1.5.3
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/test pre-kubermatic-e2e-anexia-flatcar-1.25

**Comment by ahmedwaleedmalik** [comment]
@marioreggiori for backports you can also leave a comment in the `Special notes for your reviewer` section. In general, backporting it to 2.21 means that we should backport it to 2.22 as well.

**Comment by marioreggiori** [comment]
Will do in the future :+1: thanks!

**Pull request merged**
