### PR TITLE
Add EventRateLimit admission plugin configuration

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
This adds support for the `EventRateLimit` admission plugin. It adds a configuration API to `Cluster` resources to set it up. The addition of this plugin to the list of supported plugins is driven by security benchmarks recommending the usage of it.

The `EventRateLimit` plugin allows configuring several buckets that limit admission of `Events` generated within the cluster, to make sure no excessive event generation overwhelms the Kubernetes API. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/edgematic/issues/51

**Special notes for your reviewer**:

- I tried to add this to the kubermatic-api, I'm just not sure I found every instance of it. Please check that :-)

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Support for configuring the EventRateLimit admission plugin
```

Signed-off-by: Marvin Beckers <marvin@kubermatic.com>

### CODE REVIEW

**Review by kron4eg — COMMENTED** [review]
/approve

**Comment by embik** [comment]
@maciaszczykm thanks for reviewing, unfortunately I had to bump the chart version since `master` changed. Can you please lgtm again? Thanks!

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
