### PR TITLE
Anexia: fix args for conformance tests

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What does this PR do / Why do we need it**:

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/test pre-kubermatic-e2e-aws-ubuntu-1.24-ce

Pod was not scheduled

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
