### PR TITLE
Scrape cAdvisor metrics for user clusters & disable the graceful termination of Prometheus

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Scrape cAdvisor metrics for user clusters & disable the graceful termination of Prometheus

**Does this PR introduce a user-facing change?**:
```release-note
cAdvisor metrics are now being scraped for user clusters
```

### CODE REVIEW

**Review by alvaroaleman — COMMENTED** [review]
Why disable the graceful termination? Doesn't that increase the risk of a broken tsdb?

**Comment by mrIncompetent** [comment]
> Why disable the graceful termination? Doesn't that increase the risk of a broken tsdb?

We use an emptyDir for storage

**Comment by mrIncompetent** [comment]
/hold 
i screwed up the yaml formatting

**Pull request merged**
