### PR TITLE
Backup credentials api

### LINKED ISSUE #7573: Backups - Add endpoints  for create/update backup s3 credentials

### PR DESCRIPTION
**Pull request by lsviben**
**What this PR does / why we need it**:
Adds API endpoint for creating/updating backup credentials

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7573 

**Does this PR introduce a user-facing change?**:

```release-note
Added API endpoint for creating/updating S3 backup credentials per Seed.
```

### CODE REVIEW

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Comment by xrstf** [comment]
/hold

temporarily

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
