### PR TITLE
Add comments to default k8s versions

### PR DESCRIPTION
**Pull request by imharshita**
Signed-off-by: Harshita sharma <harshita.sharma6174@gmail.com>

**What does this PR do / Why do we need it**: Add comments to default k8s versions

**Does this PR close any issues?**:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by xrstf** [comment]
Wait, wasn't the plan that we only have to maintain minor releases for external providers? Now we suddely have to keep up with all their patch releases as well?

In any case, please put a link in the code to the source wher you got that list from, regardless whether it's just minor versions or full versions.

**Comment by imharshita** [comment]
> Wait, wasn't the plan that we only have to maintain minor releases for external providers? Now we suddely have to keep up with all their patch releases as well?
> 
> In any case, please put a link in the code to the source wher you got that list from, regardless whether it's just minor versions or full versions.

Yes the plan was to keep only major.minor versions but , it's not working out for aks.
for EKS its completely all right.
These is a temporary change.
I am working on fetching the list by making an api call to `GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/{location}/orchestrators?api-version=2019-08-01
`
Doc: https://docs.microsoft.com/en-us/rest/api/aks/container-services/list-orchestrators?tabs=HTTP#orchestratorversionprofile

But it is not straightforward.
1. First, we need to fetch an authorization token using OAuth Authorization.
2. then we need to make a rest API call to get the list, then filter it out.

2nd is easy. 1. is something which I have not done before.
So, we have 2 options, either we wait till I figure it out and create a PR. (i will try asap)
or we keep this list till with major.minor.patch versions (only for aks) till I push my changes.
wdyt?

sorry for changing the plan, my bad.

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
