### PR TITLE
do not add finalizers when cluster is unhealthy

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: when deletion of a cluster was requested and the cluster is unhealthy additional finalizers (if requested) for volumes and/or load balancers removal will not be added.

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
if we decide to merge this pull then we can close https://github.com/kubermatic/kubermatic/pull/2799

**Comment by alvaroaleman** [comment]
@p0lyn0mial I am actually starting to think that it would be better to implement this in the controller instead. Any thoughts on that?

**Comment by p0lyn0mial** [comment]
@alvaroaleman may I know what have you decided ? Do you want to merge one of the two pull we have prepared ?

**Comment by alvaroaleman** [comment]
@p0lyn0mial I havent decided anything at all, my thinking right now is:

> @p0lyn0mial I am actually starting to think that it would be better to implement this in the controller instead. Any thoughts on that?

WDYT?

**Comment by p0lyn0mial** [comment]
I assume you are referring to controller manager, if only we could display cluster events that would be awesome, otherwise the end users may not know why a cluster is pending deletion. In fact this is no different from knowing for example why a cluster wasn't fully initialised. I think that in the near future we will add an endpoint for retrieving the events and we will adjust the dashboard.

**Comment by alvaroaleman** [comment]
> I assume you are referring to controller manager

Yes

> if only we could display cluster events that would be awesome, otherwise the end users may not know why a cluster is pending deletion. In fact this is no different from knowing for example why a cluster wasn't fully initialised. I think that in the near future we will add an endpoint for retrieving the events and we will adjust the dashboard.

I agree, events in the UI will be a big step forward. But it doesn't really have anything to do with the decision weather the API or the controller should take care of handling the case that is causing issues here?

Do you think the check is better placed in the API or in the controller? IMHO its the controller, otherwise we distribute the special case handling in a weird way among different binaries

**Comment by p0lyn0mial** [comment]
> Do you think the check is better placed in the API or in the controller?

Yes, I agree. It would be better if the check was in the controller.
Will you add it ? Can we close the pulls ?

**Comment by alvaroaleman** [comment]
> Will you add it ? Can we close the pulls ?

Yes, will do. Thanks for your effort anyways, thought!

**Pull request closed without merging**
