### PR TITLE
Change KonnectivityEnabled flag to a pointer to make defaulting easier

### PR DESCRIPTION
**Pull request by mate4st**
**What this PR does / why we need it**:

Change KonnectivityEnabled flag to a pointer to make defaulting easier.

```release-note
Change KonnectivityEnabled flag to a pointer in ClusterNetworkingConfig to make defaulting easier.
```

### CODE REVIEW

**Comment by rastislavs** [comment]
@PratikDeoghare PTAL - @WeirdMachine originally wanted to enable Konnectivity by default, but then we decided to just change the `KonnectivityEnabled` flag to a pointer to make defaulting easier and rely on default cluster templates for enabling Konnectivity default until we finish all Konnectivity tasks.

**Review by PratikDeoghare — APPROVED** [review]

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
