### PR TITLE
Fix: scrape annotations in s3-exporter must not be labels but annotations

### PR DESCRIPTION
**Pull request by bashofmann**
**What this PR does / why we need it**: Fix: scrape annotations must not be labels but annotations

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by xrstf** [comment]
<strike>Two brains one thought, this has just been fixed in #1823.</strike>

**Comment by bashofmann** [comment]
This is s3-exporter not nginx-ingress-controller

**Comment by xrstf** [comment]
Oh I'm terribly sorry, I must have overlooked that small but significant detail. :-/

**Comment by bashofmann** [comment]
No worries, I could've made this more obvious in the PR title to begin with

**Review by xrstf — APPROVED** [review]

**Pull request merged**
