### PR TITLE
Add config option for kube-proxy mode to cluster CR

### LINKED ISSUE #3935: Add configoption for kube-proxy mode (iptables/ipvs) to the cluster CR
**User Story**

As an operator of Kubermatic I want to configure the default kube-proxy mode

**Acceptance criteria**
* There is a field on the cluster that indicates the kube-proxy mode
* There is a migration that sets it to `iptables` if its empty
* There is a configoption in the API that allows to configure the default for the field for new cluster
* The configoption defaults to `ipvs`

### PR DESCRIPTION
**Pull request by nikhita**
Fixes https://github.com/kubermatic/kubermatic/issues/3935

Defaults to ipvs, if not specified.

For older clusters, they are migrated with proxy mode set to iptables
since that was the one used before.

**Does this PR introduce a user-facing change?**:

```release-note
The kube-proxy mode (ipvs/iptables) can now be configured. If not specified, it defaults to ipvs.
```

### CODE REVIEW

**Comment by nikhita** [comment]
```
 --- FAIL: TestRetagImageForAllVersions (0.71s)
    main_test.go:31: Error calling getImagesForVersion: failed to get images from addons: failed to get images for addon kube-proxy: failed to parse addon templates in ../../../addons/kube-proxy: failed to execute templating on file ../../../addons/kube-proxy/configmap.yaml: template: configmap.yaml:42:21: executing "configmap.yaml" at <.Cluster.Address.ProxyMode>: can't evaluate field ProxyMode in type v1.ClusterAddress
    main_test.go:31: Error calling getImagesForVersion: failed to get images from addons: failed to get images for addon kube-proxy: failed to parse addon templates in ../../../addons/kube-proxy: failed to execute templating on file ../../../addons/kube-proxy/configmap.yaml: template: configmap.yaml:42:21: executing "configmap.yaml" at <.Cluster.Address.ProxyMode>: can't evaluate field ProxyMode in type v1.ClusterAddress
    main_test.go:31: Error calling getImagesForVersion: failed to get images from addons: failed to get images for addon kube-proxy: failed to parse addon templates in ../../../addons/kube-proxy: failed to execute templating on file ../../../addons/kube-proxy/configmap.yaml: template: configmap.yaml:42:21: executing "configmap.yaml" at <.Cluster.Address.ProxyMode>: can't evaluate field ProxyMode in type v1.ClusterAddress
    main_test.go:31: Error calling getImagesForVersion: failed to get images from addons: failed to get images for addon kube-proxy: failed to parse addon templates in ../../../addons/kube-proxy: failed to execute templating on file ../../../addons/kube-proxy/configmap.yaml: template: configmap.yaml:42:21: executing "configmap.yaml" at <.Cluster.Address.ProxyMode>: can't evaluate field ProxyMode in type v1.ClusterAddress 
```

I'm guessing this part needs to be updated after the PR is merged so the image is updated too:

https://github.com/kubermatic/kubermatic/blob/ad381253808932a13e03b71f1123e3daf0d7015b/addons/kube-proxy/configmap.yaml#L42

**Comment by alvaroaleman** [comment]
@nikhita You also need to set that in `addons/kube-proxy/configmap.yaml`, else this setting has no effect

**Comment by nikhita** [comment]
/retest 

now that the image was actually updated

**Comment by alvaroaleman** [comment]
@nikhita I think the issue is that the addon references `.Cluster.Address.ProxyMode` which doesn't exist, its in `.Cluster.Spec.ClusterNetwork` or sth

**Comment by nikhita** [comment]
All green! :)

**Comment by alvaroaleman** [comment]
Just wanna quickly verify this works on all distributions, other than that, lgtm
/test pull-kubermatic-e2e-do-centos-1.15
/test pull-kubermatic-e2e-hetzner-ubuntu-1.15

**Pull request merged**
