### PR TITLE
Fix Cluster Backup feature not getting enabled

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
In #13807 we refactored the new Cluster Backup feature. This was done because the old implementation was not able to handle multiple seeds. However during that refactoring I also overlooked some aspects and so #13807 fixed one half ot the feature but broke the other half.

Right now, without any fixes, enabling the Cluster Backup feature on a usercluster will simply not do anything.

This is because the velero-controller now runs in the user-cluster-controller-manager. Importantly, this controller-manager does _not_ use `cluster-admin` permissions, but has actual RBAC restrictions. And the ctrl-mgr simply has no permissions to get ClusterBackupStorageLocations (CBSLs) out of the `kubermatic` namespace. Neither does it have permissions to fetch the associated credential Secret for the CBSL. And the velero-controller was written to just log a message on the debug level and then do nothing.

Additionally, besides permission issues, the controller-runtime cache was not configured to cache anything outside of the cluster namespace. So even if permissions worked, it would have been impossible to actually retrieve the CBSL.

To fix this, I added yet another controller, this time running in the seed-controller-manager. This new `rbac-controller` is responsible for creating/removing the Role/RoleBinding in the `kubermatic` namespace, necessary for each user-cluster-ctrl-mgr.

Once the RBAC is in place, I reconfigured the seed Manager to allow caching of some objects in the `kubermatic` namespace. After speaking with @embik we decided to restrict permissions even further and allow to only access a single CBSL and its Secret. This meant tightening the generated Role, but also that the user-cluster-ctrl-mgr needs to know the CBSL/Secret names upon boot up already.

This made it necessary to inject these names via command-line flags. These new flags are now set by the seed-controller-manager.

Additionally, the old velero-controller was fixed to issue the event, in case something goes bad, on the _seed cluster_, not the _user cluster_, where the event is basically lost and forgotten. Also, the controller used a client that never loaded the velero APIs, so it was never actually able to provision Velero resources inside the user cluster.

Lastly there is a small cleanup in this PR that removes an unused leftover velero-kubeconfig volume from the Velero deployment. It didn't prevent the Velero Pods from running, but was just confusing. It's a leftover from #13010 when Velero was (IMHO for insufficient reasons) moved from the seed to the user cluster.

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Fix Cluster Backup feature not provisioning Velero inside user clusters.
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by judge-red** [comment]
Sorry, this isn't really the right place for this, but not sure what would be the best place. I just can't stop wonder: why isn't Velero deployed as a system application like Cilium is? I guess the BSL, schedules, etc. would still need to be deployed through other means, but still. Deploying the Velero with the Helm chart through an application would also make the values editable, so end users could tweak it to their needs beyond what can be configured in the CBSL, schedules, etc.

But my understanding of the SC<>UC relationship, all the controllers, and the whole code base here is very, very, very limited, I'm just a systems engineer and KKP admin :) If I sputter total nonsense, don't waste your time explaining everything to me - I trust you do know better for real - but maybe this wasn't considered before or should be reconsidered, so I wanted to add my 5c.

**Comment by xrstf** [comment]
> why isn't Velero deployed as a system application like Cilium is?

I  guess because originally Velero was running on the _seed_, where IMHO it should also be moved to again. Right now if your cluster is dead and Velero cannot run, you cannot restore a previous backup. From what I heard the main focus of the Velero integration is _volume_ snapshots, which require functioning node-agents anyway, but IMHO it's still unfortunate that resource backups also require a working cluster.

Enforced applications were also not a thing when this feature was originally implemented.

As much as it looks like it, we do not all enjoy hand-translating Helm outputs into Go code, and over time we want to move more towards Helm-based installations (using Argo or flux internally), but that's far out of scope for this PR, which should just quickly and urgently bring the feature back to life.

**Review by embik — APPROVED** [review]
/approve

**Pull request merged**
