### PR TITLE
Fix swagger.json

### PR DESCRIPTION
**Pull request by nikhita**
pull-kubermatic-verify is failing on master right now. Not sure how this didn't get caught earlier...

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @zreigz

### CODE REVIEW

**Comment by maciaszczykm** [comment]
/lgtm
/approve

The job `...-verify` says otherwise. I think the check may be flaky, switching its results from time to time :/

**Comment by nikhita** [comment]
Yeah, running update-swagger again flips the results :flushed:

**Comment by zreigz** [comment]
it seems that the swagger verify became flaky, it's not related with API client but with swagger itself

**Comment by zreigz** [comment]
@nikhita @maciaszczykm I will take a look and try to fix this

**Comment by zreigz** [comment]
i forgot regenerate api client

**Comment by zreigz** [comment]
seems to work right now. Let's try one more time

/test pull-kubermatic-verify

**Pull request merged**
