### PR TITLE
conformance-tests: bump k8s versions

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

This PR bumps Kubernetes versions used for the conformance tests binaries to the latest ones.

**Special notes for your reviewer**:

I don't have permissions to push to Docker Hub, so someone will have to do that for me.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Did you publish the image? Could you also bump the versions in:

* config/kubermatic/static/master/versions.yaml
* The infra repo for both this image here and the kube version in the 1.16 job

**Comment by xmudrii** [comment]
@alvaroaleman Done, PTAL. The image is still not pushed. I think I have access to our Docker Hub account. I created a PR in the infra repo to update jobs and versions https://github.com/kubermatic/infra/pull/620

**Comment by xmudrii** [comment]
@alvaroaleman It seems like this is going to conflict with PRs @kdomanski opened. Should I just update the image and leave @kdomanski to update `versions.yaml`?

**Comment by xmudrii** [comment]
@alvaroaleman PTAL. I've reverted changes I made to `config/kubermatic/static/master/versions.yaml` because it seems like PRs @kdomanski created covered those changes. I've updated the manifests in the infra repo and that PR is already merged.

**Pull request merged**
