### PR TITLE
Use autodetection for openstack bs version

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
This PR enables the automatic detection of the BlockStorage API version for OpenStack clusters according to https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#block-storage

Blocked by https://github.com/kubermatic/machine-controller/pull/480

**Release note**:
```release-note
Enable automatic detection of the OpenStack BlockStorage API version within the cloud config
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@mrIncompetent Why does this require kubermatic/machine-controller#480 ?

**Comment by mrIncompetent** [comment]
@alvaroaleman 

> @mrIncompetent Why does this require kubermatic/machine-controller#480 ?

Because we would otherwise deploy the control plane with "auto" & the kubelets would use v2 (As it was hardcoded).
This will lead to differences in environments where v3 is available.

**Pull request merged**
