### PR TITLE
Update label usage for cAdvisor metrics

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
In Kubernetes 1.14 the label names `pod_name` and `container_name` in cAdvisor metrics [have been renamed to `pod` and `container`](https://github.com/kubernetes/kubernetes/pull/69099). The old labels were still available until they were [removed in 1.16](https://github.com/kubernetes/kubernetes/pull/80376).

This PR updates all of our Prometheus/Grafana stuff to work exclusively with the new label names (`pod` and `container`). Support for 1.14 has recently been dropped in #4987.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

let me install this manually at least once to see if i made a typo somewhere

**Comment by xrstf** [comment]
/hold cancel

I re-purposed the PR to only forward-adjust for 1.16, as we dropped 1.14 support today.

**Review by kron4eg — APPROVED** [review]
/lgtm 
/approve

**Pull request merged**
