### PR TITLE
default the fieldPath of a Seed's kubeconfig objectRef to 'kubeconfig'

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Kubeconfig Secrets have commonly a single key `kubeconfig`. Our code so far expected this to be explicitly configured in a Seed's objectRef, and failed with a bad error message when no fieldPath was set. We never noticed because we auto-migrated the datacenters.yaml and that creates a fully-spec'ed objectRef.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]

**Comment by kdomanski** [comment]
cc @xrstf

**Pull request merged**
