### PR TITLE
better slack templates for alerts

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This PR changes the Slack notifications for alerts.

* Alerts are not grouped anymore, because that made creating good-looking Slack messages extremely hard.
* We have a proper fallback text for mobile notifications.
* Each single alert takes up less space in Slack.

Old:

screenshot_2019-01-18_10-38-47

New:

screenshot_2019-01-18_10-38-26

Customers not using our templates and instead use the defaults will not notice any changes, hence the empty changelog entry.

We require the current beta version from Alertmanager because they added the `match` template function, which makes it possible to match on the seed cluster name and display fancy flags without hardcoding the seed cluster names into the template. A stable 0.16.0 is supposed to be released next week (prometheus/alertmanager#1714).

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
/lgtm
Alerts now look nice :heart_eyes: 

Should we document switch to Alertmanager 0.16.0 somehow or only when we switch to a stable version?

**Comment by xrstf** [comment]
I would document it with the coming PR when we update to 0.16.0 -- should happen before we cut 2.9.

**Comment by mrIncompetent** [comment]
@xrstf This does not work dev. The alertmanager pod is crashing with:
```
Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="template: kubermatic.tmpl:10: function \"match\" not defined"
```

**Pull request merged**
