### PR TITLE
Upgrade machinecontroller to v1.30.0

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Upgrade machinecontroller to v1.30.0
```

### CODE REVIEW

**Review by moadqassem — APPROVED** [review]
/approve 
/lgtm

**Comment by kron4eg** [comment]
> /cherrypick release/v2.17

it's already in the 2.17

**Pull request merged**
