### PR TITLE
new endpoint to get Anexia templates

### LINKED ISSUE #6891: Add a new endpoint to get Anexia templates

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: new endpoint to get Anexia templates

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6891

```release-note
NONE
```

### CODE REVIEW

**Review by kgroschoff — COMMENTED** [review]
/lgtm

Will create ui issue

**Comment by zreigz** [comment]
@kgroschoff I had to rebase PTAL

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Pull request merged**
