### PR TITLE
define alert for containers that have been OOMKilled

### LINKED ISSUE #2259: add alerts for OOMKilled pods
**User Story**
As a user I'd like to get alerted when my pods (and especially the critical components of Kubermatic) are getting OOMKilled. 

A pod metric for that has been recently introduced in `kube-state-metrics` and we can set up an alert on it as soon as it makes it into a release. https://github.com/kubernetes/kube-state-metrics/commit/5119063031ef8fbefeedcef4fbba2f8578cce719

**Acceptance criteria**
 - [ ] an Alert is triggered whenever a pod is OOMKilled

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Alert on containers that have been OOMKilled at least twice in the last 30 minutes. The implementation is based on https://github.com/kubernetes/kube-state-metrics/pull/535#issuecomment-446682139.

**Which issue(s) this PR fixes**:
Fixes #2259

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
/lgtm

I guess we may also need to update documentation and add a `runbook_url` in a follow-up

**Comment by xrstf** [comment]
Our runbooks are so horribly out-of-date it's not even funny anymore. :-/

**Pull request merged**
