### PR TITLE
External Cluster(EKS): Support for assume role

### LINKED ISSUE #11040: External Clusters - EKS cluster should support asume role
As feedback from a customer call. The asume role function of AWS is a must have for them to take this in consideration. As I see from other customer use cases as well, I think this is needed in a same way as "normal cluster" in AWS could be created.

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:
Support for using assume role for EKS external clusters.

**Which issue(s) this PR fixes**:

Fixes #11040

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
External clusters on EKS now support assume role.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/retest
Just vSphere things.

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
