### PR TITLE
ensure no clashes with top-level keys in values.yaml

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
Some of our charts use their top-top-level directory inside their values.yaml, like the logging charts. This leads to us creating a broken example values.yaml because we have the same top-level keys multiple times.

This PR extends the sync-charts.sh script to filter the YAML line by line and keep track of known top-level keys. This works under the assumption that charts with the same top-level key are added one after another with no gaps to the values.yaml.

For the next point release (i.e. 2.10) of Kubermatic we should instead fix the charts, but this would be too much for a bugfix release in the 2.9 branch.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/shrug

What do you think about changing the publishing to

a )just render a concatenated `values.examples.yaml` inside this repo and add a presubmit that ppl dont forget
b) Publish the results post-merge?


That way we can like see the generated file and spot mistakes, right now its more like "I think this will do the right thing"

**Comment by xrstf** [comment]
I would much rather spend time fixing the charts than building larger hacks around them.

**Comment by alvaroaleman** [comment]
> I would much rather spend time fixing the charts than building larger hacks around them.

Sure. What I meant is: We currently can only review the scripts that generate these charts but not the result of that generation. IMHO it would make sense to version the result of that generation inside this repo so we can check if it matches our expectations.

I am pretty sure if we had had that already we would have noticed the issue with the duplicate top level keys ourselves.

**Pull request merged**
