### PR TITLE
add possibility to configure if terms of service should be displayed

### PR DESCRIPTION
**Pull request by kgroschoff**
**What this PR does / why we need it**:
This PR adds the possibility to configure if terms of service should be displayed, related to this frontend PR:  https://github.com/kubermatic/dashboard-v2/pull/830

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
/

**Special notes for your reviewer**:
/

**Documentation**:

**Release note**:
```release-note
Displaying the terms of service can now be toggled in values.yaml
```

### CODE REVIEW

**Review by p0lyn0mial — APPROVED** [review]
will you also change a value file in the secret repo so that it's on in cloud ?

**Comment by kgroschoff** [comment]
I guess if @mrIncompetent is ok with that I could do it, yes.

**Comment by p0lyn0mial** [comment]
> I guess if @mrIncompetent is ok with that I could do it, yes.

oh, I thought that displaying terms of use in cloud is a requirement. We don't have to show it if there is no need.

**Review by mrIncompetent — APPROVED** [review]

**Comment by mrIncompetent** [comment]
sgtm @kgroschoff can you file an issue to figure out, how to make the terms configurable? 
So the text to display

**Pull request merged**
