### PR TITLE
Update cert-manager to 1.2.0

### LINKED ISSUE #6593: Upgrade of cert-manager to v1 CRDs
**User Story**

To integrate with a customer setup we need quickly to support the `cert-manager.io/v1` CRDs.
As Jetstack finally released a `v1` version of there CRDs the current helm chart needs to get updated. Also the operator and potential all other controllers need to support it.

As the upgrade of version `0.16` to `1.x` seems not to have special requirements, besides of the new CRD version. We would only need to take care that our helm chart reflects the newest version and provide a guide how to update the CRD versions.
https://cert-manager.io/docs/installation/upgrading/

**Acceptance criteria**
- [ ] KKP can work with cert-manager version v1
- [ ] helm charts are updated
- [ ] KKP operator and controllers support version v1
- [ ] Upgrade procedure is documented and tested

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This PR performs a long overdue update on the cert-manager. Now that all other charts in the KKP stack do not use `Certificate` resources directly, but instead only set annotations on Ingress objects, the migration from v1alpha2 to v1 is easier to accomplish.

Unfortunately, a clean migration is not possible without excessive amounts of migration code. We not just bump to v1, but we also switch to the "non-legacy" CRDs. Just applying these over the older legacy CRDs does not work.

The migration is therefore:

```bash
helm -n cert-manager delete cert-manager

# do not delete by `kubectl delete -f crd/cert-manager.crds.yaml`,
# as these might be the new CRDs when you downloaded the new KKP release
kubectl delete crd certificaterequests.cert-manager.io
kubectl delete crd certificates.cert-manager.io
kubectl delete crd challenges.acme.cert-manager.io
kubectl delete crd clusterissuers.cert-manager.io
kubectl delete crd issuers.cert-manager.io
kubectl delete crd orders.acme.cert-manager.io

# remove all finalizers from all stuck resources

# do not continue unless _all_ cert-manager CRDs are gone from the cluster

# just in case Helm orphaned these
kubectl delete validatingwebhookconfigurations cert-manager-webhook
kubectl delete mutatingwebhookconfigurations cert-manager-webhook

# install new CRDs
kubectl apply -f charts/cert-manager/crd/cert-manager.crds.yaml

# install fresh chart
helm3 -n cert-manager install cert-manager charts/cert-manager/
```

This PR also introduces a super simple mechanism to run "integration tests" on Helm charts. Since we got rid of the canary-ci-deployment job, we were left without any real tests and it will probably take some more time before we can have really fancy kind-based tests.

**Which issue(s) this PR fixes**:
Fixes #6593

**Does this PR introduce a user-facing change?**:
```release-note
**ACTION REQUIRED:** Update cert-manager to 1.2.0
```

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

1.2.0 is already out. Didn't see that one.

**Comment by kron4eg** [comment]
@xrstf I suggest to edit the title and release note to make it super clear that this is ACTION-REQUIRED change.

**Comment by xrstf** [comment]
Assuming the next PR will automate the migration, but sure..

**Review by kron4eg — COMMENTED** [review]
/hold

to let other people see it

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
