### PR TITLE
Remove support for Kubernetes 1.25 (EOL 2023-10-28)

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
As was discussed on sig-release, Kubernetes 1.25 support should be removed in KKP 2.24 (ref: https://github.com/kubermatic/machine-controller/pull/1709, https://github.com/kubermatic/operating-system-manager/pull/312) before the release.

Because KKP 2.23 still supported both Kubernetes 1.24 and 1.25 and we are dropping support for both of them, reconcile logic for **both** versions (e.g. image selections, addon conditionals, etc) need to stay in so KKP can continue to reconcile clusters prior to upgrading them (basically just during the mixed-version transition of upgrading KKP; it's a small window, but we want to keep our users safe).

This PR explicitly drops 1.24 and 1.25 from the support AND upgrade matrix. This means that prior to upgrading KKP 2.23 to 2.24, all user clusters need to be upgraded to 1.26 or 1.27. I prefer this explicit upgrade requirement over implicitly upgrading all user clusters once KKP 2.24 has been rolled out, because it gives KKP admins control over when upgrades happen, but I'm open to changing this if that is not the popular opinion.

This PR also drops:
- OpenStack CCM migration tests - The CCM migration cannot run on Kubernetes 1.26 or higher, because `>= 1.25` is the cut-off for running with in-tree OpenStack CCM.
- Some unit tests for the validation webhook that test scenarios which involve 1.24 and 1.25, and do not make sense to be tested against higher versions.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind cleanup

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
- Remove support for Kubernetes 1.25
- User clusters require upgrading to Kubernetes 1.26 prior to upgrading to KKP 2.24
```

**Documentation**:

```documentation
https://github.com/kubermatic/docs/pull/1533
```

### CODE REVIEW

**Comment by embik** [comment]
/hold

integration tests won't succeed.

**Comment by xrstf** [comment]
/override pre-kubermatic-test-integration

Datacenter is down at the moment.

**Pull request merged**
