### PR TITLE
Add keepalive-time setting for Konnectivity

### PR DESCRIPTION
**Pull request by mfranczy**
**What this PR does / why we need it**:
Allows to discover broken connections earlier based on the time specifed in the setting (default 1m)

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add keepalive-time Konnectivity setting + set keepalive to 1m by default
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by mfranczy** [comment]
@PratikDeoghare @rastislavs I tested PR and it works well with the default value 1m. However something is wrong with overriding the default value in the seed config. I am not sure if it's my env or something is broken thus this should not land in the minor release this Friday. I have to find out what's wrong.

**Comment by rastislavs** [comment]
> @PratikDeoghare @rastislavs something is wrong with overriding the value in the seed config. I am not sure if it's my env or something is broken thus this should not land in the minor release yet. 

agree, no worries, let's not rush it

**Comment by rastislavs** [comment]
/hold cancel

I think the PR is now good to go. I tested manually and it seems to be working as expected:
 - the keepalive value from the `DefaultComponentSettings` is propagated properly for newly created clusters (not for existing, but that is how `DefaultComponentSettings` works)
 - for existing clusters the keepalive value from the cluster spec propagates properly

**Pull request merged**
