### PR TITLE
bump machine controller to v1.34.0

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
Bumping machine controller from v1.33.0 to v1.34.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by kron4eg** [comment]
@moadqassem you’ve forgot to update fixtures

**Comment by moadqassem** [comment]
> @moadqassem you’ve forgot to update fixtures

They are updated :)

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
