### PR TITLE
Add isDefault flag to the RuleGroup API

### LINKED ISSUE #8452: Add default flag for RuleGroups
We need to be able to distinguish rulegroup applied by admin and users rulegroup, for that we need to add `default` flag to rulegroup

### PR DESCRIPTION
**Pull request by rastislavs**
**What does this PR do / Why do we need it**:
Adds a flag indicating whether a RuleGroup is default (added by an admin).

This a a follow-up on the original PR: https://github.com/kubermatic/kubermatic/pull/8459

**Does this PR close any issues?**:
Fixes #8452

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
Add isDefault flag to the RuleGroup API
```

### CODE REVIEW

**Review by kgroschoff — COMMENTED** [review]
/lgtm

**Review by xrstf — APPROVED** [review]
/approve

**Pull request merged**
