### PR TITLE
Remove unused openshift code

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Removes all the `getMasterConfig` code from the openshift controller, it was being used with openshift 3.11, but with openshift 4.1.9, everything has its own config so its unused.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

/assign @nikhita

### CODE REVIEW

**Comment by nikhita** [comment]
Needs rebase :/

**Comment by alvaroaleman** [comment]
@nikhita updated, ptal

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Comment by alvaroaleman** [comment]
@nikhita had to fix merge conflicts again so I need another approval :grimacing:

**Pull request merged**
