### PR TITLE
Restore envoy.yaml in nodeport-proxy Docker image

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
#3830 made the nodeport-proxy easier to debug, but accidentally broke the envoy Pods inside user cluster namespaces by moving the configuration into a ConfigMap.

This PR reverts the ConfigMap part of the old PR.

**Does this PR introduce a user-facing change?**:
```release-note
Fix broken NodePort-Proxy for user clusters with LoadBalancer expose strategy.
```

/cherry-pick release/v2.12

### CODE REVIEW

**Comment by xrstf** [comment]
/cherrypick release/v2.12

Why oh why is it `git cherry-pick`, but `/cherrypick` in Prow... :-D

**Comment by alvaroaleman** [comment]
> Why oh why is it git cherry-pick, but /cherrypick in Prow... :-D

Both of them work.

**Comment by alvaroaleman** [comment]
@xrstf Could you manually set the expose strategy on a cluster to test this?

**Comment by xrstf** [comment]
Seems to work just fine in my test cluster.

**Pull request merged**
