### PR TITLE
Fetch kubeone error codes and message from logs

### LINKED ISSUE #9495: Incroporate KubeOne exitcode and KubeOne JSON log for error handling
### What would you like to be added? / User Story
- Incorporate KubeOne error exit codes for error handling in KubeOne Controller, to determine the error type which is then stored in external cluster CRD condition Phase https://github.com/kubermatic/kubeone/blob/a01b6a3e7ae82f239163b400140084e78e490c54/pkg/fail/exitcodes.go#L21-L29

- Fetch error message from kubeone pod JSON logs, which is then stored in external cluster CRD condition Message

### PR DESCRIPTION
**Pull request by imharshita**
Signed-off-by: Harshita sharma <harshita.sharma6174@gmail.com>

**What does this PR do / Why do we need it**:
- Fetch kubeone error codes from kubeone pod for a cluster management operations to determine the error type which is then stored in External cluster CRD.
- Also fetch the error message from kubeone json logs fetched from the pod logs and store it in the External cluster CRD.

**Special notes for your reviewer**:

**Does this PR close any issues?**:
Fixes #9495

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by imharshita** [comment]
kubeone pkg: "k8c.io/kubeone/pkg/fail" is not released yet, hence i importing @latestcommit

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve ⚡

**Pull request merged**
