### PR TITLE
Support deleting LoadBalancer services on cluster deletion

### LINKED ISSUE #1985: OpenStack clusters are not deleted properly when a LoadBalancer exists in the cluster
When we try to delete an OpenStack cluster that has a Service with the type "LoadBalancer", the cluster hangs at the `kubermatic.io/cleanup-openstack-network` finalizer because the cluster's network can't be deleted before the OpenStack loadbalancer including its pool, listener and security group are deleted.

Either the Service resource needs to be deleted manually before deleting the cluster (which will trigger Kubernetes to delete the LB resources in OpenStack), or the cluster creation logic needs to check for OpenStack resources that are attached to the network and clean these up as well.

### PR DESCRIPTION
**Pull request by bashofmann**
**What this PR does / why we need it**:

On OpenStack any LoadBalancer services need to be deleted on cluster
deletion, because otherwise the OpenStack network can not be deleted
since there is still a LoadBalancer, Security Group and Floating IP
attached to it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1985

**Special notes for your reviewer**:
I'm not quite sure, if I'm adding this logic in the right place. Especially using the constant in two different packages is not really nice.
 On the one hand it's fairly related to OpenStack, on the other hand, the function just talks with the Kubernetes API and may be also necessary or at least not hurting for other providers.

**Release note**:

```release-note
Delete OpenStack LoadBalancers on cluster deletion to prevent errors deleting the OpenStack network
```

### CODE REVIEW

**Comment by kdomanski** [comment]
I'd prefer to make the `deletingLoadBalancerServices` function provider-agnostic and instead check for the finalizer befor it's call in `cleanupCluster`. @alvaroaleman what do you think?

**Comment by alvaroaleman** [comment]
> I'd prefer to make the deletingLoadBalancerServices function provider-agnostic and instead check for the finalizer befor it's call in cleanupCluster. @alvaroaleman what do you think?

Yes, that would be perfect. Also the finalizer itself should be provider-agnostic

**Comment by mrIncompetent** [comment]
Please have a look at https://app.zenhub.com/workspaces/all-kubermatic--58863654794153994b62af76/issues/kubermatic/kubermatic/2448

It will be cloud provider agnostic and it is in our sprint.

**Comment by mrIncompetent** [comment]
@bashofmann We implemented the backend part in https://github.com/kubermatic/kubermatic/pull/2514
With the difference: We're not automatically adding the finalizer.

Can this PR be closed ?

**Comment by bashofmann** [comment]
@mrIncompetent Yes this can be closed then. Would be nice to have https://github.com/kubermatic/kubermatic/issues/2449 soon then.

**Pull request closed without merging**
