### PR TITLE
Supported providers fix

### PR DESCRIPTION
**Pull request by mlavacca**
Signed-off-by: Mattia Lavacca <lavacca.mattia@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]

**Review by kron4eg — COMMENTED** [review]
/approve

**Pull request merged**
