### PR TITLE
Reset .spec.values when migrating existing ApplicationInstallations

### LINKED ISSUE #13734: Forbidden: Only values or valuesBlock can be set, but not both simultaneously / Invalid value: "null": value is immutable
### What happened?

After upgrading to KKP 2.25.9, we see this Event in many UCs. It seems all UC using Cilium that existed before the upgrade are affected:

```
default              2m7s        Warning   ReconcilingError           cluster/nkfqdbmf8q                                              failed to ensure ApplicationInstallation kube-system/cilium: failed to update object *v1.ApplicationInstallation "kube-system/cilium": admission webhook "applicationinstallations.apps.kubermatic.k8c.io" denied the request: ApplicationInstallation validation request 4331e449-85f2-4d08-a932-2140f77b6707 denied: [spec.values: Forbidden: Only values or valuesBlock can be set, but not both simultaneously spec.valuesBlock: Forbidden: Only values or valuesBlock can be set, but not both simultaneously spec.values: Invalid value: "{\"certgen\":{\"podSecurityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}}},\"cni\":{\"exclusive\":false},\"hubble\":{\"relay\":{\"enabled\":true,\"podSecurityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}}},\"tls\":{\"auto\":{\"method\":\"cronJob\"}},\"ui\":{\"backend\":{},\"enabled\":true,\"frontend\":{},\"securityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}}}},\"ipam\":{\"operator\":{\"clusterPoolIPv4MaskSize\":\"24\",\"clusterPoolIPv4PodCIDRList\":[\"172.25.0.0/16\"]}},\"k8sServiceHost\":\"nkfqdbmf8q.os-zh.kaas.switch.ch\",\"k8sServicePort\":32561,\"kubeProxyReplacement\":\"strict\",\"operator\":{\"podSecurityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}},\"replicas\":1,\"securityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}}},\"podSecurityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}}}": unable to unmarshal values: the fields Values and ValuesBlock cannot be used simultaneously. Please delete one of them. spec.values.cni: Invalid value: "null": value is immutable spec.values.ipam: Invalid value: "null": value is immutable spec.values.kubeProxyReplacement: Not found: "null" spec.values.operator: Invalid value: "null": value missing or incorrect spec.values.operator.securityContext: Invalid value: "null": value is immutable]
```

One customer is reporting that connections are sporadically interrupted (not sure whether from or to the workload on the UC) but we can't be sure whether there's a connection.

### Expected behavior

No errors and no events.

### How to reproduce the issue?

Presumably:
- deploy KKP 2.25.8
- create UC with Cilium
- upgrade KKP to 2.25.9
- check UC for events

### How is your environment configured?

- KKP version: 2.25.9
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

N/A imho, let me know otherwise

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your user cluster?

Ubuntu 22.04

### Additional information

Probably related to #13276 which was backported to 2.25.9 (#13702) without any notice in the changelog, thus we missed checking for problems on staging before rolling this out on production :(

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:

When we added migration for `spec.values` to `spec.valuesBlock` in the Cilium CNI `ApplicationInstallation` (#13276), we unfortunately missed something crucial: The reconciler code works on the existing object. This means that fields of existing objects will remain set unless explicitly "nulled".

This is what I believe is happening now (and has been shipped in 2.25.9 as undocumented change) and is causing #13734: An `ApplicationInstallation` for Cilium gets reconciled, the migration code sets `spec.valuesBlock` - but doesn't reset `spec.values`, thus the final object handed to the client has _both_ fields set. This is invalid though, and the webhook rejects it.

**Which issue(s) this PR fixes**:

Fixes #13734

**What type of PR is this?**
/kind bug
/kind regression

**Special notes for your reviewer**:

**ONLY MERGE THIS ONCE IT'S BEEN VERIFIED TO WORK.**

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix failure to migrate Cilium `ApplicationInstallations` to new `valuesBlock` field
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
Reminder: The 2.25 release note needs to mention that this fixes an undocumented change in 2.25.9.

**Review by cnvergence — APPROVED** [review]
/approve

**Pull request merged**
