### PR TITLE
Upgrade Anexia CCM to v1.5.1

### PR DESCRIPTION
**Pull request by marioreggiori**
**What this PR does / why we need it**:
Upgrade Anexia CCM to v1.5.1.

**What type of PR is this?**
/kind bug
/kind regression

**Special notes for your reviewer**:
We would like to backport this change to v2.21 & v2.20 after this PR was accepted.

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update Anexia CCM (cloud-controller-manager) to version 1.5.1
```

**Documentation**:

```documentation
None
```

### CODE REVIEW

**Comment by xrstf** [comment]
/retest

CCM failures were unrelated to this PR.

**Comment by marioreggiori** [comment]
Is there anything I can do to help getting this merged? Is it okay for me to trigger retest?

**Comment by ahmedwaleedmalik** [comment]
/retest

@marioreggiori these failures are unrelated to your change so we'll take care of that.

**Comment by ahmedwaleedmalik** [comment]
Requires https://github.com/kubermatic/kubermatic/pull/11658 to be merged first.

**Review by xrstf — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
/override pre-kubermatic-test-integration

vSphere strikes again.

/override pre-kubermatic-mla-e2e

flaking

**Comment by ahmedwaleedmalik** [comment]
> Thanks for getting this merged 🚀 Would it be possible to cherry-pick the changes onto the v2.21 & v2.20 release branches, or should we create separate PRs for backporting?

I have created a backport for [2.21](https://github.com/kubermatic/kubermatic/pull/11692). Although for 2.20, it seems that you folks didn't backport the CCM changes as it's still on version `0.1.0` and requires more changes than just a version bump for image.

**Comment by marioreggiori** [comment]
> > Thanks for getting this merged rocket Would it be possible to cherry-pick the changes onto the v2.21 & v2.20 release branches, or should we create separate PRs for backporting?
> 
> @marioreggiori I have created a backport for [2.21](https://github.com/kubermatic/kubermatic/pull/11692). Although for 2.20, it seems that you folks didn't backport the CCM changes as it's still on version `0.1.0` and requires more changes than just a version bump for the image.

Thanks you for the manual backport to `v2.21` :+1:. Regarding `v2.20`: we haven't had that on our radar.. How long will this version be supported? Do you think it's still reasonable to bring it up-to-date?

**Comment by marioreggiori** [comment]
Sorry for the ping @ahmedwaleedmalik. A recommendation on whether or not we should update the Anexia Provider part of the `v2.20` release branch would be greatly appreciated.

**Comment by ahmedwaleedmalik** [comment]
Hi @marioreggiori

> How long will this version be supported?
It will be supported for 2 more minor releases, KKP 2.23 release is planned for May 2023. https://docs.kubermatic.com/kubermatic/v2.21/architecture/support-policy/

> Do you think it's still reasonable to bring it up-to-date?

It's reasonable to do that IMO. But it also depends on you folks. If you are already on KKP 2.21 then maybe it's adequate enough and you don't need to update 2.20.

**Pull request merged**
