### PR TITLE
v2 health endpoint

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: get health status for the cluster

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

```release-note
get health status for the cluster: GET /api/v2/projects/{project_id}/clusters/{cluster_id}/health
```

### CODE REVIEW

**Comment by xrstf** [comment]
@zreigz is this for 2.15?

**Comment by zreigz** [comment]
> @zreigz is this for 2.15?

It's for V2 endpoints, it can be used for 2.15 because it will be easier cherry-pick other commits. I can take care to add to 2.15 other V2 endpoints because it will solve problems with resolving the conflicts.

**Pull request merged**
