### PR TITLE
Add release validation document

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Adds a document that contains a minimal set of validations that must be executed prior to doing a release

**Special notes for your reviewer**:

If anything comes to mind that is missing right now, please point it out.

**Documentation**:

**Release note**:

```release-note
NONE
```

cc @kdomanski @mrIncompetent

### CODE REVIEW

**Review by mrIncompetent — APPROVED** [review]

**Comment by mrIncompetent** [comment]
@kdomanski Please have a look

**Comment by mrIncompetent** [comment]
ping @kdomanski

**Review by kdomanski — APPROVED** [review]
Looks good. Wish we had the ability to run all the these tests. ;-)

**Comment by alvaroaleman** [comment]
I think with prow in place we will manage to have that for the next release :)

**Pull request merged**
