### PR TITLE
Use kubernetes instead of kubermatic in tags

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://github.com/kubermatic/kubermatic/pull/3419#discussion_r281936673

/assign @alvaroaleman 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/lgtm
/approve
/hold

for @mrIncompetent to confirm this wont create compatibility issues with old clusters
/cherrypick release/v2.10

**Comment by mrIncompetent** [comment]
/hold cancel

We had to verify this with a customer. All good :+1:

**Comment by nikhita** [comment]
Needs lgtm and approve too :grimacing:

**Comment by nikhita** [comment]
/assign @maciaszczykm 
for approval

**Review by maciaszczykm — APPROVED** [review]
/approve

**Pull request merged**
