### PR TITLE
Delete in-cluster resources before deleting nodes

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
Why are we doing this change?

**Comment by alvaroaleman** [comment]
> Why are we doing this change?

Because in a situation where a user deployed a controller for one of PVs/LBs and wants them to cleaned up on deletion, we currently end up in a dead lock, as we delete all nodes and hence the respective controller pods before deleting the PVs/LBs

**Comment by mrIncompetent** [comment]
> > Why are we doing this change?

> Because in a situation where a user deployed a controller for one of PVs/LBs and wants them to cleaned up on deletion, we currently end up in a dead lock, as we delete all nodes and hence the respective controller pods before deleting the PVs/LBs

In case we delete a PVC which gets consumed by a Pod, the PVC won't disappear as long the Pod is running. Deleting a PVC does not trigger a pod to restart - instead the running Pod blocks the PVC deletion.
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection

So the correct solution would rather be to delete the PVC & delete the consumer?

**Comment by alvaroaleman** [comment]
> So the correct solution would rather be to delete the PVC & delete the consumer?

Good point. Will fix it up later

**Comment by mrIncompetent** [comment]
@alvaroaleman Shall we close this PR ?

**Comment by alvaroaleman** [comment]
I actually want to keep it as a reminder to myself

**Comment by mrIncompetent** [comment]
@alvaroaleman You mind if we only  cherry-pick this into v2.10 ?

**Comment by alvaroaleman** [comment]
No.

/cherrypick release/v2.10

**Pull request merged**
