### PR TITLE
Use seed client in Constraint endpoints

### LINKED ISSUE #6944: Kubernetes Constraints endpoints stop working when Master and Seed are on different clusters.
In the constraints endpoints, we currently use an impersonation client created by using kubeconfig of the master cluster:
https://github.com/kubermatic/kubermatic/blob/eb95175f79cc71379b56ecd2e341e11bbfa57749/cmd/kubermatic-api/main.go#L264
This works fine in the scenario when master and seed are on the same cluster, but this will stop working if Master and Seed are on different clusters since the client should talk to Seed by using kubeconfig of the seed cluster.

### PR DESCRIPTION
**Pull request by jiachengxu**
**What this PR does / why we need it**:
This PR switches the impersonation client from using master kubeconfig to seed kubeconfig, in order to make the constraint endpoints work when seed and master are on different clusters.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6944 

**Special notes for your reviewer**:

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jiachengxu** [comment]
Thanks @lsviben! do you think we need to cherry-pick this?

**Comment by lsviben** [comment]
yes, cherry pick it to 2.17, it will be a part of 2.17.1

**Pull request merged**
