### PR TITLE
Update to Go 1.16.1

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
:tada:

**Does this PR introduce a user-facing change?**:
```release-note
Update to Go 1.16.1
```

### CODE REVIEW

**Comment by xrstf** [comment]
/override pre-kubermatic-license-validation

This is a known problem, tracked in https://github.com/kubermatic/machine-controller/issues/913

**Comment by xrstf** [comment]
/hold

holding so i can time this properly.

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by xrstf** [comment]
/override pre-kubermatic-license-validation

This is a known problem, tracked in kubermatic/machine-controller#913

**Pull request merged**
