### PR TITLE
Add support for creating rbac bindings to group subjects

### PR DESCRIPTION
**Pull request by bashofmann**
**What this PR does / why we need it**:
Add support for creating rbac bindings to group subjects. Before only user subjects were supported.

**Special notes for your reviewer**:
When this is merged, we can also create a PR for the dashboard changes.

**Does this PR introduce a user-facing change?**:

```release-note
Add support for creating rbac bindings to group subjects
```

### CODE REVIEW

**Comment by bashofmann** [comment]
Since I can't see the test results: Which verify Job did I miss, that is failing?

**Comment by zreigz** [comment]
please run `hack/update-swagger.sh` and `hack/gen-api-client.sh`

**Pull request merged**
